[PHP 8.0] Add new DOM interfaces
php/doc-en pull request #1025
Opened 2021-10-14 07:02 UTC by saundefined

Add new `DOMChildNode` and `DOMParentNode` interfaces.

2021-11-28 05:08 UTC, mallardduck requested changes
I think updates to `DOMElement` are also necessary. For instance it should be updated so the class reflects that it now `implements DOMParentNode, DOMChildNode`. Going based off changes noted here https://github.com/php/php-src/pull/4709, I've compiled this list of the items needing updates to class synopsis:

- [ ] `DOMElement` needs `implements DOMParentNode, DOMChildNode`
- [ ] `DOMDocument` needs `implements DOMParentNode`
- [ ] `DOMFragment` needs `implements DOMParentNode`
- [ ] `DOMCharacterData` needs `implements DOMChildNode`

2021-11-29 06:22 UTC, saundefined commented
@mallardduck thanks!

Yep, as far as I can see, these changes implemented in #839

2021-11-29 16:27 UTC, mallardduck approved these changes
Merge along with: https://github.com/php/doc-en/pull/839

2021-11-29 17:06 UTC, cmb69 reviewed
Thank you for the PR! It might make sense to add some further methods to the see also sections, e.g. `DOMNode::appendChild` comes to mind. I'm not quite sure about the usage of "current node"; AIUI, this refers to `$this`, so perhaps makes that more explicit.

2021-11-29 17:06 UTC, cmb69 commented on reference/dom/domchildnode/replaceWith.xml
> +   A combination of <methodname>DOMChildNode::remove</methodname> + <methodname>DOMChildNode::append</methodname>.
```suggestion
   Replaces the current node with new <parameter>nodes</parameter>.
   A combination of <methodname>DOMChildNode::remove</methodname> and <methodname>DOMChildNode::append</methodname>.
```

2021-11-29 17:06 UTC, cmb69 commented on reference/dom/domparentnode/append.xml
> +  <refpurpose>Appends one or many nodes to the list of children behind the last child node</refpurpose>
```suggestion
  <refpurpose>Appends nodes after the last child node</refpurpose>
```

2021-11-29 17:06 UTC, cmb69 commented on reference/dom/domparentnode/append.xml
> +   Appends one or many <parameter>nodes</parameter> to the list of children behind the last child node.
```suggestion
   Appends one or many <parameter>nodes</parameter> to the list of children after the last child node.
```

2021-11-29 17:06 UTC, cmb69 commented on reference/dom/domparentnode/prepend.xml
> +  <refpurpose>Prepends one or many nodes to the list of children before the first child node</refpurpose>
```suggestion
  <refpurpose>Prepends nodes before the first child node</refpurpose>
```

2022-01-11 04:51 UTC, saundefined commented
Sorry for the long implementation =(

@cmb69 Thanks for the review, as always =)

> It might make sense to add some further methods to the see also sections, e.g. `DOMNode::appendChild` comes to mind.

Added new links.

> AIUI, this refers to `$this`, so perhaps makes that more explicit.

What do you think about "object context" instead of "current node"?

2022-01-11 11:19 UTC, cmb69 commented
> What do you think about "object context" instead of "current node"?

Maybe, not sure. `DOMNode::hasChildNodes()` just states "Checks if node has children", so maybe we should just use "the node" instead of "current node" here? While that is not particularly specific, it might be good enough.

2022-01-11 11:55 UTC, cmb69 approved these changes
Thank you!

2022-01-11 12:10 UTC, merged