Add Locale::getLanguage() and make getPrimaryLanguage() its alias
php/doc-en pull request #1085
Opened 2021-11-11 19:32 UTC by ramsey

This documentation change supports the php-src pull request at https://github.com/php/php-src/pull/7644

2022-12-09 14:39 UTC, cmb69 reviewed
Thank you for the PR! Besides some minor nits (see below) this looks good to me, but the new method/function also needs entries in reference/intl/versions.xml; otherwise:

![Screenshot 2022-12-09 153759](https://user-images.githubusercontent.com/2306138/206726134-3f1786cf-51eb-4b6c-be2b-56698fc3b319.gif)

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-language.xml
> +   Gets the language for the input locale
Even though this has been copied, let's stick with basic English punctuation rules :)
```suggestion
   Gets the language for the input locale.
```

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-language.xml
> +       The locale to extract the language code from
```suggestion
       The locale to extract the language code from.
```

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-primary-language.xml
> +   Gets the language for the input locale
Since this line is modified anyway:
```suggestion
   Gets the language for the input locale.
```

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-primary-language.xml
> +    <methodname>Locale::getPrimaryLanguage</methodname> is an alias of <methodname>Locale::getLanguage</methodname>.
This is only the case as of PHP 8.2.0, so:
```suggestion
    As of PHP 8.2.0, <methodname>Locale::getPrimaryLanguage</methodname>
    is an alias of <methodname>Locale::getLanguage</methodname>.
```

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-primary-language.xml
> +       The locale to extract the language code from
```suggestion
       The locale to extract the language code from.
```

2022-12-09 14:39 UTC, cmb69 commented on reference/intl/locale/get-language.xml
> +  <methodsynopsis role="oop">
@kocsismate, do we want to fix the `role` right away?

2022-12-09 14:45 UTC, cmb69 requested changes
Ugh, it seems https://github.com/php/php-src/pull/7644 has never been merged.

2022-12-13 14:45 UTC, kocsismate commented on reference/intl/locale/get-language.xml
> +  <methodsynopsis role="oop">
Yes :)

2022-12-23 22:24 UTC, afilina commented
@ramsey If the php-src PR was closed without merging, is this documentation PR still relevant?

2022-12-23 22:27 UTC, ramsey commented
This PR can be closed, since the other was closed without merging. Thanks!

2022-12-23 22:27 UTC, closed without merging