Fixed info about @ operator
php/doc-en pull request #1196
Opened 2021-12-11 13:29 UTC by dg

Corrects some misunderstandings of the UPGRADING document

- It says that the error_reporting (ie. value returned by error_reporting() or ini_get('error_reporting ')) is changed, not the severity value passed to the handler.

- It says that the error_reporting() == 0 should be replaced with !(error_reporting() & $err_no) in code, not the return with return false. So there is currenctly no way how to detect @ operator.

- "Prior to PHP 8.0.0, the value of the severity passed to the custom error handler was always 0" - no true

- "return false; // Silenced" - not true, if the function returns false then the normal error handler continues, so it is not "silenced".

(partially reverts "Cleanup and update docs related to @ operator" commit 12b1d4704ea448b55ec155619be1e50c0e67e9f9.)

2021-12-12 00:06 UTC, Girgias requested changes

2021-12-12 00:06 UTC, Girgias commented on appendices/migration80/incompatible.xml
> +        return; // Silenced
Please use ``return true;`` here.

We document the error handler to be a callable which returns a bool in the docs or ``set_error_handler()``, although the actual semantics are kinda batshit crazy I'm not super keen on providing contradicting information.

2021-12-12 00:06 UTC, Girgias commented on language/operators.xml
> +    the diagnostic has been suppressed.
Why are you removing this section?

Just fix the return value in the custom error handler.

2021-12-12 00:26 UTC, dg commented on language/operators.xml
> +    the diagnostic has been suppressed.
Because it is not possible to know that the @ operator has been used. Since version 8.0, the `error_reporting()` no longer returns 0 when `@` is used. This is pointed out in UPGRADING that a test for zero is no longer possible and must be modified. 

Neither now nor before could the operator be reliably recognized or distinguished from the own error_reporting setting.

2021-12-12 00:28 UTC, dg commented on appendices/migration80/incompatible.xml
> +        return; // Silenced
Oh, that's an mistake in the documentation, because the callable must have a return value of ?bool.

See return value explanation, null is important value https://www.php.net/manual/en/function.set-error-handler.php#refsect1-function.set-error-handler-returnvalues

2021-12-12 00:37 UTC, Girgias commented on appendices/migration80/incompatible.xml
> +        return; // Silenced
No the return value can be literally anything: https://3v4l.org/UeNn4 but only ``false`` will cause PHP to run the built-in error_handler.
Moreover if the function has a return type of ``?bool`` you would still need to use ``return null;``.

And I'm not sure it is really sensible trying to explain the very weird semantics of how the return value is checked. Others may have another opinion on this.

2021-12-12 00:49 UTC, Girgias commented on language/operators.xml
> +    the diagnostic has been suppressed.
I'm pretty sure this needs to be kept, as a suppressed/silenced diagnostic if it's ignored in the INI error_reporting will still trigger the error handler even though it should *probably* not do anything. See: https://3v4l.org/0nMbF

This might need rephrasing of the section, but I don't think deleting this make a ton of sense.

2021-12-12 01:24 UTC, dg commented on appendices/migration80/incompatible.xml
> +        return; // Silenced
My point is that `return false` is followed by `silenced`, which is confusing. It doesn't really matter what is returned there, but just calling the built-in handler can't be called *silencing*.

2021-12-12 01:28 UTC, dg commented on language/operators.xml
> +    the diagnostic has been suppressed.
How can you detect that @ was used? See https://3v4l.org/4WBrj and https://3v4l.org/paLuC

2021-12-12 01:35 UTC, dg commented on appendices/migration80/incompatible.xml
> +        return; // Silenced
Actually, I have to say that it's actually better to `return false;` than to `return; // Silenced`, because it populates the values in error_get_last()

2022-01-14 08:46 UTC, dg commented
Please, what prevents merging? The documentation doesn't tell the truth and it confuses the user unnecessarily.

2022-01-14 13:03 UTC, cmb69 commented on language/operators.xml
> +    the diagnostic has been suppressed.
The PHP manual currently is supposed to document PHP 7.0 to 8.1. If there are behavioral differences, this can be indicated with "as of PHP 8.0.0" or "prior to PHP 8.0.0".

2022-04-03 15:07 UTC, Crell commented
See @cmb69's comments on 14 January. That still needs to be addressed.

2022-04-04 17:16 UTC, dg commented
@Crell done

2022-04-04 18:54 UTC, Crell commented on language/operators.xml
> +     returned always <literal>0</literal> if the error was suppressed by the <literal>@</literal> operator.
```suggestion
     always returned <literal>0</literal> if the error was suppressed by the <literal>@</literal> operator. 
```

2022-04-04 19:26 UTC, Girgias commented on language/operators.xml
> +     Since version 8, it returns the value of <literal>E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE</literal>.
```suggestion
     As of PHP 8.0., it returns the value <literal>E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE</literal>.
```

2022-04-04 19:27 UTC, Girgias commented on language/operators.xml
> +     As of PHP 8.0., it returns the value <literal>E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE</literal>.
```suggestion
     As of PHP 8.0.0, it returns the value <literal>E_ERROR | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR | E_PARSE</literal>.
```

2022-04-04 19:28 UTC, merged

2022-04-05 15:47 UTC, dg commented
Thanks for the merge.