Sync ext/dom properties with stubs - part 1
php/doc-en pull request #1295
Opened 2022-01-04 09:52 UTC by kocsismate

2022-04-13 21:10 UTC, Girgias requested changes
Phrasing needs to be updated for the other files

2022-04-13 21:10 UTC, Girgias commented on reference/dom/domdocumentfragment.xml
> +        and <varname>childElementCount</varname> properties are added now.
```suggestion
        and <varname>childElementCount</varname> properties have now been added.
```
or just
```suggestion
        and <varname>childElementCount</varname> properties have been added.
```

2022-04-20 07:28 UTC, kocsismate commented on reference/dom/domdocumentfragment.xml
> +        and <varname>childElementCount</varname> properties are added now.
Fixed! Can you please have another look sometime? :)

2022-04-20 12:37 UTC, cmb69 approved these changes
Thank you!

2022-04-20 12:48 UTC, merged