Document mysqli_sql_exception::getSqlState()
php/doc-en pull request #1310
Opened 2022-01-08 09:52 UTC by kocsismate

I have to admit that the descriptions are not too informative.

2022-01-08 12:47 UTC, cmb69 reviewed
Thank you! This looks good to me, but maybe @kamil-tekiela has suggestions for improvement.

2022-01-08 13:21 UTC, kamil-tekiela requested changes

2022-01-08 13:21 UTC, kamil-tekiela commented on reference/mysqli/mysqli_sql_exception/getsqlstate.xml
> +  <refpurpose>Gets the SQL error state</refpurpose>
This is incorrect. This function does not return the state of the error. It returns the [SQLSTATE](https://mariadb.com/kb/en/sqlstate/) code. The name is stylized in all caps.

2022-01-08 13:21 UTC, kamil-tekiela commented on reference/mysqli/mysqli_sql_exception/getsqlstate.xml
> +   The SQL error state.
```suggestion
   Returns a string containing the SQLSTATE error code for the last error. The error code consists of five characters.
```

2022-01-08 13:21 UTC, kamil-tekiela commented on reference/mysqli/mysqli_sql_exception/getsqlstate.xml
> +   Gets the SQL error state.
Please copy the description from https://www.php.net/manual/en/mysqli.sqlstate.php or from https://www.php.net/manual/en/mysqli-stmt.sqlstate.php

2022-01-08 21:04 UTC, kamil-tekiela commented on reference/mysqli/mysqli_sql_exception/getsqlstate.xml
> +   The error code consists of five characters. <literal>'00000'</literal> means no error.
```suggestion
   The error code consists of five characters.
```
😄

2022-01-10 13:54 UTC, kamil-tekiela approved these changes
LGTM Thanks!

2022-01-10 13:55 UTC, merged