PDOStatement::bindParam maxLength is confusing
php/doc-en pull request #1371
Opened 2022-02-01 20:41 UTC by Karmel0x

https://www.php.net/manual/en/pdostatement.bindparam.php
___
It has no effect on input parameters, but is even passed in the examples.

2022-02-01 21:37 UTC, kamil-tekiela requested changes
Thanks. This is a well-spotted mistake. Could you please wrap the constant name in the literal tag?

2022-02-01 21:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/bindparam.xml
> +        Meaningful only when <parameter>type</parameter> parameter is PDO::PARAM_INPUT_OUTPUT.
```suggestion
        Meaningful only when <parameter>type</parameter> parameter is <literal>PDO::PARAM_INPUT_OUTPUT</literal>.
```

2022-02-01 21:43 UTC, cmb69 commented on reference/pdo/pdostatement/bindparam.xml
> +        Meaningful only when <parameter>type</parameter> parameter is PDO::PARAM_INPUT_OUTPUT.
Isn't `<constant>` more appropriate here?

2022-02-01 21:58 UTC, kamil-tekiela commented on reference/pdo/pdostatement/bindparam.xml
> +        Meaningful only when <parameter>type</parameter> parameter is PDO::PARAM_INPUT_OUTPUT.
Ahh yes. I have been ill in the past couple of days so forgive my mistakes.

2022-02-01 22:16 UTC, Karmel0x commented on reference/pdo/pdostatement/bindparam.xml
> +        Meaningful only when <parameter>type</parameter> parameter is PDO::PARAM_INPUT_OUTPUT.
https://github.com/php/doc-en/blob/be0ed69b711ec94903e802ffa67d80845553c35d/reference/pdo/pdostatement/bindparam.xml#L69
then it should be here too ?

2022-02-02 17:49 UTC, kamil-tekiela approved these changes

2022-02-02 17:51 UTC, merged

2022-02-02 17:51 UTC, kamil-tekiela commented
Thanks!