document ext-mysqli exception throwing on their respective pages
php/doc-en pull request #1413
Opened 2022-02-16 23:00 UTC by Parsonswy

Document exception throwing behavior of `mysqli_*` functions as discussed in #1368.

I also adjusted docs for a few functions that look like they always return true:
- [mysqli_close](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L669)
- [mysqli_stmt_close](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L2029)
- [mysqli_field_seek](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L1301)

My understanding of PHP internals is limited, but while digging through these functions I noticed some do not seem to throw `mysqli_sql_exceptions`. Those noted only return true/false when the driver reports an error. I am not sure that this is intentional and wanted to raise them just in case. 
- [mysqli_begin_transaction](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_nonapi.c#L1207)
- [mysqli_savepoint](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_nonapi.c#L1256)
- [mysqli_release_savepoint](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_nonapi.c#L1284)
- [mysqli_send_long_data](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L1982)
- [mysqli_stmt_reset](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L2132)

2022-02-17 12:41 UTC, kamil-tekiela commented
The text seems to be identical in all cases. Can you make it a snippet instead, please?

2022-02-17 12:47 UTC, cmb69 commented
"snippets" are XML entities, and these can be defined in [language-snippets.ent](https://github.com/php/doc-en/blob/14b55b8b4ba3a51b38cd3b1c360e21df632ca890/language-snippets.ent#L1877).

2022-04-03 18:49 UTC, Girgias requested changes

2022-04-03 18:49 UTC, Girgias commented on reference/mysqli/mysqli/real-query.xml
> +  </para>
```suggestion
  &mysqli.conditionalexception;
```
Seems to have been forgotten

2022-04-03 18:49 UTC, Girgias commented on reference/mysqli/mysqli_result/construct.xml
> + </refsect1>
Constructors do no have a return value section, as they don't return a value per say.
So please remove it again.

2022-04-03 18:49 UTC, Girgias commented on reference/mysqli/mysqli_stmt/construct.xml
> + </refsect1>
Ditto

2022-04-09 16:05 UTC, Parsonswy commented
My bad. Changes made.

2022-04-13 20:36 UTC, Girgias approved these changes

2022-04-13 21:13 UTC, kamil-tekiela commented
Thanks for these changes. I will review them over the weekend.

2022-04-22 18:37 UTC, kamil-tekiela requested changes
You missed:
 - `mysqli_stmt_fetch`
 - `mysqli_stmt_attr_set`

2022-04-22 18:37 UTC, kamil-tekiela commented on reference/mysqli/mysqli/savepoint.xml
> + <refsect1 role="errors">
This one doesn't report errors. It's probably a bug, but... I don't know if anyone really cares about this one to do something about it.

2022-12-24 15:53 UTC, afilina commented on reference/mysqli/mysqli/savepoint.xml
> + <refsect1 role="errors">
> You missed:
> - mysqli_stmt_fetch
> - mysqli_stmt_attr_set

Can we merge what we have here and open a ticket for additional changes? I'm hoping that we can limit the scope so that PRs can get through.

2022-12-27 03:27 UTC, Parsonswy commented on reference/mysqli/mysqli/savepoint.xml
> + <refsect1 role="errors">
Sorry! I forgot I had this outstanding. I believe this addresses all the feedback items.

2022-12-29 17:54 UTC, cmb69 reviewed
Thank you!

2022-12-29 17:54 UTC, cmb69 commented on reference/mysqli/mysqli_result/field-seek.xml
> +   &return.true.always;
This function will no longer return `false` as of PHP 8.0.0, so this change is basically correct, but that does not match the stub (https://github.com/php/php-src/blob/383053c4aa9fc9775b51e22f70a80c4822bef353/ext/mysqli/mysqli.stub.php#L1460). So we should first fix the stub.

2022-12-29 17:54 UTC, cmb69 commented on language-snippets.ent
> +and the requested operation fails, a <classname>mysqli_sql_exception</classname> is thrown.</para>'>
This looks misleading; AFAIK, unless `MYSQL_REPORT_ERROR` is also set, nothing happens. OTOH, if `MYSQLI_REPORT_STRICT` is not set, a warning will be raised, what we can easily document here.

2023-01-08 00:35 UTC, kamil-tekiela commented on language-snippets.ent
> +and the requested operation fails, a <classname>mysqli_sql_exception</classname> is thrown.</para>'>
Suggestion:
> If mysqli error reporting is enabled (`MYSQLI_REPORT_ERROR`) and the requested operation fails, a warning is generated. If, in addition, the mode is set to `MYSQLI_REPORT_STRICT`, a `mysqli_sql_exception` is thrown instead.

2023-01-26 03:56 UTC, Parsonswy commented on language-snippets.ent
> +and the requested operation fails, a <classname>mysqli_sql_exception</classname> is thrown.</para>'>
I've updated the snippet.

2023-01-26 04:22 UTC, Parsonswy commented on reference/mysqli/mysqli_result/field-seek.xml
> +   &return.true.always;
I can open a PR for this, unless you'd prefer to do it?

This would need to go into `PHP-8.2` so `true` could be the return type, right? Or is there a more correct type that can go into the stub right now that I am not aware of.

2023-01-27 19:59 UTC, kamil-tekiela requested changes
I think this can be merged, but I would move the return value changes to a new PR, and please fix the small nits I pointed out. Other than that, good job!

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/bind-param.xml
> +  <refsect1 role="errors">
```suggestion
 <refsect1 role="errors">
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli/use-result.xml
> +  <refsect1 role="errors">
```suggestion
 <refsect1 role="errors">
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli/store-result.xml
> +  <refsect1 role="errors">
```suggestion
 <refsect1 role="errors">
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli/ping.xml
> +  <refsect1 role="errors">
```suggestion
 <refsect1 role="errors">
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli/multi-query.xml
> +  <refsect1 role="errors">
```suggestion
 <refsect1 role="errors">
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli/close.xml
> +   &return.true.always;
Can this be moved to a new PR?

2023-01-27 19:59 UTC, kamil-tekiela commented on language-snippets.ent
> +a warning is generated. If, in addition, the mode is set to<constant>MYSQLI_REPORT_STRICT</constant>,
```suggestion
a warning is generated. If, in addition, the mode is set to <constant>MYSQLI_REPORT_STRICT</constant>,
```

2023-01-27 19:59 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/close.xml
> +   &return.true.always;
Please move to a separate PR.

2023-01-27 20:43 UTC, kamil-tekiela commented on reference/mysqli/mysqli_result/field-seek.xml
> +   &return.true.always;
What about this one?

2023-01-27 20:47 UTC, Parsonswy commented on reference/mysqli/mysqli/close.xml
> +   &return.true.always;
Yep. https://github.com/php/doc-en/pull/2255

2023-01-27 20:53 UTC, kamil-tekiela approved these changes
Thank you.

2023-01-27 20:53 UTC, merged

2023-01-27 20:54 UTC, Parsonswy commented on reference/mysqli/mysqli_result/field-seek.xml
> +   &return.true.always;
Moved the doc bit.

I wasn't sure which branch to PR in `php-src` for the stub change.