Add array destructuring documentation to array syntax section
php/doc-en pull request #145
Opened 2020-09-08 22:06 UTC by rask

This redoes the original PR I made against this repo, but which got stale: #19 

Adds basic syntax documentation for array destructuring.

2020-11-01 05:05 UTC, Girgias requested changes
I'm concerned that the array type pages is maybe not the best place as it's already a massive and dense page, but this has nothing to do with the PR really.

2020-11-01 05:05 UTC, Girgias commented on language/types/array.xml
> +     Array destructuring is available only in PHP versions 7.1 and newer.
```suggestion
     Array destructuring is available as of PHP 7.1.0.
```

2020-11-01 05:05 UTC, Girgias commented on language/types/array.xml
> +    This feature is similar to what the <function>list</function> construct offers.
```suggestion
    This feature is equivalent to the <function>list</function> construct.
```

2021-01-07 20:04 UTC, afilina commented
Pinging @rask to address suggestions. Looks like this PR fell through the cracks.

2021-03-08 15:42 UTC, cmb69 requested changes
IMO, we should not duplicate the description of `list()` (array destructoring is just syntax sugar for that, like literal arrays are syntax sugar for `array()`.  Instead we should clarify on the list man page, that the shorthand syntax is supported as of PHP 7.1.0 and maybe give some examples. It may make sense to add a short note to the array docs, telling users that literal arrays used as lvalues are actually destructuring and link to list (just in case somebody is mislead by that construct).

2021-03-14 02:03 UTC, gallogit requested changes
Corregir errores del sistema para licencias en México multriples

2021-03-14 02:10 UTC, gallogit approved these changes
Corregir error

2021-08-06 14:29 UTC, afilina commented
The comments were not addressed by the author in over a year, despite a reminder in January. Should we consider this PR abandoned and close it? @rask

2021-08-06 19:45 UTC, kamil-tekiela commented
I have opened a new PR recently which tried to address the open points in this PR and add even more information to the page. I believe my PR supersedes this one.

2021-08-06 19:51 UTC, cmb69 commented
Oh, right, there is PR #796, so I'm closing this one.

2021-08-06 19:51 UTC, closed without merging