Document where wordwrap() wraps
php/doc-en pull request #1524
Opened 2022-04-17 03:09 UTC by da2x

2022-04-17 09:07 UTC, cmb69 requested changes
The `<refpurpose>` is supposed to be a *brief* summary of the function, and is also shown, for instance, when a function is linked in a see-also section. This refpurpose is definitely too long.

2022-05-05 19:17 UTC, tiffany-taylor commented
This change can be moved to [line 23](https://github.com/php/doc-en/blob/d6cf75ebfde169545af475cd5205af33f13a3c37/reference/strings/functions/wordwrap.xml#L23), probably with some slight wording changes.

2024-09-29 09:29 UTC, cmb69 approved these changes
Thank you!

2024-09-29 11:53 UTC, Girgias approved these changes

2024-09-29 11:54 UTC, merged