Implicit incompatible float to int conversions
php/doc-en pull request #1528
Opened 2022-04-19 12:42 UTC by saundefined

2022-04-19 12:51 UTC, kamil-tekiela commented on language/types/float.xml
> +var_dump(foo(8.1)); // Deprecated: Implicit conversion from float-string "8.1" to int loses precision as of PHP 8.1.0
```suggestion
var_dump(foo(8.1)); // "Deprecated: Implicit conversion from float 8.1 to int loses precision" as of PHP 8.1.0
```
It's not a string. Did you want to add both examples?

2022-04-19 13:00 UTC, saundefined commented on language/types/float.xml
> +var_dump(foo(8.1)); // Deprecated: Implicit conversion from float-string "8.1" to int loses precision as of PHP 8.1.0
Thanks,

Indeed, I'd add both examples if it doesn't seem redundant

2022-04-19 13:06 UTC, cmb69 reviewed
Thank you for the PR!

2022-04-19 13:19 UTC, saundefined commented on language/types/float.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a &float; to &integer;.
Thank you, clarified it, also added an example.

2022-04-19 17:04 UTC, Girgias requested changes

2022-04-19 17:04 UTC, Girgias commented on language/types/float.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a not integral &float; to &integer;.
This is on the wrong page, it should be in ``language/types/finteger.xml``

2022-04-19 17:16 UTC, cmb69 commented on language/types/float.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a not integral &float; to &integer;.
Right (s/finteger/integer, though). And it is not about converting to float from integer, but rather about converting to int from float.

2022-04-20 06:20 UTC, saundefined commented on language/types/float.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a not integral &float; to &integer;.
Thanks! Moved it

2022-04-20 07:21 UTC, kocsismate commented on language/types/integer.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a not integral &float; to &integer;.
What about this?
```suggestion
    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a nonintegral &float; to &integer;.
```

2022-04-20 07:23 UTC, kocsismate commented on language/types/integer.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a not integral &float; to &integer;.
Would it be worth to emphasize here in addition to the example below that the notice is only emitted when the conversion loses precision?

2022-04-28 06:08 UTC, kocsismate commented on language/types/integer.xml
> +    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting and loses precision a non-integral &float; to &integer;.
```suggestion
    As of PHP 8.1.0, a deprecation notice is emitted when implicitly converting a non-integral &float; to &integer; which loses precision.
```

2022-04-28 06:14 UTC, kocsismate approved these changes
This sounds good to me. Hopefully native speakers do agree ^^

2022-04-28 10:56 UTC, Girgias commented on language/types/integer.xml
> +var_dump(foo(8.1)); // 8 before PHP 8.1.0
```suggestion
var_dump(foo(8.1)); // 8 prior to PHP 8.1.0
```

2022-04-28 10:57 UTC, Girgias approved these changes

2022-04-28 10:57 UTC, merged