applied during french translation doc/en@14e5e29fd12657263368b305369d…
php/doc-en pull request #1536
Opened 2022-04-22 10:03 UTC by eugene-augier

See: https://github.com/php/doc-fr/pull/211

2022-04-22 11:04 UTC, cmb69 commented
Do we have any style guides which prefer one comment style over the other? Otherwise, it's not unlikely that we see a commit in the future which changes the style again.

cc @kamil-tekiela

2022-04-22 11:17 UTC, kamil-tekiela requested changes
I am not sure what comment style is mandated by PHP Manual, but in general, we use single-line comment syntax for single-line comments and multi-line syntax for multi-line comments. 

These are good changes, but that one example needs more changes. I seem to have missed it in my redesign.

2022-04-22 11:43 UTC, cmb69 commented
> I am not sure what comment style is mandated by PHP Manual, but in general, we use single-line comment syntax for single-line comments and multi-line syntax for multi-line comments.

The [style guidelines](http://doc.php.net/tutorial/style.php) are terse, and just refer to [PEAR CS](https://pear.php.net/manual/en/standards.comments.php) which explicitly allows both styles. We might be better off to document our preferred style in the style guidelines.

2022-04-22 11:58 UTC, eugene-augier commented
Generally speaking, single-line comments used at the layer of PHP frameworks are declared with `//`, that's why I proposed these changes. 

Of course I understand that the php documentation is an independent project from the upper software layers.

2022-04-22 12:03 UTC, cmb69 commented
I'm not against these changes, but I'm concerned that a follow-up PR/commit might change back to some other style (and such comments are a burden for translators). Therefore I think we need to make a decision, and to document it. This should probably be discussed on the phpdoc mailing list.

@Girgias, do we already have scripts to check code examples?

2022-04-22 12:08 UTC, eugene-augier commented
I completely understand your point.

2022-04-22 12:21 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> +mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
No, it's better if you don't. BTW if you want to use try-catch, use it only for the line you expect to throw, not the whole code.

2022-04-22 12:21 UTC, kamil-tekiela approved these changes

2022-04-22 12:32 UTC, Girgias commented
> I'm not against these changes, but I'm concerned that a follow-up PR/commit might change back to some other style (and such comments are a burden for translators). Therefore I think we need to make a decision, and to document it. This should probably be discussed on the phpdoc mailing list.
> 
> @Girgias, do we already have scripts to check code examples?

We have a linter check if code segment compile, but it doesn't check the style, (nor the output). But that would be a good script to have

2022-04-22 12:50 UTC, cmb69 commented
> But that would be a good script to have

I very much agree. But that would likely bring us back to the "we must not use existing apps, to not endorse them". :( And writing our own CS checker appears to be overkill.

2022-04-22 12:51 UTC, eugene-augier commented
> > I'm not against these changes, but I'm concerned that a follow-up PR/commit might change back to some other style (and such comments are a burden for translators). Therefore I think we need to make a decision, and to document it. This should probably be discussed on the phpdoc mailing list.
> > @Girgias, do we already have scripts to check code examples?
> 
> We have a linter check if code segment compile, but it doesn't check the style, (nor the output). But that would be a good script to have

I am open to work on this project.
We could check that the php code is syntactically valid by the way, that would avoid some errors.
```php
$url = "path"/;
```

2022-04-22 13:01 UTC, Girgias commented
> > > I'm not against these changes, but I'm concerned that a follow-up PR/commit might change back to some other style (and such comments are a burden for translators). Therefore I think we need to make a decision, and to document it. This should probably be discussed on the phpdoc mailing list.
> > > @Girgias, do we already have scripts to check code examples?
> > 
> > 
> > We have a linter check if code segment compile, but it doesn't check the style, (nor the output). But that would be a good script to have
> 
> I am open to work on this project. We could check that the php code is syntactically valid by the way, that would avoid some errors.
> 
> ```
> $url = "path"/;
> ```

Great, the script is located in doc-base and the current one we have is: https://github.com/php/doc-base/blob/master/scripts/qa/check-examples.php which checks for syntactically valid code (and no errors), which is a good start, but some code examples fail on purpose and so currently the whole page need to be silenced :|

2022-04-28 08:06 UTC, eugene-augier commented
Hi @cmb69 

After some private discussions with Girgias, I would like to propose some changes on `php/doc-base`.
When you have the time and desire, this is the one I mentioned above.

Thanks!

2022-08-16 20:45 UTC, kamil-tekiela commented
Can we merge this?

2023-01-13 17:09 UTC, cmb69 commented
I still don't think we should make cosmetic changes without having some kind of style guide which justifies these changes. Thus, I'm going to commit only the relevant parts of the PR.

Thanks all!

2023-01-13 17:09 UTC, closed without merging