Update documentation for ldap_search()
php/doc-en pull request #1629
Opened 2022-06-16 08:48 UTC by noonlit

Noticed that the array return type value was specified in the function signature but not in the documentation. I assume that it is an array of Ldap\Result :)

Additionally, the text about parallel searches seems to be out of date, as it is referencing the previous function signature.

2022-06-16 09:01 UTC, saundefined reviewed
Thank you!

2022-06-20 08:51 UTC, kocsismate commented on language-snippets.ent
> +<!ENTITY ldap.return-result 'Returns an <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instance, an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</cl
Please use a different entity as this one is also used where an array is not returned. One example is https://www.php.net/manual/en/function.ldap-bind-ext.php

2022-06-20 08:57 UTC, kocsismate commented on language-snippets.ent
> +<!ENTITY ldap.return-result 'Returns an <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instance, an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</cl
Also, I think the current wording is missing an `or`. So I'd prefer something like:
`Returns an LDAP\Result, or an array of LDAP\Result instances, or false on failure.`

We should also make sure that all the affected descriptions also describe exactly when an array is returned -- just like how `ldap_search` does so.

2022-06-20 09:35 UTC, noonlit commented on language-snippets.ent
> +<!ENTITY ldap.return-result 'Returns an <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instance, an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</cl
I'll update the PR, except for adding the 'or'. It doesn't seem to be missing: https://github.com/php/doc-en/blob/master/language-snippets.ent#L703

2022-06-20 10:13 UTC, cmb69 commented on language-snippets.ent
> +<!ENTITY ldap.return-result 'Returns an <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instance, an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</cl
I think this is mostly fine, but I'd go with "Returns an LDAP\Result instance, an array of LDAP\Result **instances**, or false on failure." (the last clause should actually be `&return.falseforfailure;`)

2022-06-21 05:51 UTC, noonlit commented on language-snippets.ent
> +<!ENTITY ldap.return-result 'Returns an <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instance, an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</cl
Fixed the missing 'instances', used a separate entity (sorry about that, I didn't notice), and updated more ldap functions that had array in the signature but not in the return values. Please let me know if I've missed any of them.

2022-06-21 09:25 UTC, cmb69 requested changes
Thank you for the PR! From what I can tell (I'm not used to ext/ldap), this is basically a good improvement, but there are some issues which should be resolved before merging.

2022-06-21 10:22 UTC, cmb69 commented on language-snippets.ent
> +When doing parallel searches an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instances is returned, except in case of error, when the return value will be &false;
Nice, but I'd include the `<para>` in the entity definition (what also allows to drop the xmlns declarations from the inner elements):
```suggestion
<!ENTITY ldap.return-result-array-info '<para  xmlns="http://docbook.org/ns/docbook">It is also possible to perform parallel searches. In this case, the first argument should be an array of
<classname>LDAP\Connection</classname> instances, rather than a single one.
If the searches should not all use the same base DN and filter, an array of base DNs and/or an array of filters can be passed as arguments instead.
These arrays must be of the same size as the <classname>LDAP\Connection</classname> instances array,
since the first entries of the arrays are used for one search, the second entries are used for another, and so on.
When doing parallel searches an array of <classname>LDAP\Result</classname> instances is returned, except in case of error, when the return value will be &false;.</para>'>
```
And of course, the `<para>` elements in the description sections should be removed in this case.

2022-06-21 10:39 UTC, noonlit commented on language-snippets.ent
> +When doing parallel searches an array of <classname xmlns="http://docbook.org/ns/docbook">LDAP\Result</classname> instances is returned, except in case of error, when the return value will be &false;
Thanks!

2022-06-21 10:54 UTC, kocsismate approved these changes

2022-06-21 11:22 UTC, merged