Remove PHP 5 from OOP section
php/doc-en pull request #165
Opened 2020-10-25 23:13 UTC by tiffany-taylor

I'll start working on removal of PHP 5 from OOP section, this was a file I encountered while browsing the manual. I'll add more files as I go through.

2020-11-13 12:54 UTC, tiffany-taylor commented
Changing this to just the static keyword page as I probably won't have the time to go over all of the OOP5 pages.

2020-11-13 13:05 UTC, cmb69 requested changes
Thanks, very nice, except for the commented issue.

2020-11-13 13:05 UTC, cmb69 commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
That doesn't look quite right. The initialization restriction to "literal or constant" only applies prior to PHP 5.6.

2020-11-13 13:14 UTC, tiffany-taylor commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
Does this mean static properties can be initialized with an expression as well? Trying to see how I should wordsmith it.

2020-11-13 13:41 UTC, cmb69 commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
With a constant expression, i.e. "some limited expressions are possible, provided they can be evaluated at compile time"

2020-11-29 00:24 UTC, tiffany-taylor commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
> Static variables have limited expression support, provided they can be evaluated at compile time.
How is that?

2020-11-29 00:26 UTC, tiffany-taylor commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
Or maybe:
> Static variables have limited support for expressions, provided they can be evaluated at compile time.

2020-11-29 13:11 UTC, cmb69 commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
Well, actually I think we should define "constant expression" in a central place, and then just link to it. Currently, the most fitting definition (but IMO still a bit unspecific) is in https://www.php.net/manual/en/language.oop5.constants.php, but probably should be in https://www.php.net/manual/en/language.constants.php, but that page doesn't even mention global `const` definitions, which are explained in https://www.php.net/manual/en/language.constants.syntax.php. Total mess :(

2021-01-08 15:12 UTC, afilina commented on language/oop5/static.xml
> +    are possible, provided they can be evaluated at compile time.
Pinging @tiffany-taylor in case this fell through the cracks.

2021-01-16 09:51 UTC, Girgias commented
Closing as this should have been covered by #277

2021-01-16 09:51 UTC, closed without merging