Document the role of the window parameter
php/doc-en pull request #1660
Opened 2022-06-28 17:37 UTC by greg0ire

This is copy/pasted from https://bugs.php.net/bug.php?id=68556

I'm not sure what the difference between `simpara` and `para` is, or where to learn more about them.

@USalsi I think you are the original author, please review.

2022-06-28 18:10 UTC, cmb69 commented
> I'm not sure what the difference between `simpara` and `para` is, or where to learn more about them.

See https://tdg.docbook.org/tdg/4.5/simpara.html vs. https://tdg.docbook.org/tdg/4.5/para.html. TL;DR: we render `<simpara>` as `<p>`, and `<para>` as `<div>`. So use it respectively, unless the usage on a page is already different (there is a general preference for `<para>`).

2022-07-07 15:57 UTC, greg0ire commented
@cmb69 it seems like @USalsi is not responding… can you please review this?

2022-09-21 19:01 UTC, TimWolla reviewed
From what I see the various formats are accurately described now. I don't feel qualified to comment on whether the behavior of the filter is correctly described. I did not use it so far.

2022-09-21 19:01 UTC, TimWolla commented on appendices/filters.xml
> +       eader, otherwise set window=31.
```suggestion
       header, otherwise set window=31.
```

2023-08-02 17:22 UTC, afilina commented
> @cmb69 it seems like @USalsi is not responding… can you please review this?

@cmb69 Looks like this PR is waiting on you. Are you qualified to review it, and if not, could you request a review from someone who is?

2026-09-08 07:53 UTC, lacatoire commented on appendices/filters.xml
> +       performed when the window parameter is set in the range from -8 up to
```suggestion
       performed when the window parameter is set in the range from -9 up to
```

2026-09-08 07:53 UTC, lacatoire commented on appendices/filters.xml
> +       The 2 bytes header, read as 16 bit unsigned number in little-endian
```suggestion
       The 2 bytes header, read as 16 bit unsigned number in big-endian
```

2026-09-08 07:54 UTC, lacatoire commented on appendices/filters.xml
> +       maximum length of the compressed data; beyond this limit, only the
```suggestion
       from 9+16=25 up to 15+16=31. Note that there is a limit of 4GB to the
       maximum length of the uncompressed data; beyond this limit, only the
```

2026-09-08 07:54 UTC, lacatoire commented on appendices/filters.xml
> +       header, otherwise set window=31.
```suggestion
       use window=$W+16. A GZIP header carries no window size, so set
       window=31 unless the value used for compression is known.
```

2026-09-08 07:56 UTC, lacatoire requested changes

2026-09-08 07:58 UTC, lacatoire commented on appendices/filters.xml
> +       operating system set to the current system (<literal>\x00</literal> = Windows,
```suggestion
       compression method (<literal>\x08</literal>), a zero flag byte, a zero
       modification time on 4 bytes, an extra-flags byte that depends on the
       compression level, and the operating system set to the current system
       (<literal>\x00</literal> = FAT filesystem,
```

2026-09-08 08:00 UTC, lacatoire commented on appendices/filters.xml
> +    value used for compression, because no attempt is made to reallocate.
```suggestion
    allocated by the decompressor. For the ZLIB format this value must be
    greater or equal to the one recorded in the header, which is checked at
    decompression time; for the other formats it only has to be large enough
    for the match distances actually present in the data.
```

2026-09-09 06:24 UTC, greg0ire commented
@lacatoire thanks, I applied all your suggestions.

2026-09-09 06:25 UTC, merged