strtotime() fixes from comments
php/doc-en pull request #1669
Opened 2022-06-30 21:02 UTC by Crell

I deleted another bunch of comments.  These are the changes worth keeping.

In particular, the current discussion of separator parsing is incorrect, as the new code sample shows.  It's quite bonkers.

2022-07-01 08:37 UTC, cmb69 reviewed
Thank you! Looks good to me, but maybe @derickr likes to review.

2022-07-01 08:37 UTC, cmb69 commented on reference/datetime/functions/strtotime.xml
> +5/6/21 is interpreted as Thu, 06 May 2021 00:00:00 +0200
The timezone offset [depends on the configured default timezone](https://3v4l.org/37l7k); either explicitly set the timezone, or point that out (a comment may suffice), or use some other format than `r` which doesn't show the timezone (offset) at all.

2022-07-01 08:40 UTC, cmb69 commented on reference/datetime/functions/strtotime.xml
> + <refsect1>
The `<refsect1>` needs a `role` attribute. I think this section should either be integrated with the existing example section, or the existing notes section.

2022-07-01 08:55 UTC, derickr requested changes
Left some comments, but I'm wondering whether we should continue to promote `strtotime` over the DateTime classes, where all of these parsing rules also apply. I have a vague idea to deprecate the functions that operate on just timestamps at some point vaguely soon.

2022-07-01 08:55 UTC, derickr commented on reference/datetime/functions/strtotime.xml
> +    Strings with a <literal>.</literal> separator are interpreted as a timestamp, not a date.
That's not called a `timestamp`, which is usually used for the Unix timestamp (Seconds since midnight 1970). I think you should just say `time`.

2022-07-01 08:55 UTC, derickr commented on reference/datetime/functions/strtotime.xml
> +    Strings with a <literal>.</literal> separator are interpreted in European order.
`European` vs `US` order is quite western-worldy worded. I am not sure whether you can improve on that?

2022-07-01 08:55 UTC, derickr commented on reference/datetime/functions/strtotime.xml
> +  <para>If the selected interpretation results in an illogical date (such as a month out of range), &false; will be returned.</para>
You might want to add saying that a day of of range for a specific month, does get parsed, but overflows happen.

2022-07-01 08:55 UTC, derickr commented on reference/datetime/functions/strtotime.xml
> +    which will get mangled into a timestamp on <literal>3 March</literal>.
`mangled` → `overflowed` or something similar.

2022-07-01 08:55 UTC, derickr commented on reference/datetime/functions/strtotime.xml
> +    which will get mangled into a timestamp on <literal>3 March</literal>.
And maybe add that `first day of February` would make this work.

2022-07-01 14:28 UTC, Crell commented on reference/datetime/functions/strtotime.xml
> +    Strings with a <literal>.</literal> separator are interpreted in European order.
I'm happy to use whatever better terminology you suggest here.

2022-07-01 15:24 UTC, guilliamxavier commented on reference/datetime/functions/strtotime.xml
> +    That is, <literal>h.i.s</literal>.
The reality seems more complicated: https://github.com/php/doc-en/blob/d45ff7a3e78243470d1b7e5141d7ded022286d7f/reference/datetime/formats.xml#L509-L514 (example: https://3v4l.org/t7b56)

2022-07-01 15:53 UTC, Crell commented
Updates based on feedback above.  Most notably, removed the description of the different date separator rules (as they're even more bonkers than I thought), and just made the link to the existing format docs much more prominent.

@derickr I'm all for directing people away from this function toward something else.  If there's a specific "please use this instead" link I should include I can toss that into the description.  Otherwise we can punt on it until there's more internals movement on the subject.  Your call.

2022-07-13 15:42 UTC, derickr approved these changes

2022-07-13 15:47 UTC, merged