Update Win32Service doc for 1.0.0 version
php/doc-en pull request #171
Opened 2020-10-30 23:03 UTC by macintoshplus

This PR update the documentation for the new Win32Service version 1.0.0.

This version will be released for PHP 8.0

2020-11-01 04:58 UTC, Girgias requested changes
Haven't annotated each individual line as some of the comments are applicable to many other instances.

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/book.xml
> +<!-- $Revision: 330340 $ -->
Seems like a revision ref sneaked into the pages

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/constants.xml
> +      These constants is no longer used on Win32Service 1.0.0 and newer.
```suggestion
      These constants are no longer used as of Win32Service 1.0.0.
```

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +        Since the version 1.0.0, a <literal>ValueError</literal> is throw if the value is empty.
```suggestion
        As of version 1.0.0, a <classname>ValueError</classname> is throw if the value is empty.
```
Arguably this needs the ValueError page added before this works, but that should be done ASAP anyway.

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +    Since version 1.0.0, returns <type>void</type>.
```suggestion
    As of version 1.0.0, returns <type>void</type>.
```

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +        <entry>1.0.0</entry>
I think to not confuse with PHP version changelogs the PECL package name still needs to be present, @cmb69 can you confirm?

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-delete-service.xml
> +        <entry>Throw <literal>ValueError</literal> on wrong data in parameters. Throw <literal>Win32ServiceException</literal> on error. The function return <type>void</type>.</entry>
```suggestion
        <entry>
         Throws a <classname>ValueError</classname> on invalid data in parameters.
         Throws a <classname>Win32ServiceException</classname> on error.
         The function's return type is now <type>void</type>.
        </entry>
```
Splitting into multiple lines to be under 80 chars

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-get-last-control-message.xml
> +   Before version 1.0.0, if SAPI is not <literal>"cli"</literal>, this function emits an <constant>E_ERROR</constant> level error.
```suggestion
   Prior to version 1.0.0, if SAPI is not <literal>"cli"</literal>, this function emits an <constant>E_ERROR</constant> level error.
```
Nit, but I think the usual should be "Prior to" might misremember tho

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/functions/win32-get-last-control-message.xml
> +    Since version 1.0.0, shall throw <type>Win32ServiceException</type> if SAPI is not <literal>"cli"</literal>
```suggestion
    As of version 1.0.0, will throw a <classname>Win32ServiceException</classname> if SAPI is not <literal>"cli"</literal>
```

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/setup.xml
> +   The Windows version supported is the same as the Visual C++ redistributable package used to build PHP.
```suggestion
   The versions of Windows supported are the same as the Visual C++ redistributable package used to build PHP.
```

2020-11-01 04:58 UTC, Girgias commented on reference/win32service/win32serviceexception.xml
> +    to the older constant name.
Some grammar issues and I'm not sure what is meant, something like:
```
The exception code is equal to the error constant returned by Windows.
The exception message is based on the constant name.
```
?

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/book.xml
> +<!-- $Revision: 330340 $ -->
Changed

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/constants.xml
> +      These constants is no longer used on Win32Service 1.0.0 and newer.
Changed

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +        Since the version 1.0.0, a <literal>ValueError</literal> is throw if the value is empty.
Changed

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +    Since version 1.0.0, returns <type>void</type>.
Changed

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/functions/win32-delete-service.xml
> +        <entry>Throw <literal>ValueError</literal> on wrong data in parameters. Throw <literal>Win32ServiceException</literal> on error. The function return <type>void</type>.</entry>
Changed

2020-11-01 10:53 UTC, macintoshplus commented on reference/win32service/functions/win32-get-last-control-message.xml
> +   Before version 1.0.0, if SAPI is not <literal>"cli"</literal>, this function emits an <constant>E_ERROR</constant> level error.
Changed

2020-11-01 10:55 UTC, macintoshplus commented on reference/win32service/functions/win32-get-last-control-message.xml
> +    Since version 1.0.0, shall throw <type>Win32ServiceException</type> if SAPI is not <literal>"cli"</literal>
changed

2020-11-01 10:55 UTC, macintoshplus commented on reference/win32service/setup.xml
> +   The Windows version supported is the same as the Visual C++ redistributable package used to build PHP.
Changed

2020-11-01 12:18 UTC, cmb69 commented on reference/win32service/functions/win32-continue-service.xml
> +        <entry>1.0.0</entry>
Yes; that was very recently fixed for all packages, so should be kept. It's particularly important for the generated [changelog in the appendix](https://www.php.net/manual/en/doc.changelog.php).

2020-11-01 14:50 UTC, macintoshplus commented on reference/win32service/win32serviceexception.xml
> +    to the older constant name.
Previously, all error code is a PHP constant like this:

```php
const ERROR_INVALID_HANDLE = 0x00000006;
```
as of version 1.0.0, this error is converted in exception created like this:

```php
new Win32ServiceException('Error invalid handle', 0x00000006);
```
It's suffisant explation to understand?

Note: sorry for my english...

2020-11-01 14:57 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +        <entry>1.0.0</entry>
I have add prefix on all changelog entry.

2020-11-01 15:08 UTC, cmb69 commented on reference/win32service/functions/win32-delete-service.xml
> +        <entry>Throw <literal>ValueError</literal> on wrong data in parameters. Throw <literal>Win32ServiceException</literal> on error. The function return <type>void</type>.</entry>
Note that the 80 characters are rather a soft limit; up to 100 characters may be quite okay as well.

2020-11-01 15:25 UTC, Girgias commented on reference/win32service/functions/win32-send-custom-control.xml
> +      </para>
Now that I think about it, wouldn't it be better to move this to the  `<refsect1 role="errors">` section?

2020-11-01 16:01 UTC, Girgias commented on reference/win32service/win32serviceexception.xml
> +    to the older constant name.
How about this?
```
The exception replaces the old mechanism where the error value needed to be compared to constants to detect which error was emitted. The Exception code is equal to the value of the error value and the exception message is based on the corresponding constant name.
```

2020-11-01 16:37 UTC, macintoshplus commented on reference/win32service/win32serviceexception.xml
> +    to the older constant name.
Yes

2020-11-26 20:24 UTC, macintoshplus commented on reference/win32service/functions/win32-send-custom-control.xml
> +      </para>
@Girgias I have moved this error into `errors` section. It's good ?

2020-11-27 16:21 UTC, Girgias requested changes
Sorry took me while to get round to this.

Please pay attention to indentation which is 1 space per level in XML, 4 spaces for PHP examples.
If you can update the sections and changelogs similarly to what I've done for the first example, as we want the most recent versions to be on top.

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/constants.xml
> +      These constants are no longer used as of Win32Service 1.0.0.
```suggestion
      These constants are no longer in use as of Win32Service 1.0.0.
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +  </para>
```suggestion
  <para>
   &return.void;
  </para>
  <para>
   Prior to version 1.0.0, &win32service.noerror.false.error;
  </para>
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +      </row>
```suggestion
      <row>
       <entry>PECL win32service 1.0.0</entry>
       <entry>
        Throws a <classname>ValueError</classname> on invalid data in parameters,
        previously &false; was returned.
       </entry>
      </row>
      <row>
       <entry>PECL win32service 1.0.0</entry>
       <entry>
        Throws a <classname>Win32ServiceException</classname> on error,
        previously &false; was returned.
       </entry>
      </row>
      <row>
       <entry>PECL win32service 1.0.0</entry>
       <entry>
        The return type is now <type>void</type>, previously it was (describe type here).
       </entry>
      </row>
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +    As of version 1.0.0, a <classname>ValueError</classname> is throw if the
```suggestion
    A <classname>ValueError</classname> is thrown if the 
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-continue-service.xml
> +    <classname>Win32ServiceException</classname> on error.
```suggestion
    A <classname>Win32ServiceException</classname> is thrown on error.
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-create-service.xml
> +  </para>
Same as above

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-create-service.xml
> +   </para>
Same as above (also indentation nits)

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-create-service.xml
> +      </row>
Same as above (split into multiple rows)

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-set-service-exit-code.xml
> +, if SAPI is not <literal>"cli"</literal>, this function emits an
```suggestion
   Prior to version 1.0.0, if the SAPI is not <literal>"cli"</literal>, this function emits an
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-set-service-exit-mode.xml
> +is changed. When the exit mode is not gracefuly, the exit code used can be set
```suggestion
   If <parameter>gracefulMode</parameter> parameter is provided, the exit mode
   is changed. When the exit mode is not gracefuly, the exit code used can be set
```
Nit indentation

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-set-service-exit-mode.xml
> +, if SAPI is not <literal>"cli"</literal>, this function emits an
```suggestion
   Prior to version 1.0.0, if SAPI is not <literal>"cli"</literal>, this function emits an
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/functions/win32-start-service-ctrl-dispatcher.xml
> +<constant>E_ERROR</constant> level error.
```suggestion
   Prior to version 1.0.0, if SAPI is not <literal>"cli"</literal>, this function emits an 
   <constant>E_ERROR</constant> level error.
```

2020-11-27 16:21 UTC, Girgias commented on reference/win32service/versions.xml
> +
Unnecessary line break

2020-11-28 21:01 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +      </row>
Changed

2020-11-28 21:01 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +  </para>
Changed

2020-11-28 21:02 UTC, macintoshplus commented on reference/win32service/constants.xml
> +      These constants are no longer used as of Win32Service 1.0.0.
Changed

2020-11-28 21:02 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +    As of version 1.0.0, a <classname>ValueError</classname> is throw if the
Changed

2020-11-28 21:02 UTC, macintoshplus commented on reference/win32service/functions/win32-continue-service.xml
> +    <classname>Win32ServiceException</classname> on error.
Changed

2020-11-28 21:02 UTC, macintoshplus commented on reference/win32service/functions/win32-create-service.xml
> +  </para>
Changed

2020-11-28 21:02 UTC, macintoshplus commented on reference/win32service/functions/win32-create-service.xml
> +   </para>
All changed

2020-11-28 21:03 UTC, macintoshplus commented on reference/win32service/functions/win32-create-service.xml
> +      </row>
All changed

2020-11-28 21:03 UTC, macintoshplus commented on reference/win32service/functions/win32-set-service-exit-code.xml
> +, if SAPI is not <literal>"cli"</literal>, this function emits an
Changed

2020-11-28 21:03 UTC, macintoshplus commented on reference/win32service/functions/win32-set-service-exit-mode.xml
> +, if SAPI is not <literal>"cli"</literal>, this function emits an
Changed

2020-11-28 21:03 UTC, macintoshplus commented on reference/win32service/functions/win32-start-service-ctrl-dispatcher.xml
> +<constant>E_ERROR</constant> level error.
Changed

2020-11-28 21:03 UTC, macintoshplus commented on reference/win32service/versions.xml
> +
Changed

2020-11-29 01:15 UTC, Girgias approved these changes
LGTM, do you have commit karma on doc-en?

2020-11-29 13:50 UTC, cmb69 commented
Thank you for the PR! I reverted most of the unrelated whitespace changes, to make it a bit easier for translators (who certainly have a lot of work to do right now, due to PHP 8).

2020-11-29 13:52 UTC, closed without merging