Add call-user-func-array Changelog
php/doc-en pull request #1714
Opened 2022-07-22 15:36 UTC by bburnichon

Indicates change in keys handling

2022-07-22 15:52 UTC, cmb69 requested changes
Thank you!

2022-07-22 15:52 UTC, cmb69 commented on reference/funchand/functions/call-user-func-array.xml
> +        <parametername>args</parametername> keys will now be interpreted as parameter names, instead of being silently ignored..
Double full-stop:
```suggestion
        <parametername>args</parametername> keys will now be interpreted as parameter names, instead of being silently ignored.
```

2022-07-25 08:34 UTC, bburnichon commented
Looks like I did not follow the DTD for the XML. I am not used to this one and do not know what I should do. I took an example somewhere else in the doc. Any hints?

2022-07-25 09:05 UTC, cmb69 commented
There are skeletons for most of the documentation pages in https://github.com/php/doc-base/tree/master/RFC/skeletons/.

Anyway, this looks good now. Thank you!

2022-07-25 09:05 UTC, merged