Updating mysqli docs: mysqli::__construct
php/doc-en pull request #178
Opened 2020-11-04 23:23 UTC by kamil-tekiela

This is yet another PR attempting to modernize and explain better mysqli manual. 
Changes:
1. Provided new code examples.  
First, examples with exception mode enabled and setting the correct charset (the typo in output was fixed, but also changed to "or similar"). Then, a modernized example of extending mysqli class. Followed by the examples of manual error checking for completeness. 
2. Added a new sentence to the first parameter "The TCP/IP protocol is used if a host name and port number are provided together e.g. `localhost:3308`"
3. Return section now split up for all 3 "variants". Constructor only returns an instance, function returns an instance or false, and the method returns null or false. 
4. Added errors section. I was not sure about this, but I decided that it is very relevant for people who would like to catch the exception and are looking for its name. 
5. Changed the wording of some sentences for easier reading.
6. Removed the outdated and unnecessary example from `mysqli_connect` page. We should either keep a separate documentation page for each variant (e.g. like we do with `mysqli_real_connect`) or maintain all of them together and keep `mysqli_connect` page as an alias stub page only. However, given that the only difference is the return value I added a note pointing it out.

2021-01-07 16:23 UTC, afilina commented on reference/mysqli/functions/mysqli-connect.xml
> -   <title><function>mysqli_connect</function> example</title>
There is indeed no point in duplicating the example if this method is an alias.

2021-01-07 17:49 UTC, afilina requested changes
Thank you very much for all the improvements!
I made multiple suggestions for your consideration.

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +/* Setting the proper charset after establishing a connection */
```suggestion
/* Set the desired charset after establishing a connection */
```

I would avoid referring to it as the "proper" charset because it depends, but it's good to nudge people towards it in the example.

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +/* Setting the proper charset after establishing a connection */
```suggestion
/* Set the desired charset after establishing a connection */
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +/* Setting the proper charset after establishing a connection */
```suggestion
/* Set the desired charset after establishing a connection */
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +/* Setting the proper charset after establishing a connection */
```suggestion
/* Set the desired charset after establishing a connection */
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +class MyMysqli extends mysqli {
```suggestion
class FooMysqli extends mysqli {
```

"MyMy" can be a bit confusing to read.

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +$db = new MyMysqli('localhost', 'my_user', 'my_password', 'my_db', 3306, null, 'utf8mb4');
```suggestion
$db = new FooMysqli('localhost', 'my_user', 'my_password', 'my_db', 3306, null, 'utf8mb4');
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +	public function __construct($host, $user, $pass, $db, $port, $socket, $charset) {
I don't think that this is the best example. We shouldn't change the signature of the method that we're overloading. It's not a good practice. We can "overload" a constructor using a static constructor. Example: https://3v4l.org/37ToN

If static constructors make the example too complex for beginners, perhaps we can add an example that doesn't require overloading of the constructor.

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +   <para>If error reporting is disabled, the developer is responsible for failure checking and their proper handling</para>
```suggestion
   <para>If error reporting is disabled, the developer is responsible for checking and handling failures</para>
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +}
```suggestion
mysqli_reporting(MYSQLI_REPORT_OFF);
$mysqli = new mysqli('localhost', 'my_user', 'my_password', 'my_db');
if ($mysqli->connect_errno) {
	throw new RuntimeException('mysqli connection error: ' . $mysqli->connect_error);
}
```

1. Explicitly turn off error reporting instead of nudging people towards`@`. It also makes the example more similar to the others where `mysqli_reporting` is used.
2. Throw an exception instead of calling `exit;`, which avoids all sorts of problems down the line, especially with unit tests.

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +	exit;
```suggestion
 throw new RuntimeException('mysqli error: ' . $mysqli->error);
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +}
```suggestion
mysqli_reporting(MYSQLI_REPORT_OFF);
$mysqli = mysqli_connect('localhost', 'my_user', 'my_password', 'my_db');
if (mysqli_connect_errno()) {
	throw new RuntimeException('mysqli connection error: ' . mysqli_connect_error());
}
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +	exit;
```suggestion
	throw new RuntimeException('mysqli error: ' . mysqli_error($mysqli));
```

2021-01-07 17:49 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +    if the connection failed, use either the
```suggestion
    &style.oop; only: If the connection fails, an object is still returned. To check 
    whether the connection failed, use either the 
```

2021-01-07 20:40 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +       The TCP/IP protocol is used if a host name and port number are provided together e.g. <literal>localhost:3308</literal>.
Sure, it doesn't matter much here. The idea was just to show the difference. 3307/3308 is also a commonly used port e.g. on my own server, the default port is actually 3307 for MariaDB. I understand though that PHP has port 3306 set as the default port which means that if users like me want to connect to a server listening on port 3307 or 3308 they have to provide the port number which makes this a common scenario.

2021-01-07 20:52 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +   <methodname>mysqli::__construct</methodname> always returns an object which represents the connection to a MySQL Server,
There are 3 methods/functions described on this page. It needs to be explicitly stated how each of them differs. Each one has different possible return values.

2021-01-09 19:40 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +}
This is a good suggestion, but the idea here was to silence all errors including warnings. I think many people are used to this kind of error suppression, although I agree this is a terrible practice. 

If we are to make it more explicit, then do you mind if I prepend `error_reporting(0);` to the example? It will make it clear that PHP errors go hand in hand with mysqli errors.

2021-01-09 19:52 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +	public function __construct($host, $user, $pass, $db, $port, $socket, $charset) {
I don't like my example, but I am not a big fan of yours, either. I don't think it's a good example of polymorphism. I would rather do what you suggested at the end. We should come up with a better example of extending mysqli class that doesn't involve changing constructor's signature. I haven't got anything in mind at the moment. 

The main thing is that both my and your example is much better than the existing one. :)

Another thing we could do is simply remove that example, but I would prefer to avoid that. We could instead use the [example I have been using for teaching purposes](https://stackoverflow.com/a/64884939/1839439) or something similar. I am open to ideas.

2021-01-11 20:45 UTC, afilina commented on reference/mysqli/mysqli/construct.xml
> +}
Yes, that's a reasonable alternative.

2021-01-11 21:22 UTC, afilina commented
I reviewed the latest changes. LGTM.

2021-01-12 15:10 UTC, cmb69 commented
Thank you!

2021-01-12 15:11 UTC, closed without merging