ArrayAccess:: method need a return type
php/doc-en pull request #1798
Opened 2022-09-06 11:42 UTC by nenge123

ArrayAccess::offsetSet($offset, $value):void
ArrayAccess::offsetExists($offset):bool
ArrayAccess::offsetUnset($offset):void
ArrayAccess::offsetGet($offset):mixed

2022-09-06 14:02 UTC, cmb69 reviewed
Thank you for the PR!

Given that the manual is supposed to document PHP 7 and PHP 8, adding return types would be [confusing for PHP 7 users](https://3v4l.org/CnaNe). What about adding `#[ReturnTypeWillChange]` attributes? That would [work for PHP 7 and 8](https://3v4l.org/Ae1nK).

2022-09-06 14:15 UTC, sy-records requested changes

2022-09-06 14:15 UTC, sy-records commented on language/predefined/arrayaccess.xml
> + */
There is no need to state it here.
```suggestion

```

2022-09-06 14:15 UTC, sy-records commented on language/predefined/arrayaccess.xml
> +    public function offsetSet($offset, $value):void {
Using `#[ReturnTypeWillChange]` is the best

2023-01-18 16:35 UTC, afilina commented
@nenge123: There is an unaddressed comment.
@sy-records: Asked for a second review to make sure that your change request was addressed the way you expected.

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    );
```suggestion
    public $container = [
        "one"   => 1,
        "two"   => 2,
        "three" => 3,
    ];
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    public function offsetGet($offset):mixed {
Nit:
```suggestion
    public function offsetGet($offset): mixed {
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
>      public function __construct() {
```suggestion
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
>      }
```suggestion
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    public function offsetSet($offset, $value):void {
```suggestion
    public function offsetSet($offset, $value): void {
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    public function offsetExists($offset):bool {
```suggestion
    public function offsetExists($offset): bool {
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    public function offsetUnset($offset):void {
```suggestion
    public function offsetUnset($offset): void {
```

2023-07-26 13:14 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +print_r($obj->container);
```suggestion
```

2023-07-26 13:15 UTC, Girgias commented on language/predefined/arrayaccess.xml
> +    public function offsetSet($offset, $value): void {
```suggestion
    ];

    public function offsetSet($offset, $value): void {
```

2023-07-26 13:17 UTC, merged