Updating mysqli: fixing mysqli_report
php/doc-en pull request #180
Opened 2020-11-06 22:27 UTC by kamil-tekiela

Couple of much needed fixes:

1. Changed the wording and the explanation to make it clearer what this function actually does.  
Remove "A function helpful in improving queries during code development and testing." which might be true but is also unnecessary and misleading. Besides, in OO style it is not a function...
2. This function [never returns `false`.](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_report.c#L34) 
3. Fixed broken examples. Come on, this is just a disgrace that a PHP manual has broken examples. 
4. Added a third example showing the most common use case of enabling errors without bad index errors. 
5. Removed links to `mysqli_debug` and `mysqli_dump_debug_info`. They're not really related and having them in See also can be quite confusing.

2021-01-07 18:01 UTC, afilina requested changes
Added a few suggestions. Otherwise, LGTM.

2021-01-07 18:01 UTC, afilina commented on reference/mysqli/mysqli_driver/report-mode.xml
> -    <member><function>mysqli_dump_debug_info</function></member>
I'd argue that those are still related, because error reporting and debugging are within the same area of interests.

2021-01-09 18:30 UTC, kamil-tekiela commented on reference/mysqli/mysqli_driver/report-mode.xml
> -    <member><function>mysqli_dump_debug_info</function></member>
I can see where you are coming from, but that is actually something that I would like to prevent. I don't want people confusing these two functions with error reporting. `mysqli_debug` is meant for debugging of mysqli internal code, not userland code. `mysqli_dump_debug_info` triggers a debug function in the MySQL C API, which can be helpful to debug problems but is not part of error reporting. What I am proposing is not removing them from the manual, just removing a link from the `mysqli_report` page. I want to keep the links in the "See also" section relevant only for error reporting. MySQLi debugging is described on other pages in the manual.

2021-01-09 19:54 UTC, afilina approved these changes

2021-01-10 12:32 UTC, cmb69 commented
Thank you!

Please note that we do not document the return value in case of failing zend_parse_parameters(); this is already covered by the note on https://www.php.net/manual/en/functions.internal.php, and as of PHP 8.0.0 a TypeErrror is thrown in this case.

Also note that code examples in the manual should be indented with four spaces instead of tabs.

2021-01-10 12:32 UTC, closed without merging