add docs for `ini_parse_quantity` function
php/doc-en pull request #1810
Opened 2022-09-08 14:38 UTC by realFlowControl

Hello there :vulcan_salute:

this will add the documentation for the `ini_parse_quantity` function as found in #1803 

Kind regards
Florian

2022-09-30 11:39 UTC, Girgias commented
Just landed [0f8b9eb49bd644f07175e9191d2cc146737446ad](https://github.com/php/php-src/commit/0f8b9eb49bd644f07175e9191d2cc146737446ad) to add support for ``0b`` and ``0o`` prefixes, wondering if it makes sense to add examples with prefixes in the docs? (hex has worked since forever)

2022-09-30 11:47 UTC, devnexen commented on reference/info/functions/ini-parse-quantity.xml
> +       Multiplier can be any of <literal>k</literal>/<literal>K</literal> (1024),
I would suggest
`The following multipliers are supported :
  <literal>k</literal>/<literal>K</literal> (1024),
...
`

2022-09-30 11:47 UTC, devnexen commented on reference/info/functions/ini-parse-quantity.xml
> +   <literal>0</literal> in case of unparsable shorthand and raises a
`raises an <constant>E_WARNING</constant> level error` or something approaching

2022-09-30 12:11 UTC, cmb69 commented on reference/info/functions/ini-parse-quantity.xml
> +       <literal>g</literal>/<literal>G</literal> (1073741824).
I suggest to mark-up the numbers:
```suggestion
       Multiplier can be any of <literal>k</literal>/<literal>K</literal> (<literal>1024</literal>),
       <literal>m</literal>/<literal>M</literal> (<literal>1048576</literal>),
       <literal>g</literal>/<literal>G</literal> (<literal>1073741824</literal>).
```

2022-09-30 12:12 UTC, cmb69 commented
> wondering if it makes sense to add examples with prefixes in the docs?

I think it would make more sense, to add some `ini_get()` examples.

2022-09-30 12:14 UTC, cmb69 commented on reference/info/functions/ini-parse-quantity.xml
> +
```suggestion
 <refsect1 role="seealso">
  &reftitle.seealso;
  <simplelist>
   <member><function>ini_get</function></member>
  </simplelist>
 </refsect1>
```

2022-11-03 18:13 UTC, devnexen commented
Looks good but cc @cmb69

2022-11-03 20:25 UTC, realFlowControl commented on reference/info/functions/ini-parse-quantity.xml
> +   <literal>0</literal> in case of unparsable shorthand and raises a
:heavy_check_mark:

2022-11-03 20:42 UTC, realFlowControl commented
Hey there,
sorry for taking so long to come back to this PR. I think I incorporated all your hints :smile: 
Hope everything is fine, if there is something else, just ping.
@Girgias, @cmb69: I added the prefixes to the docs, I think it should be there for completeness.

2022-11-04 11:50 UTC, Girgias commented on reference/info/functions/ini-parse-quantity.xml
> +   Returns the interpreted size in bytes as &integer; on success, or
```suggestion
   Returns the interpreted size in bytes as an &integer; on success, or
```

2022-11-04 11:57 UTC, Girgias requested changes
Not totally sure for the wording of the error section, but warnings should ideally not be mentioned in the return value section (yes the manual is not super consistent on this)

2022-11-04 11:57 UTC, Girgias commented on reference/info/functions/ini-parse-quantity.xml
> + </refsect1>
```suggestion
 <refsect1 role="returnvalues">
  &reftitle.returnvalues;
  <para>
   Returns the interpreted size in bytes as an &integer;.
  </para>
 </refsect1>

 <refsect1 role="errors">
  &reftitle.errors;
  <para>
   If the value cannot be parsed, or an invalid multiplier is used, an <constant>E_WARNING</constant> is raised.
  </para>
 </refsect1>
```

2022-11-04 11:57 UTC, Girgias commented on reference/info/functions/ini-parse-quantity.xml
> +
Maybe add some examples for the prefixes?

2022-12-01 13:16 UTC, realFlowControl commented on reference/info/functions/ini-parse-quantity.xml
> +
Thanks for the hint, I added two additional examples, one with binary and one octal.

2022-12-05 14:19 UTC, cmb69 reviewed
Besides the missing link, this looks good to me.

2022-12-05 14:19 UTC, cmb69 commented on reference/info/functions/ini-parse-quantity.xml
> +   Returns the interpreted size in bytes on success from an ini shorthand.
I think it makes sense to link to the explanation of ini shorthands:
```suggestion
   Returns the interpreted size in bytes on success from an <link linkend="faq.using.shorthandbytes">ini shorthand</link>.
```

2022-12-05 16:28 UTC, realFlowControl commented on reference/info/functions/ini-parse-quantity.xml
> +       octal (prefixed with <literal>0o</literal> or <literal>0O</literal>) or binary (prefixed with
You are right, just added this in docs and example

2022-12-05 16:50 UTC, cmb69 approved these changes
Thank you!

2022-12-05 17:11 UTC, Girgias approved these changes

2022-12-05 17:11 UTC, merged