Updating mysqli: Improving Quick Start guide
php/doc-en pull request #184
Opened 2020-11-11 23:27 UTC by kamil-tekiela

This PR aims to fix Quick Start guide in mysqli by removing manual error checking where possible, using OO style for function names and in the code (to encourage developers to use it more in new code), and fixing See also links. 

Other changes:
- Fixed grammar and typos in some places
- Changed the wording on Multiple Statements page. Previous text sounded as if SQL injection is only possible with multiple statements. 
- See also links were removed/added in some place. Although there seems to be no consistency or logic in them.
- Closing tags were removed from examples. They were not there in the beginning and adding them is a bad coding practice.
- It is possible to open TCP/IP connection using `localhost:3306`. That sentence has been changed to reflect what can be done rather than what can't be done.
- Some examples were removed as they were unnecessary and only bloated the page.
- Variable `$res` was renamed to `$result`
- Examples of executing queries were simplified. 
- Call to `$stmt->more_results()` in SP examples was removed. It was confusing and not needed in this context.
- `$stmt->store_result()` was added to the last example in SP to avoid the "Out of sync" error.

Hopefully, this will make the page more useful to people who are only starting with mysqli. Having simple examples showing the best practices is very important.

2021-01-07 19:23 UTC, afilina requested changes

2021-01-07 19:23 UTC, afilina commented on reference/mysqli/quickstart.xml
> -]]>
The example has been removed, but the text above still refers to multi-inserts. I don't see such an example elsewhere on the page either. I think that it's a valuable example.

2021-01-07 19:23 UTC, afilina commented on reference/mysqli/quickstart.xml
> +   <emphasis role="bold">Quick prepared/non-prepared statement comparison</emphasis>
```suggestion
   <emphasis role="bold">Quick comparison of prepared and non-prepared statements</emphasis>
```

2021-01-07 19:23 UTC, afilina commented on reference/mysqli/quickstart.xml
> +$mysqli->query("INSERT INTO test(id) VALUES (1), (2), (3)");
The example being replaced does not have all these statements. I suppose that they were inferred from the previous example. Perhaps we can get rid of them here and jump straight to `$stmt = $mysqli->prepare("CALL p()")` to make this example more focused.

2021-01-07 19:23 UTC, afilina commented on reference/mysqli/quickstart.xml
> +   but it requires special handling.
I kinda prefer the original wording because it mentions the advantages. It's up to you though.

2021-01-07 22:49 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> +    <member><function>mysqli_init</function></member>
`mysqli::init` and `mysqli_init` are two completely different functions. The PR is to deprecate `mysqli::init()` which serves almost no purpose. `mysqli_init()` is still a useful function in the procedural set of mysqli functions. While `new mysqli()` can replace `mysqli_init()`, the function is just a procedural variant of creating a mysqli object without establishing a connection. 

See also RFC I have created https://wiki.php.net/rfc/improve_mysqli

2021-01-07 23:00 UTC, kamil-tekiela commented
@afilina Thank you very much for your reviews, Anna! I really appreciate someone taking the time to go over the changes and submit improvement suggestions. I have already accepted some of your proposals, but I will need more time to review the other ones and commit them to my PRs.

2021-01-09 20:17 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> +   and establishing the network connection with <methodname>mysqli::real_connect</methodname>.
I prefer not to add any more examples to this PR. I might suggest a new PR with an example later.

2021-01-09 21:01 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
>  }
I don't see any reason why would we want that. The binding should happen only once, because the variables bound do not change within the loop.

2021-01-09 21:15 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> +   but it requires special handling.
I removed that line on purpose. I do not want people to think that there is an advantage of using `multi_query()` over prepared statements. In fact, I still haven't found any good reason to use that function. Let's not give people any ideas that it somehow improves performance, at the cost of security and usability. Besides, I haven't been able to understand what it meant by "reduces client-server". Don't we need to make the same number of trips to the server (1 multi_query + N next_result)?  Unless it was meant to be all UPSERT queries where we discard the results. Either way, that sentence didn't make much sense to me.

2021-01-09 21:31 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> +$mysqli->query("INSERT INTO test(id) VALUES (1), (2), (3)");
True, but I wanted all examples to be self-contained. You can copy the code and run it to produce the shown results (which are missing in this case). I propose that we make all examples self-contained and this is why I just now added the output too.

2021-01-09 21:41 UTC, kamil-tekiela commented on reference/mysqli/quickstart.xml
> -]]>
Ok, if you think the example was valuable then I will try to add it back. 

The reason why I removed it is because it was neither here nor there. That page talks about prepared statements and how to bind parameters and then out of a sudden we have an example of a non-prepared query with constant values.  How does it apply to prepared statements? How can I replace the constant literals with placeholders? It might be a nice piece of advice, but it doesn't belong here. Unless we should how to bind parameters to multi-INSERT query then this example shouldn't be there. One can always check the MySQL manual for an example of such syntax.

2021-01-11 19:16 UTC, afilina commented on reference/mysqli/quickstart.xml
> +    <member><function>mysqli_init</function></member>
Right, thanks for clarifying this for me.

2021-01-11 19:30 UTC, afilina approved these changes

2021-01-11 19:30 UTC, afilina commented on reference/mysqli/quickstart.xml
>  }
My bad, I didn't realize that `$stmt->bind_param` receives arguments by reference.

2021-01-11 19:30 UTC, afilina commented on reference/mysqli/quickstart.xml
> +$mysqli->query("INSERT INTO test(id) VALUES (1), (2), (3)");
I'm okay with making them self-contained in the quickstart guide, but not everywhere. If that is also what you had in mind, then we're in agreement.

2021-03-08 16:02 UTC, afilina commented
Looks like there is nothing preventing this from being merged.

2021-03-08 17:28 UTC, cmb69 commented
Thank you both!

2021-03-08 17:29 UTC, closed without merging