Document new 8.2 curl constants
php/doc-en pull request #1911
Opened 2022-10-23 20:31 UTC by ekinhbayar

Hi, thought I can help with #1803 regarding the curl constants. Made a list below, but I could use some pointers as to what goes where, which other pages need to be updated, if I'm missing any I had planned below.

- [x] Updated constants list and [getinfo options](https://www.php.net/manual/en/function.curl-getinfo.php)

CURLINFO_PROXY_ERROR (libcurl >= 7.73.0) https://curl.se/libcurl/c/CURLINFO_PROXY_ERROR.html
CURLINFO_REFERER     (libcurl >= 7.76.0) https://curl.se/libcurl/c/CURLINFO_REFERER.html
CURLINFO_RETRY_AFTER (libcurl >= 7.66.0) https://curl.se/libcurl/c/CURLINFO_RETRY_AFTER.html

- [ ] Update constants list and [curl_version](https://www.php.net/manual/en/function.curl-version.php)
CURL_VERSION_GSASL (libcurl >= 7.76.0)
CURL_VERSION_HSTS (libcurl >= 7.74.0)
CURL_VERSION_HTTP3 (libcurl >= 7.66.0)
CURL_VERSION_UNICODE (libcurl >= 7.72.0)
CURL_VERSION_ZSTD (libcurl >= 7.72.0)

- [ ] Update constants list and [setopt options](https://www.php.net/manual/en/function.curl-setopt.php)
CURLOPT_AWS_SIGV4 (libcurl >= 7.75.0)
CURLOPT_CAINFO_BLOB (libcurl >= 7.77.0)
CURLOPT_DOH_SSL_VERIFYHOST (libcurl >= 7.76.0)
CURLOPT_DOH_SSL_VERIFYPEER (libcurl >= 7.76.0)
CURLOPT_DOH_SSL_VERIFYSTATUS (libcurl >= 7.76.0)
CURLOPT_HSTS_CTRL (libcurl >= 7.74.0)
CURLOPT_HSTS (libcurl >= 7.74.0)
CURLOPT_MAIL_RCPT_ALLLOWFAILS (libcurl >= 7.69.0)
CURLOPT_MAXAGE_CONN (libcurl >= 7.65.0)
CURLOPT_MAXFILESIZE_LARGE
CURLOPT_MAXLIFETIME_CONN (libcurl >= 7.80.0)
CURLOPT_PROXY_CAINFO_BLOB (libcurl >= 7.77.0)
CURLOPT_SASL_AUTHZID (libcurl >= 7.66.0)
CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 (libcurl >= 7.80.0)
CURLOPT_SSL_EC_CURVES (libcurl >= 7.73.0)
CURLOPT_UPKEEP_INTERVAL_MS (libcurl >= 7.62.0)
CURLOPT_UPLOAD_BUFFERSIZE (libcurl >= 7.62.0)
CURLOPT_XFERINFOFUNCTION (libcurl >= 7.32.0)

- [ ] Update constants list and [setopt options](https://www.php.net/manual/en/function.curl-setopt.php)
CURLAUTH_AWS_SIGV4 (libcurl >= 7.75.0)

- [ ] alt_svc related
CURLALTSVC_H1 (libcurl >= 7.64.1)
CURLALTSVC_H2 (libcurl >= 7.64.1)
CURLALTSVC_H3 (libcurl >= 7.64.1)
CURLALTSVC_READONLYFILE (libcurl >= 7.64.1)
CURLOPT_ALTSVC_CTRL (libcurl >= 7.64.1)
CURLOPT_ALTSVC (libcurl >= 7.64.1)

- [ ] PROTO_*
CURLPROTO_MQTT (libcurl >= 7.71.0)

- [ ] PX_*
CURLPX_BAD_ADDRESS_TYPE (libcurl >= 7.73.0)
CURLPX_BAD_VERSION (libcurl >= 7.73.0)
CURLPX_CLOSED (libcurl >= 7.73.0)
CURLPX_GSSAPI (libcurl >= 7.73.0)
CURLPX_GSSAPI_PERMSG (libcurl >= 7.73.0)
CURLPX_GSSAPI_PROTECTION (libcurl >= 7.73.0)
CURLPX_IDENTD_DIFFER (libcurl >= 7.73.0)
CURLPX_IDENTD (libcurl >= 7.73.0)
CURLPX_LONG_HOSTNAME (libcurl >= 7.73.0)
CURLPX_LONG_PASSWD (libcurl >= 7.73.0)
CURLPX_LONG_USER (libcurl >= 7.73.0)
CURLPX_NO_AUTH (libcurl >= 7.73.0)
CURLPX_OK (libcurl >= 7.73.0)
CURLPX_RECV_ADDRESS (libcurl >= 7.73.0)
CURLPX_RECV_AUTH (libcurl >= 7.73.0)
CURLPX_RECV_CONNECT (libcurl >= 7.73.0)
CURLPX_RECV_REQACK (libcurl >= 7.73.0)
CURLPX_REPLY_ADDRESS_TYPE_NOT_SUPPORTED (libcurl >= 7.73.0)
CURLPX_REPLY_COMMAND_NOT_SUPPORTED (libcurl >= 7.73.0)
CURLPX_REPLY_CONNECTION_REFUSED (libcurl >= 7.73.0)
CURLPX_REPLY_GENERAL_SERVER_FAILURE (libcurl >= 7.73.0)
CURLPX_REPLY_HOST_UNREACHABLE (libcurl >= 7.73.0)
CURLPX_REPLY_NETWORK_UNREACHABLE (libcurl >= 7.73.0)
CURLPX_REPLY_NOT_ALLOWED (libcurl >= 7.73.0)
CURLPX_REPLY_TTL_EXPIRED (libcurl >= 7.73.0)
CURLPX_REPLY_UNASSIGNED (libcurl >= 7.73.0)
CURLPX_REQUEST_FAILED (libcurl >= 7.73.0)
CURLPX_RESOLVE_HOST (libcurl >= 7.73.0)
CURLPX_SEND_AUTH (libcurl >= 7.73.0)
CURLPX_SEND_CONNECT (libcurl >= 7.73.0)
CURLPX_SEND_REQUEST (libcurl >= 7.73.0)
CURLPX_UNKNOWN_FAIL (libcurl >= 7.73.0)
CURLPX_UNKNOWN_MODE (libcurl >= 7.73.0)
CURLPX_USER_REJECTED (libcurl >= 7.73.0)

- [ ] SSLOPT_*
CURLSSLOPT_AUTO_CLIENT_CERT (libcurl >= 7.77.0)
CURLSSLOPT_NATIVE_CA (libcurl >= 7.71.0)
CURLSSLOPT_NO_PARTIALCHAIN (libcurl >= 7.68.0)
CURLSSLOPT_REVOKE_BEST_EFFORT (libcurl >= 7.70.0)

- [ ] CURLE_PROXY (libcurl >= 7.73.0)

- [ ] CURLFTPMETHOD_DEFAULT

- [ ] CURLMOPT_MAX_CONCURRENT_STREAMS (libcurl >= 7.67.0)

- [ ] HSTS related
CURLHSTS_ENABLE (libcurl >= 7.74.0)
CURLHSTS_READONLYFILE (libcurl >= 7.74.0)

2022-10-24 22:19 UTC, ekinhbayar commented
Did not update and [curl_version](https://www.php.net/manual/en/function.curl-version.php) page for the CURL_VERSION new flags, looks like we never kept the full list there.

2022-10-24 23:30 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +             the one it finds most secure.
I can drop these changes for _ANY and _ANYSAFE. These changes felt easier to maintain, given the addition of _AWS_SIGV4 means there can be more, but I'm not going to die on that hill.

2022-11-04 12:34 UTC, Girgias requested changes

2022-11-04 12:34 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 8.2.0 and cURL >= 7.73.0
We use ``as of`` for versions instead of ``since``

2022-11-04 12:36 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +             the one it finds most secure.
Looks reasonable to me :)

2022-11-04 12:39 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +            Available since PHP 8.2.0 and cURL 7.77.0
For versions we use "as of" instead of "since"

2022-11-04 12:40 UTC, Girgias commented
So other than the nits, the first 3 commits look good to me. The cURL manual is a mess so I'm not exactly sure where everything is meant to go, maybe @cmb69 knows?

2022-11-04 14:15 UTC, cmb69 commented on reference/curl/constants.xml
> +     Available since PHP 8.2.0 and cURL >= 7.73.0
Yeah, I think we should start doing that even for ext/curl (at least for new stuff; there are already 166 "since"s in that file alone).

2022-11-04 14:27 UTC, cmb69 reviewed
Thank you for the PR! Looks mostly good (I've left some comments) for now.

> The cURL manual is a mess so I'm not exactly sure where everything is meant to go, maybe @cmb69 knows?

Looks good so far (in the long run we need to improve the structure, but given we're close to PHP 8.2.0 GA, let's postpone this).

2022-11-04 14:27 UTC, cmb69 commented on reference/curl/constants.xml
> +     Available since PHP 8.2.0 and cURL >= 7.76.0
Should probably drop the `>=` here (and elsewhere):
```suggestion
     Available since PHP 8.2.0 and cURL 7.76.0
```

2022-11-04 14:27 UTC, cmb69 commented on reference/curl/constants.xml
> +     Available since PHP 8.2.0 and cURL >= 7.66.0
```suggestion
     Available since PHP 8.2.0 and cURL 7.66.0
```

2022-11-04 14:27 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +             This option overrides the other auth types you might have set in CURLOPT_HTTPAUTH.
```suggestion
             This option overrides the other auth types you might have set in <constant>CURLOPT_HTTPAUTH</constant>.
```

2022-11-04 14:27 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +            The name of a PEM file holding one or more certificates to verify the
It might make sense to [define an acronym](https://github.com/php/doc-base/blob/master/entities/acronyms.xml) for PEM ("Privacy-Enhanced Mail"), but than can be done in a completely separate commit; well, actually *should* be done separately, since there are already so many uses of the term.

2022-11-04 14:31 UTC, Girgias commented on reference/curl/constants.xml
> +    <constant>CURLOPT_DOH_SSL_VERIFYPEER</constant>
```suggestion
  <varlistentry xml:id="constant.curlopt-doh-ssl-verifystatus">
   <term>
    <constant>CURLOPT_DOH_SSL_VERIFYSTATUS</constant>
```

Duplicate constant name, not sure which one is which

2022-11-04 23:01 UTC, ekinhbayar commented
Thanks a ton for the reviews! They sure helped a lot. I'll be onto these changes this weekend and try my best to document more and more of these constants following the same notes.

2022-11-06 18:48 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +             <constant>CURLAUTH_AWS_SIGV4</constant>,
With this addition I've marked off CURLAUTH_AWS_SIGV4 from the list, not sure if these are needed to be documented somewhere else besides here

2022-11-06 19:00 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +            The name of a PEM file holding one or more certificates to verify the
I can prepare that as a separate PR if someone else doesn't beat me to it 👍

2022-11-06 19:01 UTC, ekinhbayar commented
I realize some setopt entries define the versions available while others don't. What's the preference regarding this?

2022-11-07 00:23 UTC, Girgias commented
> I realize some setopt entries define the versions available while others don't. What's the preference regarding this?

I think if an entry is available in every cURL version past the minimal version for PHP 7.0 then the version availability can be skipped. Otherwise it should be mentioned.

2022-11-07 00:31 UTC, Girgias commented on reference/curl/constants.xml
> +    <constant>CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256</constant>
```suggestion
  <varlistentry xml:id="constant.curlopt-ssh-host-public-key-sha256">
   <term>
    <constant>CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256</constant>
```

2022-11-07 00:31 UTC, Girgias commented on reference/curl/constants.xml
> +    <constant>CURLOPT_SASL_AUTHZID</constant>
```suggestion
  <varlistentry xml:id="constant.curlopt-sasl-authzid">
   <term>
    <constant>CURLOPT_SASL_AUTHZID</constant>
```

2022-11-07 00:31 UTC, Girgias commented on reference/curl/constants.xml
> +     using the "Certificate Status Request" TLS extension (OCSP stapling).
```suggestion
     Tell cURL to verify the status of the DNS-over-HTTPS server certificate
     using the "Certificate Status Request" TLS extension (OCSP stapling).
```
Whitespace

2022-11-07 14:35 UTC, cmb69 commented
@Girgias, to make the white-space checker happy, you'd need to squash.

2022-11-08 23:26 UTC, ekinhbayar commented
lol, I really thought one would be able to request review from multiple reviewers, sorry for all that ^^. I believe I finally powered through the remaining constants with the last couple commits here. Hoping we can re-trigger the checks :-)

2022-11-09 12:00 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLOPT_UPLOAD_BUFFERSIZE</constant></entry>
The value of `CURLOPT_UPLOAD_BUFFERSIZE` should be an int, but it is in the boolean section.

2022-11-09 12:01 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLOPT_HSTS</constant></entry>
The value of `CURLOPT_HSTS` is supposed to be a string, but it is listed in the integer section.

2022-11-09 12:02 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLOPT_AWS_SIGV4</constant></entry>
The value of `CURLOPT_AWS_SIGV4` is supposed to be a string, but it is listed in the integer section.

2022-11-09 12:06 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           </entry>
Splitting this description across two columns doesn't look right. Instead consider:
```suggestion
           <entry valign="top">
            <simpara>
             Allow RCPT TO command to fail for some recipients.
            </simpara> 
            <simpara>
             When sending data to multiple recipients, by default cURL will abort SMTP conversation if at least one of
             the recipients causes RCPT TO command to return an error. This option tells cURL to ignore errors and
             proceed with the remaining valid recipients. If all recipients trigger RCPT TO failures and this flag is
             set, cURL will abort the SMTP conversation and return the error received from the last RCPT TO command.
            </simpara> 
           </entry>
```

2022-11-09 12:09 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLMOPT_MAX_CONCURRENT_STREAMS</constant></entry>
This is a curl-multi option, so should be described on the [curl_multi_setopt](https://www.php.net/manual/en/function.curl-multi-setopt.php) page.

2022-11-09 12:10 UTC, cmb69 commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLOPT_CAINFO_BLOB</constant></entry>
The value of `CURLOPT_CAINFO_BLOB` is supposed to be a string, but it is in the integer section.

2022-11-09 17:06 UTC, cmb69 commented
`E_TOO_MANY_CONSTANTS` :(

2022-11-09 22:44 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLMOPT_MAX_CONCURRENT_STREAMS</constant></entry>
Ah thank you, so this is where these were.

2022-11-09 23:04 UTC, ekinhbayar commented
Oh noes, I forgot that I used the interface to commit the changes prior to my force push @cmb69 :P which apparently completely nuked your suggested edit for a paragraph I can't remember which 😓

2022-11-09 23:05 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +           <entry valign="top"><constant>CURLOPT_CAINFO_BLOB</constant></entry>
Could you take another looksee at this specific one please? It looks like it is under the string section now

2022-11-10 12:25 UTC, Girgias commented on reference/curl/constants.xml
> +  </varlistentry>
```suggestion
  <varlistentry xml:id="constant.curlsslopt-auto-client-cert">
   <term>
    <constant>CURLSSLOPT_AUTO_CLIENT_CERT</constant>
    (<type>int</type>)
   </term>
   <listitem>
    <simpara>
     Available as of PHP 8.2.0 and cURL 7.77.0
    </simpara>
   </listitem>
  </varlistentry>
  <varlistentry xml:id="constant.curlsslopt-native-ca">
   <term>
    <constant>CURLSSLOPT_NATIVE_CA</constant>
    (<type>int</type>)
   </term>
   <listitem>
    <simpara>
     Available as of PHP 8.2.0 and cURL 7.71.0
    </simpara>
   </listitem>
  </varlistentry>
  <varlistentry xml:id="constant.curlsslopt-no-partialchain">
   <term>
    <constant>CURLSSLOPT_NO_PARTIALCHAIN</constant>
    (<type>int</type>)
   </term>
   <listitem>
    <simpara>
     Available as of PHP 8.2.0 and cURL 7.68.0
    </simpara>
   </listitem>
  </varlistentry>
  <varlistentry xml:id="constant.curlsslopt-revoke-best-effort">
   <term>
    <constant>CURLSSLOPT_REVOKE_BEST_EFFORT</constant>
    (<type>int</type>)
   </term>
   <listitem>
    <simpara>
     Available as of PHP 8.2.0 and cURL 7.70.0
    </simpara>
   </listitem>
  </varlistentry>
```
"As of" instead of "since" (no idea why it's diffing the whole thing)

2022-11-10 12:28 UTC, ekinhbayar commented
Permission to fix all the `since` to be `as of` in a single commit here? :') or should I wait this to be merged and then PR that like a normal person

2022-11-10 12:30 UTC, Girgias commented
> Permission to fix all the `since` to be `as of` in a single commit here? :') or should I wait this to be merged and then PR that like a normal person

Probably can do yes, this is going to be a pain for translators *anyway* since it is cURL. That's probably one of the smallest annoyances

2022-11-10 13:35 UTC, ekinhbayar commented
I think I will fix them all together on a separate PR, just like how I started on the PEM definition

2022-11-11 00:49 UTC, ekinhbayar commented on reference/curl/functions/curl-setopt.xml
> +           </entry>
I can't seem to find a way to reapply this suggestion even after marking it as unresolved :(

2023-01-17 16:14 UTC, ekinhbayar commented
Apologies for the silence here, I think I had done all final suggestions on this branch. I can PR the other two fixes after this one individually. Let me know if I can help further to get these ones marked as done.

2023-02-13 01:44 UTC, Girgias commented
@cmb69 ping. :)

2023-08-02 16:20 UTC, afilina commented
@ekinhbayar There is a failure on `check-whitespace` in the checks. Also, there is a change request from @Girgias. Do you need help with completing this?

2023-08-07 12:15 UTC, ekinhbayar commented
@afilina thanks for the ping! I'll take a look at both and move this forward.

2023-08-07 13:46 UTC, Girgias reviewed
Some wording nits

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 7.0.7 and cURL 7.38.0.
```suggestion
     Available as of PHP 7.0.7 and cURL 7.38.0.
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 7.0.7 and cURL 7.22.0
```suggestion
     Available as of PHP 7.0.7 and cURL 7.22.0
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since cURL 7.15.5
```suggestion
     Available as of cURL 7.15.5
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since cURL 7.15.5
```suggestion
     Available as of cURL 7.15.5
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 7.0.7 and cURL 7.37.0
```suggestion
     Available as of PHP 7.0.7 and cURL 7.37.0
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 7.0.7 and cURL 7.37.0
```suggestion
     Available as of PHP 7.0.7 and cURL 7.37.0
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/constants.xml
> +     Available since PHP 8.2.0 and cURL 7.71.0.
```suggestion
     Available as of PHP 8.2.0 and cURL 7.71.0.
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/functions/curl-getinfo.xml
> +          of the <constant>CURLPX_*</constant> values. The error code will be <constant>CURLPX_OK</constant> if no
```suggestion
          of the <constant>CURLPX_<replaceable>*</replaceable></constant> values.
          The error code will be <constant>CURLPX_OK</constant> if no
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/functions/curl-multi-setopt.xml
> +            should support on connections done using HTTP/2. Valid values range from 1 to 2147483647 (2^31 - 1).
```suggestion
            should support on connections done using HTTP/2. Valid values range from
            <literal>1</literal> to <literal>2147483647</literal> (<literal>2^31 - 1</literal>).
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/functions/curl-multi-setopt.xml
> +            Default is 100.
```suggestion
            Default is <literal>100</literal>.
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +            Default maximum age is set to 118 seconds.
```suggestion
            Default maximum age is set to <literal>118</literal> seconds.
```

2023-08-07 13:46 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +            Default is 60 seconds.
```suggestion
            Default is <literal>60</literal> seconds.
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion

```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/constants.xml
> +
```suggestion
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/functions/curl-getinfo.xml
> +          transfer returned a <constant>CURLE_PROXY</constant> error. The returned value will be exactly one
```suggestion
          <constant>CURLINFO_PROXY_ERROR</constant> - The detailed (SOCKS) proxy error code when the most recent
          transfer returned a <constant>CURLE_PROXY</constant> error. The returned value will be exactly one
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +             native CA store for certificate verification. Works only on Windows
```suggestion
             native CA store for certificate verification. Works only on Windows
```

2023-08-07 13:57 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +            <constant>CURLFTPMETHOD_NOCWD</constant> and
```suggestion
            <constant>CURLFTPMETHOD_NOCWD</constant>, and
```

2023-08-07 14:02 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +           </entry>
Re-suggest CMB suggestion
```suggestion
           <entry valign="top">
            <simpara>
             Allow RCPT TO command to fail for some recipients.
            </simpara> 
            <simpara>
             When sending data to multiple recipients, by default cURL will abort SMTP conversation if at least one of
             the recipients causes RCPT TO command to return an error. This option tells cURL to ignore errors and
             proceed with the remaining valid recipients. If all recipients trigger RCPT TO failures and this flag is
             set, cURL will abort the SMTP conversation and return the error received from the last RCPT TO command.
            </simpara> 
           </entry>
```

2023-08-07 14:02 UTC, Girgias commented on reference/curl/functions/curl-setopt.xml
> +           </entry>
Fucking hell GitHub

2023-08-07 14:05 UTC, merged

2023-08-07 21:09 UTC, ekinhbayar commented
Ah, by the time I sat down for this it seems all has been resolved :-) thank you and sorry for this taking so, so long!

2023-08-07 21:17 UTC, Girgias commented
> Ah, by the time I sat down for this it seems all has been resolved :-) thank you and sorry for this taking so, so long!

It's fine the issues were minors, if you want to do the follow-up on the PEM acronym feel free!