Updates for RFC: Locale-independent case conversion
php/doc-en pull request #1934
Opened 2022-11-03 10:18 UTC by tstarling

* Add a detailed description of what is meant by ASCII case conversion to strtolower() and strtoupper().
* Replace locale-related text on ucfirst(), lcfirst() and ucwords() with text about ASCII case conversion.
* Remove entity note.locale-single-byte since it was only used on ucwords().
* Add changelog entries to all the functions mentioned in the RFC.

2022-11-04 12:10 UTC, Girgias requested changes

2022-11-04 12:10 UTC, Girgias commented on reference/array/constants.xml
> +     characters will be converted.
```suggestion
     <function>array_change_key_case</function>. As of PHP 8.2.0, only ASCII
     characters will be converted.
```
For versions we use ``As of`` instead of ``since``

2022-11-04 12:10 UTC, Girgias commented on reference/array/constants.xml
> +     converted.
```suggestion
     keys to upper case. As of PHP 8.2.0, only ASCII characters will be
     converted.
```

2022-11-04 12:10 UTC, Girgias commented on reference/array/constants.xml
> +     sort strings case-insensitively. Since PHP 8.2.0, only ASCII case folding
```suggestion
     sort strings case-insensitively. As of PHP 8.2.0, only ASCII case folding
```

2022-11-04 12:10 UTC, Girgias commented on reference/strings/functions/lcfirst.xml
> +       <function>setlocale</function>. Only ASCII characters will be converted.
Add an XML entity for this and the case folding changelog entries?

2022-11-07 00:46 UTC, tstarling commented on reference/strings/functions/lcfirst.xml
> +       <function>setlocale</function>. Only ASCII characters will be converted.
Done.

2022-11-07 00:52 UTC, Girgias approved these changes
LGTM :)

2022-11-07 14:17 UTC, merged