random: Add description to the jumping methods of Xoshiro256StarStar
php/doc-en pull request #1991
Opened 2022-11-10 19:54 UTC by TimWolla

2022-11-11 09:40 UTC, cmb69 reviewed
Thank you!

2022-11-11 09:40 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
I'm not quite sure about the `2^128` notation; are we using that elsewhere in the manual? The PHP equivalent would be `2**128` which *might* be more suitable.

2022-11-11 09:40 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   a blueprint.
That "and then jumping an engine acting as a blueprint" sounds strange.

2022-11-11 09:40 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jumplong.xml
> +   engine instance into 2^64 non-overlapping instances with 2^192 values each, by repeatedly
Is that "2^64" correct here?

2022-11-11 10:20 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
> are we using that elsewhere in the manual?

We are indeed:

https://www.php.net/manual/en/language.types.integer.php:

> If the float is beyond the boundaries of int (usually +/- 2.15e+9 = 2^31 on 32-bit platforms and +/- 9.22e+18 = 2^63 on 64-bit platforms)

https://www.php.net/manual/en/function.lcg-value

> The function combines two CGs with periods of 2^31 - 85 and 2^31 - 249.

--------

The `**` notation (`[0-9]\s*\*\*\s*[0-9]`) only appears in the luasandbox docs. The best solution would be a proper supertext (`<sup>`) feature. Is that available (I didn't test :smile: )?

2022-11-11 10:21 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   a blueprint.
It does indeed. I've rephrased this sentence multiple times and this is the best I came up with. Any suggestions?

2022-11-11 10:23 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jumplong.xml
> +   engine instance into 2^64 non-overlapping instances with 2^192 values each, by repeatedly
Yes. Xoshiro256** has 256 bits of state and a period of `2^256 - 1`. By jumping ahead 2^192 steps, this period is split into 64 bits of "prefix" and 192 bits of "unique sequence for the prefix".

2022-11-11 11:53 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
Oh, indeed [DocBook 4.5 supports `<superscript>`](https://tdg.docbook.org/tdg/4.5/superscript.html), but I don't know if that is properly supported by PhD. I'll check later, if nobody beats me to it. :)

2022-11-11 12:00 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
I've just tested it: It works. Perfect, I'll use that one.

2022-11-11 13:04 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
Actually quite funny that `<superscript>` is supported by PhD, but never used in the manual so far.

2022-11-11 14:00 UTC, Girgias commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
Well, I suppose we have some follow up PRs to do (I can imagine this also be useful for the ``**`` operator and ``pow()`` functions pages)

2022-11-11 14:03 UTC, Girgias commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   a blueprint.
```suggestion
   <link linkend="language.oop5.cloning">cloning</link> and then jumping the engine which acts as
   a blueprint.
```

Maybe? ``the`` because we are referring to the original blueprint instance

2022-11-11 14:26 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   Moves the algorithm’s state ahead by 2^128 steps, as if <function>Random\Engine\Xoshiro256StarStar::generate</function>
This one is now resolved.

2022-11-11 14:30 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   a blueprint.
No, the comma is definitely not correct. What I intent to explain here is the “pattern” that is also used for the ext/random example on the PHP 8.2 release page: https://github.com/php/web-php/pull/675#pullrequestreview-1160537517

Basically the following:

```
$blueprint = new Xoshiro256StarStar();

while (($request = $server->accept())) {
  $requestEngine = clone $blueprint; // Clone the blueprint.
  $blueprint->jump(); // Jump the blueprint to ensure $requestEngine has 2^128 non-overlapping values.
  // Now the request may use the $requestEngine without worrying about reused numbers
}
```

2022-11-11 14:30 UTC, Girgias requested changes
Refpurpose also need to use the superscript tag

2022-11-11 14:30 UTC, Girgias commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +  <refpurpose>Efficiently move the engine ahead by 2^128 steps</refpurpose>
```suggestion
  <refpurpose>Efficiently move the engine ahead by 2<superscript>128</superscript> steps</refpurpose>
```

2022-11-11 14:30 UTC, Girgias commented on reference/random/random/engine/xoshiro256starstar/jumplong.xml
> +  <refpurpose>Efficiently move the engine ahead by 2^192 steps</refpurpose>
```suggestion
  <refpurpose>Efficiently move the engine ahead by 2<superscript>192</superscript>steps</refpurpose>
```

2022-11-11 14:31 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +  <refpurpose>Efficiently move the engine ahead by 2^128 steps</refpurpose>
This does not render properly. It will show up as `2128` in the method lists.

2022-11-11 14:40 UTC, Girgias commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +  <refpurpose>Efficiently move the engine ahead by 2^128 steps</refpurpose>
AAAAAAAAAAAAAAAAAAAA gosh do I hate PhD at times... okay leave it then

2022-11-11 14:59 UTC, cmb69 commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +  <refpurpose>Efficiently move the engine ahead by 2^128 steps</refpurpose>
Indeed, basically PhD strips all tags here (see https://github.com/php/phd/blob/master/phpdotnet/phd/Reader.php). So I agree that we should stick with what we have here.

2022-11-13 12:22 UTC, zeriyoshi approved these changes

2022-11-15 17:39 UTC, TimWolla commented on reference/random/random/engine/xoshiro256starstar/jump.xml
> +   then jumping an engine acting as a blueprint.
@Girgias Thank you. I've taken your suggestion with some rephrasing (“values” → “sequences” and adding some extra information (2^128 possible sequences)). PTAL :smiley:

2022-11-15 17:53 UTC, cmb69 approved these changes
Thank you!

2022-11-15 18:15 UTC, Girgias approved these changes

2022-11-16 04:42 UTC, zeriyoshi approved these changes

2022-11-16 07:38 UTC, merged