Updating mysqli: fetch functions
php/doc-en pull request #207
Opened 2020-11-21 16:16 UTC by kamil-tekiela

Pushed by this comment https://stackoverflow.com/questions/64933761/how-to-return-integer-of-count-mysql-query-result-in-php/64933840?noredirect=1#comment114809131_64933840 I updated the mysqli docs to show the best practices usage

Fixes:
- Aligned examples. OO and procedural examples where using different variable names. An example of iterator was using different style and data
- Improved descriptions. Some words were confusing and even wrong. 
- Aligned notes. All notes are in the same place and follow similar grammar
- Removed manual error checking from examples
- Removed unnecessary LIMIT 50,5
- Added .similar to the example results

2021-01-07 14:41 UTC, afilina requested changes
LGTM.
I added an optional suggestion, as well as my feedback for the maintainers.

2021-01-07 14:41 UTC, afilina commented on reference/mysqli/mysqli_result/fetch-array.xml
> +   by using the field names of the result set as keys.
This really eases the comprehension of the sentence.

2021-01-07 14:41 UTC, afilina commented on reference/mysqli/mysqli_result/fetch-array.xml
> +$mysqli = new mysqli("localhost", "my_user", "my_password", "world");
I'm definitely in favor of using the built-in error reporting and avoiding any occurrences of `exit()`, which is a terrible practice to promote.

2021-01-07 14:41 UTC, afilina commented on reference/mysqli/mysqli_result/fetch-array.xml
> +printf("%s (%s)\n", $row[0], $row["CountryCode"]);
I agree with removing unnecessary code from the example to keep it focused.

2021-01-07 14:41 UTC, afilina commented on reference/mysqli/mysqli_result/fetch-assoc.xml
> +   <para><classname>mysqli_result</classname> can be iterated using &foreach;. The result set will always be iterated from the beginning until the end.</para>
```suggestion
   <para><classname>mysqli_result</classname> can be iterated using &foreach;. The result set will always be iterated from the first element, regardless of the current position.</para>
```

2021-01-07 14:53 UTC, kamil-tekiela commented on reference/mysqli/mysqli_result/fetch-assoc.xml
> +   <para><classname>mysqli_result</classname> can be iterated using &foreach;. The result set will always be iterated from the beginning until the end.</para>
"first element" -> "first row" maybe? I have been struggling with this sentence myself actually, so I do appreciate the suggestion.

2021-01-07 16:45 UTC, afilina commented on reference/mysqli/mysqli_result/fetch-assoc.xml
> +   <para><classname>mysqli_result</classname> can be iterated using &foreach;. The result set will always be iterated from the beginning until the end.</para>
I took the idea for "first element" from here.

![image](https://user-images.githubusercontent.com/199835/103919049-943dba80-50dd-11eb-8500-dc6a906b7cfc.png)

I don't mind either way since there's no standard regarding this in the docs. In some places, these are called "entries". "Row" seems well suited for this context.

2021-01-09 17:11 UTC, afilina commented
LGTM.

2021-01-09 18:08 UTC, kamil-tekiela commented
Should I merge PR #39 into this PR? I believe the other PR has some good suggestions that I didn't notice before.

2021-02-22 16:57 UTC, cmb69 commented
Thank you!

2021-02-22 16:58 UTC, closed without merging