Explicitly mention that spl_autoload_register will drop any leading backslash
php/doc-en pull request #2330
Opened 2023-02-28 11:49 UTC by TimWolla

Due to this guarantee there is no need to perform this unnecessary check within the autoloader.

2023-03-04 23:30 UTC, kamil-tekiela commented on reference/spl/functions/spl-autoload-register.xml
> +class_exists(\AbsoluteName\WithNamespace::class);
While your PR makes senses to me, your example is misleading. Please see `var_dump(\AbsoluteName\WithNamespace::class);`. https://3v4l.org/mBbet

2023-03-05 11:54 UTC, TimWolla commented on reference/spl/functions/spl-autoload-register.xml
> +class_exists(\AbsoluteName\WithNamespace::class);
Good catch, thank you. Fixed.

2023-03-06 11:04 UTC, kamil-tekiela requested changes

2023-03-06 11:04 UTC, kamil-tekiela commented on reference/spl/functions/spl-autoload-register.xml
> +       backslash of a fully-qualified classname.
```suggestion
       The <parameter>class_name</parameter> will not contain the leading
       backslash of a fully-qualified identifier.
```

`classname` is not actually a word. Besides, it's not just classes that get loaded here. Replace this word with either `identifier` or `name`. See https://www.php.net/manual/en/language.namespaces.rules.php

You also touch on another point here, why is the param called `$class_name` at all? [`spl_autoload()`](https://www.php.net/manual/en/function.spl-autoload.php) lists it as `$class`. Which name is correct?

2023-03-06 11:04 UTC, kamil-tekiela commented on reference/spl/functions/spl-autoload-register.xml
> +    <title>The classname will be provided without the leading backslash</title>
```suggestion
    <title>The identifier will be provided without the leading backslash</title>
```

2023-03-09 07:14 UTC, Girgias requested changes
I agree with @kamil-tekiela's comments, so addressing those would be great!

2023-03-09 07:14 UTC, Girgias commented on reference/spl/functions/spl-autoload-register.xml
> +       backslash of a fully-qualified classname.
``$class`` is the correct name if you look at the stubs. So that needs to be fixed.

2023-03-09 16:48 UTC, TimWolla commented on reference/spl/functions/spl-autoload-register.xml
> +       backslash of a fully-qualified classname.
All done, I believe. PTAL (and feel free to merge directly if it is good).

2023-03-09 16:55 UTC, kamil-tekiela approved these changes
LGTM

2023-03-09 16:56 UTC, merged