Restored the caution of the usort() comparison function
php/doc-en pull request #2368
Opened 2023-03-18 04:41 UTC by koseki

* #2365

2023-03-20 14:01 UTC, Girgias requested changes
Please see related issue for requested changes.

2023-03-22 03:36 UTC, Girgias approved these changes
Small nit about adding literal tags but LGTM :)

2023-03-22 03:36 UTC, Girgias commented on language-snippets.ent
> +  compare such values as equal.
```suggestion
  <literal>0.99</literal> and <literal>0.1</literal> will both be cast to an
  integer value of <literal>0</literal>, which will compare such values as equal.
```

2023-03-22 22:25 UTC, koseki commented
@Girgias Thank you for reviewing!

There seems to be no reference to the `&return.callbacksort;` other than here.
Can I merge this into `&sort.callback.description;` or should be left at this moment?

2023-03-23 13:08 UTC, merged