call_user_func_array $args need not be indexed
php/doc-en pull request #2385
Opened 2023-03-26 04:16 UTC by mjec

Since PHP 8.0, the keys can be used as argument names.

2023-03-26 22:05 UTC, Girgias requested changes
This needs a changelog entry at minimum. The PHP docs must document PHP 7 + 8 behaviour.

2023-03-26 22:10 UTC, mjec commented
> This needs a changelog entry at minimum. The PHP docs must document PHP 7 + 8 behaviour.

The changelog already has an entry for this:

> 8.0.0 	args keys will now be interpreted as parameter names, instead of being silently ignored.

Is that sufficient or should the description of args be expanded to explicitly specify 7 + 8 behaviors?

2023-03-29 15:22 UTC, Girgias commented
> > This needs a changelog entry at minimum. The PHP docs must document PHP 7 + 8 behaviour.
> 
> The changelog already has an entry for this:
> 
> > 8.0.0 	args keys will now be interpreted as parameter names, instead of being silently ignored.
> 
> Is that sufficient or should the description of args be expanded to explicitly specify 7 + 8 behaviors?

I think the PHP 8.0 behaviour should be described in the description of the args param, and the current changelog entry should be sufficient to say well the PHP 7 behaviour is different because the keys are ignored and only positional args where accepted

2023-03-30 12:53 UTC, Girgias approved these changes
Brilliant, thank you!

2023-03-30 12:53 UTC, merged