Add nullsafe arrow.
php/doc-en pull request #244
Opened 2020-11-26 20:20 UTC by Crell

I included a Note giving guidance on when to use it, because I keep fielding "but doesn't this just encourage bad error handling? questions from people. I figure this is a case where some usage guidance is warranted.

2020-11-27 16:30 UTC, Girgias commented
I think the token page and the language/operator page should also be update to include a mention/link to this page.

Other than that LGTM

2020-11-28 12:26 UTC, cmb69 commented
May prefer the term "nullsafe operator" over "nullsafe arrow"?

2020-11-28 14:06 UTC, kamil-tekiela commented on language/oop5/basic.xml
> +   "nullsafe" arrow instead: <literal>?-></literal>. The nullsafe arrow work the same as property
The `->` is called "object operator". We should call `?->` the "nullsafe object operator" or just "nullsafe operator". Don't call it an arrow as this is very ambiguous.

2020-11-28 17:34 UTC, iluuu1994 commented
We do call it "nullsafe operator" and "nullsafe object operator" internally. I don't have a preference but I'd stick with one of the two.

2020-11-28 17:38 UTC, Crell commented
I went with nullsafe operator for conciseness, and added it to the token list.

The -> operator is not in the operators page as is (one of the comments notes it), and it's not in the precedence list in zend_language_parser.y either, much to my surprise.  That seems like a larger question to resolve than I want to get into here.

2020-11-28 17:41 UTC, kamil-tekiela requested changes

2020-11-28 17:41 UTC, kamil-tekiela commented on appendices/tokens.xml
> +     <entry>-&gt;</entry>
`?-&gt;` instead of `-&gt;`

2020-11-28 17:43 UTC, Crell commented on appendices/tokens.xml
> +     <entry>-&gt;</entry>
Sigh. Thanks.

2020-11-28 17:49 UTC, cmb69 commented
> The -> operator is not in the operators page as is (one of the comments notes it), and it's not in the precedence list in zend_language_parser.y either, much to my surprise. That seems like a larger question to resolve than I want to get into here.

I agree that this can be resolved another time.

2020-11-28 23:09 UTC, cmb69 approved these changes
Thank you! I left a few commits and applied with respective changes.

2020-11-28 23:09 UTC, cmb69 commented on language/oop5/basic.xml
> +   object being dereferenced is <literal>null</literal> then <literal>null</literal>
When referring to the `null` value, it's usually best to denote it as `&null;`.

2020-11-28 23:09 UTC, cmb69 commented on language/oop5/basic.xml
> +    <title>Class name resolution</title>
Interesting example for "class name resolution". ;)

2020-11-28 23:09 UTC, cmb69 commented on language/oop5/basic.xml
> +// This line in PHP 8.0:
This gets confusing when PHP 8.1.0 will be released: does it work only for PHP 8.0?

2020-11-28 23:10 UTC, closed without merging