Update construct.xml
php/doc-en pull request #2454
Opened 2023-04-27 20:25 UTC by mattkolb

Docs need updating according to this:
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.mysqli

2023-04-29 18:44 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +   <methodname>mysqli::connect</methodname> returns &null; on success&return.falseforfailure;. As of PHP 8.1, returns true on success.
```suggestion
   <methodname>mysqli::connect</methodname> returns &null; on success&return.falseforfailure;. As of PHP 8.1, returns &true; on success.
```

2023-06-26 15:31 UTC, Girgias requested changes
This is missing a Changelog section.

2023-08-12 13:40 UTC, Girgias requested changes

2023-08-12 13:40 UTC, Girgias commented on reference/mysqli/mysqli/construct.xml
> +      </row>
Must be above the 7.4.0 change log entry

2023-08-12 13:40 UTC, Girgias commented on reference/mysqli/mysqli/construct.xml
> +   As of PHP 8.1.0, returns &true; on success.
```suggestion
   <methodname>mysqli::connect</methodname> &return.success;.
```
Is what I want to use, but the entity starts with an uppercase letter. :-/

Also, the "return value" for ``__construct()`` doesn't really make sense looking at it

2023-08-12 13:52 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +   As of PHP 8.1.0, returns &true; on success.
I don't think I can use this entity here. This page should probably be split into 3 separate pages. For now, I would suggest to keep it as it is in the PR.

2023-08-12 14:01 UTC, Girgias commented on reference/mysqli/mysqli/construct.xml
> +   As of PHP 8.1.0, returns &true; on success.
Possibly, or maybe just into 2 where the constructor is seperate.

But I would use more the wording:

```xml
   <methodname>mysqli::connect</methodname> returns &true; on success&return.falseforfailure;.
   Prior to PHP 8.1.0, returns &null; on success.
```

2023-08-12 14:30 UTC, Girgias approved these changes

2023-08-12 14:31 UTC, merged