Oci8 removes old PHP5 related description
php/doc-en pull request #2492
Opened 2023-05-24 03:35 UTC by mowangjuanzi

2023-05-25 19:27 UTC, Girgias requested changes
Please also remove mentions of the old PECL version, otherwise LGTM

2023-05-25 19:27 UTC, Girgias commented on reference/oci8/constants.xml
> +           Oracles' External or OS authentication.  Introduced in PECL OCI8 1.3.4.
I think at this point one can just remove the "Introduced in PECL" version as they are that old and nobody should use them (as they don't even work on PHP 7)

2023-05-26 02:26 UTC, mowangjuanzi commented on reference/oci8/constants.xml
> +           Oracles' External or OS authentication.  Introduced in PECL OCI8 1.3.4.
```
// from http://pecl.php.net/package/oci8
Use 'pecl install oci8-2.2.0' to install for PHP 7.
```

So I remove the PECL OCI8 < 2.2.0 description?

2023-05-26 09:32 UTC, Girgias commented on reference/oci8/constants.xml
> +           Oracles' External or OS authentication.  Introduced in PECL OCI8 1.3.4.
Yes please!

2023-05-26 09:34 UTC, Girgias approved these changes

2023-06-19 03:14 UTC, mowangjuanzi commented
Is it possible to merge? 😁

2023-06-19 13:21 UTC, merged

2023-06-19 13:21 UTC, Girgias commented
Sorry, thought you had merge rights on doc-en. .-.

2023-06-19 13:59 UTC, mowangjuanzi commented
Haha, I only have doc-zh.