Clarifications about getElementsByTagNameNS
php/doc-en pull request #2501
Opened 2023-05-29 18:56 UTC by nielsdos

And while we're here, make the documentation consistent.

Never contributed to the docs before, so not sure about wording etc :P

2023-05-29 21:45 UTC, Girgias requested changes
Ditto the changes onto the other page.

2023-05-29 21:45 UTC, Girgias commented on reference/dom/domdocument/getelementsbytagnamens.xml
> +       Passing <type>null</type> matches the empty namespace.
```suggestion
       Passing &null; matches the empty namespace.
```
For the value `null` we use the entity (we have some similarly for true and false, you can have a look in `language-snippets.ent` and another `.ent` file the ones we define)

2023-05-29 21:45 UTC, Girgias commented on reference/dom/domdocument/getelementsbytagnamens.xml
>         The special value <literal>*</literal> matches all namespaces.
```suggestion
       The special value <literal>"*"</literal> matches all namespaces.
```
I would enclose it in quotes to show that we mean the string with an asteriks

2023-05-30 16:02 UTC, nielsdos commented
Thanks, applied the suggestions.

2023-05-31 09:34 UTC, Girgias approved these changes
I wonder if it makes sense to deprecate the behaviour of passing ``null`` to these functions as it is rather confusing.

2023-05-31 09:34 UTC, merged

2023-05-31 15:17 UTC, Girgias commented
So the spec is just weird :| yeah let's follow the spec.