Add an example for str_getcsv with empty input
php/doc-en pull request #2504
Opened 2023-05-31 15:41 UTC by apeschar

It's surprising that `str_getcsv("")` returns `[null]`. This adds an example to warn users of this behavior.

2023-08-12 13:21 UTC, kamil-tekiela commented
I think an example on its own is insufficient. I wonder why is the value `NULL`. Is this by design? Do you have any supporting evidence that this behaviour should be documented?

2023-08-15 14:04 UTC, apeschar commented
> I think an example on its own is insufficient.

I've added a note to the return values section to match the note that is attached to [fgetcsv](https://www.php.net/fgetcsv). Without the error part, since str_getcsv never fails.

> I wonder why is the value NULL. Is this by design?

It's like this because of the original implementation of fgetcsv.

https://github.com/php/php-src/blob/master/ext/standard/string.c#L5139-L5143

There's this commit which makes the "weird" behaviour more explicit:

https://github.com/php/php-src/commit/4ccf0b01819677dbdd3fbb330f9220606866028b

I assume that at this point it's unlikely for this behaviour to be changed?

> Do you have any supporting evidence that this behaviour should be documented?

I think the fact that it's noted in the docs for fgetcsv, is mentioned as weird in the above commit and that it surprised me (and you?) should indicate that documenting this behaviour is useful.

2023-08-15 14:50 UTC, Girgias requested changes
This function is cursed, and I don't think it will ever change.

Moreover, for some reason, it also right trims newlines: https://3v4l.org/UJ8JN

Pure joy.

2023-08-15 14:50 UTC, Girgias commented on reference/strings/functions/str-getcsv.xml
> +    <title><function>str_getcsv</function> example with empty input</title>
```suggestion
    <title><function>str_getcsv</function> example with an empty string</title>
    <caution>
     <simpara>
      On an empty string this function returns the value <code>[null]</code>
      instead of an empty array.
     </simpara>
    </caution>
```

2023-08-15 15:03 UTC, apeschar commented
For your enjoyment, I'll share another example where it introduces a null byte when you give it an unterminated quoted string:

~~~
> str_getcsv('""')
= [
    "",
  ]

> str_getcsv('"')
= [
    "\0",
  ]
~~~

https://3v4l.org/NsGVO

2023-08-15 15:12 UTC, kamil-tekiela commented
> For your enjoyment, I'll share another example where it introduces a null byte when you give it an unterminated quoted string:
> 
> ```
> > str_getcsv('""')
> = [
>     "",
>   ]
> 
> > str_getcsv('"')
> = [
>     "\0",
>   ]
> ```
> 
> https://3v4l.org/NsGVO

This must be a bug.

2023-08-15 15:31 UTC, apeschar commented
> This must be a bug.

Created an issue for it:
https://github.com/php/php-src/issues/11982

2023-08-15 16:22 UTC, Girgias approved these changes

2023-08-15 16:23 UTC, merged