Document named arguments
php/doc-en pull request #251
Opened 2020-11-29 16:29 UTC by ekinhbayar

Initial draft for documenting named arguments on the functions page. 

Feedback is most welcomed! This PR could also use a quick fact-check and I'd appreciate pointing out what's missing that needs documentation. 

This PR also documents deprecation of optional args after mandatory ones.

2020-11-29 17:55 UTC, Girgias requested changes
Looks good, other than the mix of parameter and arguments, which we might need to figure out when to use which in what context and try to normalize this in the whole docs :(

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +    One exception to this rule are parameters of the form
```suggestion
    One exception to this rule are arguments of the form
```
To keep this consistent with the beginning of the paragraph?

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +    Type $param = &null;, where the &null; default makes the type implicitly
```suggestion
    <code>Type $param = &null;</code>, where the &null; default makes the type implicitly
```
Maybe? @cmb69 might want to confirm is that would work

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +     function based on the parameter name, rather than the parameter position.
```suggestion
     function based on the argument name, rather than the argument position.
```
Again for consistency with the beginning of the paragraph

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +     Named arguments are passed by prefixing the value with the parameter name
```suggestion
     Named arguments are passed by prefixing the value with the argument name
```

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +     You can combine named arguments with positional arguments. In this case,
```suggestion
     Named arguments can be combined with positional arguments. In this case,
```
Usage of "you" in the docs is to be limited to the tutorial section for the most part

2020-11-29 17:55 UTC, Girgias commented on language/functions.xml
> +     <title>Same as above example with a different order of parameters</title>
```suggestion
     <title>Same example as above with a different order of parameters</title>
```

2020-11-29 22:55 UTC, Girgias commented on language/functions.xml
> +    One exception to this rule are parameters of the form
So I might have been getting the correctness wrong looking at: https://github.com/php/doc-en/pull/241#issuecomment-735455648, so maybe ignore these comments.

2020-11-29 23:49 UTC, ekinhbayar commented on language/functions.xml
> +    One exception to this rule are parameters of the form
In this specific example, I think parameters is the correct wording indeed since it's about the function signature which is the place to use the word parameter, though I wouldn't be surprised if I had gotten it wrong elsewhere in the PR :-)

2020-11-29 23:51 UTC, ekinhbayar commented on language/functions.xml
> +    Type $param = &null;, where the &null; default makes the type implicitly
I'd be happy to do this, I wasn't sure if that'd undo the use of `&null;` tbh. I could totally use `null` instead, if that would be the case.

2020-11-29 23:53 UTC, ekinhbayar commented on language/functions.xml
> +     function based on the parameter name, rather than the parameter position.
I think this one is a legit use of argument, as it's again talking about the name vs position of the parameter at the function definition.

2020-11-29 23:53 UTC, ekinhbayar commented on language/functions.xml
> +     Named arguments are passed by prefixing the value with the parameter name
Same as above. If you do agree would you please mark these cases as resolved?

2020-11-29 23:56 UTC, ekinhbayar commented
@Girgias  Feel free to create an issue for `argument` vs `parameter` usage throughout the docs and even assign it to me. I can work on this over time in a single PR. Happy to make sure we keep this consistent across the docs :-) I'll commit the other changes shortly.

2020-11-30 00:00 UTC, cmb69 commented on language/functions.xml
> +    Type $param = &null;, where the &null; default makes the type implicitly
It seems to me that `<code><replaceable>Type</replaceable> $param = &null;</code>` might be the proper markup, and might render as desired as well (fingers crossed!)

2020-11-30 00:04 UTC, ekinhbayar commented
Yup, by the looks of the failure, I do need to use null explicitly in the code block.

2020-11-30 01:21 UTC, Girgias commented on language/functions.xml
> +     Named arguments are passed by prefixing the value with the parameter name
*well I can't*

2020-12-04 14:14 UTC, ekinhbayar commented
@cmb69 @Girgias, is there anything I can do here to help closing/completing this one?

2020-12-04 23:26 UTC, closed without merging