Remove PHP 5 from mysqli, PDO_MySQL and mysqlnd
php/doc-en pull request #253
Opened 2020-11-29 20:03 UTC by kamil-tekiela

I was not sure what to do about https://www.php.net/manual/en/mysqli.installation.php

2021-01-07 20:01 UTC, afilina requested changes
Besides one nitpicky suggestions, LGTM.

2021-01-07 22:52 UTC, cmb69 reviewed
Thanks! Overall a very nice cleanup. Please check my review comments.

2021-01-07 22:52 UTC, cmb69 commented on reference/mysqli/constants.xml
> -      Available since PHP 5.3.0. (MySQL 5.1.10 and up)
Sadly, PHP 7.0.0 is supposed to [work with MySQL >= 4.1.13 and MySQL >= 5.0.7](https://github.com/php/php-src/blob/php-7.0.0/ext/mysqli/config.m4#L87), so please keep the relevant info for MySQL.

2021-01-07 22:52 UTC, cmb69 commented on reference/mysqli/book.xml
> -</appendix>
Even if there are no respective changelogs *currently*, I think we should leave that appendix (may comment it out).

2021-01-07 23:05 UTC, kamil-tekiela commented on reference/mysqli/book.xml
> -</appendix>
Are you sure about this? I was really surprised when I discovered [this section](https://www.php.net/manual/en/changelog.mysqli.php). I believe that all changes should be logged under the functions that they belong too. Not many people will go looking through the manual to find some hidden page that contains a list of all the changes. Besides, it looks like nobody was maintaining it anyway. If we leave it there, how will we make sure that people update them when they update the manual? I haven't found such section in other books in the manual.

2021-01-07 23:06 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> -      Available since PHP 5.3.0. (MySQL 5.1.10 and up)
I'll review it over the weekend and add it back in. Thanks!

2021-01-07 23:35 UTC, cmb69 commented on reference/mysqli/book.xml
> -</appendix>
That page is autogenerated by the `<?php generate-changelog-for?>` processing instruction. IMO a nice feature, that can be helpful to get an overview.

2021-01-09 16:35 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> -      Available since PHP 5.3.0. (MySQL 5.1.10 and up)
Added the note + 2 other back in.

2021-01-09 16:36 UTC, kamil-tekiela commented on reference/mysqli/book.xml
> -</appendix>
Reverted the commit

2021-01-09 17:14 UTC, afilina commented
Checked the new commits. Looks like all suggestions were addressed.

2021-01-10 11:46 UTC, cmb69 commented
Thank you!

2021-01-10 11:48 UTC, closed without merging