Improve str_pad documentation
php/doc-en pull request #2535
Opened 2023-06-21 08:56 UTC by houssemz

IIMHO, we need to specify that `length` is the desired length of the final padded chain. In my case, it was unclear.

2023-08-12 13:14 UTC, kamil-tekiela requested changes
Right, but this is obvious, isn't it? What else would it be?

2023-08-12 13:14 UTC, kamil-tekiela commented on reference/strings/functions/str-pad.xml
> +       This is the desired length of the final padded string.
```suggestion
       The desired length of the final padded string.
```

2023-08-29 08:50 UTC, houssemz commented
> 

Thank you for the review.
Not so obvious, IMHO :)

2023-08-29 10:12 UTC, merged

2023-08-29 10:13 UTC, kamil-tekiela commented
Thanks.