Add chapter on Attributes in language section.
php/doc-en pull request #254
Opened 2020-11-30 22:36 UTC by beberlei

I am not particularly good at documneting things, but this is an acceptable start I hope, for the Attributes feature. it covers the basics:

- Syntax
- Reflection API
- Declaring Attribute Classes

A bunch of things are missing for now:

- Better Examples, not `Thing` and such
- `ReflectionAttribute` class in reflection book
- `getArguments()` methods in every relevant reflection component
- Explanation of internal attributes declared in Core and Extensions

2020-12-01 14:52 UTC, Girgias requested changes
Can't comment on the general text as I don't really understand the feature, but the usage of `you` should be avoided in the docs. So if you could change that that would be great. :)

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    properties and constants can be the target of an attribute. The metadata
Should we add links to the relevant pages?

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    feature and its concrete use in an application. In a way it is
The usage of `you` should be limited to the tutorial section.
```suggestion
    With attributes the generic implementation of a
    feature and its concrete use in an application can be decoupled . In a way it is
```
Or something along does lines, as the suggestion doesn't read well.

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    only be implemented by classes, yet attributes can be declared also
```suggestion
    annotating extra information and configuration. Interfaces can only
    be implemented by classes, yet attributes can also be declared
```

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +     that has optional methods to use attributes. Lets assume you have a
`you` usage

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    when you request an instance of the attribute through the Reflection API. As such you should define
`you` usage twice

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    that you can query for attribute name, arguments and to instantiate an instance of the represented attribute.
`you` usage

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    Instead of iterating all attributes on the reflection instance, you can only retrieves those that you are interested
`you` usage

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +    In the most simple case you only need an empty class and add the <literal>#[Attribute]</literal> attribute declared in the global namespace.
3x usage of ``you``

2020-12-01 14:52 UTC, Girgias commented on language/attributes.xml
> +   argument to the <literal>#[Attribute]</literal> declaration.
2x usage of ``you``

2020-12-04 18:52 UTC, cmb69 approved these changes
Thank you! Besides the few nits, I think this is good to be merged. The rest of the documentation updates can be done later.

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +      implementations of an action handler require setup other do not. Instead of requiring all classes
```suggestion
      implementations of an action handler require setup and others do not. Instead of requiring all classes
```

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +    <literal>]</literal>. Inside one or many attributes are listed,
```suggestion
    <literal>]</literal>. Inside, one or many attributes are listed,
```

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +    Attribute names and their arguments are resolved to a class and the arguments to its constructor,
```suggestion
    Attribute names and their arguments are resolved to a class and the arguments are passed to its constructor,
```

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +    validated and not earlier.
```suggestion
    to handle errors regarding missing attribute classes, mistyped or missing arguments. Only after
    calling <function>newInstance</function>, objects of the attribute class are instantiated and the correct matching of arguments
    is validated, not earlier.
```

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +   To restrict the type of declaration an attribute can be assigned to, pass a bitmask as the first
```suggestion
   To restrict the type of declaration an attribute can be assigned to, a bitmask can be passed as the first
```

2020-12-04 18:52 UTC, cmb69 commented on language/attributes.xml
> +    properties and constants can be the target of an attribute. The metadata
Might be more noise than actually being useful.

2020-12-04 23:16 UTC, closed without merging