Document ReflectionProperty::setValue PHP 8.3 deprecation
php/doc-en pull request #2594
Opened 2023-07-23 13:58 UTC by kylekatarnls

Document the consequence of [`11703`](https://github.com/php/php-src/pull/11703) for `ReflectionProperty::setValue`

2023-07-25 14:13 UTC, Girgias requested changes
This requires a changelog entry, and usually we have a predefined XML entity for features that are deprecated that needs to be added

2023-10-05 00:07 UTC, Girgias commented
Ping @kylekatarnls please address review comments

2023-10-06 16:05 UTC, kylekatarnls commented
Changelog added.

> we have a predefined XML entity for features that are deprecated that needs to be added

I used the tags that I found in many places for similar changes as of a certain PHP version (in `final`, `constant` etc.) if you have another template in mind can you please give me a page that is using the last standard (with regard that the method is not fully deprecated only calling it with 1 parameter is)?

2023-10-06 16:06 UTC, Girgias approved these changes
LGTM, thank you!

2023-10-06 16:31 UTC, merged