Document LIBXML_NOXMLDECL support
php/doc-en pull request #2602
Opened 2023-07-26 16:16 UTC by nielsdos

Documentation for https://github.com/php/php-src/pull/11794

2023-07-26 20:56 UTC, Girgias requested changes

2023-07-26 20:56 UTC, Girgias commented on reference/dom/domdocument/savexml.xml
> + </refsect1>
Changelogs come before exampls and after return value/error  section

2023-07-26 20:56 UTC, Girgias commented on reference/dom/domdocument/savexml.xml
> +       Starting from PHP 8.3, <link linkend="libxml.constants">LIBXML_NOXMLDECL</link> is also supported.
More future proof wording
```suggestion
       Additional Options.
       The <link linkend="libxml.constants">LIBXML_NOEMPTYTAG</link>
       and <link linkend="libxml.constants">LIBXML_NOXMLDECL</link> options are supported.
       Prior to PHP 8.3.0, only the <link linkend="libxml.constants">LIBXML_NOEMPTYTAG</link>
       option is supported.
```

2023-07-31 14:18 UTC, Girgias approved these changes

2023-08-12 13:06 UTC, kamil-tekiela approved these changes

2023-10-05 00:05 UTC, merged