Update `SplFixedArray` methods + add PHP 8.2.0 changelog entry
php/doc-en pull request #2618
Opened 2023-07-28 13:07 UTC by alexandre-daubois

Fix https://github.com/php/doc-en/issues/1702

2023-07-28 13:28 UTC, Girgias requested changes
The documentation documents both PHP 7 and 8 so removing the deprecated methods is a no go.

Has the version.xml file been updated to indicate they have been deprecated and removed? As that would help a bit.

2023-07-28 15:05 UTC, alexandre-daubois commented
Thanks for the tip about `versions.xml`. Does it look better now?

2023-07-28 15:32 UTC, Girgias reviewed
@kocsismate can you have a quick look?

2023-07-28 15:32 UTC, Girgias commented on reference/spl/versions.xml
> + <function name="splfixedarray::__unserialize" from="PHP 8 &gt;= 8.2.0"/>
Are these just implemented as of 8.2?

2023-07-28 15:32 UTC, Girgias commented on reference/spl/versions.xml
> + <function name="splfixedarray::jsonSerialize" from="PHP 8 &gt;= 8.1.0"/>
Ditto

2023-07-28 19:01 UTC, kocsismate commented on reference/spl/splfixedarray/unserialize.xml
> +  <refpurpose>Deserializes the <parameter>data</parameter> parameter into a SplFixedArray object</refpurpose>
```suggestion
  <refpurpose>Deserializes the <parameter>data</parameter> parameter into an SplFixedArray object</refpurpose>
```

2023-07-29 14:18 UTC, alexandre-daubois commented on reference/spl/versions.xml
> + <function name="splfixedarray::__unserialize" from="PHP 8 &gt;= 8.2.0"/>
I checked the reflection, and yes they came up in 8.2 🙂

2023-07-29 14:18 UTC, alexandre-daubois commented on reference/spl/versions.xml
> + <function name="splfixedarray::jsonSerialize" from="PHP 8 &gt;= 8.1.0"/>
Same, it came up in 8.1 👍

2023-07-29 14:21 UTC, alexandre-daubois commented on reference/spl/splfixedarray/unserialize.xml
> +  <refpurpose>Deserializes the <parameter>data</parameter> parameter into a SplFixedArray object</refpurpose>
Updated both, thanks for the review!

2023-07-31 14:22 UTC, Girgias commented on reference/spl/splfixedarray.xml
> +        magic methods are added to <classname>SplFixedArray</classname>.
```suggestion
        The <methodname>SplFixedArray::__serialize</methodname> and <methodname>SplFixedArray::__unserialize</methodname>
        magic methods have been added to <classname>SplFixedArray</classname>.
```

Or something along those lines. :)

2023-07-31 14:22 UTC, Girgias approved these changes
One comment and then good to land

2023-07-31 14:26 UTC, alexandre-daubois commented on reference/spl/splfixedarray.xml
> +        magic methods are added to <classname>SplFixedArray</classname>.
Updated, that's better :+1:

2023-07-31 15:50 UTC, merged