Improve `xml_parser_get/set_option` parameters section
php/doc-en pull request #2630
Opened 2023-07-31 09:47 UTC by alexandre-daubois

Fix https://github.com/php/doc-en/issues/2233

2023-07-31 13:58 UTC, Girgias requested changes

2023-07-31 13:58 UTC, Girgias commented on reference/xml/functions/xml-parser-get-option.xml
>    </para>
The ValueError/E_WARNING should be put into a new Error/Exception section like other pages in between the return value and changelog sections.

2023-07-31 13:58 UTC, Girgias commented on reference/xml/functions/xml-parser-set-option.xml
> +   <parameter>option</parameter> generated a <constant>E_WARNING</constant>.
Ditto.

2023-07-31 13:58 UTC, Girgias commented on language-snippets.ent
> +  <parameter>option</parameter> is invalid.
It would be better IMHO to have this as a separate changelog entry for PHP 8.0. And if it's only those two functions, then it doesn't even need a new XML entity.

2023-08-01 06:50 UTC, alexandre-daubois commented on reference/xml/functions/xml-parser-get-option.xml
>    </para>
Added! :slightly_smiling_face:

2023-08-01 06:50 UTC, alexandre-daubois commented on language-snippets.ent
> +  <parameter>option</parameter> is invalid.
I removed the XML entity and added a separate entry

2023-08-01 14:01 UTC, merged

2023-08-01 14:01 UTC, Girgias commented
Thank you!