Add mention of `is_a()` and `instanceof` in `class_implements()` and `class_parents()` pages
php/doc-en pull request #2697
Opened 2023-08-21 11:30 UTC by alexandre-daubois

Fix https://github.com/php/doc-en/issues/1606

2023-08-21 12:28 UTC, Girgias requested changes

2023-08-21 12:28 UTC, Girgias commented on reference/spl/functions/class-implements.xml
> +  &note.no-remote;
Why this entity?
Doesn't seem related at all and something from a copy/paste.

2023-08-21 12:28 UTC, Girgias commented on reference/spl/functions/class-implements.xml
> +    or the <function>is_a</function> function.
Personalisation:
```suggestion
    To check that an object implements an interface, &instanceof;
    or the <function>is_a</function> function should be used instead.
```

2023-08-21 12:28 UTC, Girgias commented on reference/spl/functions/class-implements.xml
> +    <member><function>is_a</function></member>
Instanceof should also be mentionned here

2023-08-22 11:01 UTC, alexandre-daubois commented on reference/spl/functions/class-implements.xml
> +    <member><function>is_a</function></member>
Added :slightly_smiling_face:

2023-08-22 11:01 UTC, alexandre-daubois commented on reference/spl/functions/class-implements.xml
> +    or the <function>is_a</function> function.
Updated!

2023-08-22 12:32 UTC, Girgias approved these changes

2023-08-22 12:32 UTC, merged