Copy and modify mb_str_pad from str_pad
php/doc-en pull request #2750
Opened 2023-09-07 15:00 UTC by youkidearitai

I've mostly just copied from `str_pad`, so any pointers are welcome.

closes: #2701

2023-09-07 17:44 UTC, TimWolla commented on appendices/aliases.xml
> +     </row>
I do not believe this is accurate. Also the `mbstrlen()` alias which already exists in the file does not appear to exist either: https://3v4l.org/BRCas

2023-09-07 18:34 UTC, nielsdos requested changes
Looks mostly good, thanks for working on this.
Just some remarks.

2023-09-07 18:34 UTC, nielsdos commented on appendices/aliases.xml
> +     </row>
Tim is right, that seems to be a leftover from the PHP4 days.

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +  <refpurpose>Pad a string to a certain length with another string to multibyte version</refpurpose>
```suggestion
  <refpurpose>Pad a multibyte string to a certain length with another multibyte string</refpurpose>
```

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +   <methodparam choice="opt"><type>string</type><parameter>encoding</parameter><initializer>null</initializer></methodparam>
```suggestion
   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>encoding</parameter><initializer>&null;</initializer></methodparam>
```

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +   padding length. If the optional argument
```suggestion
   padding length, where the length is measured in Unicode codepoints. If the optional argument
```

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +      <para>
This whole paragraph may be replaced with the entity `&mbstring.encoding.parameter;` (the para tags should be removed too, i.e.: `<listitem>&mbstring.encoding.parameter;</listitem>`. (but I can't make a multi-line suggestion unfortunately)

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +      <para>
And I believe the note about the ValueError exception should be in a separate errors section.
https://www.php.net/manual/en/function.mb-strlen.php puts it in the error section, although it seems outdated because it claims a warning is raised instead of a ValueError... (https://3v4l.org/E9s0i)

2023-09-07 18:34 UTC, nielsdos commented on reference/mbstring/functions/mb-str-pad.xml
> +      <para>
I filed an issue for the error conditions: https://github.com/php/doc-en/issues/2751

2023-09-08 10:54 UTC, youkidearitai commented on appendices/aliases.xml
> +     </row>
Ah, This was an aliases. Reverted, thanks.

2023-09-08 10:55 UTC, youkidearitai commented
@nielsdos @TimWolla Thanks very much! I fixed.

2023-09-08 12:05 UTC, Girgias commented on reference/mbstring/functions/mb-str-pad.xml
> +       If the value of <parameter>length</parameter> is negative,
Is no ValueError emitted for negative lengths?

2023-09-08 12:05 UTC, Girgias commented on reference/mbstring/functions/mb-str-pad.xml
> +       <constant>STR_PAD_RIGHT</constant>.
```suggestion
       Optional argument <parameter>pad_type</parameter> can be
       <constant>STR_PAD_RIGHT</constant>, <constant>STR_PAD_LEFT</constant>,
       or <constant>STR_PAD_BOTH</constant>.
       By default <constant>STR_PAD_RIGHT</constant>.
```
Is more typical wording

2023-09-08 12:05 UTC, Girgias commented on reference/mbstring/functions/mb-str-pad.xml
> +   This function returns the <parameter>string</parameter> string
```suggestion
   This function returns the <parameter>string</parameter>
```
This probably reads better and is a common technique used by the documentation

2023-09-08 12:19 UTC, youkidearitai commented on reference/mbstring/functions/mb-str-pad.xml
> +       If the value of <parameter>length</parameter> is negative,
Yes, no ValueError throws.

```
$ sapi/cli/php -r 'var_dump(mb_str_pad("あいうえお", -333, "🎉", STR_PAD_BOTH));'
string(15) "あいうえお"
```

2023-09-08 12:34 UTC, youkidearitai commented on reference/mbstring/functions/mb-str-pad.xml
> +   This function returns the <parameter>string</parameter> string
Thanks, fixed.

2023-09-08 13:14 UTC, Girgias commented on reference/mbstring/functions/mb-str-pad.xml
> +       If the value of <parameter>length</parameter> is negative,
sad :(

2023-09-08 13:16 UTC, Girgias commented
This also needs an entry in ``reference/mbstring/versions.xml`` to indicate it is available as of 8.3

2023-09-08 14:26 UTC, youkidearitai commented
> This also needs an entry in reference/mbstring/versions.xml to indicate it is available as of 8.3

@Girgias Thank you very much. Add to reference/mbstring/versions.xml .

2023-10-05 00:09 UTC, Girgias approved these changes

2023-10-05 00:09 UTC, merged