Remove PHP 5 mentions from OO section
php/doc-en pull request #277
Opened 2020-12-15 01:42 UTC by Girgias

2021-01-07 15:37 UTC, afilina requested changes
Amazing work!
I have some suggestions and questions.

2021-01-07 15:37 UTC, afilina commented on language/oop5/interfaces.xml
> +     An interface, together with type declaring, provides a good way to make sure
```suggestion
     An interface, together with type declarations, provides a good way to make sure
```

2021-01-07 15:37 UTC, afilina commented on language/oop5/properties.xml
> +   They may be referred to using other terms such as <emphasis>fields</emphasis>,
Nice catch! For those who don't know why the mention of `attributes` was removed here, it's because that now refers to a different concept and can no longer be used interchangeably: https://wiki.php.net/rfc/attributes_v2

2021-01-07 15:37 UTC, afilina commented on language/oop5/properties.xml
> +    compatibility with PHP 4, of declaring class properties is by using
```suggestion
    An alternative and not recommended way of declaring class properties, as it is to maintain backward
    compatibility with PHP 4, is by using
```

- Alternate != alternative.
- "An alternative and not recommended way of declaring class properties" should be together to ease comprehension.
- Moved the comma to properly delimit the non-essential clause regarding backwards compatibility.

2021-01-07 15:37 UTC, afilina commented on language/oop5/properties.xml
> -   <title>Heredoc and Nowdoc</title>
Was this section removed due to duplication? https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
If that is the case, can we link to that page from here?

2021-01-07 15:37 UTC, afilina commented on language/oop5/properties.xml
> -    <title>Valid property types</title>
Was this section removed because of duplication with this? https://www.php.net/manual/en/language.types.php
If that is the case, can we at least link to that page from here?

2021-01-07 15:37 UTC, afilina commented on language/oop5/references.xml
> +   to the same value. In PHP an object variable doesn't contain the object
```suggestion
   to the same value. In PHP, an object variable doesn't contain the object
```

2021-01-07 15:37 UTC, afilina commented on language/oop5/traits.xml
> +   PHP implements a method of code reuse called Traits.
```suggestion
   PHP implements a way to reuse code called Traits.
```

Might as well avoid ambiguity with "methods" :)

2021-01-07 15:37 UTC, afilina commented on language/types/declarations.xml
> +       The property must be an &instanceof; the parent class of the class
Maybe a bit nitpicky, but multiple occurrences of "class" makes the sentence harder to understand. Perhaps we can assume that "parent" == "parent class" and simplify.

```suggestion
       The property must be an &instanceof; the parent of the class
```

2021-01-07 16:10 UTC, Girgias commented on language/oop5/constants.xml
> -  <title>Constant expression example</title>
Not really as I though this would be covered by the link to the constant page.
I can reintroduce it

2021-01-07 16:11 UTC, Girgias commented on language/oop5/properties.xml
> -   <title>Heredoc and Nowdoc</title>
This might need to be moved up to a constant expression part (and we might want to introduce a separate page talking about this as this concept comes up quite often)

2021-01-07 16:12 UTC, Girgias commented on language/oop5/properties.xml
> -    <title>Valid property types</title>
The ``<xref linkend="language.types.declarations" />`` above should link to the page, might expanding on what you explicitly want?

2021-01-07 16:39 UTC, afilina commented on language/oop5/constants.xml
> -  <title>Constant expression example</title>
Ah, I see. Yeah, there is an example of constant expression on this page: https://www.php.net/manual/en/language.constants.syntax.php

I really like the example on this page though, as it's specific to _class_ constants and makes this page more complete. It's just a personal preference though and I'm not married to it. It's really up to you.

2021-01-07 16:40 UTC, afilina commented on language/oop5/properties.xml
> -   <title>Heredoc and Nowdoc</title>
Is there a place where we can log this as a TODO ticket? I'd like to take a stab at it at some point. In the mean time, we can definitely remove this duplicate example.

2021-01-07 23:20 UTC, cmb69 commented on language/oop5/properties.xml
> -   <title>Heredoc and Nowdoc</title>
I think filing a respective ticket at https://bugs.php.net could be useful.

2021-01-08 14:33 UTC, afilina commented on language/oop5/properties.xml
> -   <title>Heredoc and Nowdoc</title>
Looks like it's already a thing: https://bugs.php.net/bug.php?id=68040
Bookmarked.

2021-01-08 14:34 UTC, afilina commented
LGTM.

2021-01-09 01:14 UTC, Girgias commented on language/oop5/constants.xml
> -  <title>Constant expression example</title>
Reintroduced the example with some amendments, wdyt?

2021-01-09 01:16 UTC, Girgias commented on language/oop5/interfaces.xml
> -   </note>
This note should probably be maintained in some sense, maybe as a Warning

2021-01-09 03:14 UTC, Girgias commented
I wonder if I shouldn't split the method signature section into a separate PR.

2021-01-10 02:02 UTC, Girgias commented
@cmb69 @afilina could you please review once again?

2021-01-10 14:02 UTC, cmb69 commented on language/oop5/basic.xml
> +    a deprecation notice.
It seems to me that we're swallowing to much relevant info. E.g. is calling a non-static method statically allowed as of PHP 8.0.0? What's the value of $this in this case prior to PHP 8.0.0?

2021-01-11 15:21 UTC, afilina commented
@Girgias No objections from me.

2021-01-12 02:37 UTC, Girgias commented on language/oop5/basic.xml
> +    a deprecation notice.
Indeed, restored information.

2021-01-12 20:54 UTC, cmb69 approved these changes
Thank you! A added a nit comment; otherwise LGTM (I'm fine with committing the TODO markers).

2021-01-12 20:54 UTC, cmb69 commented on language/oop5/references.xml
>     itself as value anymore. It only contains an object identifier which allows
```suggestion
   itself as value. It only contains an object identifier which allows
```

2021-01-13 04:02 UTC, closed without merging