Overhaul XML handler docs
php/doc-en pull request #2832
Opened 2023-10-03 15:25 UTC by Girgias

This also removes the last remaining usage of the ``&note.func-callback;`` language snippet.

2023-10-03 18:31 UTC, nielsdos reviewed
Changes look good.
I just have to check whether false can actually be passed, and if so, in which cases...

2023-10-03 18:31 UTC, nielsdos commented on language-snippets.ent
> + it can be the name of a method of an object set with
I think this wording is not optimal.
The note about array(obj, method) was removed, and this `can` is suggestive that this is the usual way to go about it (and no other way is possible).
Not sure how to improve it though.

2023-10-03 18:31 UTC, nielsdos commented on reference/xml/functions/xml-set-element-handler.xml
> +   <parameter>start_handler</parameter> is called when a new XML element is
Due to the fact that the newline is not rendered in the HTML output, it looks like `parser.start_handler` is called (...), which I find confusing tbh.

2023-10-03 18:31 UTC, nielsdos commented on reference/xml/functions/xml-set-end-namespace-decl-handler.xml
> -       <constant>XML_ERROR_EXTERNAL_ENTITY_HANDLING</constant>.
I wonder how long this wrong remark has been in the manual

2023-10-03 19:08 UTC, nielsdos requested changes
False remarks

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-external-entity-ref-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>system_id</parameter></methodparam>
system_id can never be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-external-entity-ref-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>open_entity_names</parameter></methodparam>
open_entity_names cannot be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-character-data-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>data</parameter></methodparam>
Can't be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-notation-decl-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>notation_name</parameter></methodparam>
Can't be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-notation-decl-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>system_id</parameter></methodparam>
system_id can never be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-processing-instruction-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>target</parameter></methodparam>
Target and data can never be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-start-namespace-decl-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>uri</parameter></methodparam>
uri can't be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-unparsed-entity-decl-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>system_id</parameter></methodparam>
system_id can never be false

2023-10-03 19:08 UTC, nielsdos commented on reference/xml/functions/xml-set-unparsed-entity-decl-handler.xml
> +        <methodparam><type class="union"><type>string</type><type>false</type></type><parameter>entity_name</parameter></methodparam>
entity_name cannot be false

2023-10-04 12:58 UTC, Girgias commented on reference/xml/functions/xml-set-element-handler.xml
> +   <parameter>start_handler</parameter> is called when a new XML element is
Right, I'll split this into a new para tag

2023-10-04 12:58 UTC, Girgias commented on language-snippets.ent
> + it can be the name of a method of an object set with
Oh I forgot to describe the param if it is a callable >_>

2023-10-04 12:59 UTC, Girgias commented on reference/xml/functions/xml-set-element-handler.xml
>          <methodparam><type>string</type><parameter>name</parameter></methodparam>
Yes, because it didn't use ``_xml_xmlchar_zval()`` :D

2023-10-04 23:29 UTC, merged