Generate some standard methodsynopses based on stubs
php/doc-en pull request #289
Opened 2020-12-23 23:44 UTC by kocsismate

These are mostly simpler cases (e.g. when only parameter names changed).

2020-12-26 19:27 UTC, cmb69 commented
Thank you! I've [committed most of this](http://svn.php.net/viewvc?view=revision&revision=352191), but left a couple of functions for closer review.

2021-05-04 17:27 UTC, Girgias commented
Ping, this seems to have gotten stale

2021-05-23 11:33 UTC, cmb69 commented
I've merged the changes to abs(), ceil(), floor() and round() now (e2a460ca39fece49eefdd5bd2282e5ba7b488fea).

2021-08-17 14:54 UTC, afilina commented
Besides the merge conflicts, what else is preventing this PR from being merged?

2021-09-17 20:08 UTC, kamil-tekiela requested changes
I think this can be merged but without `assert` changes. That page needs more work.

2021-09-17 20:08 UTC, kamil-tekiela commented on reference/info/functions/assert.xml
> +   <methodparam choice="opt"><type class="union"><type>Throwable</type><type>string</type><type>null</type></type><parameter>description</parameter><initializer>&null;</initializer></methodparam>
Why is this line changed? It looks like this `<methodsynopsis>` should be removed. I think it's better to leave the `assert` page out of this PR and then deal with it separately.

2021-09-17 20:08 UTC, kamil-tekiela commented on reference/info/functions/assert.xml
> +    any — literal values such as 1 or "two" will not be passed via
Why this change?

2021-09-17 20:08 UTC, kamil-tekiela commented on reference/math/functions/srand.xml
> +   or with a random value if <parameter>seed</parameter> is 0.
```suggestion
   or with a random value if <parameter>seed</parameter> is <literal>0</literal>.
```

2021-09-17 20:32 UTC, cmb69 commented on reference/info/functions/assert.xml
> +    any — literal values such as 1 or "two" will not be passed via
The change itself is fine, but I think there shouldn't be an mdash. Maybe an ndash, or a semicolon, or some rewording is more appropriate. OTOH, this is not really related to this PR.

2021-09-19 09:00 UTC, kocsismate commented
I got rid of assert, rebased to master, and implemented the suggested change.

2021-09-19 09:01 UTC, kocsismate commented on reference/info/functions/assert.xml
> +    any — literal values such as 1 or "two" will not be passed via
> Why this change?

gen_stub.php (ext/dom) changes these by some reason.

2021-09-19 11:30 UTC, kamil-tekiela approved these changes

2021-09-19 11:30 UTC, merged

2021-09-19 11:30 UTC, kamil-tekiela commented
Thanks. Looks good to me.