Synchronize ext/dom with the stubs based on the PHP 8.3 changes
php/doc-en pull request #2890
Opened 2023-10-28 09:01 UTC by kocsismate

2023-10-28 10:50 UTC, TimWolla commented
Duplicate of #2813?

2023-10-28 10:56 UTC, kocsismate commented
Nope, fortunately this one synchronizes the class synopses. 🙂

2023-10-28 11:53 UTC, Girgias reviewed
I'll wait for @nielsdos to comment about the descriptions but looks good to me otherwise

2023-10-28 12:34 UTC, nielsdos requested changes
Thank you for working on this Máté!
I have some remarks and description suggestions :slightly_smiling_face:

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domelement.xml
> +      <para>The element class name</para>
```suggestion
      <para>A string representing the classes of the element separated by spaces</para>
```

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domnode.xml
> +    <classsynopsisinfo role="comment">&Constants;</classsynopsisinfo>
I only added these constants in 8.**4**, they are here to support the compareDocumentPosition method that was added in 8.4.

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domnode.xml
> +  <section xml:id="domnode.constants">
Same as earlier: they're 8.4 material

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domnode.xml
> +      <para>The parent of this element. If there is no such element, this returns &null;.</para>
```suggestion
      <para>The parent element of this element. If there is no such element, this returns &null;.</para>
```

Otherwise it might be confused with parent**Node**, which is the parent node of the element.

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domnode.xml
> +      <para></para>
```suggestion
      <para>Whether the node is connected to a document</para>
```

2023-10-28 12:34 UTC, nielsdos commented on reference/dom/domnode.xml
> +       <entry>8.3.0</entry>
Same remark about the constants as earlier.

2023-10-29 09:56 UTC, kocsismate commented on reference/dom/domnode.xml
> +    <classsynopsisinfo role="comment">&Constants;</classsynopsisinfo>
Ohh, I totally missed that :/ And thanks for the heads up!

2023-10-29 14:37 UTC, merged