Generate imap methodsynopses based on stubs
php/doc-en pull request #292
Opened 2020-12-29 11:29 UTC by kocsismate

2020-12-29 11:29 UTC, kocsismate commented
@Girgias here it is! :)

2020-12-29 11:33 UTC, kocsismate commented on reference/imap/functions/imap-mutf7-to-utf8.xml
> -  <methodsynopsis role="procedural">
The role wasn't really needed, was it?

2020-12-29 11:33 UTC, kocsismate commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
Is there a better wording for this?

2020-12-29 11:33 UTC, kocsismate commented on reference/imap/functions/imap-sort.xml
> +       <parameter>reverse</parameter> now accepts <type>bool</type> rather than <type>int</type>
Is this wording ok? I tried to search for previous entries, but I couldn't find any

2020-12-29 13:05 UTC, cmb69 commented on reference/imap/functions/imap-mutf7-to-utf8.xml
> -  <methodsynopsis role="procedural">
I'd leave the roles, even if they are superfluous.

2020-12-29 15:28 UTC, Girgias requested changes
As the resource to object conversion is a PHP 8.1 affair, none of the changelog entries should be there, and all ``IMAPConnection`` type declarations should be changed back to resource.

2020-12-29 15:28 UTC, Girgias commented on language-snippets.ent
> +
This is incorrect, as this is only on master and PHP 8.1

2020-12-29 15:28 UTC, Girgias commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
This should also have a note at the top, look in the language snippets there are various variations about deprecated and removed, one of them is for function aliases

2020-12-29 15:28 UTC, Girgias commented on reference/imap/functions/imap-mutf7-to-utf8.xml
> +<refentry xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="function.imap-mutf7-to-utf8">
Dumb question, but how does the ordering work? As it seems usually it's the id, then docbook xmlns and then the w3c one, but it sometimes get randomly changed?

2020-12-29 15:28 UTC, Girgias commented on reference/imap/functions/imap-sort.xml
> +       <parameter>reverse</parameter> now accepts <type>bool</type> rather than <type>int</type>
```suggestion
       <parameter>reverse</parameter> is now <type>bool</type> instead of <type>int</type>
```
Maybe?

2020-12-30 09:47 UTC, kocsismate commented on language-snippets.ent
> +
:( I forgot it.. It was the major part of this PR for me to add these entries :S

2020-12-30 12:58 UTC, Girgias commented on language-snippets.ent
> +
I think if you can comment the section out, it would make it easier when PHP 8.1 rolls out. Or need to keep this diff around to apply it next year. :)

2020-12-30 13:04 UTC, cmb69 commented on language-snippets.ent
> +
Or provide a separate PR with this (which could either be labelled PHP-8.1, or could target a separate branch).

2020-12-30 13:09 UTC, kocsismate commented on language-snippets.ent
> +
Thanks for the ideas, but all this will be unnecessary for PHP 8.1. Since we're going to have reliable type info in the docs soon, we'll be able to generate the changelog for he next release. My script is already prepared for that, we only have to come up with a good default wording :)

2020-12-30 16:44 UTC, kocsismate commented on reference/imap/functions/imap-mutf7-to-utf8.xml
> -  <methodsynopsis role="procedural">
I'll revert these changes

2020-12-30 16:44 UTC, kocsismate commented on reference/imap/functions/imap-mutf7-to-utf8.xml
> +<refentry xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="function.imap-mutf7-to-utf8">
As it turned out, it was due to a tiny regex issue :)

2020-12-30 16:58 UTC, kocsismate commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
It wasn't deprecated before, was it?

2020-12-30 17:06 UTC, cmb69 commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
Apparently, not.

2020-12-30 17:12 UTC, kocsismate commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
@Girgias Was it intentional then? 🤔

2020-12-30 17:16 UTC, cmb69 commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
Actually, it appears to have been [removed accidentially](https://github.com/php/php-src/pull/4724). ;)

2020-12-30 17:17 UTC, kocsismate commented
I'm closing this in favor of https://github.com/php/doc-en/pull/297 (I messed up the branches :D)

2020-12-30 17:17 UTC, closed without merging

2020-12-30 17:21 UTC, kocsismate commented on reference/imap/functions/imap-header.xml
> +       This function alias was removed.
No, it was removed as part of: https://github.com/php/php-src/pull/6179/files#diff-58ec1face941cc36f27cf1fe312fd29ceb27b2c305ffc8f63645566de5c72688L36 But it also appears for me that it was unintentional.