[PHP 8.3] New DOM methods
php/doc-en pull request #2922
Opened 2023-11-06 17:38 UTC by saundefined

2023-11-06 20:22 UTC, nielsdos requested changes
Thanks a lot for this Sergey!
Here's a first round of feedback :slightly_smiling_face:

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domelement/toggleattribute.xml
> +
If &null;, the function will toggle the attribute.
If &true;, the function adds the attribute.
If &false;, the function removes the attribute.

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domelement/toggleattribute.xml
> +$dom = new DOMDocument();
Suggested example and output:

```php
<?php

$dom = new DOMDocument();
$dom->loadXML("<?xml version='1.0'?><container selected=""/>");

var_dump($dom->documentElement->toggleAttribute('selected'));
echo $dom->saveXML() . PHP_EOL;

var_dump($dom->documentElement->toggleAttribute('selected'));
echo $dom->saveXML();

```

Output:
```
bool(false)
<?xml version="1.0"?>
<container/>

bool(true)
<?xml version="1.0"?>
<container selected=""/>
```

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domnode/contains.xml
> +   Returns &true; if node contains other node, &false; otherwise.
```suggestion
   Returns &true; if node contains <parameter>other</parameter> node, &false; otherwise.
```

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domnode/contains.xml
> +   Checks if node contains other node.
```suggestion
   Checks if node contains <parameter>other</parameter> node.
```

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domnode/getrootnode.xml
> +
This parameter has no influence at the moment because it influences the shadow DOM, which is not supported yet.

2023-11-06 20:22 UTC, nielsdos commented on reference/dom/domparentnode/replacechildren.xml
> +       The nodes to replace.
```suggestion
       The nodes replacing the children.
```

2023-11-06 20:31 UTC, saundefined commented
@nielsdos, thanks a lot!

2023-11-06 20:40 UTC, nielsdos commented
No no, thank you ;)
I'm going to do another double check tomorrow or so.
And I'll let @Girgias also have a sanity check, especially for the docbook-specific rules that I'm less familiar with :)

2023-11-06 22:15 UTC, Girgias commented on reference/dom/domnode/contains.xml
> +   </programlisting>
Missing output of true in a screen tag?

2023-11-06 22:15 UTC, Girgias commented on reference/dom/domnode/getrootnode.xml
> +   Returns root node.
```suggestion
   Returns the root node.
```

2023-11-06 22:15 UTC, Girgias commented on reference/dom/domnode/isequalnode.xml
> +]]>
Output of true in screen tag?

2023-11-06 22:15 UTC, Girgias commented on reference/dom/domnode/getrootnode.xml
> +]]>
Output in screen tag?

2023-11-07 15:57 UTC, Girgias commented on reference/dom/domelement/toggleattribute.xml
> +$dom = new DOMDocument();
@saundefined could you use this better example?

2023-11-07 16:04 UTC, saundefined commented on reference/dom/domelement/toggleattribute.xml
> +$dom = new DOMDocument();
My bad, I was sure I had fixed that,
thanks for the reminder

2023-11-07 16:05 UTC, merged

2023-11-07 16:05 UTC, Girgias commented
Thank you!

2023-11-07 16:33 UTC, nielsdos commented on reference/dom/domnode/contains.xml
> +   <screen>
Is there an &example.outputs; missing here? I see it in the other examples but not here.

2023-11-07 16:33 UTC, nielsdos commented on reference/dom/domnode/isequalnode.xml
> +   <screen>
Same example.outputs question

2023-11-07 16:49 UTC, saundefined commented on reference/dom/domnode/contains.xml
> +   <screen>
Fixed in [cdbee08](https://github.com/php/doc-en/commit/cdbee08c7312e25ad733047ae65c4628c24aa1b8)
(also found yet another mistake)