Fix `debug_backtrace` argument description
php/doc-en pull request #2935
Opened 2023-11-12 20:59 UTC by GromNaN

There is an inversion in the documentation of the values `0` and `1`. 

Demonstration: https://3v4l.org/m3MD6

Documentation introduced by #1630

2023-11-12 21:26 UTC, GromNaN commented on reference/errorfunc/functions/debug-backtrace.xml
> -             <entry><code>debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS &amp; DEBUG_BACKTRACE_PROVIDE_OBJECT)</code></entry>
The bit-and operator `&` is irrelevant when using bit masks.

2023-11-12 21:26 UTC, GromNaN commented on reference/errorfunc/functions/debug-backtrace.xml
> +             <entry><code>debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT|DEBUG_BACKTRACE_IGNORE_ARGS)</code></entry>
This additional combination `DEBUG_BACKTRACE_PROVIDE_OBJECT|DEBUG_BACKTRACE_IGNORE_ARGS` was missing.

2023-11-13 12:19 UTC, Girgias requested changes
Thank you!

Needs some additional tiny markup fixes but LGTM :)

2023-11-13 12:50 UTC, GromNaN reviewed
Thanks for your review, but I think it's correct. However I don't know how to test.

2023-11-13 12:50 UTC, GromNaN commented on reference/errorfunc/functions/debug-backtrace.xml
> -             <entry><code>debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS &amp; DEBUG_BACKTRACE_PROVIDE_OBJECT)</code></entry>
I don't think so. There is only one line for `$options=0`. So I omitted the `morerows` attribute.

2023-11-13 12:50 UTC, GromNaN commented on reference/errorfunc/functions/debug-backtrace.xml
> +             <entry><code>debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT|DEBUG_BACKTRACE_IGNORE_ARGS)</code></entry>
Same here, there is 2 rows for this result, so `morerow=1`

2023-11-14 01:06 UTC, Girgias commented on reference/errorfunc/functions/debug-backtrace.xml
> -             <entry><code>debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS &amp; DEBUG_BACKTRACE_PROVIDE_OBJECT)</code></entry>
Ah yes indeed, I was confused.

2023-11-14 01:14 UTC, Girgias approved these changes

2023-11-14 01:21 UTC, merged