Enhancement: Switch from Travis CI to GitHub Actions
php/doc-en pull request #299
Opened 2020-12-30 22:01 UTC by localheinz

This PR

* [x] switches from Travis CI to GitHub Actions

💁‍♂️ You can see this in action at https://github.com/localheinz/doc-en/pull/1, where, however, it currently [fails](https://github.com/localheinz/doc-en/pull/1/checks?check_run_id=1627965910#step:4:31) with

![CleanShot 2020-12-30 at 23 00 51](https://user-images.githubusercontent.com/605483/103383417-f18ca700-4af2-11eb-8cb3-2d0f48b5219d.png)

2020-12-30 22:04 UTC, cmb69 commented on .github/workflows/integrate.yaml
> +          repository: "salathe/phpdoc-base"
Any reason why you use salathe/phpdoc-base instead of php/doc-base?

2020-12-30 22:06 UTC, localheinz commented on .github/workflows/integrate.yaml
> +        uses: "actions/checkout@v2"
For reference, see https://github.com/actions/checkout.

2020-12-30 22:06 UTC, localheinz commented on .github/workflows/integrate.yaml
> +          repository: "salathe/phpdoc-base"
@cmb69 

Thank you for taking a look - that was a leftover from my outdated fork. Updated!

2020-12-30 22:13 UTC, localheinz commented on .github/workflows/integrate.yaml
> +  LANGUAGE: "en"
I have extracted an environment variable here, so it can be referenced in multiple places

- for the directory where to check out this repository
- for the command that runs to build the documentation

Does that make sense?

2020-12-30 22:21 UTC, cmb69 commented on .github/workflows/integrate.yaml
> +  LANGUAGE: "en"
I don't see any real advantage, but it certainly doesn't hurt either.

Anyhow, thanks a lot for the PR!

2020-12-30 22:24 UTC, localheinz commented on .github/workflows/integrate.yaml
> +name: "Integrate"
The name of the workflow appears in the Checks section:

![CleanShot 2020-12-30 at 23 22 48](https://user-images.githubusercontent.com/605483/103384265-0c144f80-4af6-11eb-9e95-5d5ff96c432b.png)

as well as in the Checks tab:

![CleanShot 2020-12-30 at 23 24 12](https://user-images.githubusercontent.com/605483/103384286-2bab7800-4af6-11eb-86ad-895309a7fe79.png)

2020-12-30 22:25 UTC, localheinz commented on .github/workflows/integrate.yaml
> +    name: "Build"
The name of the job appears in the Checks section:

![CleanShot 2020-12-30 at 23 22 48](https://user-images.githubusercontent.com/605483/103384265-0c144f80-4af6-11eb-9e95-5d5ff96c432b.png)

as well as in the Checks tab:

![CleanShot 2020-12-30 at 23 24 12](https://user-images.githubusercontent.com/605483/103384286-2bab7800-4af6-11eb-86ad-895309a7fe79.png)

2020-12-30 22:32 UTC, Girgias commented on .github/workflows/integrate.yaml
> +          - "7.2"
Any reason for picking 7.2?

2020-12-30 22:34 UTC, localheinz commented on .github/workflows/integrate.yaml
> +          - "7.2"
Yes, it is the same version that is currently used on Travis CI, see:

https://github.com/php/doc-en/blob/06e8e34994d0d5183cf43b72932a2ffa48406dce/.travis.yml#L5

2020-12-30 22:37 UTC, localheinz commented on .github/workflows/integrate.yaml
> +        uses: "shivammathur/setup-php@v2"
For reference, see https://github.com/shivammathur/setup-php.

If preferred, I can use the corresponding binary directly, but using this action, setting up PHP is more convenient.

2020-12-30 22:37 UTC, localheinz commented on .github/workflows/integrate.yaml
> +          - "7.2"
Can we use a modern version?

Which one would you suggest?

2020-12-30 22:41 UTC, nikic submitted a review, later dismissed
Turns out we can't use GH actions right now, as we need someone to verify the @php-pulls email address. Marking as changes requested until we can get that done.

2020-12-30 22:45 UTC, Girgias commented on .github/workflows/integrate.yaml
> +          - "7.2"
PHP 8.0 works as I've built the docs using that. :)

2020-12-30 22:48 UTC, localheinz commented on .github/workflows/integrate.yaml
> +          - "7.2"
Will update in a moment!

2020-12-30 22:54 UTC, localheinz commented on .github/workflows/integrate.yaml
> +  LANGUAGE: "en"
We could parse the language from the name of the repository, making the workflows identical across all variations!

2020-12-31 00:00 UTC, cmb69 commented on .github/workflows/integrate.yaml
> +  LANGUAGE: "en"
Would it be possible to simplify the individual actions for each translation by moving some common stuff to doc-base?

2020-12-31 09:14 UTC, localheinz commented on .github/workflows/integrate.yaml
> +  LANGUAGE: "en"
@cmb69 

> Would it be possible to simplify the individual actions for each translation by moving some common stuff to doc-base?

Not that I can think of, but perhaps something will come up!

2021-01-02 23:11 UTC, localheinz commented
@nikic 

Thank you for the update!

2021-01-06 06:14 UTC, jhdxr commented on .github/workflows/integrate.yaml
> +        uses: "shivammathur/setup-php@v2"
"ubuntu-latest" includes a pre-installed php already, and it's good enough to build the document already. I prefer to remove this part entirely to make the whole script simpler.

2021-01-06 11:46 UTC, localheinz commented on .github/workflows/integrate.yaml
> +        uses: "shivammathur/setup-php@v2"
@jhdxr

Adjusted!

2021-01-08 15:23 UTC, afilina requested changes

2021-01-08 15:23 UTC, afilina commented on .github/workflows/integrate.yaml
> +  pull_request: null
Unless I'm mistaken, this will only run when we push to master, but not when we open a PR, meaning that we can't see whether a PR breaks the build. I don't see the checks on this PR:
![image](https://user-images.githubusercontent.com/199835/104031422-b3e6e880-519a-11eb-944d-88df8619e2ef.png)

I would expect to see checks on a PR that first introduces GitHub actions. See checkmark next to a commit on this PR:
![image](https://user-images.githubusercontent.com/199835/104031827-41c2d380-519b-11eb-921f-77bfb453e436.png)

This can be solved by specifying nothing instead of `null`. Example on [roave/dont](https://github.com/Roave/Dont/blob/1.4.x/.github/workflows/phpunit.yml#L4)

2021-01-08 16:41 UTC, localheinz commented on .github/workflows/integrate.yaml
> +  pull_request: null
@afilina

> Unless I'm mistaken, this will only run when we push to master, but not when we open a PR, meaning that we can't see whether a PR breaks the build. I don't see the checks on this PR:

Yes, you are mistaken. This will run jobs for pull requests.

The reason you are not seeing checks here is because a workflow for GitHub Actions has not been defined in this repository yet, and because I do not have write privileges. I am pushing from a fork.

As pointed out in the body of the pull request, you can see this in action in https://github.com/localheinz/doc-en/pull/1.

2021-01-08 17:05 UTC, cmb69 commented
> […], as we need someone to verify the @php-pulls email address.

Who could do that?

2021-01-08 17:06 UTC, nikic commented
@cmb69 This is already done, so it's fine to merge.

2021-01-08 17:11 UTC, localheinz commented
Quick heads-up, the workflow is exactly the same as the one in https://github.com/php/doc-de/pull/2, with one slight difference:

```diff
--- doc-de/.github/workflows/integrate.yaml	2021-01-08 18:06:49.000000000 +0100
+++ doc-en/.github/workflows/integrate.yaml	2021-01-08 18:08:30.000000000 +0100
@@ -17,7 +17,7 @@
     strategy:
       matrix:
         language:
-          - "de"
+          - "en"

     steps:
       - name: "Checkout php/doc-${{ matrix.language }}"
```

The idea is to use workflows with the least differences across all repositories.

Instead of using a matrix, we could also parse the language identifier from the repository name, if that makes sense.

2021-01-08 17:14 UTC, localheinz commented on .github/workflows/integrate.yaml
> +  pull_request: null
@afilina 

Quick note on why I use 

```yaml
  pull_request: null
```

here: I use [`yamllint`](https://github.com/adrienverge/yamllint) in my repositories to lint YAML files, and the configuration I use complains when leaving it empty.

For an example, see https://github.com/ergebnis/php-library-template/blob/f6af5cb5c234a146f620061e95b34b432bf2e1c8/.github/workflows/integrate.yaml#L32-L37.

2021-01-08 17:22 UTC, cmb69 commented
> The idea is to use workflows with the least differences across all repositories.

That makes sense.

> Instead of using a matrix, we could also parse the language identifier from the repository name, if that makes sense.

I think it's good as is.

Is this ready to be merged, @localheinz ?

2021-01-08 17:23 UTC, afilina commented on .github/workflows/integrate.yaml
> +  pull_request: null
Thanks for clarifying :)

2021-01-08 18:01 UTC, localheinz commented
@cmb69 

👍

2021-01-08 18:20 UTC, cmb69 commented
Thank you, @localheinz !

2021-01-08 18:20 UTC, closed without merging

2021-01-08 18:20 UTC, localheinz commented
Thank you, @cmb69!

2021-01-08 18:30 UTC, localheinz commented
@cmb69 

Is there interest in adding more tooling to the workflows?

2021-01-08 18:40 UTC, cmb69 commented
Well, it might be nice to actually build the documentation for pull request, so it could be viewed, but I have doubts that that's reasonably doable. Other than that, running ./configure as it's done now, is probably all we need. :)

2021-01-08 21:28 UTC, localheinz commented
@cmb69 

That sounds quite cool, actually, and should be possible!