Generate mysqli methodsynopses based on stubs
php/doc-en pull request #301
Opened 2021-01-01 18:53 UTC by kocsismate

2021-01-01 18:54 UTC, kocsismate commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
is it the correct spelling, isn't it?

2021-01-01 18:55 UTC, Girgias commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
No, only use ``an`` if the noun starts with a vowel, so it's ``a stdClass``/``a standard  class``

2021-01-01 19:06 UTC, kocsismate commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
But isn't this an exceptional case? I agree that "a standard class" make sense, but a "stdClass" sounds really weird (when you say "S-T-D" literally).

2021-01-01 19:15 UTC, Girgias commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
Right because `S` is a vowel sound, so you'd use `an`, but you don't just have the initialism so how I pronounce it is ``a S-T-D class`` where S-T-D becomes an adjective (kinda?), but that might be incorrect soooo, might need to ask some other native folks

2021-01-01 21:48 UTC, cmb69 commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
Well, I pronounce it "standard class", but that might be uncommon.

2021-01-04 16:23 UTC, kamil-tekiela reviewed
Thanks for the PR. It looks really good. I have left a few small notes about things that have to be adjusted. Everything else looks good to me.

2021-01-04 16:23 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/error.xml
> +   <type class="union"><type>string</type><type>null</type></type><methodname>mysqli_stmt_error</methodname>
Same as the property the function always returns a string. The code probably needs to be adjusted.

2021-01-04 16:23 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/send-long-data.xml
> +   <methodparam><type>int</type><parameter>param_num</parameter></methodparam>
In hindsight, we should have changed the parameter name to `$index`

2021-01-04 16:23 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/sqlstate.xml
> +   <type class="union"><type>string</type><type>null</type></type><methodname>mysqli_stmt_sqlstate</methodname>
Same as with the others. Technically the code has an if statement but the only possible return value is a string.

2021-01-04 16:56 UTC, kocsismate commented on reference/mysqli/mysqli/affected-rows.xml
> +   <methodparam><type>mysqli</type><parameter>mysql</parameter></methodparam>
I also forgot what happened, but a git blame leads to https://github.com/php/php-src/pull/6172, and one of last suggestions was this change. Still no clue about the reasoning, but I'm ok either way.

2021-01-04 16:59 UTC, kocsismate commented on reference/mysqli/mysqli/begin-transaction.xml
> +       <parameter>name</parameter> is now nullable.
Almost. It became nullable to have a sensible default value, because functions have to work the same way when optional parameters are *not* passed and when they are passed with their default value.

2021-01-04 17:03 UTC, kocsismate commented on reference/mysqli/mysqli/character-set-name.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>null</type></type><methodname>mysqli::character_set_name</methodname>
`mysqli::character_set_name()` does this:

```C
cs_name = mysql_character_set_name(mysql->mysql);
if (cs_name) {
    RETURN_STRING(cs_name);
}
```

I'm not sure what `mysqlnd_character_set_name()` does exactly, but if you are sure that it always returns a non-null result, please update the stubs and add an assertion for the C code.

2021-01-04 17:07 UTC, kocsismate commented on reference/mysqli/mysqli/commit.xml
> +   <methodparam choice="opt"><type>int</type><parameter>flags</parameter><initializer>-1</initializer></methodparam>
No idea. I mean, it came from the mysqli stubs we have (as every change here besides the change logs)...

2021-01-04 17:15 UTC, kocsismate commented on reference/mysqli/mysqli/construct.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>password</parameter><initializer>&null;</initializer></methodparam>
This is not true. https://github.com/php/php-src/commit/9cf6a5413a563b0c174a6cb4974bfd0795ce43e4 fixed the default value handling by making these params nullable with a null default value.

2021-01-04 17:16 UTC, kocsismate commented on reference/mysqli/mysqli/error.xml
> +   <type class="union"><type>string</type><type>null</type></type><methodname>mysqli_error</methodname>
Nice catch! But this is also a problem with the stubs.

2021-01-04 17:19 UTC, kocsismate commented on reference/mysqli/mysqli/get-client-info.xml
> +   <methodparam choice="opt"><type class="union"><type>mysqli</type><type>null</type></type><parameter>mysql</parameter><initializer>&null;</initializer></methodparam>
See discussion in my PR for details: https://github.com/php/php-src/pull/4878#pullrequestreview-309797488

But I guess we can remove the parameter from the documentation.

2021-01-04 17:24 UTC, cmb69 commented on reference/mysqli/mysqli/connect-error.xml
> +  <fieldsynopsis><type>string</type><varname linkend="mysqli.connect-error">mysqli-&gt;connect_error</varname></fieldsynopsis>
@kamil-tekiela, could you please provide a PR to fix the [mysqli stubs](https://github.com/php/php-src/blob/PHP-8.0/ext/mysqli/mysqli.stub.php)?

2021-01-04 17:25 UTC, kocsismate commented on reference/mysqli/mysqli/real-connect.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>hostname</parameter><initializer>&null;</initializer></methodparam>
Are you looking at the right branch? They are definitely nullable.

But again, every change in this PR is autogenerated from the canonical source of truth (mysqli.stub.php), so I'd appreciate if you could review the stubs first, so that I can update this PR after the issues are addressed "upstream".

2021-01-04 17:27 UTC, kocsismate commented on reference/mysqli/mysqli_result/fetch-all.xml
> +   <modifier>public</modifier> <type class="union"><type>array</type><type>false</type></type><methodname>mysqli_result::fetch_all</methodname>
I guess the stub was not updated after the warning promotion in this function.

2021-01-04 18:16 UTC, kamil-tekiela commented on reference/mysqli/mysqli/connect-error.xml
> +  <fieldsynopsis><type>string</type><varname linkend="mysqli.connect-error">mysqli-&gt;connect_error</varname></fieldsynopsis>
How can I do that? Properties/constants are not defined in the stubs. Should they also be defined in stubs? Is there a separate file for properties?

2021-01-04 18:23 UTC, cmb69 commented on reference/mysqli/mysqli/connect-error.xml
> +  <fieldsynopsis><type>string</type><varname linkend="mysqli.connect-error">mysqli-&gt;connect_error</varname></fieldsynopsis>
Ah, right, there are no stubs for properties and constants yet, so nothing to do in this regard, However, it seems that there may be several functions/methods with incorrect info, and that should be fixed in the stub file first. :)

2021-01-04 18:33 UTC, kamil-tekiela commented on reference/mysqli/mysqli/construct.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>password</parameter><initializer>&null;</initializer></methodparam>
@nikic Could you share your opinion? I haven't noticed any change to the default values between PHP 7 and 8. Whether I pass NULL or an empty string the behaviour is the same. For `mysqli_connect()`, `mysqli::connect()`, `mysqli_real_connect()` and `mysqli::real_connect()` the first 3 parameters are as follows:
 - Host: The default value is taken from INI file and if not present then the default is "localhost"
 - Username: The default value is taken from INI file and if not present then the default is ""
 - Password: The default value is taken from INI file and if not present then the default is ""

For mysqli constructor, the first argument is a little magical. If nothing is provided, not even NULL or empty string, then it falls back to `mysqli_init()`. 

This is also inline with what the MySQL doc says https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-connect.html

What change have you made to these functions recently?

2021-01-04 19:54 UTC, kamil-tekiela commented on reference/mysqli/mysqli/get-charset.xml
> +   <modifier>public</modifier> <type class="union"><type>object</type><type>null</type></type><methodname>mysqli::get_charset</methodname>
It looks like this is for libmysql client. Mysqlnd always sets the charset but we can't guarantee that libmysql does also.

2021-01-04 20:22 UTC, kamil-tekiela commented on reference/mysqli/mysqli/real-connect.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>hostname</parameter><initializer>&null;</initializer></methodparam>
To clarify, I meant that even though all arguments are nullable (in the sense than you can provide all NULL arguments) the default values are not NULL. Even if you pass NULL as the hostname then the value will be a string 'localhost'.

2021-01-04 20:27 UTC, kocsismate commented on reference/mysqli/mysqli/real-connect.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>hostname</parameter><initializer>&null;</initializer></methodparam>
Yes, but from an end-user perspective, it doesn't matter what the implementation do with the default value. Sure, in this particular case, `"localhost"` could have been defined as default, but it can't be changed anymore, and `null` is also ok.

2021-01-04 21:18 UTC, kamil-tekiela commented on reference/mysqli/mysqli_result/fetch-field-direct.xml
> +   <modifier>public</modifier> <type class="union"><type>object</type><type>false</type></type><methodname>mysqli_result::fetch_field_direct</methodname>
After some research I have learned that there is a way to get false values. So let's forget this one.

2021-01-06 12:46 UTC, kamil-tekiela commented on reference/mysqli/mysqli/poll.xml
> +     <term><parameter>reject</parameter></term>
It looks like you will need to adjust this manually. Your script must have got confused with the parameter names.

2021-01-06 13:03 UTC, kamil-tekiela commented on reference/mysqli/mysqli/get-client-info.xml
> +   <methodparam choice="opt"><type class="union"><type>mysqli</type><type>null</type></type><parameter>mysql</parameter><initializer>&null;</initializer></methodparam>
Opened PR to fix this. https://github.com/php/php-src/pull/6576

2021-01-06 13:06 UTC, kamil-tekiela commented on reference/mysqli/mysqli/real-connect.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>hostname</parameter><initializer>&null;</initializer></methodparam>
Ok, let's make the signatures for connect methods as you're suggesting. I will have a think about how to improve these manual pages so that we don't lose this crucial information.

2021-02-13 17:46 UTC, kocsismate commented
@kamil-tekiela I've just rebased to master, and adapted a few recent changes. Can you please take another look on this PR?

2021-02-18 22:19 UTC, kamil-tekiela requested changes
It looks good. I am as happy as a grumpy man can be. The mysqli docs still has a lot of issues for which I will hopefully submit more PRs after yours gets accepted.

2021-02-18 22:19 UTC, kamil-tekiela commented on reference/mysqli/mysqli_result/num-rows.xml
> +  <fieldsynopsis><type>int</type><varname linkend="mysqli-result.num-rows">mysqli_result-&gt;num_rows</varname></fieldsynopsis>
@kocsismate Can you make the return value the same as `mysqli_num_rows()`?
```suggestion
  <fieldsynopsis><type class="union"><type>int</type><type>string</type></type><varname linkend="mysqli-result.num-rows">mysqli_result-&gt;num_rows</varname></fieldsynopsis>
```

2021-02-20 12:27 UTC, kocsismate commented
@kamil-tekiela I've just added the suggested change!

2021-03-12 14:02 UTC, kocsismate commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
What should be the final article choice? :) @cmb69 Is it possible to merge? Or it would take too much time to review? :S

2021-03-12 14:07 UTC, kamil-tekiela commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
If not specified, an object of type <classname>stdClass</classname> is returned.

2021-03-12 14:08 UTC, cmb69 commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
I'm still not sure whether "a" or "an" is correct. The name of that class is so well chosen... ;)

Anyhow, I'll review this over the weekend.

2021-03-12 14:14 UTC, kamil-tekiela commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
Greping the docs finds only `a stdClass object` or just `stdClass` without an article.

2021-03-12 14:25 UTC, cmb69 commented on reference/mysql/functions/mysql-fetch-object.xml
> +        If not specified, an <classname>stdClass</classname> object is returned.
Thanks! So I suggest to stick with "a".

2021-03-18 22:33 UTC, cmb69 commented
Thanks to all of you! I have committed most of the changes as 7e5d0d1bb69180c9de1992edf9613215c975fa57, but was not sure about the rest. Rebased onto master.

2021-08-17 14:54 UTC, afilina commented
Besides a need to rebase, what else is preventing this PR from being merged?

2021-12-28 08:42 UTC, kocsismate commented
I'm closing this PR in favor of a few followups

2021-12-28 08:42 UTC, closed without merging