mysqli_xdevapi: fix typos/change wording
php/doc-en pull request #3014
Opened 2023-12-13 16:08 UTC by msamesch

This fixes some typos, adds some tags, and tries to improve wording.

2023-12-15 01:33 UTC, Girgias requested changes
Thank you! I have left some comments and ssuggestions. :)

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/execute.xml
> +   A DocResult object that can be used to either fetch results from,
```suggestion
   A <classname>DocResult</classname> object that can be used to either fetch results from,
```
Maybe while at it? Although this might require the namespace prefix to be added too for the link generation to work.

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/fields.xml
> +      Can be either a single string or an array of strings identifying the
```suggestion
      Can either be a single string or an array of strings identifying the
```
"either be A or B" is the correct way to phrase this

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/groupby.xml
> +   It is often used with aggregate functions such as COUNT,MAX,MIN,SUM etc.
Maybe put the SQL functions in a ``literal`` or ``code`` tag?

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/groupby.xml
> +   A CollectionFind object that can be used for further processing.
Ditto classname tag remark for CollectionFind (but maybe it makes more sense to check all of these in a follow-up PR)

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/lockexclusive.xml
> +   modify() function. Essentially, this function uses row locks to serialise
```suggestion
   modify() function. Essentially, this function uses row locks to serialise
```
Is modify a method, a function, if so add a function/methodname tag to it is probably a good idea.

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/lockexclusive.xml
> +   ignore any locks set on the records that exist in the read view.
```suggestion
   Locks the document exclusively.
   As long as the document is locked,
   other transactions can't update the document,
   use <code>SELECT ... LOCK IN SHARE MODE</code>,
   or read the data in certain transaction isolation levels.
   Consistent reads ignore any locks set on the records that exist in the read view.
```
Possibly re-indent as such for nice breaks for translations?

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/lockshared.xml
> +   latest values.
```suggestion
   If any of these rows were changed by another transaction that hasn't been committed,
   the query will wait until that transaction has ended to be able to use the latest values.
```

Rewording and also remove personalization.

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/arrayinsert.xml
> +   appends the new element at the end of the array.
Ideally we would remove the usage of ``you`` here

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/arrayinsert.xml
> +      The INDEX field is zero based, so the first item of the array has an index of 0.
Maybe add some ``<replaceable>`` tags?

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
This sentence is confusing, does it mean that one should not call the constructor?

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionremove/construct.xml
> +   <methodname>mysql_xdevapi\Collection::remove</methodname> method.
Ditto confusing sentence

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/columnresult/construct.xml
> +   by the <methodname>mysql_xdevapi\RowResult::getColumns</methodname> method.
Ditto

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/columnresult/isnumbersigned.xml
> +   <methodname>mysql_xdevapi\RowResult::getColumns</methodname> method.
Ditto

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/construct.xml
> +   <title><function>mysql_xdevapi\Schema::__construct</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::__construct</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/createcollection.xml
> +   <title><function>mysql_xdevapi\Schema::createCollection</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::createCollection</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/createcollection.xml
> +    <title><function>mysql_xdevapi\Schema::createCollection</function> example</title>
```suggestion
    <title><methodname>mysql_xdevapi\Schema::createCollection</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/dropcollection.xml
> +   <title><function>mysql_xdevapi\Schema::dropCollection</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::dropCollection</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/existsindatabase.xml
> +   <title><function>mysql_xdevapi\Schema::existsInDatabase</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::existsInDatabase</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/getcollection.xml
> +   <title><function>mysql_xdevapi\Schema::getCollection</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::getCollection</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/getcollectionastable.xml
> +  <refpurpose>Get collection as Table object</refpurpose>
```suggestion
  <refpurpose>Get collection as a Table object</refpurpose>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/getcollectionastable.xml
> +   <title><function>mysql_xdevapi\Schema::getCollectionAsTable</function> example</title>
```suggestion
   <title><methodname>mysql_xdevapi\Schema::getCollectionAsTable</methodname> example</title>
```

2023-12-15 01:33 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/schema/getcollectionastable.xml
> +   A Table object for the collection.
Add a classname tag?

2023-12-15 16:52 UTC, msamesch commented on reference/mysql_xdevapi/mysql_xdevapi/schema/existsindatabase.xml
> +   <title><function>mysql_xdevapi\Schema::existsInDatabase</function> example</title>
That's what I had in mind when I reviewed it. At least it was consistently outdated in line with the rest in this chapter. ;)

2023-12-15 17:08 UTC, msamesch commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
Yes and I was unsure about this (and the likes).

2023-12-15 17:25 UTC, msamesch commented on reference/mysql_xdevapi/mysql_xdevapi/collectionfind/groupby.xml
> +   A CollectionFind object that can be used for further processing.
So I'll leave it.

2023-12-15 18:13 UTC, msamesch commented
Thank you for the review. I don't know how to change the rest.

2023-12-16 17:03 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
@rsomla1 or @FilipJaniszewski would you be able to explain?

2023-12-16 17:06 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
Looking at the source code, it seems the constructor is declared but does.... nothing?

2023-12-16 18:02 UTC, msamesch commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
OK, thank you for the clarification.

2023-12-16 21:49 UTC, merged

2023-12-18 15:51 UTC, rsomla1 commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
Sorry to be late for the party. Yes, the idea is that you should not construct `CollectionModify` objects directly but get instances from `Collection::modify()` method.

2023-12-20 14:18 UTC, Girgias commented on reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
> +   <methodname>mysql_xdevapi\Collection::modify</methodname> method.
> Sorry to be late for the party. Yes, the idea is that you should not construct `CollectionModify` objects directly but get instances from `Collection::modify()` method.

I would probably recomend making the constructor throw then, we do this with opaque objects that were introduced to replace resources, CurlHandle would be such an object within php-src that shows how it can be done