Update pattern.syntax.xml; meta-characters
php/doc-en pull request #3057
Opened 2024-01-02 00:41 UTC by mmalferov

I'm not sure what exactly question mark are "extends the meaning of" _what?_

2024-01-03 12:46 UTC, Girgias reviewed
The suggested wording is probably more what is intended, but not a regex expert maybe @TimWolla or @iluuu1994 know?

PS: please rebase your branch instead of merging master in, it makes for confusing commit lists.

2024-01-03 12:46 UTC, Girgias commented on reference/pcre/pattern.syntax.xml
> +        quantifiers lazy (see <link linkend="regexp.reference.repetition">repetition</link>))</entry>
```suggestion
       <entry>?</entry>
       <entry>
        Extends the meaning of the character <literal>(</literal>.
        If used as a quantifier it is the optional quantifier (equivalent to <literal>{0,1}</literal>.
        It also changes the behaviour of greedy quantifiers to be lazy quantifiers
        (see <link linkend="regexp.reference.repetition">repetition</link>).
       </entry>
```

2024-01-03 14:14 UTC, iluuu1994 commented on reference/pcre/pattern.syntax.xml
> +        quantifiers lazy (see <link linkend="regexp.reference.repetition">repetition</link>))</entry>
I think @mmalferov assumed `(,`is a typo.

What the text is saying is that `?` is used in `(?:` for non-capturing groups, that it can be used to make greedy quantifiers lazy (e.g. the first capture group in `(a??)(a*)` will be empty for `aaa`), and that it is a "0 or 1" quantifier in other contexts.

Including these examples might make the text clearer.

2024-01-05 16:02 UTC, TimWolla commented on reference/pcre/pattern.syntax.xml
> +        quantifiers lazy (see <link linkend="regexp.reference.repetition">repetition</link>))</entry>
> What the text is saying is that `?` is used in `(?:` for non-capturing groups,

Not just that, but also naming a sub-pattern (`(?P<name>…)`) and setting specific options for a single sub-pattern, e.g. `(?:(?i)saturday|sunday)` (taken from https://www.php.net/manual/en/regexp.reference.subpatterns.php).

So perhaps the correct wording is:

> Allows configuring a sub-pattern's option if used as the first character in a sub-pattern started by `(`. If used as a quantifier [the rest of Girgias' suggestion]

2024-04-12 15:06 UTC, Girgias requested changes

2024-04-12 15:06 UTC, Girgias commented on reference/pcre/pattern.syntax.xml
> +        Extends the meaning of the character <literal>(</literal>.
```suggestion
        Extends the meaning of the <literal>(</literal> character.
```

2024-04-12 15:06 UTC, Girgias commented on reference/pcre/pattern.syntax.xml
> +        If used as a quantifier it is the optional quantifier (equivalent to <literal>{0,1}</literal>.
```suggestion
        If used as a quantifier it is the optional quantifier (equivalent to <literal>{0,1}</literal>).
```

2024-04-12 15:06 UTC, Girgias commented on reference/pcre/pattern.syntax.xml
> +        It also changes the behaviour of greedy quantifiers to be lazy quantifiers
Possibly better wording
```suggestion
        It also transforms greedy quantifiers into lazy quantifiers
```

2024-04-12 17:15 UTC, mmalferov commented on reference/pcre/pattern.syntax.xml
> +        Extends the meaning of the character <literal>(</literal>.
I moved the word `character` after the literal tag

2024-04-16 09:56 UTC, Girgias commented on reference/pcre/pattern.syntax.xml
> +        If used as a quantifier extends the meaning of the <literal>(</literal> character.
This sentence is now confusing to me.

2026-09-07 19:08 UTC, merged