Improve example code to read ini shorthand
php/doc-en pull request #3084
Opened 2024-01-08 23:05 UTC by PPazderski

The existing example code cannot handle any later added shorthand formats and is simply outdated when a dedicated standard function exists.

2024-01-10 21:03 UTC, Girgias requested changes

2024-01-10 21:03 UTC, Girgias commented on reference/info/functions/ini-get.xml
> +echo 'post_max_size in bytes = ' . ini_parse_quantity(ini_get('post_max_size'));
This function is only available as of PHP 8.2, and the documentations covers PHP as of PHP 7.0.0.

So just replacing this line is not generally what we do. It might be better to rewrite the example completely to not try to compute the number of bytes.

2024-01-10 21:35 UTC, PPazderski commented on reference/info/functions/ini-get.xml
> +echo 'post_max_size in bytes = ' . ini_parse_quantity(ini_get('post_max_size'));
Ok I missed that. What brought me initial here was the kinda confusing code comment in the example which became this way from a change removing all references to PHP 5 and 7 (a0ae28d3bc85f927c22649ebd9a590b921534b7d).

Made me falsely believe PHP 7 isn't relevant here anymore. So it is to early for this change.

2024-01-10 21:46 UTC, Girgias commented on reference/info/functions/ini-get.xml
> +echo 'post_max_size in bytes = ' . ini_parse_quantity(ini_get('post_max_size'));
No worries :) That commit only removed references to PHP ***7.0.0*** as this is the new "baseline", There are still plenty of PHP 7.1.0 mentions :)

2025-03-04 21:51 UTC, philip commented on reference/info/functions/ini-get.xml
> +echo 'post_max_size in bytes = ' . ini_parse_quantity(ini_get('post_max_size'));
Update this PR to _add_ the new example with an "Available as of PHP 8.2.0" code comment?

2025-03-06 14:08 UTC, Girgias commented on reference/info/functions/ini-get.xml
> +echo 'post_max_size in bytes = ' . ini_parse_quantity(ini_get('post_max_size'));
> Update this PR to _add_ the new example with an "Available as of PHP 8.2.0" code comment?

This would work yes.

2026-09-04 06:38 UTC, lacatoire commented
Superseded by #4372, merged in January 2025, which made the same change: the `return_bytes()` helper is gone and the example now calls `ini_parse_quantity(ini_get('post_max_size'))`. Nothing left to rebase here.

Thanks for the work @PPazderski, and sorry this was not flagged when the other PR landed.

2026-09-04 06:38 UTC, closed without merging