IntlChar::istitle example correction
php/doc-en pull request #3099
Opened 2024-01-10 18:52 UTC by leonardolara

The current example is incorrect and is identical to the example of islower.xml.

The istitle() function determines wether the character is a titlecase code point ("Lt" general category of Unicode). Titlecase characters are digraphs (in one character) formed by a combination of two glyphs, one uppercase and the other lowercase.

The examples included in this commit were retrieved from the Unicode specification, also presented in https://www.compart.com/en/unicode/category/Lt

2024-01-10 21:24 UTC, Girgias requested changes
LGTM other than the nit

2024-01-10 21:24 UTC, Girgias commented on reference/intl/intlchar/istitle.xml
> +var_dump(IntlChar::istitle("Α"));
Please add a space between ``//`` and the comment.

2024-01-11 00:43 UTC, leonardolara commented on reference/intl/intlchar/istitle.xml
> +var_dump(IntlChar::istitle("Α"));
Spaces added.

2024-01-11 19:02 UTC, Girgias approved these changes

2024-01-11 19:04 UTC, merged