Document approach to set cookie params not known to setcookie()
php/doc-en pull request #3101
Opened 2024-01-10 23:27 UTC by morsssss

As per [discussion in the StackOverflow chat](https://chat.stackoverflow.com/transcript/message/56990396#56990396), I added a note to the `setcookie()` doc to say that one can use `header()` to create cookies with arbitrary params. I then added an example to the `header()` doc.

I also propose a minor language fix-up.

2024-01-11 18:38 UTC, Girgias requested changes
Overall looks good, just wording changes

2024-01-11 18:38 UTC, Girgias commented on reference/network/functions/header.xml
> +      <function>setcookie</function> provides a convenient way to set cookies. However, <function>header</function> lets you include parameters that <function>setcookie</function> may not support.
Please do not use personalization (i.e. ``you``) in the documentation.

Also please split lines at sensible break points to, ideally, be less than 80 chars.

2024-01-11 18:38 UTC, Girgias commented on reference/network/functions/setcookie.xml
> +         To set a cookie that includes parameters that aren't among the keys listed, you can use <function>header</function>.
ditto

2024-01-11 22:28 UTC, morsssss commented on reference/network/functions/header.xml
> +      <function>setcookie</function> provides a convenient way to set cookies. However, <function>header</function> lets you include parameters that <function>setcookie</function> may not support.
Sorry about the breakpoints! Fixing that now.

As far as "you" goes - the existing two examples use "you" consistently. I thought I'd try to be consistent with them, and I don't like using passive voice.

But if you're saying that none of these should be using "you", I will try to set a better example with my own example!

2024-01-11 22:35 UTC, morsssss commented on reference/network/functions/setcookie.xml
> +         To set a cookie that includes parameters that aren't among the keys listed, you can use <function>header</function>.
Ok! Here, removing the word "you" was trivial.

2024-01-12 00:57 UTC, Girgias commented on reference/network/functions/header.xml
> +      <function>setcookie</function> provides a convenient way to set cookies. However, <function>header</function> lets you include parameters that <function>setcookie</function> may not support.
I know there are already some places that use "you" which shouldn't (most of the docs except the tutorial and FAQ sections) but let's not introduce more of them.

2024-01-12 00:59 UTC, Girgias commented on reference/network/functions/header.xml
> +      <function>setcookie</function> may not support.
One possible amendment
```suggestion
      However, to include parameters that are not supported by
      <function>setcookie</function> the <function>header</function>
      can be used to include them.
```

2024-01-12 18:47 UTC, morsssss commented on reference/network/functions/header.xml
> +      <function>setcookie</function> provides a convenient way to set cookies. However, <function>header</function> lets you include parameters that <function>setcookie</function> may not support.
Ok! "You" removed.

2024-01-12 18:48 UTC, morsssss commented on reference/network/functions/header.xml
> +      <function>setcookie</function> may not support.
I tried this, took a look, and was inspired to create a variant that looked good to me... wdyt?

2024-01-14 13:15 UTC, Girgias commented on reference/network/functions/header.xml
> +      But <function>header</function> can be used to include attributes that
This "but" is just confusing
```suggestion
      <function>header</function> can be used to include attributes that 
```

2024-01-14 13:16 UTC, Girgias commented on reference/network/functions/setcookie.xml
> +         To set a cookie that includes parameters that aren't among the keys listed,
Use attribute here too? Or keep parameters

2024-01-16 23:38 UTC, morsssss commented on reference/network/functions/setcookie.xml
> +         To set a cookie that includes parameters that aren't among the keys listed,
Good catch. Making this change.

2024-01-17 00:12 UTC, morsssss commented on reference/network/functions/header.xml
> +      But <function>header</function> can be used to include attributes that
I don't love it either. It's hard for me to do this without using a subject... but I think this may be more what you're looking for.

2024-01-18 12:13 UTC, Girgias approved these changes
LGTM Thank you!

2024-01-18 12:13 UTC, Girgias commented on reference/network/functions/header.xml
> +    </para>
```suggestion
    <para>
     <function>setcookie</function> provides a convenient way to set cookies. 
     To set a cookie that includes attributes which <function>setcookie</function>
     doesn't support, <function>header</function> can be used.
    </para>
```

2024-01-18 12:14 UTC, merged

2024-01-18 16:03 UTC, morsssss commented
Thanks for all your help @Girgias !