Remove description of old version
php/doc-en pull request #3139
Opened 2024-01-24 16:02 UTC by mowangjuanzi

2024-01-24 23:23 UTC, sy-records requested changes

2024-01-24 23:23 UTC, sy-records commented on reference/mail/functions/mail.xml
> +      </para>å
```suggestion
      </para>
```

2024-01-24 23:28 UTC, sy-records approved these changes

2024-01-25 13:34 UTC, Girgias approved these changes

2024-01-25 13:35 UTC, merged