Remove references to `mysql` extension and to versions below 7.0
php/doc-en pull request #315
Opened 2021-01-09 00:56 UTC by afilina

- Remove references to `mysql` extension and related examples.
- Unify and cleanup preserved examples.
- Add missing `mysqli` charset example.
- Remove link to `reference.mysql.book` so that we could eventually retire it.
- Remove references to old PHP versions, except where it made sense to keep it (I think it makes sense to keep "PHP version introduced" in case we add new extensions in the future).

Note: this PR only focuses on mysqlinfo pages in order to make this bug obsolete: https://bugs.php.net/bug.php?id=72158

2021-01-10 12:58 UTC, kamil-tekiela requested changes

2021-01-10 12:58 UTC, kamil-tekiela commented on reference/mysqlinfo/concepts.xml
> +$mysqli  = new mysqli("localhost", "my_user", "my_pass", "world");
The parameter name is `$password` and we use `my_password` throughout the manual, can we keep it as it was?

2021-01-10 12:58 UTC, kamil-tekiela commented on reference/mysqlinfo/concepts.xml
> +   <title>Setting the character set example: mysqli</title>
I think that there already is mysqli charset example few lines above. This one should probably be removed.

2021-01-10 12:58 UTC, kamil-tekiela commented on reference/mysqlinfo/concepts.xml
>  print_r( $mysqli->get_charset() );
Can this be changed to `character_set_name()`?

2021-01-10 12:58 UTC, kamil-tekiela commented on reference/mysqlinfo/set.xml
> +     There are several PHP APIs
There are 2 in the standard. Can we change the sentence to avoid the word several?

2021-01-10 13:09 UTC, cmb69 commented on reference/mysqlinfo/concepts.xml
> +   <title>Setting the character set example: mysqli</title>
This appears to duplicate the [mysqli example above](https://www.php.net/manual/en/mysqlinfo.concepts.charset.php#example-1631).

2021-01-11 15:02 UTC, afilina commented on reference/mysqlinfo/set.xml
> +     There are several PHP APIs
I changed to "several" to avoid chasing down occurrences of this whenever new APIs are added or removed in the future. I have seen this become a big maintenance burden over time in documentation in other projects.

2021-01-11 15:05 UTC, afilina commented on reference/mysqlinfo/concepts.xml
> +$mysqli  = new mysqli("localhost", "my_user", "my_pass", "world");
In the same file, I have seen my_pass on many occasions. In any case, this was not the original intent of this PR, so I'll just undo this change to keep this PR more focused.

2021-01-11 15:42 UTC, kamil-tekiela commented
LGTM

2021-01-11 17:03 UTC, cmb69 commented on reference/mysqlinfo/concepts.xml
> -?>
Well, PEAR CS mandates these, and the examples are still supposed to [adhere to that CS](http://doc.php.net/tutorial/style.php). IMO we should change that, but that would likely require discussion on the docs mailing list.

2021-01-11 19:14 UTC, afilina commented on reference/mysqlinfo/concepts.xml
> -?>
Alright, I changed all examples back to use closing tag. First I address the remaining 513 documentation bugs, then I fight for a different CS. Priorities :)

2021-01-11 19:28 UTC, kamil-tekiela commented on reference/mysqlinfo/concepts.xml
> -?>
I am not sure that the PEAR CS demands an empty statement or a closing PHP tag at the end of every PHP code block. I think it is a convention or tradition rather than a rule in CS. It certainly is not the best practice. It doesn't make much difference in PHP manual, but I don't think it is something we should enforce. 

IMHO this should be a topic of yet another discussion. If it is something that should be changed then we should do it rather than talk about it. Arguing about such small details leads to bikeshedding and in the meantime nothing gets done. 

However, it makes absolute no sense to remove `?>` and leave `$uresult->close();` there. Either remove both or leave both. Personal recommendation of mine would be to avoid using `mysqli_result::close()` at all times, but as we know the manual recommends using it many places for reasons unknown.

2021-01-11 19:35 UTC, afilina commented on reference/mysqlinfo/concepts.xml
> -?>
Closing connections can be critical in long-running processes. I just had a client last week with such a problem. Since it seems that more debate would be required and this change is not explicitly part of the PR, I'd shelf it for the time being.

2021-01-11 20:03 UTC, kamil-tekiela commented on reference/mysqlinfo/concepts.xml
> -?>
No, not closing the connection (although I do believe that should also be avoided but it's an entirely different topic). I meant closing `mysqli_result` which IMHO is absolutely useless. 

But, as much as I would like to complain, this is probably the only place in the whole manual where `mysqli_result::close()` is used correctly. Almost... That function is used on unbuffered results to consume internally all remaining records waiting on the wire. The problem in this example is that all rows have been read already, there is nothing else to consume.

2021-01-11 20:43 UTC, afilina commented on reference/mysqlinfo/concepts.xml
> -?>
I actually have a better reason to remove it: that's not the point of the example and the other example doesn't close results. Sent a commit.

2021-01-12 13:10 UTC, cmb69 commented
Thank you!

2021-01-12 13:10 UTC, closed without merging