[PHP 8.3] Update `get_class` and `get_parent_class`
php/doc-en pull request #3186
Opened 2024-02-17 08:17 UTC by saundefined

2024-02-18 15:55 UTC, Girgias requested changes

2024-02-18 15:55 UTC, Girgias commented on reference/classobj/functions/get-class.xml
> +        previously, calling this function inside a class returned the name of that class.
```suggestion
        Calling <function>get_class</function> without an argument now emits an
        <constant>E_DEPRECATED</constant> warning;
        previously, calling this function inside a class returned the name of that class.
```

2024-02-18 15:55 UTC, Girgias commented on reference/classobj/functions/get-parent-class.xml
> +       previously, calling this function inside a class returned the parent class name of that class.
Ditto

2024-02-19 00:11 UTC, Girgias approved these changes

2024-02-19 00:11 UTC, merged

2024-02-19 11:24 UTC, leonardolara commented on reference/classobj/functions/get-parent-class.xml
> +       Calling <function>get_class</function> without an argument now emits an
Shouldn't it be "get-parent-class" ?