Sync some methodsynopses with stubs
php/doc-en pull request #3199
Opened 2024-02-21 13:39 UTC by kocsismate

I intended to fix some of the methodsynopses which didn't need a changelog.

2024-02-21 16:41 UTC, nielsdos requested changes
Looks mostly right, thx

2024-02-21 16:41 UTC, nielsdos commented on reference/intl/intlgregoriancalendar/createfromdate.xml
> +   <modifier>public</modifier> <modifier>static</modifier> <type>static</type><methodname>IntlGregorianCalendar::createFromDate</methodname>
```suggestion
   <modifier>public</modifier> <modifier>static</modifier> <methodname>IntlGregorianCalendar::createFromDate</methodname>
```

2024-02-22 22:10 UTC, kocsismate commented on reference/intl/intlgregoriancalendar/createfromdate.xml
> +   <modifier>public</modifier> <modifier>static</modifier> <type>static</type><methodname>IntlGregorianCalendar::createFromDate</methodname>
Hm, It's a static method with a static return type ^^

2024-02-22 22:17 UTC, nielsdos commented on reference/intl/intlgregoriancalendar/createfromdate.xml
> +   <modifier>public</modifier> <modifier>static</modifier> <type>static</type><methodname>IntlGregorianCalendar::createFromDate</methodname>
Ah wow indeed. Sorry, then this is right.

2024-02-22 22:17 UTC, nielsdos approved these changes
My mistake, LGTM. Thanks.

2024-02-23 18:11 UTC, Girgias commented on reference/errorfunc/functions/trigger-error.xml
> +   <type>true</type><methodname>trigger_error</methodname>
Only as of PHP 8.0, it used to return false for invalid error levels.

2024-02-23 18:11 UTC, Girgias commented on reference/network/functions/long2ip.xml
> +   <type>string</type><methodname>long2ip</methodname>
This is a change only on master.

2024-02-23 18:11 UTC, Girgias commented on reference/stream/functions/stream-context-set-options.xml
> +   <type>true</type><methodname>stream_context_set_options</methodname>
This looks wrong, also doesn't seem to have a stub?

2024-02-23 18:11 UTC, Girgias commented on reference/stream/functions/stream-context-set-params.xml
> +   <type>true</type><methodname>stream_context_set_params</methodname>
This also seems wrong?

2024-02-23 18:11 UTC, Girgias commented on reference/outcontrol/functions/ob-start.xml
> +   <methodparam choice="opt"><type class="union"><type>callable</type><type>null</type></type><parameter>callback</parameter><initializer>&null;</initializer></methodparam>
Welp... time to add to my list to refactor this function to use the ZPP callable check...

2024-02-25 06:45 UTC, kocsismate commented on reference/stream/functions/stream-context-set-options.xml
> +   <type>true</type><methodname>stream_context_set_options</methodname>
there is a stub for it: https://github.com/php/php-src/blob/e630aacf795dfbfd875a624856674e29de32c42a/ext/standard/basic_functions.stub.php#L3398

2024-02-25 06:49 UTC, kocsismate commented on reference/stream/functions/stream-context-set-params.xml
> +   <type>true</type><methodname>stream_context_set_params</methodname>
They have always (?) returned true. The return type is actually true since my refactoring: https://github.com/php/php-src/pull/12720

2024-03-20 22:16 UTC, kocsismate commented on reference/network/functions/long2ip.xml
> +   <type>string</type><methodname>long2ip</methodname>
Yes, but it couldn't return false before as well according to https://github.com/php/php-src/pull/13395
So we can then document it, right?

2024-03-20 22:18 UTC, kocsismate commented on reference/outcontrol/functions/ob-start.xml
> +   <methodparam choice="opt"><type class="union"><type>callable</type><type>null</type></type><parameter>callback</parameter><initializer>&null;</initializer></methodparam>
Would be nice :)

2024-03-20 22:20 UTC, kocsismate commented on reference/errorfunc/functions/trigger-error.xml
> +   <type>true</type><methodname>trigger_error</methodname>
Your are right, I've just added an errors and a changelog section!

2024-04-16 10:03 UTC, Girgias commented on reference/stream/functions/stream-context-set-params.xml
> +   <type>true</type><methodname>stream_context_set_params</methodname>
Right, it used to return false on invalid stream context, which is a ZPP failure effectively

2024-04-16 10:04 UTC, Girgias commented on reference/network/functions/long2ip.xml
> +   <type>string</type><methodname>long2ip</methodname>
Ah yeah that's fine

2024-04-16 10:06 UTC, Girgias approved these changes
One nit, LGTM otherwise

2024-04-16 10:06 UTC, Girgias commented on reference/errorfunc/functions/trigger-error.xml
> +       <parameter>error_level</parameter> is specified. Previously, it returned &false;.
```suggestion
       The function now throws a <classname>ValueError</classname> if an invalid
       <parameter>error_level</parameter> is specified. Previously, it returned &false;.
```

2024-04-16 11:02 UTC, merged