Remove unnecessary try-catch statements from PDO manual
php/doc-en pull request #323
Opened 2021-01-10 18:15 UTC by kamil-tekiela

Since now PHP has exception mode set to default, the try-catch on the constructor page is useless. Previously, people have been catching these exceptions to silence them just like the rest of PDO functions. Now, there is no observable difference between the constructor or any other PDO function with default settings in terms of exception throwing. 

The idea is to make the examples simple and to the point without any unnecessary noise. The try-catch statements serve no visible purpose and without proper explanation they are just confusing to new developers. 

The information is not lost, as we have 2 dedicated pages in the manual for [connections](https://www.php.net/manual/en/pdo.connections.php) and [error handling](https://www.php.net/manual/en/pdo.error-handling.php). 

There were 3 other examples where the try-catch was unnecessarily used. These were even worse because there was no code to recover from the exceptional situation, there was only a print statement, and they were encompassing arbitrary code within a function. If code fails then it should be handled by the error handler if the code can't recover from it. A try-catch with no means to recover is just dirty code. 
The examples used 2 spaces for indentation, I changed it to 4. 
Now, the examples are clean and short, and they continue to demonstrate the idea behind them.

2021-01-11 16:16 UTC, afilina requested changes
Agreed. I see way too much nonsensical error handling in legacy code, possibly inspired by such examples.

I just have a tiny correction and a couple of questions.

2021-01-11 16:16 UTC, afilina commented on reference/pdo/pdo/construct.xml
> +   to connect to the requested database fails regardless of which <constant>PDO::ATTR_ERRMODE</constant> is currently set.
```suggestion
   to connect to the requested database fails, regardless of which <constant>PDO::ATTR_ERRMODE</constant> is currently set.
```

2021-01-11 16:16 UTC, afilina commented on reference/pdo/pdostatement/fetch.xml
> -    $stmt = null;
Good catch! There's no point in setting a local var to null right before the end of a method.

2021-01-11 16:16 UTC, afilina commented on reference/pdo/pdostatement/setfetchmode.xml
> +foreach ($stmt as $row) {
Although I prefer teaching `foreach` as well, didn't `$stmt->fetch()` make it a bit easier for people to wrap their head around the concept of "fetch" mode?

2021-03-06 14:42 UTC, kamil-tekiela commented on reference/pdo/pdostatement/setfetchmode.xml
> +foreach ($stmt as $row) {
Hi Anna, Thanks for pointing it out and sorry for the delayed reply. This was changed on purpose. `fetch()` method already accepts fetch style as the first argument. The idea here was to show how `setFetchMode()` can be used when iterating over the statement with `foreach`. This is something that is not obvious, especially for someone migrating from mysqli. I would like to keep my change if that is ok.

2021-03-08 15:40 UTC, afilina commented on reference/pdo/pdostatement/setfetchmode.xml
> +foreach ($stmt as $row) {
Yeah, that's fine then.

2021-03-08 15:42 UTC, afilina approved these changes

2021-03-08 16:05 UTC, cmb69 commented
Thank you!

2021-03-08 16:05 UTC, closed without merging