Refactor OO section part 2
php/doc-en pull request #329
Opened 2021-01-13 07:22 UTC by Girgias

Some misses from the first time and doing some drive by fixes.

2021-01-13 19:50 UTC, afilina requested changes
Partial review. Will check the rest later today.

2021-01-13 19:50 UTC, afilina commented on language/oop5/autoload.xml
>      it can contain some dangerous characters such as <literal>../</literal>.
I don't see how one can supply `../` as the class name here. I don't see a test for it and I can't reproduce the behavior. Perhaps this refers to some very old bug. Without a code snipper demonstrating it, that warning doesn't really make any sense to me.

2021-01-13 19:50 UTC, afilina commented on language/oop5/magic.xml
> +    is emitted. Prior to PHP 8.0.0, no diagnostic was emitted.
This doesn't seem to be the case even in 8.0.0: https://3v4l.org/hW7eN

2021-01-13 21:51 UTC, Girgias commented on language/oop5/magic.xml
> +    is emitted. Prior to PHP 8.0.0, no diagnostic was emitted.
No visibility === public visibility, however it seems a diagnostic depends on the magic methods, amazing... (see https://3v4l.org/PS0lf and https://3v4l.org/q5N43)

2021-01-13 21:59 UTC, afilina requested changes

2021-01-13 21:59 UTC, afilina commented on language/oop5/static.xml
> +   These can also be accessed within an instantiated class object.
```suggestion
   These can also be accessed statically within an instantiated class object.
```

Not sure whether the distinction is needed here.

2021-01-13 22:53 UTC, salathe commented on language/oop5/autoload.xml
>      it can contain some dangerous characters such as <literal>../</literal>.
The note was added in 2007 in response to https://bugs.php.net/42744.  PHP added validation to the class name in 2014 (php/php-src@2d31eadbbf147a157cb4a0c89adaf30fee7371f0, PHP 5.4.24 and PHP 5.5.8), which rendered the note obsolete for folks using those or newer versions of PHP.

2021-01-13 23:04 UTC, afilina commented on language/oop5/autoload.xml
>      it can contain some dangerous characters such as <literal>../</literal>.
Thanks for finding this out, @salathe. I was looking for the error in phpt files starting with `call_user_func*`, heh.

2021-01-15 05:45 UTC, Girgias commented on language/oop5/magic.xml
> +    Otherwise a fatal error is emitted.
There isn't a rule, and I probably just copy pasted it from code output. But yeah not great to be inconsistent.

2021-03-04 22:52 UTC, Crell commented on language/oop5/static.xml
> +     generated an <constant>E_DEPRECATED</constant> warning.
The verb tenses here are hurting my brain.  It really feels like "prior to 8.. were deprecated..." is more correct.  I can see the reason for using "is", but I really think "were" is more correct.

```suggestion
     Prior to PHP 8.0.0, calling non-static methods statically were deprecated, and
     generated an <constant>E_DEPRECATED</constant> warning.
```

2021-03-04 23:00 UTC, Girgias commented on language/oop5/static.xml
> +     generated an <constant>E_DEPRECATED</constant> warning.
Fixed and I think it makes more sense indeed.

2021-03-04 23:05 UTC, cmb69 commented on language/oop5/static.xml
> +     generated an <constant>E_DEPRECATED</constant> warning.
Not a native speaker, but the plural looks wrong to me (the past tense looks right, though present perfect may be even more appropriate).

2021-03-04 23:07 UTC, closed without merging