Rewrite MySQLnd statistic page
php/doc-en pull request #3357
Opened 2024-04-28 02:09 UTC by Girgias

- Remove personalization
- Improve document structure
- DocBook 5.2 conformance

This is probably easier by comparing to the actual live page: https://www.php.net/manual/en/mysqlnd.stats.php

The only things that really ought to be looked at, are my `TODO` comments.

2024-04-30 00:24 UTC, kamil-tekiela commented
Thanks, I am in the process of reviewing this but there are a lot of changes here and it has raised many questions for me. I hope to get back to you with something tomorrow or the day after tomorrow.

2024-04-30 17:27 UTC, Girgias commented
> Thanks, I am in the process of reviewing this but there are a lot of changes here and it has raised many questions for me. I hope to get back to you with something tomorrow or the day after tomorrow.

No worries, I also had many questions while rewriting this and expected this to take a while to review :)

2024-04-30 22:52 UTC, kamil-tekiela requested changes
Thank you for this PR. I appreciate how much work you have put into this. I like how the page looks now and I am happy with most of your changes. I have highlighted some typos and answered your TODOs. I have also left some TODOs for myself as I investigate these statistics. I'll need some time to do this and in the meantime you can fix the issues I identified. 

I have a gripe with this whole feature. I would love it if we could deprecate the statistics and remove them soon. I think I lost some of my sanity while reading this page. But that is off-topic.

2024-04-30 22:52 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      <!-- TODO: Document -->
The total number of times a persistent connection has been reused.

2024-04-30 22:52 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      <!-- TODO: Does it really have the total size in bytes? -->
Bytes are reported in `bytes_received_rset_row_packet` and the number of packets is reported in `packets_received_rset_row`. There are 7 statistics like this that have corresponding bytes/package entries. The bit "and their total size in bytes" needs to be removed from here.

2024-04-30 22:52 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +   <!-- TODO: Should this be split in two? -->
I don't see any need to do that.

2024-04-30 22:52 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      <!-- TODO: Do not use First Class Callable syntax -->
Maybe use `new mysqli(/*...*/)`?

2024-04-30 22:52 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +     ini.mysqlnd.net-cmd-buffer-size with this statistic -->
Is the link not enough?

2024-05-01 15:25 UTC, Girgias commented on reference/mysqlnd/stats.xml
> +      but for prepared statements.
Actually I think the `<term>` tag should have been: `rows_buffered_from_server_ps`

2024-05-01 15:28 UTC, Girgias commented on reference/mysqlnd/stats.xml
> +      This statistic is only available with <literal>ext/mysqli</literal>.
Aren't some statistics available when using the PDO driver? As this was my impression? It also used to be able to get statistics from the old mysql extension sooo

2024-05-01 15:37 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      This statistic is only available with <literal>ext/mysqli</literal>.
It's actually more confusing than this. Statistics are part of the mysqlnd extension. They have nothing to do with PDO or mysqli. As long as mysqlnd was compiled with this feature, it will collect the statistics regardless of which extension is using it. But to view the statistics, you need to have mysqli extension enabled. It is possible that since PDO doesn't use all features of mysqlnd, some statistics will never be relevant when using only PDO, but I don't think this is what this meant.

2024-05-01 15:42 UTC, Girgias commented on reference/mysqlnd/stats.xml
> +     ini.mysqlnd.net-cmd-buffer-size with this statistic -->
So, when I had a link at the INI setting description it was just a copy paste from it, so the INI setting description might need a rewrite, which is why I put that TODO comment here

2024-05-01 15:45 UTC, Girgias commented
Thank you for the review!

I tried to address each review comment in a separate commit so it's easy to figure out what changed. Still missing a couple as it seemed you needed to think about them some more. :)

2024-05-01 15:52 UTC, Girgias commented on reference/mysqlnd/stats.xml
> +      Total number of active persistent and non-persistent connections.
It looks like yes, I was just mechanically updating stuff. But even just reading the description of it, I don't see how this can be a connection level statistic.

2024-05-01 15:53 UTC, Girgias commented on reference/mysqlnd/stats.xml
> +      This statistic is only available with <literal>ext/mysqli</literal>.
That is indeed confusing :|

I do think trying to remove this feature in the long run is a good idea.

2024-05-02 16:08 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      <code>mysqli_options(MYSQLI_INIT_COMMAND , ...);</code>.
I think we should remove that sentence. The "free" is implicit most of the time, so this note is kind of useless.

2024-05-02 16:33 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +      is established.
I have tested the examples provided and neither of them can result in `reconnect` being increased. I am pretty sure that it's impossible since if that would ever happen, it would mean that the extension calling mysqlnd has messed something up. But it might be possible that there is some exotic scenario in which this is a sensible outcome, but these examples are not it. Please remove the examples and the description.

2024-05-03 01:02 UTC, Girgias commented
Made the suggested changes

2024-05-08 20:24 UTC, Girgias commented
@kamil-tekiela do you have any more comments? I would like to merge this sooner than later.

2024-05-08 21:19 UTC, kamil-tekiela approved these changes
Please address these last remarks of mine and then you can merge, I will look at the rest of it sometime in the future once I have a moment.

2024-05-08 21:19 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +     </simpara>
Let's remove this. I can't find any reason for this.

2024-05-08 21:19 UTC, kamil-tekiela commented on reference/mysqlnd/stats.xml
> +   <function>phpinfo</function> function.
What I meant here is that on top of mentioning how to get client and connection statistics, this page should also mention that both are present in phpinfo too. However, I then checked it and it turns out we already removed the output from phpinfo. https://github.com/php/php-src/commit/6ab04a6eef0750ea2d4365be7f9bcfd9caa33449

Could you please revert the commit 366506864f76c28ff1606f223851e2a80ab1b682 You were right, sorry.

2024-05-09 00:46 UTC, merged