Add example on updating values with array_walk_recursive.
php/doc-en pull request #3365
Opened 2024-05-03 15:34 UTC by gitomato

2026-01-29 21:17 UTC, lacatoire commented on reference/array/functions/array-walk-recursive.xml
> +function test_update(&$item)
```suggestion
function test_update(&$item, $key)
```

2026-01-29 21:17 UTC, lacatoire commented on reference/array/functions/array-walk-recursive.xml
> +function test_update(&$item)
The callback signature includes $key for consistency with the documented callable contract of `array_walk_recursive`().

See implementation: https://github.com/php/php-src/blob/master/ext/standard/array.c

2026-03-06 07:41 UTC, cweiske requested changes

2026-03-06 07:41 UTC, cweiske commented on reference/array/functions/array-walk-recursive.xml
> +    <title><function>array_walk_recursive</function> update example</title>
Please add a short explanatory text that awr can be used to update values. The title does not need to contain a_w_r as well, as we are on the awr page already.

2026-08-27 08:41 UTC, merged