Added version 'PHP 8' to array functions' pages
php/doc-en pull request #337
Opened 2021-01-16 17:40 UTC by Tpojka

Also fixed and improved some of examples on pages:

https://www.php.net/manual/en/function.array-walk.php
  - removed <br> tag from print function

https://www.php.net/manual/en/function.key.php
  - removed '<br>' tag and add "\n" in echo

https://www.php.net/manual/en/function.range.php
  - improved examples' readability

What is left there that I can see:

https://www.php.net/manual/en/function.array-fill.php
  - different behavior in PHP 8

https://www.php.net/manual/en/function.array-udiff-assoc.php
  - different behavior for PHP 5, PHP 7, PHP 8

https://www.php.net/manual/en/function.array-udiff-uassoc.php
  - different behavior for PHP 7, PHP 8

https://www.php.net/manual/en/function.count.php
  - different behavior for PHP 7, PHP 8

Changelog section would be appropriate similarly to 
https://www.php.net/manual/en/function.array-unique.php

2021-01-16 18:31 UTC, Girgias commented on reference/array/versions.xml
>   <function name='each' from='PHP 4, PHP 5, PHP 7' deprecated='PHP 7.2.0'/>
There should be a removed tag for PHP 8.0.0 for each()

2021-01-16 18:33 UTC, Girgias commented on reference/array/functions/range.xml
> +    }
I don't understand the point of these changes, they just clutter the function.
What you want to do seems to be just solvable by doing ``echo $number, "\n"``

2021-01-16 18:34 UTC, Girgias requested changes
The foreach changes are completely unnecessary and just clutter the example

2021-01-16 19:15 UTC, Tpojka commented on reference/array/functions/range.xml
> +    }
Result is fairly unreadable if there is no new line. 
How it is for now:
https://3v4l.org/B78cK

2021-01-16 19:21 UTC, Tpojka commented on reference/array/versions.xml
>   <function name='each' from='PHP 4, PHP 5, PHP 7' deprecated='PHP 7.2.0'/>
Didn't know such an exists. 
Like

    <function name='each' from='PHP 4, PHP 5, PHP 7' deprecated='PHP 7.2.0' removed='PHP 8'/>

?

2021-01-16 21:59 UTC, cmb69 commented on reference/array/versions.xml
>   <function name='each' from='PHP 4, PHP 5, PHP 7' deprecated='PHP 7.2.0'/>
I don't think that we use removed attributes; instead we don't update the from attribute, and explicitly add a warning to the page that the function has been removed.

2021-01-16 22:01 UTC, cmb69 commented on reference/array/functions/range.xml
> +    }
Maybe just output a space unconditionally, and a new line after each loop?

2021-01-17 01:36 UTC, Tpojka commented on reference/array/versions.xml
>   <function name='each' from='PHP 4, PHP 5, PHP 7' deprecated='PHP 7.2.0'/>
Added with `fff33ce` following similar code in docs.

2021-01-17 01:38 UTC, Tpojka commented on reference/array/functions/range.xml
> +    }
Changed in `0353cf2`.

2021-01-17 11:02 UTC, cmb69 commented
Thank you!

2021-01-17 11:02 UTC, closed without merging