Updating mysqli: prepared statements
php/doc-en pull request #338
Opened 2021-01-16 17:59 UTC by kamil-tekiela

Another PR aiming to improve mysqli docs by removing lies and deception. In this episode:
- `mysqli_stmt_bind_result()` cannot be used to bind variables to placeholders
- There is no such thing as *"null-terminated string query"*.
- A prepared statement doesn't have to have any parameter markers. The parameter binding can be skipped. This means that the SQL can contain zero or more markers.
- The trailing semicolon is ignored. The Go command (i.e. `\g`) is not allowed in any application layer client API. No idea why that note was there, but it has been throwing a lot of people off.
- The note which was copied from MySQL docs has been altered. Not only the English language was broken, but incorrect information was added. I am not aware of any limitations in regards to `? IS NULL`. The two pages in the manual had a slightly different version of the note. If it was copied from MySQL then let's bring it up to date. 
- `mysqli_stmt::prepare` can return only a boolean as far as I know
- `mysqli_stmt::execute` contained some strange notes, which I removed. Parameter markers are never replaced into the SQL by neither client nor server. They are sent separately and are used in the execution. `mysqli_stmt_fetch` doesn't have to be used. It might be used in situations where a result set is bound to variables and needs to be fetched, but it is in no way a requirement. That sentence made no sense, but I assume it was meant to inform users that `execute` doesn't return the result set. If that was the intention then there are better ways to communicate it. 
- A copy-paste of a snippet made for some strange information in `mysqli_stmt::__construct`. The first parameter is mandatory and there is no procedural version. The object needs to be a valid mysqli connection to MySQL. 
- Improved code examples and some wording.

2021-01-16 18:41 UTC, Girgias requested changes
Minor nits, as I can't comment on the content of the updates as I don't know the mysqli API

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli/prepare.xml
> +   The statement template can contain zero or more question mark (?) parameter markers⁠—also called
```suggestion
   The statement template can contain zero or more question mark (<literal>?</literal>) parameter markers⁠—also called 
```

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli_stmt/construct.xml
> -    &mysqli.link.description;
Is this just a misuse of the entity or should the entity be adjusted?

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli_stmt/execute.xml
> +   function, or by passing the second argument to <methodname>mysqli_stmt::__construct</methodname>.
Could you split this into more lines to make them less than 80 characters/line (helps with reading diffs in a CLI)

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <para>&style.procedural;</para>
Shouldn't this mimic the change made above?
```suggestion
   <title><methodname>mysqli_stmt::execute</methodname> example</title>
   <para>&style.procedural;</para>
```

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli_stmt/prepare.xml
> +   The statement template can contain zero or more question mark (?) parameter markers⁠—also called
```suggestion
   The statement template can contain zero or more question mark (<literal>?</literal>) parameter markers⁠—also called 
```
Also potentially split into more lines

2021-01-16 18:41 UTC, Girgias commented on reference/mysqli/mysqli_stmt/prepare.xml
> +   <para>&style.procedural;</para>
```suggestion
   <title><methodname>mysqli_stmt::prepare</methodname> example</title>
   <para>&style.procedural;</para>
```
As above

2021-01-16 21:39 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/construct.xml
> -    &mysqli.link.description;
The entity is ok, but it should not be used on this page. It just doesn't apply here.

2021-01-16 21:49 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <para>&style.procedural;</para>
No. The text should only be `&style.procedural;` and it should not be emphasised like the example title. I can't accept that suggestion as it was done this way on purpose. Sorry. If I were to use a title here then the layout would look worse.

2021-03-08 16:08 UTC, afilina commented
Looks like all the comments were addressed here. @Girgias?

2021-03-08 17:58 UTC, cmb69 commented
Thank you!

Generally, please consider to provide more fine grained PRs. The review process for coarse grained PRs doesn't really work well (well, maybe it doesn't work well for fine grained PRs either :)).

2021-03-08 17:58 UTC, closed without merging