Adding #[\SensitiveParameter] attribute
php/doc-en pull request #3385
Opened 2024-05-15 07:53 UTC by colshrapnel

It seems that #[\SensitiveParameter] is already used for $password parameter so it should be reflected on the man page. Though I  was unable to find how to add attributes properly and also not sure it I added correct link. So this PR has to be supervised.

2024-05-15 10:45 UTC, Girgias requested changes

2024-05-15 10:45 UTC, Girgias commented on reference/mysqli/mysqli/construct.xml
>     <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>password</parameter><initializer>&null;</initializer></methodparam>
SensitiveParameter is *not* a parameter of the function/method, it is an attribute *modifying* the behaviour of a parameter.

Using the `<modifier>` tag here is more appropriate, but this will need rendering support in PhD too.

One possible markup idea might be:
```suggestion
   <methodparam choice="opt"><modifier role="attribute">#[\SensitiveParameter]</modifier><type class="union"><type>string</type><type>null</type></type><parameter>password</parameter><initializer>&null;</initializer></methodparam>
```

Ideally it would also link to the relevant attribute automatically.

2024-05-19 09:12 UTC, closed without merging

2024-05-19 10:17 UTC, kamil-tekiela commented
Why was this PR closed?

2024-05-19 12:46 UTC, TimexPeachtree reviewed
Great