WeakMap::offsetGet() does not return null
php/doc-en pull request #3463
Opened 2024-06-20 10:00 UTC by staabm

see https://3v4l.org/QjCMI

refs https://github.com/phpstan/phpstan/issues/10655

2024-06-21 01:33 UTC, Girgias requested changes

2024-06-21 01:33 UTC, Girgias commented on language/predefined/weakmap/offsetget.xml
> +   Returns the value associated to the object passed as argument, throws a <type>Error</type> otherwise.
Errors should be in a new and dedicated Error/Exception section.

2024-06-22 07:05 UTC, staabm commented on language/predefined/weakmap/offsetget.xml
> +   Returns the value associated to the object passed as argument, throws a <type>Error</type> otherwise.
committed a fix. hopefully thats what you had in mind

2024-07-07 13:35 UTC, Girgias commented on language/predefined/weakmap/offsetget.xml
> +   Returns the value associated to the object passed as argument, throws a <type>Error</type> otherwise.
Yes that's what I had in mind, but now the mention of the Error should be removed from the return value.

And sorry for the delay.

2024-07-07 14:47 UTC, staabm commented on language/predefined/weakmap/offsetget.xml
> +   Returns the value associated to the object passed as argument, throws a <type>Error</type> otherwise.
Fixed

2024-07-07 14:49 UTC, Girgias approved these changes
Thank you

2024-07-07 14:49 UTC, merged