Add documentation for `array_find` RFC
php/doc-en pull request #3465
Opened 2024-06-20 20:08 UTC by joshuaruesweg

This pull request adds the documentation for the [array_find RFC](https://wiki.php.net/rfc/array_find) which introduced the methods `array_find`, `array_find_key`, `array_all` and `array_any`.

2024-08-26 11:58 UTC, Girgias requested changes
I only suggested some markup changes on the first function, but these should be mimicked on the other ones.

2024-08-26 11:58 UTC, Girgias commented on reference/array/functions/array-all.xml
> +   <function>array_all</function> returns &true;, if the given $callback returns
```suggestion
   <function>array_all</function> returns &true;, if the given <parameter>callback</parameter> returns
```

2024-08-26 11:58 UTC, Girgias commented on reference/array/functions/array-all.xml
> +       further elements.
Still need some improvement but it's better to mark out a signature for the callable
```suggestion
       The callback function to call to check each element, which must be
       <methodsynopsis>
        <type>bool</type><methodname><replaceable>callback</replaceable></methodname>
        <methodparam><type>mixed</type><parameter>value</parameter></methodparam>
        <methodparam><type>mixed</type><parameter>key</parameter></methodparam>
       </methodsynopsis>
       If this function returns &false;, &false; is returned from
       <function>array_all</function> and the callback will not be called for
       further elements.
```

2024-08-26 11:58 UTC, Girgias commented on reference/array/functions/array-all.xml
> +   <example>
The example tag does not need to be in the para tag

2024-10-29 22:26 UTC, TimWolla reviewed
Some stylistic suggestions to be double checked by Girgias. The refpurpose should not end with a dot and not be overly technical

2024-10-29 22:26 UTC, TimWolla commented on reference/array/functions/array-all.xml
> +   </para>
```suggestion
   &example.outputs.similar;
```

Same below.

2024-10-29 22:26 UTC, TimWolla commented on reference/array/functions/array-all.xml
> +  <refpurpose>Returns &true;, if a callback returns &true; for all elements in an array.</refpurpose>
```suggestion
  <refpurpose>Checks if all array elements satisfy a callback function</refpurpose>
```

2024-10-29 22:26 UTC, TimWolla commented on reference/array/functions/array-any.xml
> +  <refpurpose>Returns &true;, if a callback returns &true; for any element in an array.</refpurpose>
```suggestion
  <refpurpose>Checks if at least one array element satisfies a callback function</refpurpose>
```

2024-10-29 22:26 UTC, TimWolla commented on reference/array/functions/array-find-key.xml
> +  <refpurpose>Returns the key of the first element of an &array; for which a callback returns &true;.</refpurpose>
```suggestion
  <refpurpose>Returns the key of the first element satisfying a callback function</refpurpose>
```

2024-10-29 22:26 UTC, TimWolla commented on reference/array/functions/array-find.xml
> +  <refpurpose>Returns the value of the first element of an &array; for which a callback returns &true;.</refpurpose>
```suggestion
  <refpurpose>Returns the first element satisfying a callback function</refpurpose>
```

2024-10-29 22:29 UTC, Girgias commented on reference/array/functions/array-all.xml
> +   </para>
Why `.similar` the `&example.outputs` entity should suffice

2024-10-29 22:32 UTC, Girgias reviewed
Some more markup changes that I missed, also please use `<simpara>` instead of `<para>` wherever possible.

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-all.xml
> +  </para>
```suggestion
  <simplelist>
   <member><function>array_any</function></member>
   <member><function>array_filter</function></member>
   <member><function>array_find</function></member>
   <member><function>array_find_key</function></member>
  </simplelist>
```

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-find.xml
> +    <varlistentry>
The wrapping para tag is useless here, please remove

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-find.xml
> +   <simplelist>
Useless wrapping para tag

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-find-key.xml
> +   <simplelist>
Ditto

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-find-key.xml
> +   <variablelist>
Ditto

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-any.xml
> +   <simplelist>
Ditto

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-any.xml
> +    <varlistentry>
Ditto

2024-10-29 22:32 UTC, Girgias commented on reference/array/functions/array-all.xml
> +    <varlistentry>
Ditto

2024-11-03 18:58 UTC, TimWolla approved these changes

2024-11-04 02:56 UTC, Girgias approved these changes
Thank you!

2024-11-04 02:56 UTC, Girgias commented on reference/array/functions/array-all.xml
> +   the function returns &false;.
Semantic Line Break
```suggestion
   <parameter>callback</parameter> returns &true; for all elements.
   Otherwise the function returns &false;.
```

2024-11-04 02:56 UTC, Girgias commented on reference/array/functions/array-any.xml
> +   function returns &false;.
```suggestion
   <parameter>callback</parameter> returns &true; for any element.
   Otherwise the function returns &false;.
```

2024-11-04 02:57 UTC, merged