Solr 2.7.0: SolrQuery::setHighlightQuery / getHighlightQuery (hl.q)
php/doc-en pull request #3485
Opened 2024-06-25 08:04 UTC by omars44

Added API changes from PECL Solr 2.7.0

2024-06-25 08:04 UTC, omars44 commented
@Girgias ping!

2024-07-07 14:19 UTC, Girgias commented
> @Girgias ping!
> 
> I wonder why the entities file doesn't exist anymore

The entities file should be generated by configure, so you shouldn't have it included in the git sources.

2024-07-07 14:23 UTC, Girgias requested changes
Sorry for the delay, I was somewhat busy

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/gethighlightquery.xml
> +   <void />
Nit:
```suggestion
   <void/>
```

I don't know if you have stubs for the extension, but then you can partially use the gen_stub script to generate the docs.

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/gethighlightquery.xml
> +  </para>
Nit: indentation but line break
```suggestion
  <para>
   Returns previously set highlight query.
   This parameter allows you to highlight different terms or fields than those being used to retrieve documents.
  </para>
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/gethighlightquery.xml
> +<!-- Keep this comment at the end of the file
Nit:
```suggestion
</refentry>
<!-- Keep this comment at the end of the file
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> +<refentry xml:id="solrquery.sethighlightquery" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Nit:
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<refentry xml:id="solrquery.sethighlightquery" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/gethighlightquery.xml
> +<refentry xml:id="solrquery.gethighlightquery" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Nit:
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<refentry xml:id="solrquery.gethighlightquery" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> +  </para>
The manual's style guide says to not use personalization (i.e. using "you") could you rephrase the sentence?
```suggestion
  <para>
   A query to use for highlighting.
   This parameter allows you to highlight different terms or fields than those being used to retrieve documents.
  </para>
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> + </refsect1>
I'm confused by those two para tags, what purpose to they serve?

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> +   Returns the current SolrQuery object, if the return value is used.
For automatic linking.
```suggestion
   Returns the current <classname>SolrQuery</classname> object, if the return value is used.
```

2024-07-07 14:23 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> +<!-- Keep this comment at the end of the file
Nit:
```suggestion
</refentry>
<!-- Keep this comment at the end of the file
```

2024-09-05 11:45 UTC, omars44 commented on reference/solr/solrquery/sethighlightquery.xml
> + </refsect1>
extra info

2024-09-05 11:53 UTC, omars44 commented on reference/solr/solrquery/sethighlightquery.xml
> +  </para>
sure

2024-09-05 11:55 UTC, omars44 commented
@Girgias sorry took me a while to find this PR for some reason, I thought it was long time merged. Just tag me next time

2024-09-11 13:13 UTC, Girgias approved these changes

2024-09-11 13:16 UTC, Girgias commented on reference/solr/solrquery/gethighlightquery.xml
> +
```suggestion

```

2024-09-11 13:16 UTC, Girgias commented on reference/solr/solrquery/sethighlightquery.xml
> +</refentry>
```suggestion
 </refsect1>

</refentry>
```

2024-09-11 13:21 UTC, merged