Add OpenSSL constants
php/doc-en pull request #3506
Opened 2024-06-28 21:06 UTC by haszi

Partially related to https://github.com/php/doc-en/issues/3333.

2024-07-05 12:12 UTC, devnexen approved these changes
LGTM

2024-07-07 14:43 UTC, Girgias requested changes

2024-07-07 14:43 UTC, Girgias commented on reference/openssl/constants.xml
> +       -DHAVE_OPENSSL_MD2_H CFLAG when compiling PHP, and enable-md2 when
```suggestion
       <literal>-DHAVE_OPENSSL_MD2_H</literal> CFLAG when compiling PHP, and <literal>enable-md2</literal> when
```

There might be more appropriate tags, but at least have them visually distinct is a first step.

2024-07-09 15:11 UTC, Girgias approved these changes

2024-07-09 15:11 UTC, merged