Add missing mysqli constants
php/doc-en pull request #3511
Opened 2024-06-29 15:23 UTC by haszi

Add missing mysqli constants.
Rename mistyped `MYSQLI_TRANS_START_CONSISTENT_SNAPSHOT` constant to `MYSQLI_TRANS_START_WITH_CONSISTENT_SNAPSHOT`.

2024-06-29 16:34 UTC, kamil-tekiela requested changes

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS</constant>
I wonder why we have two constants for this. If you know, it would be a good idea to add to the documentation.

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
Huh, I thought this was already deprecated and due for removal. It looks like that's not the case. We should probably add it to the deprecations for PHP 8.4 as soon as possible. Also, this constant is already documented. https://www.php.net/manual/en/mysqli.store-result.php

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_SET_CHARSET_DIR</constant>
That's not true. PHP doesn't support this feature and this constant has no effect in PHP. I don't know know how it got exposed to the userland, but documenting this seems pointless. Let's just remove the constant in PHP 8.4

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +   </varlistentry>
I would recommend that we do not add this to the documentation. These constants are deprecated anyway and due for removal soon. I don't even know what is their use or if they do anything at all. If I remember correctly, I deprecated them because they have no use in PHP. These descriptions would only confuse users.

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +      Closes and reopens the backup log files.
Where did you get this from? What does it even mean? How is this constant used and what exactly does it do? 
I am not sure, but I feel like it's one of the dead constants that never got implemented in PHP. We probably should not add it to the documentation.

2024-06-29 16:34 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_ASYNC</constant>
This is already documented https://www.php.net/manual/en/mysqli.query.php

2024-06-29 19:20 UTC, haszi commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
As of PHP 8.1, this constant has no effect so I'm adding that to the description.

2024-06-29 19:28 UTC, haszi commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
> Also, this constant is already documented. https://www.php.net/manual/en/mysqli.store-result.php

The constants in this PR are part of the push to get all global constants onto their respective constants pages (and enable constant linking for all of them).

2024-06-29 19:31 UTC, haszi commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_SET_CHARSET_DIR</constant>
I'll leave the constant in the docs but remove the description. I'll remove the constant when this gets deprecated.

2024-06-29 19:42 UTC, haszi commented on reference/mysqli/constants.xml
> +   </varlistentry>
You're right, none of the six constants you deprecated in https://github.com/php/php-src/pull/6850 do anything (these two included). 

For the sake of consistency, I think we should either remove or leave all six in the docs until they are removed. What do you think?

2024-06-29 19:44 UTC, haszi commented on reference/mysqli/constants.xml
> +      Closes and reopens the backup log files.
From the mysql documentation. 

I just checked `php-src` and this is just like the six constants you deprecated, it doesn't do anything. However the other six are handled, this should be handled the same way at the same time I think.

2024-06-29 19:46 UTC, haszi commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_ASYNC</constant>
This is due to the same reason as [above](https://github.com/php/doc-en/pull/3511#discussion_r1659966368).

2024-06-29 20:22 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_SET_CHARSET_DIR</constant>
https://github.com/php/php-src/pull/14724

2024-06-29 20:22 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_SET_CHARSET_DIR</constant>
There is no point in adding this to the documentation since it should not even exist in the first place. It's a bug.

2024-06-29 20:25 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +   </varlistentry>
If any of these constants are linked to from anywhere else in the docs then leave them in the documentation but with a blank description. If they would only be listed on this single page, then just remove them altogether.

2024-06-29 20:26 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +      Closes and reopens the backup log files.
Yeah, this would used in `mysqli_refresh()` but I can't find this in the MySQL docs. I assume it's part of some extension or add-on.

2024-06-29 20:27 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
ok, but I don't know if it's a good idea to duplicate this information in both places.

2024-06-29 20:51 UTC, haszi commented on reference/mysqli/constants.xml
> +      Closes and reopens the backup log files.
I found it on [this page](https://docs.oracle.com/cd/E19957-01/mysql-refman-6.0/news.html#news-6-0-8) of the Oracle website.

2024-06-29 21:06 UTC, kamil-tekiela commented on reference/mysqli/constants.xml
> +      Closes and reopens the backup log files.
Ok, leave like that.

2024-06-29 21:09 UTC, haszi commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
@Girgias What is the oldest version of PHP we need to document? If it's 8.1, this constant could be removed (from `php-src` too).

2024-07-07 14:37 UTC, Girgias commented on reference/mysqli/constants.xml
> +     <constant>MYSQLI_STORE_RESULT_COPY_DATA</constant>
@haszi we currently document everything from PHP 7.0 onwards, so please keep it.

2024-07-08 19:24 UTC, haszi commented on reference/mysqli/constants.xml
> +   </varlistentry>
None of these are referenced anywhere in the documentation so I'm removing them.

2024-07-08 19:54 UTC, kamil-tekiela approved these changes
I think it's good enough now

2024-07-09 15:14 UTC, merged