Add documentation for Ds\Set::map()
php/doc-en pull request #3606
Opened 2024-07-24 13:45 UTC by mpesari

The method `Ds\Set::map()` was first tagged in version `v1.2.7` of the extension, although it's not mentioned in the Changelog.

* https://github.com/php-ds/ext-ds/commit/ae9ce662360e9f93b4b6c7abb78b938672be1abc

What I did:

* Copied documentation from `ds/vector/map.xml` and basically just changed `vector` -> `set`
* Tested the examples

I verified the documentation and it looks OK, apart from ALL examples which look like this:

![image](https://github.com/user-attachments/assets/32ba1843-c460-4dbe-b746-1552d9a8a6c6)

I guess it's just my environment.

2024-07-26 02:46 UTC, Girgias requested changes
Thank you!

Couple of issues that need addressing :)

2024-07-26 02:46 UTC, Girgias commented on reference/ds/ds/set/map.xml
> +print_r($set);
I would prefer using `var_dump()` over `print_r()`

2024-07-26 02:46 UTC, Girgias commented on reference/ds/ds/set/map.xml
> +   <title><function>Ds\Set::map</function> example</title>
```suggestion
   <title><methodname>Ds\Set::map</methodname> example</title>
```

2024-07-26 02:46 UTC, Girgias commented on reference/ds/ds/set/map.xml
> + </refsect1>
Indentation is 1 space for XML, please fix.

2024-07-26 02:46 UTC, Girgias commented on reference/ds/ds/set/map.xml
> +<refentry xml:id="ds-set.map" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
XLinks don't seem to be used.
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<refentry xml:id="ds-set.map" xmlns="http://docbook.org/ns/docbook">
```

2024-07-26 02:46 UTC, Girgias commented on reference/ds/ds/set/map.xml
> +<!-- Keep this comment at the end of the file
```suggestion
</refentry>
<!-- Keep this comment at the end of the file
```

2024-07-26 08:01 UTC, mpesari commented on reference/ds/ds/set/map.xml
> +print_r($set);
Sure

2024-07-26 08:01 UTC, mpesari commented on reference/ds/ds/set/map.xml
> + </refsect1>
Fixed

2024-07-26 08:10 UTC, mpesari commented on reference/ds/ds/set/map.xml
> +<refentry xml:id="ds-set.map" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Applied

2024-07-26 08:10 UTC, mpesari commented on reference/ds/ds/set/map.xml
> +<!-- Keep this comment at the end of the file
Applied

2024-07-26 10:13 UTC, Girgias reviewed
Some suggestions about wording :)

2024-07-26 10:13 UTC, Girgias commented on reference/ds/ds/set/map.xml
> +  </para>
Maybe? As it might remove the need for the below note
```suggestion
  <para>
   Returns a new <classname>Ds\Set</classname> instance where each value
   is the result of applying the <parameter>callback</parameter> to each value
   of the set.
  </para>
```

2024-07-26 10:13 UTC, Girgias commented on reference/ds/ds/set/map.xml
> + </refsect1>
Not sure the last paragraph is that useful?
```suggestion
  <variablelist>
   <varlistentry>
    <term><parameter>callback</parameter></term>
    <listitem>
     <para>
      The callback to apply to each value in the set must have the following signature:
      <methodsynopsis xmlns="http://docbook.org/ns/docbook">
       <type>mixed</type>
       <methodname><replaceable>callback</replaceable></methodname>
       <methodparam><type>mixed</type><parameter>value</parameter></methodparam>
      </methodsynopsis>
     </para>
    </listitem>
   </varlistentry>
  </variablelist>
 </refsect1>
```

2024-07-26 10:56 UTC, mpesari commented on reference/ds/ds/set/map.xml
> +  </para>
Agreed, looks cleaner now

2024-07-26 10:57 UTC, mpesari commented on reference/ds/ds/set/map.xml
> + </refsect1>
Agreed

2024-07-26 11:25 UTC, mpesari commented on reference/ds/ds.set.xml
> +       </row>
@Girgias what do you think? Added this in latest push

2024-08-26 12:00 UTC, Girgias approved these changes
Thank you, and sorry for being slow with the review :)

2024-08-26 12:00 UTC, merged