adding database server examples
php/doc-en pull request #3639
Opened 2024-08-05 09:33 UTC by robertsilen

Adding database server examples that use the MySQL protocol (MariaDB, MySQL, Percona, TiDB) as per discussion https://github.com/php/doc-en/issues/3628

2024-08-05 10:07 UTC, cmb69 requested changes
Thank you for the PR! This looks generally good to me, also some issues still need to be resolved.

@kamil-tekiela, what do you think?

2024-08-05 10:07 UTC, cmb69 commented on reference/mysqlinfo/concepts.xml
> +  <link xlink:href="">Percona Server for MySQL</link>,
Either add an URL here, or don't mark up as link.

2024-08-05 10:07 UTC, cmb69 commented on reference/mysqlinfo/concepts.xml
> +  The MySQL extensions support the MySQL protocol.
The indentation should be a single space (also below).

2024-08-05 11:30 UTC, robertsilen commented on reference/mysqlinfo/concepts.xml
> +  <link xlink:href="">Percona Server for MySQL</link>,
fixed MySQ and Percona URLs in link tags

2024-08-05 11:30 UTC, robertsilen commented on reference/mysqlinfo/concepts.xml
> +  The MySQL extensions support the MySQL protocol.
fixed

2024-08-05 11:32 UTC, robertsilen commented on reference/mysqlinfo/concepts.xml
> +  <link xlink:href="https://www.pingcap.com/tidb/">TiDB</link>.
fixed

2024-08-05 11:42 UTC, robertsilen commented on reference/mysqlinfo/concepts.xml
> +  <link xlink:href="https://mariadb.org/">MariaDB Server</link>,
Added URLs now here, will change to variables when this is merged: https://github.com/php/doc-en/pull/3639

2024-08-05 11:52 UTC, cmb69 commented
Hmm, CI is reporting "Namespace prefix xlink for href on link is not defined"; not sure why, since apparently the respective XML namespace is declared.

2024-08-05 12:25 UTC, kamil-tekiela approved these changes
It looks fine to me but I wouldn't duplicate the information. Pick one spot it fits the best.

2024-08-05 13:08 UTC, cmb69 commented
The build still fails, likely because of

https://github.com/php/doc-en/blob/227766a18bcf610c39167c4c59a5e8a8a0b504b7/reference/mysqlinfo/set.xml#L4

The XML namespace declaration should probably be added to this element.

2024-08-05 13:44 UTC, cmb69 reviewed
This looks good to me now, but I think we should merge https://github.com/php/doc-base/pull/144 first, and then adapt and merge this PR (might be a bit easier to handle for translators).

2024-08-05 13:45 UTC, cmb69 approved these changes

2024-08-06 08:43 UTC, cmb69 commented
Since https://github.com/php/doc-base/pull/144 has been merged, could you please update the PR to use these entities?

2024-08-06 09:32 UTC, merged

2024-08-06 09:32 UTC, cmb69 commented
Thank you very much!