Normalize version strings in changelog entries
php/doc-en pull request #3672
Opened 2024-08-22 14:49 UTC by jimwins

Now they're always `N.X.Y` for a PHP version, or `PECL extension N.X.Y` for PECL extensions.

2024-08-25 21:04 UTC, Girgias commented on reference/memcache/memcache/delete.xml
>    </methodsynopsis>
This doesn't seem related to the normalization, split into a new PR?

2024-08-25 21:04 UTC, Girgias commented on reference/mongodb/bson.xml
> +  <?phpdoc extension-membership="pecl" ?>
Please merge the commit that does this already on its own

2024-08-26 20:41 UTC, jimwins commented on reference/mongodb/bson.xml
> +  <?phpdoc extension-membership="pecl" ?>
Done.

2024-08-26 20:50 UTC, jimwins commented on reference/memcache/memcache/delete.xml
>    </methodsynopsis>
Split out into #3687.

2024-08-28 18:11 UTC, jimwins commented
Okay, PR is just a clean set of changes to versions now. [the change to extension-membership for the MongoDB books](https://github.com/php/doc-en/pull/3672/commits/a51ebd074abdc1cd18ef9da1628d6d5049616562) was already cherry-picked and pushed into master.

2024-09-11 12:45 UTC, Girgias requested changes

2024-09-11 12:45 UTC, Girgias commented on reference/intl/dateformatter/set-calendar.xml
>         <entry>
Either remove the whole changelog as we don't care about PHP 5 anymore or only keep the PECL 3.0.0 as you've kept it for the previous file.

2024-09-22 19:07 UTC, Girgias approved these changes
Thank you!

2024-09-23 18:15 UTC, merged