Add information about Composer and example of using it's autoloader
php/doc-en pull request #3677
Opened 2024-08-23 19:09 UTC by jimwins

Long past time that we included information about Composer in the documentation. Related PR for `doc-base` incoming.

2024-08-23 22:23 UTC, cmb69 commented
A bold move, Jim!

I'm somewhat concerned about opening a can of worms when merging this; I consider it quite likely that there quickly will be lots of PRs suggesting to add examples or even documentation about some packages, and then tooling, frameworks, IDEs, etc. Maybe we should consider defining the scope first; maybe we should handle this on a case by case basis; maybe we should instead link to some external sites (e.g. https://phptherightway.com/); maybe we should try to join forces?

In any way, we shouldn't introduce personalization into the PHP manual (e.g. no "you", but instead using passive voice).

2024-08-23 22:54 UTC, jimwins commented
I think possibly having the problem of fending off too many contributions to the manual is vastly preferable to the existing problem of not acknowledging major chunks of the PHP ecosystem in the name of some sort of neutrality.

More here: https://trainedmonkey.com/2024/08/23/writing_documentation_in_anger

The PHP project is where we gather to join forces, I don't think these fundamentals should be left to external sites.

2024-08-24 09:43 UTC, cmb69 commented
I agree (also with your blog post), but we should properly discuss this, since there has been [big drama a couple of years ago](https://github.com/php/web-bugs/pull/77), and I would not like to see this happening again. Maybe there should even be an RFC about "endorsing third-party tools" (or so), to settle this topic once and for all.

cc @Crell

2024-08-24 17:24 UTC, Crell commented
I completely agree with adding Composer references to the docs, for all the reasons @jimwins mentions.  However, I also agree that we should probably not call out `ramsey/uuid` in particular as an example.  Nothing against Ben, but that part is a much more slippery slope than composer (which has basically zero competition).  A `foo/bar` package or similar is probably better.

As far as proper discussion, the most straightforward way would be an RFC "is it OK to talk about Composer in the docs? Y/N".  (We did a similar RFC recently for linking to the Foundation site, which passed easily.)  It should be a pretty easy RFC, and would quash any squeamishness about if it's OK or not.

2024-08-24 18:20 UTC, jimwins commented
Thanks for linking to that other issue, that fills in a historical event I knew was out there but hadn't run across. As it happens, I have another related blog post:

https://trainedmonkey.com/2024/07/27/the_rules_can_matter

Here's a draft RFC that is broader than just asking for permission to mention Composer:

https://wiki.php.net/rfc/web-and-doc-use-not-endorsement

2024-08-24 18:24 UTC, cmb69 commented
> RFC "is it OK to talk about Composer in the docs? Y/N"

Possible, but rather limited in scope, as follow-ups will surely come; from Jim's blog post:

> I would love to add a chapter on static analysis tools. And another one about linting and refactoring tools. Maybe a chapter on frameworks.

And of course, there is the issue about actually using it. I think we're using Composer and a few packages already in different Web repos, but still not in some repos which could benefit from some tooling (see e.g. https://github.com/php/php-sdk-binary-tools/pull/22 or https://github.com/php/php-sdk-binary-tools/commit/78c9f7b6d71b51aa8174da1470f654bd5c612232, the latter being an issue detected with static analysis; or even https://externals.io/message/124843#124866).

2024-08-26 19:50 UTC, jrfnl commented
> ... much more slippery slope than composer (which has basically zero competition). 

Nothing against Composer, but in that case, what about PHIVE ? And shouldn't the history with PEAR and its installer be mentioned ?

I do see the slippery slope here, even in the mention of Composer.

2024-08-27 00:20 UTC, derickr commented
I had not even heard of PHIVE. And PEAR is probably going to be mothballed into a static site.

I've written a more general thought on all of this: https://news-web.php.net/php.internals/125300

> I completely agree with adding Composer references to the docs, for all the reasons @jimwins mentions. However, I also agree that we should probably not call out `ramsey/uuid` in particular as an example. Nothing against Ben, but that part is a much more slippery slope than composer (which has basically zero competition). A `foo/bar` package or similar is probably better.

Using foo/bar doesn't have any meaning for users. *real* packages do. Picking an example from a community member as opposed to a large opinionated frameworks makes perfect sense ti me.

2024-08-29 19:57 UTC, cmb69 commented
> I had not even heard of PHIVE.

Its main developer even has a php.net account (apparently for as long as you do). :)

> I do see the slippery slope here, even in the mention of Composer.

I agree. It starts with Composer. Then someone asks "what does a composer do?" Right, he's writing a Symfony. And who would sing the overture? Lara Vel, of course! And it ain't over till the slim lady sings. ;)

2024-10-11 22:03 UTC, oladoyinbov commented
It would be better to create a section on the PHP website homepage (at the footer section) to list out the most popular PHP frameworks and packages, you can check python.org for a good sample of what I am talking about.

Frameworks like Laravel, Symfony, CodeIgniter, CakePHP and Package Managers like Composer should be added to help beginners and the less informed access the PHP ecosystem more quickly.

2024-10-13 14:03 UTC, Girgias commented
> It would be better to create a section on the PHP website homepage (at the footer section) to list out the most popular PHP frameworks and packages, you can check python.org for a good sample of what I am talking about.
> 
> Frameworks like Laravel, Symfony, CodeIgniter, CakePHP and Package Managers like Composer should be added to help beginners and the less informed access the PHP ecosystem more quickly.

This is already being discussed on the Internals ML.

2024-11-24 01:58 UTC, Girgias requested changes
Final XML remarks

2024-11-24 01:58 UTC, Girgias commented on install/composer.xml
> +  </para>
This wrapping para tag is unnecessary

2024-11-24 01:58 UTC, Girgias commented on language/oop5/autoload.xml
> +    </para>
```suggestion
    <simpara>
     &link.composer; generates a <literal>vendor/autoload.php</literal>
     with is set up to automatically load packages that are being managed
     by Composer. By including this file, those packages can be used without
     any additional work.
    </simpara>
```

2024-11-24 02:44 UTC, Girgias approved these changes
LGTM

2024-11-24 03:28 UTC, jimwins commented
I'll hold off on pushing this and the accompanying `doc-base` change until at least Monday in case anyone else wants to chime in.

2024-11-24 17:35 UTC, theodorejb reviewed
Fix duplicate "the" and improve wording.

2024-11-24 21:57 UTC, Crell commented
I'm fine with @theodorejb's wording change.  Otherwise, shipit.  (Once tests pass.)

2024-11-24 22:43 UTC, jimwins commented
Integration test won't pass in CI because it requires simultaneous changes from php/doc-base#147

2024-11-25 20:52 UTC, merged