Fix type juggling notes for list() and array destructuring
php/doc-en pull request #3680
Opened 2024-08-24 19:59 UTC by tgr

Update notes about the handling of missing keys and non-arrays during array destructuring to match the behavior seen on 3v4l.org, which doesn't issue a warning or notice in some cases where the documentation claims it does. Also update list() docs to provide the same information.

list():
* missing key: https://3v4l.org/bYBt6
* destructuring an integer: https://3v4l.org/7lNhK
* a boolean: https://3v4l.org/p5LDd
* a string: https://3v4l.org/KHSAH
* null: https://3v4l.org/lk1iu

array notation:
* missing key: https://3v4l.org/KCiTC
* destructuring an integer: https://3v4l.org/louVG
* a boolean: https://3v4l.org/SWL5L
* a string: https://3v4l.org/aK90L
* null: https://3v4l.org/Y8cOY

Fixes #3640.

2024-08-31 21:58 UTC, MatmaRex commented on language/types/array.xml
> -     as of PHP 8.0.0, this issues <constant>E_WARNING</constant>.
This was about array dereferencing (`$a = 42; $a[0]`) not destructuring (`[$a] = 42;`), and I think it was correct. Only destructuring weirdly yields null with no warning.

2024-08-31 22:13 UTC, MatmaRex commented on reference/array/functions/list.xml
> +    Attempting to access element of a scalar value yields &null;.
I would say: "Attempting to unpack a scalar value assigns null to all variables." to be consistent with the existing wording.

There's also already a note above: "Strings can not be unpacked" which should probably say "Only arrays and objects that implement ArrayAccess can be unpacked".

And an example below, where the comment could be clarified:
```
// list() doesn't work with strings
list($bar) = "abcde";
var_dump($bar); // NULL
```

2025-06-23 21:43 UTC, DanielEScherzer requested changes
Sorry it has taken us so long to review this; thanks for the patch, one small issue

2025-06-23 21:43 UTC, DanielEScherzer commented on language/types/array.xml
> +     Dereferencing a scalar value ields &null;.
```suggestion
     Dereferencing a scalar value yields &null;.
```

2025-08-20 23:13 UTC, MatmaRex commented
This probably needs an update now for changes in PHP 8.5: https://wiki.php.net/rfc/warnings-php-8-5#destructuring_non-array_values

2025-08-21 16:51 UTC, tgr commented on language/types/array.xml
> -     as of PHP 8.0.0, this issues <constant>E_WARNING</constant>.
Moved the note to the right place.

2025-08-21 16:52 UTC, tgr commented on reference/array/functions/list.xml
> +    Attempting to access element of a scalar value yields &null;.
Updated the wording and the other note. IMO documenting behavior when misused is not worth the space for adding an example.

2025-08-21 16:52 UTC, tgr commented on language/types/array.xml
> +     Dereferencing a scalar value ields &null;.
Fixed.

2025-08-21 16:53 UTC, tgr commented
Sorry, I forgot about this PR completely. Thanks for the feedback, rebased and updated.

> This probably needs an update now for changes in PHP 8.5: https://wiki.php.net/rfc/warnings-php-8-5#destructuring_non-array_values

I think the docs generally don't include details about not-yet-released PHP versions?

2025-08-24 05:29 UTC, DanielEScherzer commented
> Sorry, I forgot about this PR completely. Thanks for the feedback, rebased and updated.
> 
> > This probably needs an update now for changes in PHP 8.5: https://wiki.php.net/rfc/warnings-php-8-5#destructuring_non-array_values
> 
> I think the docs generally don't include details about not-yet-released PHP versions?

Yeah, we don't need to start worrying about that yet

2025-08-24 05:30 UTC, merged