Document DOMNamedNodeMap/DOMNodeList array access syntax
php/doc-en pull request #3688
Opened 2024-08-27 08:40 UTC by jnvsor

As discussed in https://github.com/php/php-src/issues/15591 there's a read-only array access functionality to `DOMNamedNodeMap` and `DOMNodeList` which isn't documented

This is my first phpdoc PR so please review. The phd build looked fine other than `<programlisting>` tags rendering without whitespace (But that includes the ones I didn't touch so I presume it's a phd issue)

2024-08-27 09:39 UTC, Girgias requested changes
Thank you for the PR, some markup remarks.

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnodelist/item.xml
>  ?>
This should be in a new `<example>` tag.

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnodelist.xml
> +    </para>
```suggestion
    <simpara>
     Nodes in the list can be accessed by array syntax.
    </simpara>
```

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +    </programlisting>
This should be in a new example tag

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +   <example>
No need for the para tag

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnamednodemap.xml
> +    </para>
```suggestion
    <simpara>
     Nodes in the map can be accessed by array syntax.
    </simpara>
```

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnodelist/item.xml
> +    </para>
Should use simpara

2024-08-27 09:39 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +    </para>
Should use simpara

2024-08-27 10:08 UTC, jnvsor commented
Changes made, though I don't see any differences in the output markup. I presume there's another output format that does use them

2024-08-27 10:26 UTC, cmb69 commented
I think both `<para>` and `<simpara>` are still rendered as `<p>`, although that is not quite correct for `<para>` (which should be a `<div>`, or maybe one of the HTML5 elements, perhaps `<section>`), because `<para>` can contain "block elements".

2024-08-27 17:42 UTC, nielsdos approved these changes
It looks good to me content-wise but a docs expert should have a final look.

2024-09-11 13:38 UTC, Girgias approved these changes
Only some indent issues

2024-09-11 13:38 UTC, Girgias commented on reference/dom/domnamednodemap.xml
>  <!-- {{{ See also -->
Nit: indent
```suggestion
  </section>

  <section role="notes">
   &reftitle.notes;
   <note>
    <simpara>
      Nodes in the map can be accessed by array syntax.
    </simpara>
   </note>
  </section>

<!-- {{{ See also -->
```

2024-09-11 13:38 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +<![CDATA[
Indent
```suggestion
  &reftitle.examples;
  <example>
   <title>Getting an attribute on a node</title>
   <programlisting role="php">
<![CDATA[
```

2024-09-11 13:38 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +<![CDATA[
```suggestion
]]>
   </programlisting>
  </example>
  <example>
   <simpara>
    Items can be also accessed with array syntax:
   </simpara>
   <programlisting role="php">
<![CDATA[
```

2024-09-11 13:38 UTC, Girgias commented on reference/dom/domnamednodemap/getnameditem.xml
> +   </example>
```suggestion
   </programlisting>
  </example>
```

2024-09-11 13:38 UTC, Girgias commented on reference/dom/domnodelist.xml
> +
```suggestion
  <section role="notes">
   &reftitle.notes;
   <note>
    <simpara>
      Nodes in the list can be accessed by array syntax.
    </simpara>
   </note>
  </section>

```

2024-09-11 13:43 UTC, merged