Fix documentation about deprecated and removed constants in VALIDATE_URL filter
php/doc-en pull request #373
Opened 2021-01-22 23:38 UTC by bohwaz

2021-03-08 16:22 UTC, afilina requested changes

2021-03-08 16:22 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
I'm not sure about the correct form that the manual proposes, but it seems to me that a better link would be to the migration docs instead of the RFC: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.filter

2021-03-08 16:22 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants are now <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter_f
Similar to the above comment: https://www.php.net/manual/en/migration73.deprecated.php#migration73.deprecated.filter

2021-03-08 16:33 UTC, cmb69 commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
The man pages are neither supposed to link to RFCs nor the migration guide. The migration guide is supposed to link to the man pages (as soon as these have been updated). RFCs should only be mentioned in XML comments, if at all.

2021-03-08 16:36 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
Ah, thanks for the clarification. I learn every day :)

2021-03-08 16:38 UTC, afilina requested changes

2021-03-08 16:38 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
```suggestion
         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been removed.
```

2021-03-08 16:38 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants are now <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter_f
```suggestion
         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been deprecated; they never had any effect.
```

2021-03-08 16:44 UTC, cmb69 commented on reference/filter/filters.xml
> -         <constant>FILTER_FLAG_HOST_REQUIRED</constant>,
The manual is currently supposed to document PHP 7.0.0 and up, so these lines should not be removed, but rather it should be clarified that these constants are only there "(prior to PHP 8.0.0)".

2021-03-08 16:45 UTC, cmb69 commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
Instead of "they never had any effect", maybe "they are implied anyway"?

2021-03-08 20:06 UTC, bohwaz commented on reference/filter/filters.xml
> -         <constant>FILTER_FLAG_HOST_REQUIRED</constant>,
I suggest removal as mentioning them suggests that this is implemented and that the behavior will change but it won't, so it would be confusing to leave them as is IMO.

2021-08-17 14:50 UTC, afilina commented on reference/filter/filters.xml
> +         <constant>FILTER_FLAG_SCHEME_REQUIRED</constant> and <constant>FILTER_FLAG_HOST_REQUIRED</constant> constants have been <link xlink:href="https://wiki.php.net/rfc/deprecations_php_7_3#filter
I think that you're referring to my other suggestion below. I updated it.

2022-12-22 16:14 UTC, afilina commented
@cmb69 I believe that this PR is waiting on a review pass from the maintainers.

2023-08-14 18:11 UTC, bohwaz commented
Thank you @afilina I think I missed the notifications. Should be good now?

2023-08-14 20:37 UTC, Girgias commented
There are conflicts @bohwaz, could you pull the latest master and rebase the PR on top of it?

2023-08-15 09:10 UTC, bohwaz commented
Sorry I have exactly zero time.

2025-10-13 03:24 UTC, afilina commented
@Girgias Other than the merge conflicts, are these changes good to go? Checking the pulse before I invest any time into resolving a 2-year-old merge conflict.

2026-09-01 16:57 UTC, lacatoire commented
This can be closed. The file it changes, `reference/filter/filters.xml`, was deleted in #4158, and the same information now lives in `reference/filter/constants.xml`, where both constants are already marked deprecated in 7.3.0 and removed in 8.0.0:
- https://www.php.net/manual/en/filter.constants.php#constant.filter-flag-scheme-required
- https://www.php.net/manual/en/filter.constants.php#constant.filter-flag-host-required
There is nothing left to rebase.

2026-09-01 16:57 UTC, closed without merging