Move/rewrite some of the macOS and Unix install instructions
php/doc-en pull request #3763
Opened 2024-09-18 20:09 UTC by jimwins

Trying to put more emphasis/information on how to install from packages (either from distributions or third parties) and for Unix, in particular, move the stuff about compiling from source down a level so new users don't get knocked in the face with it.

2024-09-18 21:10 UTC, jimwins commented
The 'DNF' section is based on the Debian one, but could certainly use review by someone who actually uses a DNF-based system, because that's not me. Also not sure if it should treat Yum and DNF like the Debian section does with apt and aptitude.

2024-09-18 21:36 UTC, cmb69 reviewed
Thank you very much for tackling this long overdue update!

Unfortunately, I can't help much with the details about installing on non Windows systems. Hopefully, some others can provide useful comments.

2024-09-18 21:36 UTC, cmb69 commented on install/unix/debian.xml
> +  <literal>aptitude</literal> commands. This manual page uses these two
Maybe:
```suggestion
  The packages can be installed using either the <command>apt</command> or
  <command>aptitude</command> commands. This manual page uses these two
```
Same for `dnf` below.

2024-09-18 21:43 UTC, jimwins commented on install/unix/debian.xml
> +  <literal>aptitude</literal> commands. This manual page uses these two
Yeah, I left that alone at first because I didn't want to make too many unnecessary changes, but now I've gone ahead and fixed all of those.

2024-09-21 14:24 UTC, cmb69 commented on install/unix/source.xml
> +       An ANSI C compiler
From PR #3603, which I don't plan to pursue further:

```suggestion
       An ANSI C compiler (as of PHP 8.0.0, C99 compatibility is assumed)
```

2024-09-21 22:33 UTC, jimwins commented on install/unix/source.xml
> +       An ANSI C compiler
Added, also went ahead and removed `automake` and `libtool` information as per discussion on that PR.

2024-09-22 19:19 UTC, Girgias requested changes

2024-09-22 19:19 UTC, Girgias commented on install/unix/debian.xml
> +    etc. These may also be installed via the <command>apt</command> command.
Everywhere else you mention both `apt` and `aptitude`, and I know the introduction does say they are interchangeable, but it just seems weird to me to not do it here only here.

2024-09-22 19:19 UTC, Girgias commented on install/unix/dnf.xml
> +   </simpara>
This tag (and the following ones) do not need to be indented, they should use the same indentation as `<title>`

2024-09-22 19:19 UTC, Girgias commented on install/unix/dnf.xml
> +    like php-cgi, php-cli and php-dev. Determine which are needed
Should the `php-` packages be put in a literal tag?

2024-09-22 19:19 UTC, Girgias commented on install/unix/dnf.xml
> +    dependency checks, it'll prompt for those. For example, to install
Why the line break after "does"?

2024-09-22 19:19 UTC, Girgias commented on install/unix/dnf.xml
> +  <simpara>
Weird indentation here

2024-09-22 19:19 UTC, Girgias commented on install/unix/dnf.xml
> +Local variables:
Useless blank line
```suggestion
</sect1>
<!-- Keep this comment at the end of the file
Local variables:
```

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +    <itemizedlist>
What is this indentation?

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +       Basic Unix skills (being able to operate "make" and a C
`"make"` maybe should be wrapped in a `<command>` tag.

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +       An ANSI C compiler (as of PHP 8.0.0, C99 compatibility is assumed)
```suggestion
       A C compiler (as of PHP 8.0.0, C99 compatibility is assumed)
```

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +    <itemizedlist>
The `<itemizedlist>` could be a `<simplelist>`

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +    <itemizedlist>
Ditto

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +    explanations running <command>./configure --help</command>.
Personalization is used here ("you") which is against the manual style guide.

2024-09-22 19:19 UTC, Girgias commented on install/unix/source.xml
> +     MPROTECT or W^X violation protection. This kind of memory mapping is,
Some tags are required, as I don't know what "PaX", "MPROTECT", or "W^X" means here, are there literal things?

2024-09-22 19:19 UTC, Girgias commented on language-snippets.ent
> + </warning>'>
Indent should be 1 space

2024-09-23 19:40 UTC, jimwins commented on install/unix/dnf.xml
> +   </simpara>
Fixed.

2024-09-23 19:40 UTC, jimwins commented on install/unix/dnf.xml
> +    like php-cgi, php-cli and php-dev. Determine which are needed
Reworked this example to refer to packages that actually exist and marked up with `<literal>`.

2024-09-23 19:41 UTC, jimwins commented on install/unix/dnf.xml
> +    dependency checks, it'll prompt for those. For example, to install
This was just an artifact of how this paragraph was adapted from the Debian instructions. It's been reworked.

2024-09-23 19:41 UTC, jimwins commented on install/unix/dnf.xml
> +  <simpara>
Fixed.

2024-09-23 19:59 UTC, jimwins commented on language-snippets.ent
> + </warning>'>
Fixed.

2024-09-23 20:09 UTC, jimwins commented on install/unix/source.xml
> +    <itemizedlist>
Just not adjusted properly when creating this new section out of text that was in `install/unix/index.xml`. Fixed.

2024-09-23 20:09 UTC, jimwins commented on install/unix/source.xml
> +       Basic Unix skills (being able to operate "make" and a C
Done.

2024-09-23 20:17 UTC, jimwins commented on install/unix/source.xml
> +       An ANSI C compiler (as of PHP 8.0.0, C99 compatibility is assumed)
Done.

2024-09-23 20:18 UTC, jimwins commented on install/unix/source.xml
> +    <itemizedlist>
The top level of this one needs to be an `<itemizedlist>` but the nested lists can become `<simplelist>`.

2024-09-23 20:18 UTC, jimwins commented on install/unix/source.xml
> +    explanations running <command>./configure --help</command>.
Fixed.

2024-09-23 20:18 UTC, jimwins commented on install/unix/source.xml
> +     MPROTECT or W^X violation protection. This kind of memory mapping is,
Just adding direct links to more information for now, will move the links out to global-entities.ent before finalizing this.

2024-09-24 10:50 UTC, Girgias reviewed
Some more markup comments

2024-09-24 10:50 UTC, Girgias commented on install/macos/packages.xml
>      <listitem>
Just noticed this on the second read through, but do we need to have a `<para>` tag wrapping an `<itemizedlist>` tag if it is the only thing in the para tag?

Or maybe use `<simplelist>`

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> + </para>
Maybe use `<simpara>` as we don't have complex nested tags inside of it?

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> + </para>
Ditto

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> +    for the MySQL extension.
Maybe linking to the relevant manual section here would be an idea

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> +    First, note that other related packages may be desired like
The simpara tag should not have an extra indent here (and the other tags are thus also badly indented)

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> +   <link linkend="book.image">GD</link>,
You can use a simplelist with an `inline` value for the `type` attribute. https://tdg.docbook.org/tdg/5.2/simplelist

2024-09-24 10:50 UTC, Girgias commented on install/unix/dnf.xml
> + </sect2>
The indent is off here

2024-09-24 10:50 UTC, Girgias commented on install/unix/index.xml
> +    particular.
Just a "soft-rule" style note, which I usually do, is to line break on full stops/commas when you are close to reaching the line character count limit:
```suggestion
    Finally, PHP can always be installed from the source distributions,
    which allows the greatest flexibility in choosing what features,
    extensions, and server APIs to enable.
    There are sections with information about compiling and configuring
    PHP to use with different server APIs in particular.
```
This is just to showcase, as I don't know if this rearrangement fits the charater limit.

The main reason to do this, is that it is unlikely that in a further update to change two different sentences at the same time which can be tricky to find for translators.

2024-09-24 10:50 UTC, Girgias commented on install/unix/source.xml
> +   <simplelist>
This para (and subsequent ones) don't need an extra indent

2024-09-24 10:50 UTC, Girgias commented on install/unix/source.xml
> +   reference pages.
Personalization is present here

2024-09-24 10:50 UTC, Girgias commented on install/unix/source.xml
> +  </para>
Ditto personalization

2024-09-24 19:25 UTC, jimwins commented on install/macos/packages.xml
>      <listitem>
✅ 

Also removed the `<para>` around an earlier `<orderedlist>`.

2024-09-24 19:27 UTC, jimwins commented
Instead of spamming a half-dozen "done!" comments, here's one to note that all of the feedback from @Girgias was addressed. The build fails now because I moved some entities into `doc-base` and that needs to land first.

2024-09-24 19:57 UTC, Girgias approved these changes
One final comment and LGTM.

Thanks for tackling this!

2024-09-24 19:57 UTC, Girgias commented on install/unix/source.xml
> +   </member>
The "C compiler" aspect is repeated in the "Basic Unix skills" bullet point

2024-09-24 20:46 UTC, merged