configuration.xml Clarify the option descriptoins
php/doc-en pull request #3772
Opened 2024-09-23 16:55 UTC by mmalferov

Maybe we should explain the access log format in more detail?

2024-09-23 18:34 UTC, Girgias commented
Possibly? But I don't know much about it as @bukka maintains FPM

2024-09-23 22:48 UTC, jimwins approved these changes
Some minor notes, but LGTM otherwise.

2024-09-23 22:48 UTC, jimwins commented on install/fpm/configuration.xml
> +             variable. Some examples: server specifics like: <literal>%{REQUEST_METHOD}e</literal> or
```suggestion
             A variable from the server environment (same as <varname>$_ENV</varname> or <varname>$_SERVER</varname>).
             A variable name must be specified within curly brackets.
             For example: server specifics like: <literal>%{REQUEST_METHOD}e</literal> or
```

2024-09-23 22:48 UTC, jimwins commented on install/fpm/configuration.xml
>               <literal>%e</literal>
Because the name is required, maybe we can include it in the Placeholder? 

```suggestion
             <literal>%{<replaceable>name</replaceable>}e</literal>
```

2024-09-23 22:48 UTC, jimwins commented on install/fpm/configuration.xml
>               <literal>%o</literal>
Same as with %e.
```suggestion
             <literal>%{<replaceable>name</replaceable>}o</literal>
```

2024-09-23 22:48 UTC, jimwins commented on install/fpm/configuration.xml
> +             <literal>%{X-Powered-By}o</literal>, <literal>%{Transfert-Encoding}o</literal>
Note typo -- `Transfert-Encoding`

```suggestion
             Output header. The header name must be specified within curly brackets.
             For example: <literal>%{Content-Type}o</literal>,
             <literal>%{X-Powered-By}o</literal>, <literal>%{Transfer-Encoding}o</literal>
```

2024-09-23 22:48 UTC, jimwins commented on install/fpm/configuration.xml
> +            <entry>Temote IP address</entry>
typo - should be "Remote"

2024-09-23 23:36 UTC, mmalferov commented on install/fpm/configuration.xml
> +            <entry>Temote IP address</entry>
This has been fixed

2024-10-06 18:27 UTC, bukka requested changes
Thanks, it's certainly an improvement. Added some notes.

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +             A variable from the server environment (same as <varname>$_ENV</varname> or <varname>$_SERVER</varname>).
There are some differences with server as this is really just FastCGI environment variable

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +             For example: server specifics like: <literal>%{REQUEST_METHOD}e</literal> or
Maybe too many colons...

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +             <literal>Content-Length</literal> of the request (for HTTP POST request only)
Think it's not just for POST... I think FPM might not even care about method in this case but haven't checked.

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +            <entry>The query string</entry>
I don't know if `The` should be added here (most of the above entries are without `the`) but not sure what the convention is for the docs. I'm also not a native speaker. Maybe @Girgias can advise here.

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +             The request URI (without the query string,
Adding `The` might be inconsistent.

2024-10-06 18:27 UTC, bukka commented on install/fpm/configuration.xml
> +            <entry>Time the log has been written (the request has finished)</entry>
```suggestion
            <entry>Time the log was written (when the request finished)</entry>
```

2024-10-28 14:22 UTC, mmalferov commented on install/fpm/configuration.xml
> +             For example: server specifics like: <literal>%{REQUEST_METHOD}e</literal> or
I removed the extra colons

2024-10-28 14:23 UTC, mmalferov commented on install/fpm/configuration.xml
> +             A variable from the server environment (same as <varname>$_ENV</varname> or <varname>$_SERVER</varname>).
I deleted the word "server" and brought the description close to the original text that I found in the FPM configuration file `www.conf.in `:

> %e: an environment variable (same as $_ENV or $_SERVER)
>     it must be associated with embraces to specify the name of the env
>     variable. Some examples:
>     - server specifics like: %{REQUEST_METHOD}e or %{SERVER_PROTOCOL}e
>     - HTTP headers like: %{HTTP_HOST}e or %{HTTP_USER_AGENT}e

2024-10-28 14:24 UTC, mmalferov commented on install/fpm/configuration.xml
> +             <literal>Content-Length</literal> of the request (for HTTP POST request only)
The config file says:

>  %l: content-length of the request (for POST request only)

While we don't have any other data, maybe we can leave it as it is?

2024-10-28 14:25 UTC, mmalferov commented on install/fpm/configuration.xml
> +            <entry>The query string</entry>
Waiting answer from @Girgias ;)

2024-10-29 14:10 UTC, Girgias commented on install/fpm/configuration.xml
> +            <entry>The query string</entry>
I think having "The" is fine. @jimwins might have a better ieda here.

2024-10-30 18:51 UTC, jimwins approved these changes
LGTM with minor changes.

2024-10-30 18:51 UTC, jimwins commented on install/fpm/configuration.xml
> +            <entry>The query string</entry>
The is fine, but most other entries aren't written with an article like that, so it should probably be consistent. I'd just do this:

```suggestion
            <entry>Query string</entry>
```

2024-10-30 18:51 UTC, jimwins commented on install/fpm/configuration.xml
> +             The request URI (without the query string,
The parens could also be removed here

```suggestion
             Request URI without the query string,
```

(And remove `)` from following line).

2024-10-31 00:22 UTC, Girgias commented on install/fpm/configuration.xml
> +             Time taken to serve the request. It can accept the following formats for precision:
```suggestion
             Time taken to serve the request.
             It can accept the following formats for precision:
```

2024-10-31 00:22 UTC, Girgias commented on install/fpm/configuration.xml
> +             Peak of memory allocated by PHP. It can accept the following format:
```suggestion
             Peak of memory allocated by PHP.
             It can accept the following format:
```

2024-10-31 00:22 UTC, Girgias commented on install/fpm/configuration.xml
> +             see <literal>%q</literal> and <literal>%Q</literal>)
```suggestion
             see <literal>%q</literal> and <literal>%Q</literal>
```

2024-10-31 00:24 UTC, merged