PackedArray::fromJSON() and toJSON methods
php/doc-en pull request #3806
Opened 2024-09-27 18:40 UTC by jmikola

https://jira.mongodb.org/browse/PHPC-2350

2024-09-27 18:45 UTC, Girgias requested changes
Some markup comments

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/fromjson.xml
> +<refentry xml:id="mongodb-bson-packedarray.fromjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Nit: Please don't put a blank line in new files :)
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<refentry xml:id="mongodb-bson-packedarray.fromjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/fromjson.xml
> +   <member>Throws <classname>MongoDB\Driver\Exception\UnexpectedValueException</classname> if <parameter>json</parameter> is not a valid array.</member>
Possible mistake?
```suggestion
   <member>Throws <classname>MongoDB\Driver\Exception\UnexpectedValueException</classname> if <parameter>json</parameter> is invalid JSON.</member>
```

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/fromjson.xml
> +<!-- Keep this comment at the end of the file
Ditto blank line
```suggestion
</refentry>
<!-- Keep this comment at the end of the file
```

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/tocanonicalextendedjson.xml
> +<refentry xml:id="mongodb-bson-packedarray.tocanonicalextendedjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Ditto
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<refentry xml:id="mongodb-bson-packedarray.tocanonicalextendedjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/tocanonicalextendedjson.xml
> +Local variables:
Ditto
```suggestion
</refentry>
<!-- Keep this comment at the end of the file
Local variables:
```

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/torelaxedextendedjson.xml
> +<refentry xml:id="mongodb-bson-packedarray.torelaxedextendedjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Ditto

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/torelaxedextendedjson.xml
> + <refsect1 role="examples">
Missing return section

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/tocanonicalextendedjson.xml
> + <refsect1 role="examples">
Missing return section

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/fromjson.xml
> + <refsect1 role="errors">
Missing return section

2024-09-27 18:45 UTC, Girgias commented on reference/mongodb/bson/packedarray/torelaxedextendedjson.xml
> +<!-- Keep this comment at the end of the file
Ditto

2024-09-27 20:01 UTC, jmikola commented on reference/mongodb/bson/packedarray/fromjson.xml
> +<refentry xml:id="mongodb-bson-packedarray.fromjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Noted! I wasn't aware of that convention.

Out of curiosity, is it mentioned anywhere on http://doc.php.net/tutorial/?

2024-09-27 20:05 UTC, jmikola commented on reference/mongodb/bson/packedarray/fromjson.xml
> +   <member>Throws <classname>MongoDB\Driver\Exception\UnexpectedValueException</classname> if <parameter>json</parameter> is not a valid array.</member>
This was adapted from the `Document::fromJSON()` method, which says "is not a valid document". I'll change both to say "if `$json` cannot be parsed as a document" (or "an array").

It's not just a matter of the JSON being valid. `PackedArray::fromJSON()` requires an actual array (i.e. outermost brackets) or an object with sequential numeric keys. There's some more context in https://github.com/mongodb/mongo-php-driver/pull/1703.

2024-09-27 20:06 UTC, jmikola commented on reference/mongodb/bson/packedarray/torelaxedextendedjson.xml
> +
```suggestion
```

2024-09-27 20:07 UTC, jmikola commented on reference/mongodb/bson/packedarray/torelaxedextendedjson.xml
> +
```suggestion
```

2024-09-27 20:08 UTC, jmikola commented on reference/mongodb/bson/packedarray/tocanonicalextendedjson.xml
> + <refsect1 role="examples">
Thanks for catching this.

The return sections were also omitted from the corresponding Document docs. I'll add both.

2024-09-29 11:25 UTC, Girgias commented on reference/mongodb/bson/packedarray/fromjson.xml
> +<refentry xml:id="mongodb-bson-packedarray.fromjson" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Yeah between `<refsect1>` is OK. I don't think it is mentioned in the tutorial as that hasn't been updated in a while :/

2024-09-29 11:27 UTC, Girgias approved these changes
XML changes look good to me :)

2024-09-30 13:12 UTC, merged