Update CURLOPT constant descriptions
php/doc-en pull request #3818
Opened 2024-10-01 08:35 UTC by haszi

Updated descriptions of `CURLOPT_*` constants with the following:

- added some missing descriptions
- added type information on the associated accepted values
- added default values
- added cURL version information on availability, deprecation, removal 
- added applicable DocBook tags
- replaced lists of accepted value constants with their generalized version (eg.  `CURLALTSVC_*` instead of listing all `CURLALTSVC_` constants individually)
- standardized minor style details (e.g. use cURL instead of curl, libcurl, CURL; sentences to end in a period; remove double quotes from within `<literal>` tags, etc.)

Unfortunately since `CURLOPT` constants are the biggest subset of all cURL constants, the diff is pretty big.

2024-10-01 14:48 UTC, cmb69 reviewed
Wow, a lot of work. Thank you!

Just left a couple of notes, before `CURLE_OPERATION_TIMEOUTED`. :)

2024-10-01 14:48 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     unless <constant>CURLALTSVC_READONLYFILE</constant>
It might be better not to mix line wrap changes with content changes (harder for translators).

2024-10-01 14:48 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     Provides AWS V4 signature authentication on HTTP(S) header as a <type>string</type>.
Could also use `&string;`, but `<type>string</type>` might be preferred nowadays.

2024-10-01 14:48 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     Defaults to <constant>CURL_MAX_WRITE_SIZE</constant> (16kB).
Might be "dangerous" to include the actual size (16kB) here, since this might change upstream. At least maybe say
```suggestion
     Defaults to <constant>CURL_MAX_WRITE_SIZE</constant> (currently, 16kB).
```

2024-10-01 18:44 UTC, Girgias requested changes
There also seems to be missing a bunch of patch versions for cURL availability (mainly `7.1`)

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +	 CRL (Certificate Revocation List) (in PEM format)
Seems to have an unintended indent change from spaces to tab here

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.7 and deprecated as of cURL 7.84.0.
Maybe?
```suggestion
     Available as of cURL 7.7.0 and deprecated as of cURL 7.84.0.
```

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     .
Doesn't this cause whitespace?

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.1.
Should this have a patch version?

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Removed as of PHP 7.3.
```suggestion
     Removed as of PHP 7.3.0.
```

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
>      </para>
Indent slightly off here

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     If more than one method is used, cURL will poll the server to see
Ditto whitespace concern?

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     .
Ditto

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Removed as of PHP 7.3.
```suggestion
     Removed as of PHP 7.3.0.
```

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
>       the number of bytes downloaded so far, the fourth is the total
Maybe this should use method synopsis?

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.7.0 and deprecated as of 7.84.0.
```suggestion
     Available as of cURL 7.7.0 and deprecated as of cURL 7.84.0.
```

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     amount of data to be read. The callback must return a <type>string</type>
Ditto methodsynopsis remark

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
>       or the transfer will be aborted with an error.
Ditto method synopsys remark

2024-10-01 18:44 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     and set a <constant>CURLE_ABORTED_BY_CALLBACK</constant> error.
Ditto methodsynopsis remark

2024-10-02 21:22 UTC, haszi commented on reference/curl/constants_curl_setopt.xml
> +     .
Hmm. You're right, there is a space between the last item on the list and the period in the rendered file. I'll move the periods right after the `</simplelist>` tags.

2024-10-02 21:28 UTC, haszi commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.1.
Good question. I've got all the version info from the [curl website](https://curl.se/libcurl/c/symbols-in-versions.html) and it seems that up until cURL 7.11.0, none of the major versions were using a patch version on the ".0" versions. Even the [release notes](https://curl.se/ch/7.10.html) refer to these versions with a patch version.

I'm OK with either leaving it as is or adding the ".0"s to these versions. Which one do you prefer?

2024-10-02 21:55 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     Provides AWS V4 signature authentication on HTTP(S) header as a <type>string</type>.
If I remember correctly, we deliberately decided to not use the entities in the function signatures (where `<type>string</type>` is supposed to occur often).

Maybe @Girgias knows whether it's preferable to use type elements or the respective entities elsewhere.

2024-10-03 12:11 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.1.
I would prefer to add the `.0` to be consistent in our docs :)

2024-10-03 12:28 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Provides AWS V4 signature authentication on HTTP(S) header as a <type>string</type>.
It is better to use the `<type>` element, as some translations translate the entity (don't ask me why doc-fr does it, but it does).

2024-10-03 14:12 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     Provides AWS V4 signature authentication on HTTP(S) header as a <type>string</type>.
With the same reasoning, they can translate the element as well. And soon we're back to
````
beschneide(zeichenkette $zeichenkette, zeichenkette $zeichen = " \n\r\t\v\x00"): zeichenkette
````

2024-10-03 15:10 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Provides AWS V4 signature authentication on HTTP(S) header as a <type>string</type>.
I'm pretty sure some of the QA scripts that can be used for translation check this. Usually the entity is better used when we want to talk about the "concept" of a string (or other type) rather then directly referring to it as a PHP type.

But the distinction is not useful most of the time. So maybe we should just fix translations that do that.

2024-10-14 09:12 UTC, haszi commented on reference/curl/constants_curl_setopt.xml
> +     unless <constant>CURLALTSVC_READONLYFILE</constant>
Should I rebase and remove all the line wrap changes or just do it in a follow-up commit on this PR?

2024-10-14 10:01 UTC, cmb69 commented on reference/curl/constants_curl_setopt.xml
> +     unless <constant>CURLALTSVC_READONLYFILE</constant>
If the PR finally gets squashed merged, it doesn't matter; do whatever is easier for you. :)

2024-10-19 15:04 UTC, haszi commented
I think I have addressed all review comments such as:
- removed line wrap changes (all that I could find)
- added cURL .0 patch version numbers
- replaced callback descriptions with `<methodsynopsis>` elements 
- clarified that `CURLOPT_BUFFERSIZE` is *currently* 16KB (ie. can change)
- replaced tab with spaces
- added missing whitespace
- removed line break between `</simplelist>` tags and periods
- clarified that deprecation for `CURLOPT_RANDOM_FILE` is the cURL version number

2024-10-21 14:08 UTC, Girgias reviewed
It looks like we got rid of some semantic breaks :/

2024-10-21 14:08 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with a directory that holds multiple CA certificates. Use this option alongside <constant>CURLOPT_SSL_VERIFYPEER</constant>.
Minor nit, line break at the full stop before "Use this option [...]".

2024-10-21 14:08 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     The number of milliseconds to wait while trying to connect. Use <literal>0</literal> to wait indefinitely.
Ditto line break

2024-10-21 14:08 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with the name of the file containing the cookie data. The cookie file can be in Netscape format, or just plain HTTP-style headers dumped into a file.
Line break

2024-10-21 14:08 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     preferred authentication mechanism via <literal>AUTH=NTLM</literal> or <literal>AUTH=*</literal>, and should be used in conjunction with the
Is the `*` in AUTH a literal or a placeholder?

2024-10-21 14:09 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     The number of milliseconds to wait while trying to connect. Use <literal>0</literal> to wait indefinitely.
Ah was this a revert of a semantic line break?

Looking just from the previous review state was unclear ('thanks GitHub)

2024-10-26 09:37 UTC, haszi commented on reference/curl/constants_curl_setopt.xml
> +     The number of milliseconds to wait while trying to connect. Use <literal>0</literal> to wait indefinitely.
Yeah, all these line break changes all reverts.

2024-10-26 09:39 UTC, haszi commented on reference/curl/constants_curl_setopt.xml
> +     preferred authentication mechanism via <literal>AUTH=NTLM</literal> or <literal>AUTH=*</literal>, and should be used in conjunction with the
It is a literal and refers to any authorization method being acceptable.

2024-10-27 11:49 UTC, Girgias approved these changes
Readding semantic breaks where we are already editing it so it affects translations anyway

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with a directory that holds multiple CA certificates. Use this option alongside <constant>CURLOPT_SSL_VERIFYPEER</constant>.
```suggestion
     A <type>string</type> with a directory that holds multiple CA certificates.
     Use this option alongside <constant>CURLOPT_SSL_VERIFYPEER</constant>.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     The number of milliseconds to wait while trying to connect. Use <literal>0</literal> to wait indefinitely.
```suggestion
     The number of milliseconds to wait while trying to connect.
     Use <literal>0</literal> to wait indefinitely.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with the name of the file containing the cookie data. The cookie file can be in Netscape format, or just plain HTTP-style headers dumped into a file.
```suggestion
     A <type>string</type> with the name of the file containing the cookie data.
     The cookie file can be in Netscape format, or just plain HTTP-style headers dumped into a file.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with the name of a file to save all internal cookies to when the handle's destructor is called.
```suggestion
     A <type>string</type> with the name of a file to save all internal cookies to when
     the handle's destructor is called.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of PHP 7.3.0 and cURL 7.61.0.
```suggestion
     &true; to not allow URLs that include a username.
     Usernames are allowed by default.
     Available as of PHP 7.3.0 and cURL 7.61.0.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     This option accepts a <type>string</type> or &null;.
```suggestion
     Set the local IPv4 address that the resolver should bind to.
     The argument should contain a single numerical IPv4 address.
     This option accepts a <type>string</type> or &null;.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     This option accepts a <type>string</type> or &null;.
```suggestion
     Set the local IPv6 address that the resolver should bind to.
     The argument should contain a single numerical IPv6 address.
     This option accepts a <type>string</type> or &null;.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     to the file that the transfer should be written to. The default is <constant>STDOUT</constant> (the browser window).
```suggestion
     to the file that the transfer should be written to.
     The default is <constant>STDOUT</constant> (the browser window).
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     <type>string</type> may be a plain IP address, a hostname, a network interface name (under Unix), or just a plain <literal>-</literal> to use the system's default IP address.
```suggestion
     <type>string</type> may be a plain IP address, a hostname,
     a network interface name (under Unix),
     or just a plain <literal>-</literal> to use the system's default IP address.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Set to &true; to use <literal>EPRT</literal> (and <literal>LPRT</literal>) when doing active FTP downloads. Set to &false; to disable <literal>EPRT</literal> and <literal>LPRT</literal> and use
```suggestion
     Set to &true; to use <literal>EPRT</literal> (and <literal>LPRT</literal>) when doing active FTP downloads.
     Set to &false; to disable <literal>EPRT</literal> and <literal>LPRT</literal> and use <literal>PORT</literal> only.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Set to &true; to first try an <literal>EPSV</literal> command for FTP transfers before reverting back to <literal>PASV</literal>. Set to &false; to disable <literal>EPSV</literal>.
```suggestion
     Set to &true; to first try an <literal>EPSV</literal> command for FTP transfers before reverting back to <literal>PASV</literal>.
     Set to &false; to disable <literal>EPSV</literal>.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Set to a <type>string</type> with the name of the outgoing network interface to use. This can be an interface name, an IP address or a host name.
```suggestion
     Set to a <type>string</type> with the name of the outgoing network interface to use.
     This can be an interface name, an IP address or a host name.
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Set to &true; to keep sending the request body if the HTTP code returned is equal to or larger than <literal>300</literal>. The default action would be to stop sending
```suggestion
     Set to &true; to keep sending the request body if the HTTP code returned is equal to or larger than <literal>300</literal>.
     The default action would be to stop sending
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     Available as of cURL 7.1, deprecated as of cURL 7.8
```suggestion
     Available as of cURL 7.1.0, deprecated as of cURL 7.8.0
```

2024-10-27 11:49 UTC, Girgias commented on reference/curl/constants_curl_setopt.xml
> +     A <type>string</type> with the contents of the <literal>Referer: </literal> header to be used in a HTTP request.
```suggestion
     A <type>string</type> with the contents of the <literal>Referer: </literal>
     header to be used in a HTTP request.
```

2024-10-27 11:51 UTC, merged