Asymmetric Visiblity and Final properties
php/doc-en pull request #3828
Opened 2024-10-04 05:32 UTC by Crell

First stab at documenting asymmetric visibility and final properties.  (Technically final properties came in with hooks, but that's a much bigger task and it does impact aviz, so I included it here.)

2024-10-04 12:09 UTC, cmb69 reviewed
Thank you! (can't really comment on the actual contents)

2024-10-04 12:09 UTC, cmb69 commented on language/oop5/final.xml
> +    A property that is declared <literal>private(set)</literal> is implicitly <literal>final</literal>.
As a long time PHP user, the reader might wonder what this `private(set)` is, and where to find out more about it. I suggest to link that to the new "section" in visibility. I think the first `para` could have an `xml:id` which can be used for `xlink`ng.

2024-10-04 12:09 UTC, cmb69 commented on language/oop5/properties.xml
> +    <literal>protected(set)</literal>, so may be set from child classes.  That may be overridden
ditto (i.e. link)

2024-10-04 12:09 UTC, cmb69 commented on language/oop5/visibility.xml
> +   <para>There are a few caveats with asymmetric visibility to be aware of.</para>
I think this should either be a `<simpara>` or the `<para>` should include the `<itemizedlist>`. (I wonder whether PhD supports `<itemizedlist><title>…</title>…</itemizedlist>`, which might semantically be more appropriate.)

2024-10-04 20:58 UTC, Crell commented on language/oop5/visibility.xml
> +   <para>There are a few caveats with asymmetric visibility to be aware of.</para>
I have no meaningful preference here.  I have a hard time telling which list style to use where, so whatever you think PhD will accept as valid, I can go with.

2024-10-05 10:57 UTC, cmb69 commented on language/oop5/visibility.xml
> +      <![CDATA[
Nit: it's customary to not indent `<![CDATA[`:
```suggestion
<![CDATA[
```

2024-10-05 10:57 UTC, cmb69 commented on language/oop5/visibility.xml
> +      <![CDATA[
```suggestion
<![CDATA[
```

2024-10-05 10:57 UTC, cmb69 commented on language/oop5/visibility.xml
> +   <para>There are a few caveats with asymmetric visibility to be aware of.</para>
Okay, on having a closer look, I'm not even sure any list makes sense, because currently there is only *one* item. If you intented to have an item for every `<simpara>`, that needs additional markup.

<details>
<summary>Multiple list items with title</summary>

````xml
   <itemizedlist>
    <title>Caveats with asymmetric visibility</title>
    <listitem>
     <simpara>
      Only typed properties may have a separate <emphasis>set</emphasis> visibility.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      The <emphasis>set</emphasis> visibility must be the same
      as <emphasis>get</emphasis> or more restrictive. That is,
      <code>public protected(set)</code> and <code>protected protected(set)</code>
      are allowed, but <code>protected public(set) will cause a syntax error.</code>
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      If a property is <literal>public</literal> writeable, then the main visibility may be
      omitted.  That is, <code>public private(set)</code> and <code>private(set)</code>
      will have the same result.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      A property with <literal>private(set)</literal> visibility
      is automatically <literal>final</literal>, and may not be redeclared in a child class.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      Obtaining a reference to a property follows <emphasis>set</emphasis> visibility, not <emphasis>get</emphasis>.
      That is because a reference may be used to modify the property value.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      Similarly, trying to write to an array property involves both a <emphasis>get</emphasis> and
      <emphasis>set</emphasis> operation internally, and therefore will follow the <emphasis>set</emphasis>
      visibility, as that is always the more restrictive.
     </simpara>
    </listitem>
   </itemizedlist>
````

![caveats](https://github.com/user-attachments/assets/900ce6cf-67fe-4d0c-b3b7-870383900c75)
</details>

This seems to be the best solution semantically, but doesn't look like it should.

<details>
<summary>Multiple items with `simpara` as introduction</summary>

````xml
   <simpara>There are a few caveats with asymmetric visibility to be aware of:</simpara>
   <itemizedlist>
    <listitem>
     <simpara>
      Only typed properties may have a separate <emphasis>set</emphasis> visibility.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      The <emphasis>set</emphasis> visibility must be the same
      as <emphasis>get</emphasis> or more restrictive. That is,
      <code>public protected(set)</code> and <code>protected protected(set)</code>
      are allowed, but <code>protected public(set) will cause a syntax error.</code>
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      If a property is <literal>public</literal> writeable, then the main visibility may be
      omitted.  That is, <code>public private(set)</code> and <code>private(set)</code>
      will have the same result.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      A property with <literal>private(set)</literal> visibility
      is automatically <literal>final</literal>, and may not be redeclared in a child class.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      Obtaining a reference to a property follows <emphasis>set</emphasis> visibility, not <emphasis>get</emphasis>.
      That is because a reference may be used to modify the property value.
     </simpara>
    </listitem>
    <listitem>
     <simpara>
      Similarly, trying to write to an array property involves both a <emphasis>get</emphasis> and
      <emphasis>set</emphasis> operation internally, and therefore will follow the <emphasis>set</emphasis>
      visibility, as that is always the more restrictive.
     </simpara>
    </listitem>
   </itemizedlist>
````

![caveats2](https://github.com/user-attachments/assets/633dd431-a8b6-48ea-80d6-a00c845f3d6e)
</details>

Semantic nonsense, but looks quite okay.

<details>
<summary>Note without list</summary>

````xml
   <note>
    <title>Caveats with asymmetric visibility</title>
    <simpara>
     Only typed properties may have a separate <emphasis>set</emphasis> visibility.
    </simpara>
    <simpara>
     The <emphasis>set</emphasis> visibility must be the same
     as <emphasis>get</emphasis> or more restrictive. That is,
     <code>public protected(set)</code> and <code>protected protected(set)</code>
     are allowed, but <code>protected public(set) will cause a syntax error.</code>
    </simpara>
    <simpara>
     If a property is <literal>public</literal> writeable, then the main visibility may be
     omitted.  That is, <code>public private(set)</code> and <code>private(set)</code>
     will have the same result.
    </simpara>
    <simpara>
     A property with <literal>private(set)</literal> visibility
     is automatically <literal>final</literal>, and may not be redeclared in a child class.
    </simpara>
    <simpara>
     Obtaining a reference to a property follows <emphasis>set</emphasis> visibility, not <emphasis>get</emphasis>.
     That is because a reference may be used to modify the property value.
    </simpara>
    <simpara>
     Similarly, trying to write to an array property involves both a <emphasis>get</emphasis> and
     <emphasis>set</emphasis> operation internally, and therefore will follow the <emphasis>set</emphasis>
     visibility, as that is always the more restrictive.
    </simpara>
   </note>
````

![caveats2](https://github.com/user-attachments/assets/180dda44-8e34-4346-bf23-b600afa82377)
</details>

Oh, the `<simpara>`s don't have any effect.

<details>
<summary>Note without list but paras</summary>

````xml
   <note>
    <title>Caveats with asymmetric visibility</title>
    <para>
     Only typed properties may have a separate <emphasis>set</emphasis> visibility.
    </para>
    <para>
     The <emphasis>set</emphasis> visibility must be the same
     as <emphasis>get</emphasis> or more restrictive. That is,
     <code>public protected(set)</code> and <code>protected protected(set)</code>
     are allowed, but <code>protected public(set) will cause a syntax error.</code>
    </para>
    <para>
     If a property is <literal>public</literal> writeable, then the main visibility may be
     omitted.  That is, <code>public private(set)</code> and <code>private(set)</code>
     will have the same result.
    </para>
    <para>
     A property with <literal>private(set)</literal> visibility
     is automatically <literal>final</literal>, and may not be redeclared in a child class.
    </para>
    <para>
     Obtaining a reference to a property follows <emphasis>set</emphasis> visibility, not <emphasis>get</emphasis>.
     That is because a reference may be used to modify the property value.
    </para>
    <para>
     Similarly, trying to write to an array property involves both a <emphasis>get</emphasis> and
     <emphasis>set</emphasis> operation internally, and therefore will follow the <emphasis>set</emphasis>
     visibility, as that is always the more restrictive.
    </para>
   </note>
````

![caveats3](https://github.com/user-attachments/assets/e47cbcc9-5e31-44b4-bc81-6bbaf981de73)
</details>

Not great, but visually okay. Although the generated HTML of notes is semantic garbage.

So maybe go with "Multiple items with `simpara` as introduction" for now. Might be the best compromise regarding semantics and visual presentation.

2024-10-05 11:40 UTC, cmb69 commented on language/oop5/final.xml
> +    A property that is declared <literal>private(set)</literal> is implicitly <literal>final</literal>.
So, I suggest to wrap the new contents in visibility.xml in a `<sect3>` element:
````xml
   <sect3 xml:id="language.oop5.visibility-members-aviz">
    <title>Asymmetric Property Visibility</title>
````
and then change this line to something like:
```suggestion
    A property that is declared
    <link linkend="language.oop5.visibility-members-aviz"><literal>private(set)</literal></link>
    is implicitly <literal>final</literal>.
```

2024-10-06 02:36 UTC, Crell commented on language/oop5/visibility.xml
> +      <![CDATA[
Ugh.  My IDE always does that when I copy-paste code samples...

2024-10-06 02:41 UTC, Crell commented on language/oop5/final.xml
> +    A property that is declared <literal>private(set)</literal> is implicitly <literal>final</literal>.
Done

2024-10-06 02:45 UTC, Crell commented on language/oop5/visibility.xml
> +   <para>There are a few caveats with asymmetric visibility to be aware of.</para>
Er, that would be a dumb typo on my part; it was supposed to be a `<listitem><simpara></simpara></listitem>` chain all the way down, which is what I saw used elsewhere.

2024-10-06 10:15 UTC, cmb69 reviewed
Thank you! This looks quite good now, but a few things to consider.

@Girgias, since this is mostly about aviz (i.e. PHP 8.4), should we track this PR somewhere?

Also, what to do about the `<itemizedlist><title>`?

2024-10-06 10:15 UTC, cmb69 commented on language/oop5/properties.xml
> +    As of PHP 8.1.0, a property can be declared with the <literal>readonly</literal> modifier,
Nit for thought: is `<literal>` preferable to `<code>` here? I'm not sure.

2024-10-06 10:15 UTC, cmb69 commented on language/oop5/visibility.xml
> +     reading (<emphasis>get</emphasis>) and writing (<emphasis>set</emphasis>).
I don't like `<emphasis>` here (and below) for semantic reasons, although `<literal>` is also not quite appropriate.

2024-10-06 10:15 UTC, cmb69 commented on language/oop5/visibility.xml
> +     <title>Caveats regarding asymmetric visibility</title>
While this is the proper way[TM] to mark it up, the HTML rendering is off, since it is converted to `<h1>` (while the `<sect3>` title above is converted to `<h4>`). Either we fix PhD in this regard, or we should work around with having the list's title as a para/simpara above the list. I'm not happy with either.

2024-10-06 12:48 UTC, Crell commented on language/oop5/properties.xml
> +    As of PHP 8.1.0, a property can be declared with the <literal>readonly</literal> modifier,
`<literal>` seems more common from what I saw, so I tried to standardize on that.  I have no particular preference, but this seemed to be the convention.

2024-10-06 12:49 UTC, Crell commented on language/oop5/visibility.xml
> +     reading (<emphasis>get</emphasis>) and writing (<emphasis>set</emphasis>).
Yeah, I wasn't a fan of that either but don't know what's preferable.  I'm happy to change it to whatever we decide is least wrong.

2024-10-06 12:49 UTC, Crell commented on language/oop5/visibility.xml
> +     <title>Caveats regarding asymmetric visibility</title>
I'll move it back to an intro paragraph to avoid blocking this PR on PhD updates.

2024-10-11 14:59 UTC, cmb69 commented on language/oop5/visibility.xml
> +     reading (<emphasis>get</emphasis>) and writing (<emphasis>set</emphasis>).
It's probably okay to use `<literal>`; after all, it's a literal part of the aviz syntax.

2024-10-12 00:40 UTC, Crell commented on language/oop5/visibility.xml
> +     reading (<emphasis>get</emphasis>) and writing (<emphasis>set</emphasis>).
Done.

2024-10-13 12:53 UTC, cmb69 approved these changes
Thank you!

2024-10-13 14:29 UTC, Girgias requested changes
Mainly markup remarks.

2024-10-13 14:29 UTC, Girgias commented on language/oop5/final.xml
> +    <title>Final property example as of PHP 8.4.0</title>
The example tag does not need to be nested in a `<para>` tag. I see that the other ones do it, but it is just useless.

2024-10-13 14:29 UTC, Girgias commented on language/oop5/final.xml
>  ]]>
I would prefer you have a `<screen>` tag that shoes the output than a comment, as comments in examples are somewhat annoying for translators.

2024-10-13 14:29 UTC, Girgias commented on language/oop5/final.xml
> +    As of PHP 8.0.0, private methods may not be declared final except for the constructor.
Drive by improvement, add a link to the page explaining constructors?

2024-10-13 14:29 UTC, Girgias commented on language/oop5/properties.xml
> +    explicitly if desired.
I prefer to add line breaks at the end of sentences.
Because if those need to be amended in the future it is easier for translators to see what needs fixing.
```suggestion
    which prevents modification of the property after initialization.*
    Prior to PHP 8.4.0 a <literal>readonly</literal> property is implicitly private-set,
    and may only be written to from the same class.
    As of PHP 8.4.0, <literal>readonly</literal> properties are implicitly
    <link linkend="language.oop5.visibility-members-aviz"><literal>protected(set)</literal></link>,
    so may be set from child classes. 
    That may be overridden explicitly if desired.
```

2024-10-13 14:29 UTC, Girgias commented on language/oop5/visibility.xml
> +     <example>
No need to have a para tag around the example tag.

2024-10-13 14:29 UTC, Girgias commented on language/oop5/visibility.xml
> +    </itemizedlist>
Move the itemizedlist tag inside the para tag as they form "one block".

2024-10-13 14:29 UTC, Girgias commented on language/oop5/visibility.xml
> +     <example>
No need to have a para tag wrapping the example tag.

2024-10-13 14:29 UTC, Girgias commented on language/oop5/visibility.xml
> +     but creates a new property with a different internal name.
Ditto remark about using line breaks at the end of a sentence.

2024-10-13 14:29 UTC, Girgias commented on reference/reflection/reflectionproperty/isprivate.xml
> +   main visibility, and not to a <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```suggestion
   &true; if the property is private, &false; otherwise.
   Note this refers only to the  main visibility, and not to a
   <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```
Or maybe this should even be put inside a `<note>` tag.

2024-10-13 14:29 UTC, Girgias commented on reference/reflection/reflectionproperty/isprotected.xml
> +   main visibility, and not to a <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```suggestion
   &true; if the property is protected, &false; otherwise.
   Note this refers only to the main visibility, and not to a
   <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```

2024-10-13 14:29 UTC, Girgias commented on reference/reflection/reflectionproperty/ispublic.xml
> +   main visibility, and not to a <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```suggestion
   &true; if the property is marked public, &false; otherwise.
   Note this refers only to the main visibility, and not to a
   <link linkend="language.oop5.visibility-members-aviz">set-visibility</link>, if specified.
```

2024-10-13 14:30 UTC, Girgias commented
> Thank you! This looks quite good now, but a few things to consider.
> 
> @Girgias, since this is mostly about aviz (i.e. PHP 8.4), should we track this PR somewhere?

Please add it to the milestone, and I will create an issue the moment I finish the migration guide.

> 
> Also, what to do about the `<itemizedlist><title>`?

What is the issue here?

2024-10-13 15:01 UTC, cmb69 commented
> > Also, what to do about the `<itemizedlist><title>`?
> 
> What is the issue here?

PhD issue. The [`<title>` is always rendered as `<h1>`](https://private-user-images.githubusercontent.com/2306138/373865232-900ce6cf-67fe-4d0c-b3b7-870383900c75.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzE4MzksIm5iZiI6MTcyODgzMTUzOSwicGF0aCI6Ii8yMzA2MTM4LzM3Mzg2NTIzMi05MDBjZTZjZi02N2ZlLTRkMGMtYjNiNy04NzAzODM5MDBjNzUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMTQ1ODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU4YzM4OGYxY2IyODEwZGVmM2UyMGUzZjQ4ZjU2NTE3ZWNmMGYxYjc3ZDViY2Q0NjgzZTJjMTRhMmQ0NDZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.orWMAcvaum1NCVBSwR6G9YFmtBVlGAhH5jR3hxK6kHU), so is practically useless.

2024-10-13 15:11 UTC, Girgias commented
> > > Also, what to do about the `<itemizedlist><title>`?
> > 
> > 
> > What is the issue here?
> 
> PhD issue. The [`<title>` is always rendered as `<h1>`](https://private-user-images.githubusercontent.com/2306138/373865232-900ce6cf-67fe-4d0c-b3b7-870383900c75.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzE4MzksIm5iZiI6MTcyODgzMTUzOSwicGF0aCI6Ii8yMzA2MTM4LzM3Mzg2NTIzMi05MDBjZTZjZi02N2ZlLTRkMGMtYjNiNy04NzAzODM5MDBjNzUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMTQ1ODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU4YzM4OGYxY2IyODEwZGVmM2UyMGUzZjQ4ZjU2NTE3ZWNmMGYxYjc3ZDViY2Q0NjgzZTJjMTRhMmQ0NDZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.orWMAcvaum1NCVBSwR6G9YFmtBVlGAhH5jR3hxK6kHU), so is practically useless.

I suppose for the moment just leave it an open a PhD issue, as it should track nesting (because I imagine this being an issue outside of `<itemizedlist>`).

2024-10-14 02:59 UTC, Crell commented on language/oop5/properties.xml
> +    explicitly if desired.
Is there any standard for this?  @cmb69?  I have not seen that approach used anywhere else, and it feels kinda clumsy to me.

2024-10-14 08:59 UTC, cmb69 commented on language/oop5/properties.xml
> +    explicitly if desired.
No, there are now hard rules about this. Still, it can make sense to take this approach (unless overdone); "good" diffs may be more important than readability of the doc sources; after all, you can't have very good readability at all (e.g. the long `<link>` element). A rule of thumb *might* be to use relatively short lines (say 72 columns, or maybe even less), and only go above that limit where required (e.g. to not split a long "inline" element), and prefer to break lines after a full stop.

Anyway, if you take @Girgias' suggestion, don't forget to remove the spurious `*` at the end of the first line.

2024-10-14 11:33 UTC, Girgias commented on language/oop5/final.xml
> +    <title>Final property example as of PHP 8.4.0</title>
Probably because people didn't look at the DocBook spec, or PhD used to render this weirdly.

2024-10-14 11:48 UTC, Girgias commented on language/oop5/properties.xml
> +    explicitly if desired.
I fixed the suggestion.

But this is a rule that is used by other large orgs, e.g. [GitLab](https://docs.gitlab.com/ee/development/documentation/styleguide/#line-length) and is called [Semantic Line Breaks](https://sembr.org/)

2024-10-14 12:00 UTC, cmb69 commented on language/oop5/properties.xml
> +    explicitly if desired.
We should also consider https://docs.gitlab.com/ee/development/documentation/styleguide/#documentation-is-the-single-source-of-truth-ssot ;)

2024-10-15 00:22 UTC, Crell commented on language/oop5/final.xml
> +    <title>Final property example as of PHP 8.4.0</title>
OK, I took out the para on all examples in the file.

2024-10-15 15:53 UTC, Crell commented
I addressed everything above aside from the sentence-per-line bits.  That sounds like it's not a formal convention yet, and it's non-trivial to do, so I'd rather hold off until/unless there's some policy decision on it to follow.

Anything else to address before we merge this?

2024-10-15 16:06 UTC, cmb69 approved these changes
Yeah, let's not be too picky here. :)

2024-10-15 16:17 UTC, Crell commented
(Rebased to try and fix the build.)

2024-10-15 16:58 UTC, cmb69 commented on language/oop5/final.xml
> +    As of PHP 8.0.0, private methods may not be declared final except for the <link linkend="#language.oop5.decon.constructor">constructor</link>.
```suggestion
    As of PHP 8.0.0, private methods may not be declared final except for the <link linkend="language.oop5.decon.constructor">constructor</link>.
```

2024-10-15 18:48 UTC, Girgias approved these changes

2024-10-15 18:48 UTC, Girgias commented on language/oop5/visibility.xml
> +     any property that is not <literal>final</literal>.  When doing so,
Maybe there should be a link to `final` keyword here.

Feels like we should add more keywords entities to `doc-base/entities/global.ent`

2024-10-15 18:49 UTC, merged