Deprecated the second parameter to mysqli_store_result
php/doc-en pull request #3850
Opened 2024-10-07 23:28 UTC by kamil-tekiela

2024-10-08 09:42 UTC, Girgias approved these changes
One nit but LGTM

2024-10-08 09:42 UTC, Girgias commented on reference/mysqli/mysqli/store-result.xml
> +       Passing the <parameter>mode</parameter> parameter is deprecated now.
```suggestion
       Passing the <parameter>mode</parameter> parameter is now deprecated.
```

2024-10-12 15:12 UTC, Girgias approved these changes

2024-10-16 19:59 UTC, jimwins requested changes

2024-10-16 19:59 UTC, jimwins commented on reference/mysqli/mysqli/store-result.xml
> +       The parameter has had no effect since PHP 8.1.0.
```suggestion
       The parameter has had no effect as of PHP 8.1.0.
```

Style nit.

2024-10-16 20:38 UTC, jimwins approved these changes

2024-10-16 20:39 UTC, merged