Fix #1370: adding GearmanClient::setXXXCallback callback args doc
php/doc-en pull request #3861
Opened 2024-10-12 18:41 UTC by cracksalad

See #1370 
**This PR adds documentation for the callback arguments of the `GearmanClient::setXXXCallback` methods.**
___

In the [PECL extension](https://github.com/php/pecl-networking-gearman) you can see, that all callback functions are called (equally) by this code snippet:

https://github.com/php/pecl-networking-gearman/blob/a52052cdd712a95091ce926be3bcdca41c730696/php_gearman_task.c#L32-L48

If you look closely, you might note, that `task->zdata` (which is called `$context` in PHP) will be provided always (at least if it was set when `GearmanClient::addTaskXXX` was called).
For some of the `GearmanClient::setXXXCallback` methods, there are already examples in this documentation mentioning, that those two arguments are provided.

2024-10-13 14:00 UTC, Girgias requested changes
Considering the amount of times this text is repeated, I would recommend defining a new XML entity in language-snippets.ent *or* use XIncludes. :)

2024-10-15 12:55 UTC, cracksalad commented
> Considering the amount of times this text is repeated, I would recommend defining a new XML entity in language-snippets.ent _or_ use XIncludes. :)

As far as I understand, XIncludes would require relative pathes, which might be error-prone. In addition to that, the language-snippets.ent already contains entities for the Gearman extension. So I have add one there.

___

@Girgias If I summarize correctly, your other remark is about the void return type and the invalid union type (I guess "invalid" in this case means, that it is not valid PHP code, although it works fine in the docs). As I do not like the idea of expecting people to know that void functions actually return null, I tried to work around that.

2024-10-15 18:33 UTC, Girgias reviewed
One comment about the structure of the entity, but LGTM otherwise

2024-10-15 18:33 UTC, Girgias commented on language-snippets.ent
> +<!ENTITY gearman.parameter.callback '<para xmlns="http://docbook.org/ns/docbook">
This is not _just_ the callback parameter. It handles the complete variable list and only adds one parameter.

I think it would be better to leave the `<variablelist>` tag out in case some function has more parameters.

2024-10-16 09:49 UTC, Girgias approved these changes
Thank you!

2024-10-16 09:49 UTC, merged