PHP-FPM Link to extended "access.format" configuration
php/doc-en pull request #3866
Opened 2024-10-13 19:57 UTC by RoSk0

2024-10-13 19:59 UTC, Girgias requested changes

2024-10-13 19:59 UTC, Girgias commented on install/fpm/configuration.xml
> +        </para>
These should be documented in the manual, and not redirect people the sources IMHO.

In any case this needs proper markup for linking and entity usage to refer to the git repo.

2024-10-18 04:38 UTC, RoSk0 commented on install/fpm/configuration.xml
> +        </para>
Replaced the link with the actual descriptions

2024-10-21 13:47 UTC, Girgias reviewed
Some markup comments, but I would like @bukka to review the content.

2024-10-21 13:47 UTC, Girgias commented on install/fpm/configuration.xml
> +            <entry>the '?' character if query string exists</entry>
```suggestion
            <entry>the <literal>?</literal> character if query string exists</entry>
```

2024-10-21 13:47 UTC, Girgias commented on install/fpm/configuration.xml
> +            <entry>the request URI (without the query string, see %q and %Q)</entry>
```suggestion
            <entry>the request URI (without the query string, see <literal>%q</literal> and <literal>%Q</literal>)</entry>
```

2024-10-21 13:47 UTC, Girgias commented on install/fpm/configuration.xml
> +             <literal>%{<strftime_format>}t</literal> tag, e.g. for a ISO8601
This is not valid XML as it is creating a tag, use the relevant XML entities of `<` and `>`

2024-10-21 18:55 UTC, RoSk0 commented on install/fpm/configuration.xml
> +             <literal>%{<strftime_format>}t</literal> tag, e.g. for a ISO8601
Fixed

2024-11-04 02:20 UTC, Girgias commented
This now conflicts, can you rebase please?

2024-11-07 18:51 UTC, RoSk0 commented
https://github.com/php/doc-en/pull/3772 managed to get in before this.

Left only what was missing in https://github.com/php/doc-en/pull/3772 .

2024-11-08 15:38 UTC, bukka approved these changes
LGTM

2024-11-09 15:02 UTC, merged