Replace the `filename` tag with the `literal` tag for the `.php` file extension
php/doc-en pull request #3870
Opened 2024-10-14 18:45 UTC by mmalferov

2024-10-14 18:54 UTC, mmalferov commented
I also removed the trailing spaces that lead to linter errors in [install/macos/bundled.xml](https://github.com/php/doc-en/pull/3870/files#diff-39191bf405c0d2ce6613e2611f867c14d7fb02a3b65fbfe2b1a2337805f91ecb)

2024-10-15 11:14 UTC, Girgias requested changes

2024-10-15 11:14 UTC, Girgias commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
Those should be `<filename type="extension">` and not `<literal>`. See: https://tdg.docbook.org/tdg/5.2/filename

2024-10-15 11:19 UTC, mmalferov commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
It raise an error:

```
ERROR (file:////home/runner/work/doc-en/doc-en/en/chapters/tutorial.xml:23:68)
    for PHP and that all files ending in <filename type="extension">.php</filename>
--------------------------------------------------------------------^
 No declaration for attribute type of element filename
```

2024-10-15 11:20 UTC, cmb69 commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
Ah, thank you!

2024-10-15 11:49 UTC, Girgias commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
Ah my bad it is a `class` attribute and not a `type` attribute. (DocBook and the very consistent attribute names)

2024-10-15 11:51 UTC, mmalferov commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
Bring back the `literal` tag for the `.php` extension?

2024-10-15 11:58 UTC, mmalferov commented on chapters/tutorial.xml
> -    for PHP and that all files ending in <filename>.php</filename>
Done

2024-10-15 12:06 UTC, Girgias reviewed
I added some suggestions for follow-up PRs.

2024-10-15 12:06 UTC, Girgias commented on reference/opcache/preload.xml
> +  all <filename class="extension">.php</filename> files in the <filename>src</filename> directory will be preloaded, unless they
This is more for a follow-up PR, but directories should ideally also have the corresponding `class` attribute. :)
```suggestion
  all <filename class="extension">.php</filename> files in the <filename class="directory">src</filename> directory will be preloaded, unless they
```

2024-10-15 12:06 UTC, Girgias commented on install/macos/bundled.xml
> +  appropriately named <filename>php</filename> and likely exists as
This feels like it should use a `command` tag, but again follow-up PR :)
```suggestion
  appropriately named <command>php</command> and likely exists as
```

2024-10-15 12:08 UTC, Girgias approved these changes
Thank you!

2024-10-15 12:10 UTC, merged