Add missing constants and function for Memcached
php/doc-en pull request #3873
Opened 2024-10-15 14:34 UTC by cracksalad

This PR...
- adds 30 previously undocumented class constants (2 of which are new in v3.3.0)
- adds 1 previously undocumented method
- fixes some inconsistencies in constant documentation

References:
- [PECL extension source code](https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c)
- [libmemcached-awesome documentation](https://awesomized.github.io/libmemcached/libmemcached/memcached_behavior.html)

2024-10-15 14:59 UTC, cmb69 reviewed
Thank you! The markup looks okay (see comments below, though), but I don't know about the actual contents. Maybe @m6w6 can have a look?

2024-10-15 14:59 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Type: &integer;, default: <constant>Memcached::COMPRESSION_FASTLZ</constant>.</para>
As I understand it, `&integer;` and friends are discouraged nowadays.

2024-10-15 14:59 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>
Unless that is not properly supported by PhD, I would use `<simpara>` inside of `<listitem>`.

2024-10-15 16:20 UTC, cracksalad commented on reference/memcached/constants.xml
> +    <para>Type: &integer;, default: <constant>Memcached::COMPRESSION_FASTLZ</constant>.</para>
Oh okay, what to use instead?

2024-10-15 17:10 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Type: &integer;, default: <constant>Memcached::COMPRESSION_FASTLZ</constant>.</para>
You can resolve that manually: `<type>integer</type>`. However, I still don't understand why translators apparently translate `&integer;`. See https://github.com/php/doc-en/pull/3818#discussion_r1786135924 for some background.

2024-10-15 19:00 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Type: &integer;, default: <constant>Memcached::COMPRESSION_FASTLZ</constant>.</para>
It should be `<type>int</type>` however. As `integer` is not a proper PHP type :)

2024-10-15 19:02 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +   <variablelist>
The para tag wrapping the variablelist is useless here

2024-10-15 19:30 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +   <variablelist>
Yeah I don't really know why some extension docs do that. I'm not sure the inconsistency is that much of a problem compared to annoying translations with markup changes.

But I need to go back to write some doc tooling for our XML.

2024-10-16 09:37 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Type: &integer;, default: <constant>Memcached::COMPRESSION_FASTLZ</constant>.</para>
`&true;`, `&false;` and `&null;` should not be changed.

2024-10-16 11:26 UTC, cracksalad commented on reference/memcached/memcached/setencodingkey.xml
> +   <variablelist>
Removed `<para>` tags wrapping a `<variablelist>` tag for all Memcached methods. Stats: all methods accepting arguments but one were affected.

2024-10-17 17:44 UTC, m6w6 commented
Awesome work, @cracksalad, thank you so much!

2024-10-18 15:23 UTC, cmb69 commented on reference/memcached/constants.xml
> +    </para>
Just noticed that you sometimes use `<simpara>`, sometimes `<para>` and sometimes both in a  `<listitem>` element. Please use always `<simpara>` there (unless `<para>` would be required, but I don't think this is the case here).

2024-10-18 15:59 UTC, cracksalad commented on reference/memcached/constants.xml
> +    </para>
@cmb69 When using 
```xml
<simpara>foo</simpara>
<simpara>bar</simpara>
```
there is no line break in between.

In this specific example it would look like this (which in this case would not be a problem, but other cases would look worse):
![grafik](https://github.com/user-attachments/assets/5938491a-387c-463d-a92f-11a2cfd5d3a7)

2024-10-18 17:54 UTC, cmb69 commented on reference/memcached/constants.xml
> +    </para>
Oh, indeed, for whatever reason a `simpara` inside a `listitem` is rendered as `span`:

https://github.com/php/phd/blob/8428f31cfd767cff36812108c79ff4b9b518edd4/phpdotnet/phd/Package/Generic/XHTML.php#L278-L284

Although [DocBook says](https://tdg.docbook.org/tdg/5.2/simpara):

> Processing expectations
Formatted as a displayed block.

Not sure what to do. Fixing PhD seems to be trivial, but might break some intentional rendering. @Girgias, @haszi, @jimwins, thoughts?

2024-10-18 18:58 UTC, jimwins commented on reference/memcached/constants.xml
> +    </para>
I think `<simpara>` should be rendered as `<p>` and if that causes HTML layout problems when it is inside a `<note>`, `<listitem>`, or `<entry>`, we need to change the CSS styling so it looks how we want. Maybe we should make it `<p class="simpara">`.

(I would also be happy to see `<simpara>` just go away in favor of always using `<para>` because it seems rather pointless and probably some artifact of optimizing for old XML processing toolchains. But I haven't looked deeply at DocBook to see if there are places where you can only use `<simpara>` and not `<para>` that justify its existence.)

2024-10-18 19:39 UTC, jimwins commented on reference/memcached/constants.xml
> +    </para>
Yeah, mapping `<para>` to `<p>` is problematic given HTML's handling of block elements within those, but maybe we can leave that as a problem for another day. Mapping `<simpara>` to `<p>` seems rather obviously correct to me, so I'd support changing that.

2024-10-20 08:34 UTC, haszi commented on reference/memcached/constants.xml
> +    </para>
I agree with `<simpara>` being mapped to `<p>`.

I've checked `doc-en` and it seems that `<simpara>`s in `<listitem>`s are also used for simpler lists (see [here](https://www.php.net/manual/en/extensions.alphabetical.php) and [here](https://www.php.net/manual/en/function.odbc-gettypeinfo.php#refsect1-function.odbc-gettypeinfo-returnvalues)). If `<simpara>` is switched to a `<p>` element the vertical spacing will increase a lot. Which is not to say that we shouldn't make this change just that we need an alternative way of making these less vertical space-consuming lists.

2024-10-21 13:56 UTC, Girgias commented on reference/memcached/constants.xml
> +    </para>
I can see 3 solutions to the problem here.

Mapping `<simpara>` to `<p>` except if it is in a `<itemizedlist><listitem>` or `<orderedlist><listitem>` sequence.
(this would cover the issue here where a `<simpara>` is used in a `<listitem>` in a `<varlistentry>`.

We convert those compact lists to `<simplelist>` tags.

We add  a `role="compact"` on `<itemizedlist>`/`<orderedlist>` to change the processing inline (this might be annoying considering how PhD is implemented).

2024-10-26 09:53 UTC, haszi commented on reference/memcached/constants.xml
> +    </para>
I think `<simplelist>` wouldn't make sense semantically as it is supposed to be `"An undecorated list of single words or short phrases"`.

The implementation of the other two options would take about the same amount of effort but I'm in favor of the `role="compact"` on `<itemizedlist>`/`<orderedlist>` elements as this shows intent in the documentation and can directly be controlled from there instead of the special casing hack that would only be known to those few of us who were part of this conversation. :-)

2024-10-27 16:03 UTC, Girgias commented on reference/memcached/constants.xml
> +    </para>
Then let's do the `role="compact"` option. :)

2024-10-29 14:06 UTC, Girgias commented on reference/memcached/memcached/setoption.xml
> +        <member><literal>Memcached::OPT_COMPRESSION_TYPE</literal> requires <literal>Memcached::COMPRESSION_*</literal> values.</member>
Should be constant tags instead of literal no?

2024-10-29 14:06 UTC, Girgias commented on reference/memcached/constants.xml
>      <para>Type: <type>int</type>, default: <literal>3</literal>.</para>
Just realizing that normally we put the type info in the `<term>` tag, but this is a follow-up.

2024-10-31 16:22 UTC, cracksalad commented on reference/memcached/constants.xml
> +    </para>
How to proceed with this PR: Should I wait for the `role="compact"` change to be in place or should I change the `para`s to `simpara`s right now?

2024-10-31 17:05 UTC, cracksalad commented on reference/memcached/constants.xml
>      <para>Type: <type>int</type>, default: <literal>3</literal>.</para>
What about the default values? 
(1) Should they be moved to the `<term>` tag as well or 
(2) would you describe them in a `simpara` kind of as is or 
(3) should we move them to the `setOption`-method doc, cause constants do not really have defaults, or 
(4) should we restructure the "Predefined Constants" site to have different sections (one for the `OPT_*` constants, one for option values, one for `RES_*` constants etc.) and maybe use a table for the `OPT_*` constants (as is for [DateTime](https://www.php.net/manual/en/datetime.constants.php)) where we could add a column for the defaults
(5) more differently...

2024-10-31 17:57 UTC, cmb69 commented on reference/memcached/constants.xml
>      <para>Type: <type>int</type>, default: <literal>3</literal>.</para>
I don't quite understand how a constant would have a default value. However, I agree with @Girgias that we can do that in a follow-up PR; this one is already very comprehensive.

2024-10-31 17:59 UTC, cmb69 commented on reference/memcached/constants.xml
> +    </para>
I suggest to stick with you have for now. Changing to `simpara` would break the rendering, and waiting on `role="compact"` to be implemented might leave this important PR hanging around.

2024-10-31 18:32 UTC, cracksalad commented on reference/memcached/constants.xml
>      <para>Type: <type>int</type>, default: <literal>3</literal>.</para>
> I don't quite understand how a constant would have a default value.

It doesn't! But the constant is used as the "name" of an option which has a default. I think it is really important to document those defaults, but I am not sure where. Since you can think of the documentation of those constants as the documentation of the configuration options, it seems to be the right place.

2024-11-04 02:27 UTC, Girgias commented on reference/memcached/constants.xml
>      <para>Type: <type>int</type>, default: <literal>3</literal>.</para>
The standard way to markup constant lists is with `<variablelist>`, but you can have multiple ones and even add a `<title>` tag to describe the grouping, look at `streams/constants.xml` for a rewrite that I recently did.

Tables are not great as they might not fit the width of the screen (e.g. mobile) and at present nearly all constant lists don't use tables.

2024-11-04 02:33 UTC, Girgias reviewed
Please revert the markup changes for functions where the documentation did not change (effectively revert ` Remove unnecessary para tag wrapping variablelist tag for Memcached methods`). Yes, the markup is not what I consider ideal, but no need to give unnecessary work to translations.

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/construct.xml
> +   </varlistentry>
Create a new issue for this, as this is going to be forgotten...

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> + </refsect1>
No need for a para tag wrapping the simplelist

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +  <para>
To follow the new style guide
```suggestion
  <simpara>
```

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +     </para>
To follow the new style guide
```suggestion
     <simpara>
      The AES key.
     </simpara>
```

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +  </para>
To follow the new style guide
```suggestion
  <simpara>
   This method sets the AES encryption/decryption key for data written to and read from Memcached.
  </simpara>
```

2024-11-04 02:33 UTC, Girgias commented on reference/memcached/memcached/setencodingkey.xml
> +<refentry xml:id="memcached.setencodingkey" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
There is no use of this as far as I can see?
```suggestion
<refentry xml:id="memcached.setencodingkey" xmlns="http://docbook.org/ns/docbook">
```

2024-11-09 13:23 UTC, cracksalad commented
> Please revert the markup changes for functions where the documentation did not change (effectively revert ` Remove unnecessary para tag wrapping variablelist tag for Memcached methods`). Yes, the markup is not what I consider ideal, but no need to give unnecessary work to translations.

But there were exactly **42 :tada:** changed files, now there are only 5 left 😢

2024-11-09 13:41 UTC, cmb69 commented
@cracksalad, we *try* to distinguish between fixes/improvements to the documentation which affect all translations (beside EN, there are about 10 of these active), and changes which are likely only relevant for EN (such as whitespace changes, typo fixes etc.) The latter can be marked as `skip-revcheck`, so translators do not need to care about these.

The (now reverted) markup changes would have affected all translations; much work for a small gain. Still, we may consider to do these changes for EN in a separate PR; that is then still something which translators may skip at their own decision.

2024-11-09 13:54 UTC, cracksalad commented
@cmb69 I was just joking. 42 simply felt right :joy:

So this `skip-revcheck` is a PR level marking, such that we have to at least do those changes in a different PR. Did I get that right?

2024-11-09 14:28 UTC, cmb69 commented
> 42 simply felt right

Ah, got it. :)

`skip-revcheck` is applied to individual commits, but it's simpler to have separate PRs (often we want to squash-merge commits).

2024-11-09 14:51 UTC, Girgias requested changes
Some minor comments now, hopefully last round of reviews.

2024-11-09 14:51 UTC, Girgias commented on reference/memcached/memcached/addserver.xml
> -       data-related operations will set
It seems the only changes in this file are trailing whitespace changes now, which should also be reverted to make the PR/squashed merged commit more focused and not bother translations.

2024-11-09 14:51 UTC, Girgias commented on reference/memcached/memcached/setoption.xml
> +       One of the <constant>Memcached::OPT_*</constant> constant.
For automatic linking during render.
```suggestion
       One of the <constant>Memcached::OPT_<replaceable>*</replaceable></constant> constant.
```

2024-11-09 14:51 UTC, Girgias commented on reference/memcached/memcached/setoption.xml
> +         <member><constant>Memcached::OPT_COMPRESSION_TYPE</constant> requires <constant>Memcached::COMPRESSION_*</constant> values.</member>
Ditto please add `<replaceable>` tags around the `*` in constant tags.
Also maybe add some line breaks so that the lines are less than 80 chars (not mandatory but recommended)

2024-11-09 19:10 UTC, Girgias requested changes
Okay, I clearly didn't properly go through the constant list.
Hopefully this is really the last one.

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     <literal>--enable-memcached-msgpack</literal> option and the
```suggestion
     <option>--enable-memcached-msgpack</option> option and the
```

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     <literal>msgpack</literal> extension is loaded.
This probably should have a link, but considering it is external to the php docs it needs a global entity. So I would recommend doing this in a follow-up PR as this requires changes to doc-base.

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     default if you don't know or don't care.
Please remove personalization (i.e. `you`) the manual style indicates to not use it (yes we know there is a lot of existing usages).

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     This can be used to create a "domain" for your item keys. The value
Ditto remove personalization while at it please.

Edit: seeing there is a lot on this page already... well this is upsetting but might be better to done in a follow-up PR.

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Virtual Bucket hashing key distribution algorithm (also called vbucket).</para>
This is new, so might as well use the new manual style.
```suggestion
    <simpara>Virtual Bucket hashing key distribution algorithm (also called vbucket).</simpara>
```

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     Retrieval commands such as <function>Memcached::get</function> are unaffected by this setting.
Aside: as this is a pre-existing issue, but those should be in a `<methodname>` tags.
```suggestion
     Retrieval commands such as <methodname>Memcached::get</methodname> are unaffected by this setting.
```

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     failures.
Considering this is being amended regardless, add some semantic breaks?
```suggestion
     Specifies the failure limit for server connection attempts.
     The server will be removed after this many continuous connection failures.
```

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
>       <function>Memcached::getMultiByKey</function> to ensure that the CAS token values
Ditto same remark about preexiting issues in regard to the use of `<function>` tags.

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +     get a default value of NULL.
This feels like it is talking about the PHP `null` which should use an entity.
```suggestion
     get a default value of &null;.
```

2024-11-09 19:10 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Item stored.</para>
As this (and below) constants are new, could you please use:
```suggestion
    <simpara>Item stored.</simpara>
```

2024-11-09 19:24 UTC, Girgias commented
Also please rebase, as it now conflicts because of #4028

2024-11-10 15:10 UTC, cracksalad commented on reference/memcached/constants.xml
> +     <literal>msgpack</literal> extension is loaded.
I am currently working on a msgpack doc as well, PR coming soon. I will add a proper link in there.

2024-11-10 15:17 UTC, cracksalad commented on reference/memcached/constants.xml
> +     This can be used to create a "domain" for your item keys. The value
There are 10 occurences of `you` in this file. 
If I understand your reasoning correctly, I ignore your personalization related comments for now and will come back to them in a future PR.

2024-11-10 15:17 UTC, cracksalad commented on reference/memcached/constants.xml
> +     default if you don't know or don't care.
Ignoring this for now as well...

2024-11-10 15:26 UTC, cracksalad commented on reference/memcached/constants.xml
> +    <para>Item stored.</para>
Sorry, I somehow missed those.

2024-11-10 17:41 UTC, Girgias approved these changes
Thank you!

2024-11-10 17:41 UTC, Girgias commented on reference/memcached/constants.xml
> +    </para>
```suggestion
    <simpara>
     This serializer is supported only if memcached is configured with
     <option>--enable-memcached-msgpack</option> option and the
     <literal>msgpack</literal> extension is loaded.
    </simpara>
```

2024-11-10 17:41 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>The JSON array serializer. This serializer deserializes JSON to an associative array.</para>
```suggestion
    <simpara>
     The JSON array serializer.
     This serializer deserializes JSON to an associative array
    </simpara>
```

2024-11-10 17:41 UTC, Girgias commented on reference/memcached/constants.xml
> +    </para>
```suggestion
    <simpara>
     This serializer is supported only if memcached is configured with
     <option>--enable-memcached-igbinary</option> option and the
     <link linkend="intro.igbinary">igbinary</link> extension is loaded.
    </simpara>
```

2024-11-10 17:41 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Available as of Memcached 3.3.0.</para>
```suggestion
    <simpara>
     The ZSTD compression algorithm.
    </simpara>
    <simpara>
     Available as of Memcached 3.3.0.
    </simpara>
```

2024-11-10 17:41 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>The FASTLZ compression algorithm.</para>
```suggestion
    <simpara>
     The FASTLZ compression algorithm.
    </simpara>
```

2024-11-10 17:45 UTC, merged