Remove example linked link in favor of literal
php/doc-en pull request #3879
Opened 2024-10-16 21:53 UTC by alfsb

This file may need also be fully re-indented.

2024-10-16 22:13 UTC, jimwins requested changes
We can delimit the variable parts of the URLs with `<replaceable>`. We don't want to re-flow a whole document at once, but there are enough wording tweaks here to warrant making this paragraph conform to preferred styles, including semantic line breaks.

2024-10-16 22:13 UTC, jimwins commented on install/cloud/azure.xml
> +     </para>
```suggestion
     <para>
      Kudu Dashboard: if the website has the URL
      <literal><replaceable>site_name</replaceable>.azurewebsites.net</literal>,
      the Kudu dashboard is
      <literal>https://<replaceable>site_name</replaceable>.scm.azurewebsites.net/</literal>.
      The dashboard provides access to debugging capabilities, file
      management, and site extensions.
      Site extensions are an Azure mechanism to add extra programs,
      like PHP preview builds, to a website.
     </para>
```

2024-10-17 12:56 UTC, alfsb commented
> We can delimit the variable parts of the URLs with `<replaceable>`. We don't want to re-flow a whole document at once, but there are enough wording tweaks here to warrant making this paragraph conform to preferred styles, including semantic line breaks.

Revision included.

I plan wait some weeks for another reviews, and then merge in case of no opposition. Editors are welcome to merge this at any time.

2024-10-17 13:01 UTC, cmb69 approved these changes
Thank you!

2024-10-17 13:07 UTC, MauricioFauth approved these changes

2024-10-17 16:46 UTC, merged

2024-10-17 16:46 UTC, jimwins commented
Thanks!