Fix dom_import_simplexml() return type
php/doc-en pull request #3882
Opened 2024-10-17 21:24 UTC by cmb69

See <https://github.com/php/php-src/pull/16489>.

2024-10-17 21:25 UTC, nielsdos requested changes

2024-10-17 21:25 UTC, nielsdos commented on reference/dom/functions/dom-import-simplexml.xml
> +   <type class="union"><type>DomAttr</type><type>DOMElement</type></type><methodname>dom_import_simplexml</methodname>
```suggestion
   <type class="union"><type>DOMAttr</type><type>DOMElement</type></type><methodname>dom_import_simplexml</methodname>
```

2024-10-17 21:29 UTC, nielsdos commented
The documentation of this function is also a bit whack...

Description:
> This function takes the node node of class [SimpleXML](https://www.php.net/manual/en/ref.simplexml.php) and makes it into a [DOMElement](https://www.php.net/manual/en/class.domelement.php) node. This new object can then be used as a native [DOMElement](https://www.php.net/manual/en/class.domelement.php) node.

This is inaccurate now


Return values:
> The [DOMElement](https://www.php.net/manual/en/class.domelement.php) node added.

What ???

2024-10-17 21:50 UTC, cmb69 commented on reference/dom/functions/dom-import-simplexml.xml
> +   <type class="union"><type>DomAttr</type><type>DOMElement</type></type><methodname>dom_import_simplexml</methodname>
Oh, that was wishful thinking, Thank you for checking!

2024-10-17 22:05 UTC, cmb69 commented
> What ??? What does added even mean here?

Indeed, makes no sense, so updated. (a bit sad, though, since it would have had its 20th birthday in a couple of weeks ;)

Before updating/improving/fixing the description, could you please have a look at the implementation of dom_import_simplexml_common():

https://github.com/php/php-src/blob/42e179ef9dc7f5b8cf6f1135c6be8e7ffe4aa5cb/ext/dom/php_dom.c#L566-L570

Is it really okay to cast an arbitrary object to a `php_libxml_node_object`?

2024-10-18 05:31 UTC, nielsdos commented
Note that `php_libxml_import_node` will fail if the object is not actually an xml object.
I suppose it would be cleaner to check failure of `php_libxml_import_node` first and only then do the cast, but I don't think the current ordering hurts.

2024-10-18 16:48 UTC, cmb69 commented
Ah, I've overlooked `php_libxml_import_node`!

I've pushed a further commit regarding the function and the parameter descriptions. However, it seems to me that not only `SimpleXMLElement`s can be imported, but rather arbitrary objects which have been registered with libxml. Might be worth to document that at some time.

2024-10-18 18:54 UTC, nielsdos commented
Indeed it's broader than simplexml. However, in practice only DOM & simplexml register handlers to be able to do it.
Also a small nit on wording: you used "convert", but it's not actually converting in the sense that it's a clone; they're working on the same xml nodes so it's more like creating a "view". i.e. changes you make via dom are gonna be visible in simplexml and vice versa.

2024-10-18 21:50 UTC, cmb69 commented
Thanks for the clarification! I tried to improve the wording, and added a respective example.

2024-10-19 19:09 UTC, nielsdos approved these changes

2024-10-19 19:09 UTC, nielsdos commented
Thanks a lot!

2024-10-19 20:40 UTC, merged