Document `FFI\CType::getFuncParameterType()` purpose and return
php/doc-en pull request #3883
Opened 2024-10-17 22:59 UTC by DanielEScherzer

2024-10-18 00:33 UTC, jimwins requested changes
The `index` parameter should get described, too. Maybe: "Index of the parameter (zero-based)."

2024-10-18 01:04 UTC, DanielEScherzer commented
> The `index` parameter should get described, too. Maybe: "Index of the parameter (zero-based)."

Done

2024-10-18 01:09 UTC, jimwins requested changes

2024-10-18 01:09 UTC, jimwins commented on reference/ffi/ctype/getfuncparametertype.xml
> +      Index of function parameter, zero-indexed.
```suggestion
      Index of the function parameter, zero-based.
```

We use zero-based (and "zero based") in quite a few places in the docs, but not "zero indexed".

2024-10-18 01:11 UTC, DanielEScherzer commented on reference/ffi/ctype/getfuncparametertype.xml
> +      Index of function parameter, zero-indexed.
I've always heard it as "indexed" rather than "based", but if there is an existing standard in this repo, then no worries, changed

2024-10-18 14:28 UTC, cmb69 commented on reference/ffi/ctype/getfuncparametertype.xml
There should be at least a short description; maybe just duplicate the first sentence of the return type section:
```suggestion
Returns the type of a parameter for the underlying function type.
```

2024-10-22 10:22 UTC, Girgias approved these changes

2025-04-24 15:01 UTC, merged