[PHP 8.4] Add new constants and tokens from the tokenizer
php/doc-en pull request #3936
Opened 2024-10-27 10:43 UTC by driade

Once the property hooks page is done, links should be added in tokens.xml

2024-10-28 21:31 UTC, jimwins approved these changes
LGTM with one nit.

2024-10-28 21:31 UTC, jimwins commented on appendices/tokens.xml
> +      property hooks(available as of PHP 8.4.0)
Missing space.

```suggestion
      property hooks (available as of PHP 8.4.0)
```

2024-10-29 07:28 UTC, driade commented
Done!

2024-10-29 14:22 UTC, Girgias requested changes
@iluuu1994 this probably needs to be mentioned in UPGRADING

2024-10-29 15:15 UTC, driade commented on appendices/migration84/constants.xml
> + </sect2>
Done. Reordered tokens.xml too.

2024-10-29 19:10 UTC, Girgias approved these changes

2024-10-29 19:11 UTC, merged