[PHP 8.4] Add errors for GetText functions
php/doc-en pull request #3964
Opened 2024-10-29 17:40 UTC by saundefined

2024-10-29 19:12 UTC, Girgias requested changes
Tag should be amended

2024-10-29 19:12 UTC, Girgias commented on reference/gettext/functions/dgettext.xml
> +   Throws a <classname>ValueError</classname> if <parameter>domain</parameter>
Should be `<exceptionname>`

2024-10-29 21:44 UTC, cmb69 commented on reference/gettext/functions/bind-textdomain-codeset.xml
> +   is the empty &string;.
As I understand it, nowaday the following is preferred:
```suggestion
   is the empty <type>string</type>.
```

2024-10-30 07:16 UTC, saundefined commented on reference/gettext/functions/bind-textdomain-codeset.xml
> +   is the empty &string;.
I missed that, thanks! I'll keep that in mind

2024-11-03 14:37 UTC, Girgias commented
Yes, except if we want to wait for the PR that uses PI to land and use those instead?

2024-11-13 15:22 UTC, merged