PHP-8.4: LDAP changes
php/doc-en pull request #4066
Opened 2024-11-14 02:34 UTC by Girgias

I don't understand the `ldap_connect()` to `ldap_connect_wallet()` part of UPGRADING, nor do I see how `ldap_exop_sync()` is seemingly "better" than the current version? The mess of a return type is just duplicated currently....

2024-11-14 11:42 UTC, cmb69 reviewed
> I don't understand the `ldap_connect()` to `ldap_connect_wallet()` part of UPGRADING

See https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#ldap_connect for full details. TL;DR: `ldap_connect()` should be used when built against OpenLDAP; `ldap_connect_wallet()` when built against Oracle LDAP (the latter is apparently broken anyway; see https://externals.io/message/125933).

> nor do I see how `ldap_exop_sync()` is seemingly "better" than the current version?

Can't say much about that, except that generally ext/ldap is in thorough need of some TLC.

2024-11-14 11:42 UTC, cmb69 commented on reference/ldap/functions/ldap-exop-sync.xml
> +      May be NULL for some operations like <constant>LDAP_EXOP_WHO_AM_I</constant>,
```suggestion
      May be &null; for some operations like <constant>LDAP_EXOP_WHO_AM_I</constant>,
```

2024-11-14 11:42 UTC, cmb69 commented on reference/ldap/functions/ldap-exop-sync.xml
> +      may also need to be BER encoded.
Maybe
```suggestion
      may also need to be <acronym>BER</acronym> encoded.
```
(means "Basic Encoding Rules" in this context; however, "Bit Error Rate" seems also pretty common, so there might be an acronym clash)

2024-11-14 11:42 UTC, cmb69 commented on reference/ldap/functions/ldap-exop-sync.xml
> +      usually equal to the request OID.
Maybe
```suggestion
      Will be filled with the response <acronym>OID</acronym> if provided,
      usually equal to the request <acronym>OID</acronym>.
```
(means "Object Identifier")

2024-11-14 21:50 UTC, Girgias commented on reference/ldap/functions/ldap-exop-sync.xml
> +      may also need to be BER encoded.
BER seems to be LDAP specific no?

2026-05-22 17:59 UTC, jordikroon requested changes

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      &ldap.parameter.ldap;
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      The extended operation request OID.
      Can be one of the
      <constant>LDAP_EXOP_<replaceable>*</replaceable></constant>
      constants,
      or a string with the OID of the operation.
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      The extended operation request data.
      May be &null; for some operations like<constant>LDAP_EXOP_WHO_AM_I</constant>,
      may also need to be <acronym>BER</acronym> encoded.
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      Array of <link linkend="ldap.controls">LDAP Controls</link> to send with the request.
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      Will be filled with the extended operation response data if provided.
      If not provided <function>ldap_parse_exop</function> may be used on the
      result object later to get this data.
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop-sync.xml
> +     </para>
```suggestion
     <simpara>
      Will be filled with the response <acronym>OID</acronym> if provided,
      usually equal to the request <acronym>OID</acronym>.
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop.xml
>       <para>
```suggestion
     <simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop.xml
>       </para>
```suggestion
     </simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop.xml
>       <para>
```suggestion
     <simpara>
```

2026-05-22 17:59 UTC, jordikroon commented on reference/ldap/functions/ldap-exop.xml
>       </para>
```suggestion
     </simpara>
```

2026-05-22 18:20 UTC, jordikroon commented
It was time to revive this PR. Did some markup changes on behalf of.

2026-05-22 18:20 UTC, merged