Pcntl php84
php/doc-en pull request #4073
Opened 2024-11-15 11:22 UTC by devnexen

2024-11-15 11:22 UTC, devnexen commented
for #3872

2024-11-17 22:25 UTC, Girgias requested changes

2024-11-17 22:25 UTC, Girgias commented on reference/pcntl/constants.xml
> + </variablelist>
This is an enum, so it should not be documented here actually see #4080 for how such a page should look (albeit we don't have rendering support yet).

2024-11-17 22:27 UTC, devnexen commented on reference/pcntl/constants.xml
> + </variablelist>
Yes I expected you would ask me changes, kept it as a separate commit. Ok will have a look.

2024-11-17 22:30 UTC, Girgias commented on reference/pcntl/constants.xml
> + </variablelist>
Feel free to merge the first commit then :)

2024-11-17 22:59 UTC, merged