Hooks reflection
php/doc-en pull request #4110
Opened 2024-11-20 06:56 UTC by Crell

New PR, includes #4039, which generates the stubs.  Still WIP.

Resolves #4039.

2024-12-13 18:06 UTC, Girgias approved these changes

2024-12-13 18:10 UTC, Girgias commented
I didn't realize, but @Crell you didn't address some of the review comments.

2024-12-13 23:07 UTC, Crell commented on reference/reflection/reflectionproperty/gethook.xml
> +$rProp->getHook(PropertyHookType::Set); // Returns null.
Hm.  In that case, do we even need the screen tag anymore?  Just have it show output and leave it to the new wasm runner.

2024-12-14 04:58 UTC, Crell commented
Switched all the examples to generate output.  I did not include the output, because it's a hassle to do and we now have the Wasm runner that will produce it for us on-demand.

2024-12-16 05:17 UTC, Crell commented
@Girgias Which comments haven't been addressed?

2024-12-20 12:41 UTC, Girgias requested changes
Output of examples is missing.

2024-12-22 04:32 UTC, Crell commented
I disagree that manually pre-generating the output is worthwhile now that we have the Wasm runner.  If someone else would like to modify the PR to include that, go ahead, but I have limited time with a baby now, so won't be doing so.

2025-02-06 13:26 UTC, Girgias commented on reference/filesystem/functions/touch.xml
> +  </para>
Seems this snuck in the PR. when it should be in another one.

2025-02-12 21:43 UTC, Crell commented on reference/filesystem/functions/touch.xml
> +  </para>
Oops indeed.  Rebased out that commit, and also rebased on master to avoid conflicts.

2025-02-20 15:37 UTC, philip commented
+1 to committing this.

2025-02-21 19:16 UTC, merged