Document new PDO classes and methods
php/doc-en pull request #4115
Opened 2024-11-20 23:22 UTC by Girgias

Reference: https://wiki.php.net/rfc/pdo_driver_specific_subclasses and https://wiki.php.net/rfc/pdo_driver_specific_parsers

Still needs MySQLi, PGSQL, and OCI8 (although that one is going to be low priority)

@SakiTakamachi can you document, either as inline comments or in a follow-up PR the transaction attributes?

2024-11-21 00:05 UTC, kamil-tekiela requested changes

2024-11-21 00:05 UTC, kamil-tekiela commented on reference/pdo_firebird/pdo/firebird/getapiversion.xml
> +  <refpurpose>Get the API version </refpurpose>
```suggestion
  <refpurpose>Get the API version</refpurpose>
```

2024-11-21 00:05 UTC, kamil-tekiela commented on reference/pdo_firebird/pdo/firebird/getapiversion.xml
> +   Return the FireBird API as an <type>int</type>.
```suggestion
   Returns the FireBird API as an &integer;.
```

2024-11-21 00:05 UTC, kamil-tekiela commented on reference/pdo/pdo/connect.xml
> +  <refpurpose>Description</refpurpose>
Missing description.

2024-11-21 00:05 UTC, kamil-tekiela commented on reference/pdo/pdo/connect.xml
> +   database being connection if it exists,
Is this correct? What does it mean?

2024-11-21 02:56 UTC, SakiTakamachi commented on reference/pdo_firebird/pdo-firebird.xml
> +      </simpara>
```suggestion
      <simpara>
       Set transaction isolation level. , this can be one of <constant>Pdo\Firebird::READ_COMMITTED</constant>,
       <constant>Pdo\Firebird::REPEATABLE_READ</constant> and <constant>Pdo\Firebird::SERIALIZABLE</constant>.
      </simpara>
```

2024-11-21 02:56 UTC, SakiTakamachi commented on reference/pdo_firebird/pdo-firebird.xml
> +      </simpara>
```suggestion
      <simpara>
       Flag to denote the transaction isolation level is READ COMMITTED.
       This flag is the default.
      </simpara>
```

2024-11-21 02:56 UTC, SakiTakamachi commented on reference/pdo_firebird/pdo-firebird.xml
> +      </simpara>
```suggestion
      <simpara>
       Flag to denote the transaction isolation level is REPEATABLE READ.
      </simpara>
```

2024-11-21 02:56 UTC, SakiTakamachi commented on reference/pdo_firebird/pdo-firebird.xml
> +      </simpara>
```suggestion
      <simpara>
       Flag to denote the transaction isolation level is SERIALIZABLE.
      </simpara>
```

2024-11-21 02:56 UTC, SakiTakamachi commented on reference/pdo_firebird/pdo-firebird.xml
> +      </simpara>
```suggestion
      <simpara>
       Allow write operations to the database. Default is true.
      </simpara>
```

2024-11-21 11:22 UTC, Girgias commented on reference/pdo_sqlite/pdo-sqlite.xml
> +       Tests, as necessary.
This is taken from the RFC, @mbeccati can you clarify?

2024-11-21 11:22 UTC, Girgias commented on reference/pdo_sqlite/pdo/sqlite/loadextension.xml
> +  <refpurpose>Description</refpurpose>
It is from a commit that adds stubs. because I don't know what this method does.

2024-11-21 11:23 UTC, Girgias commented on reference/pdo/pdo/connect.xml
> +   database being connection if it exists,
If a class exists for the driver (e.g. mysql) it will return that instead of a generic `PDO` instance.

2024-11-21 11:24 UTC, Girgias commented on reference/pdo_sqlite/pdo/sqlite/createfunction.xml
> +   <acronym>UDF</acronym>, so that it can be called within SQL queries.
I copied this from the existing documentation, but happy to change it.

2024-11-21 16:01 UTC, kamil-tekiela commented on reference/pdo/pdo/connect.xml
> +   database being connection if it exists,
"... subclass for the corresponding PDO driver if it exists ..."

2024-11-22 23:30 UTC, Girgias commented on reference/pdo_sqlite/pdo-sqlite.xml
> +    A concrete <classname>PDO</classname> subclass representing a connection
That it is specific to a database driver

2024-11-22 23:46 UTC, Girgias commented
@sim1984 you are probably the best person to review the FireBird changes, I took some of the wording for the attributes (based on Saki's initial text) from https://ib-aid.com/articles/php-8-4-improvements-when-working-with-modern-firebird-versions

2024-11-23 00:34 UTC, kamil-tekiela commented on reference/pdo_sqlite/pdo-sqlite.xml
> +    A concrete <classname>PDO</classname> subclass representing a connection
I think it would be better without the word "concrete" in all instances here. We could also add at the end: "... representing a connection using the SQLite PDO driver"

2024-11-23 01:52 UTC, Girgias commented on reference/pdo_sqlite/pdo-sqlite.xml
> +    A concrete <classname>PDO</classname> subclass representing a connection
Done.

2024-11-23 01:53 UTC, Girgias commented
@KentarouTakeda could you have a look at the `Pdo\Pgsql` docs?

2024-11-23 06:05 UTC, KentarouTakeda reviewed
@Girgias 
I tried to write as best as I could.

Please note that my use of English and xml syntax may not be very good in some places.

2024-11-23 06:05 UTC, KentarouTakeda commented on reference/pdo_pgsql/pdo/pgsql/setnoticecallback.xml
> +
```suggestion
```

2024-11-23 06:05 UTC, KentarouTakeda commented on reference/pdo_pgsql/pdo/pgsql/setnoticecallback.xml
> +   </simpara>
```suggestion
```

2024-11-24 01:56 UTC, Girgias commented on reference/pdo_pgsql/pdo/pgsql/setnoticecallback.xml
> +  </simpara>
@KentarouTakeda do you have a description for this?

2024-11-24 02:40 UTC, KentarouTakeda commented on reference/pdo_pgsql/pdo/pgsql/setnoticecallback.xml
> +  </simpara>
Sorry, I overlooked it.
```suggestion
  <simpara>
   Set a callback to handle notice and warning messages generated by the backend.
   This includes messages emitted by PostgreSQL itself,
   as well as those raised by user-defined SQL functions using <literal>RAISE</literal>.
   Please note that the actual receipt of these messages
   depends on the backend setting <literal>client_min_messages</literal>.
  </simpara>
```

2024-11-24 07:57 UTC, Girgias commented
@kamil-tekiela can you review the `Pdo\Mysql` docs? (I don't know what the dedicated method does as it is documented no where...)

2024-11-24 08:52 UTC, SakiTakamachi commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +   </simpara>
I'm not Kamil, but...

```suggestion
   <simpara>
    Returns the number of warnings that occurred during the most recent CRUD operation.
   </simpara>
```

2024-11-25 19:33 UTC, kamil-tekiela reviewed
Partial review

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +       Perform direct queries, don't use prepared statements.
Ref. https://github.com/php/php-src/pull/16935

Can you make it say that it's just an alias?

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_IGNORE_SPACE</constant></term>
Lacks note "Can only be used in the <parameter>driver_options</parameter>
        array when constructing a new database handle."

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_FOUND_ROWS</constant></term>
Lacks note "Can only be used in the driver_options
array when constructing a new database handle."

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_SERVER_PUBLIC_KEY</constant></term>
Ref. https://github.com/php/doc-en/issues/1392

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +       TODO, Available since when?
I believe since PHP 5.6 but I am not sure. It's a connection option only. It allows to set the value of `sha256_server_public_key`. You can copy the description from https://www.php.net/manual/en/mysqli.options.php

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_SSL_KEY</constant></term>
Lacks note "Can only be used in the driver_options
array when constructing a new database handle."

Ditto for all SSL options. I wonder if there is a more efficient way than putting a note on each one of them.

2024-11-25 19:33 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +    </itemizedlist>
Copy-pasta? This should be about MySQL.

2024-11-26 02:21 UTC, Girgias commented on reference/pdo_mysql/pdo-mysql.xml
> +    </itemizedlist>
Copied from: https://wiki.php.net/rfc/pdo_driver_specific_parsers

2024-11-26 03:48 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +    </itemizedlist>
Ok, so it's just a matter of replacing "PostgreSQL" with "MySQL"

2024-11-26 03:52 UTC, kamil-tekiela commented on reference/pdo_mysql/constants.xml
> +     (<type>int</type>)
This should be string.

2024-11-26 03:52 UTC, kamil-tekiela commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
I'm pretty sure this should be string too.

2024-11-26 21:08 UTC, Girgias commented on reference/pdo_mysql/pdo-mysql.xml
> +    </itemizedlist>
Ah yes, that I did forget to update, and didn't even see the issue initially :)

2024-11-27 19:38 UTC, kamil-tekiela commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
Hold on, is this documenting the type of the constant or what value the constant takes? Because technically all of these constants are integers, but these options take different arguments, some string and some int.

2024-11-28 11:00 UTC, cmb69 commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
The type of the constant is int; the fact does it is used in e.g `getAttribute()`, and then you get a string, doesn't matter here.

2024-11-28 11:48 UTC, Girgias commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
As @cmb69 said, it is the type of the constant, not what the value of the attribute should be.

2024-11-28 14:15 UTC, kamil-tekiela commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
Ok, that's confusing then. Why does it need to be duplicated here if it's already in reference/pdo_mysql/pdo-mysql.xml 
Should we just remove the types in brackets from this page?

2024-11-28 14:28 UTC, cmb69 commented on reference/pdo_mysql/constants.xml
> +    (<type>int</type>)
It's customary to show the types of consts on the constant pages.

2024-12-01 23:59 UTC, kamil-tekiela requested changes

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +  <refpurpose>Description</refpurpose>
```suggestion
  <refpurpose>Returns the number of warnings from the last executed query</refpurpose>
```

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +  </simpara>
```suggestion
  <simpara>
   Returns the number of warnings from the last executed query.
  </simpara>
```

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +  </simpara>
It would also be a good idea to add a note such as is in https://www.php.net/manual/en/mysqli.warning-count.php

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +   Description.
```suggestion
   Returns an <type>integer</type> representing the number of warnings generated by the last query.
```

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> + </refsect1>
Remove. It doesn't generate any errors. It's only reading internal value.

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> + </refsect1>
I don't think we need this section.

2024-12-01 23:59 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +    Description.
I will try to think of some reasonable example. I see that mysqli doesn't have the best one either.

2024-12-02 18:15 UTC, Girgias commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_SERVER_PUBLIC_KEY</constant></term>
Does something still need to be done for that?

2024-12-02 18:17 UTC, kamil-tekiela commented on reference/pdo_mysql/pdo-mysql.xml
> +     <term><constant>Pdo\Mysql::ATTR_SERVER_PUBLIC_KEY</constant></term>
No, I think once this PR gets merged the issue can be closed.

2024-12-03 16:30 UTC, Girgias commented on reference/pdo_mysql/pdo/mysql/getwarningcount.xml
> +    Description.
Added

2024-12-03 16:45 UTC, merged