add XSLTProcessor::registerPHPFunctionNS and DOMXPath::registerPhpFunctionNS
php/doc-en pull request #4129
Opened 2024-11-22 22:30 UTC by frederikbosch

Hopefully this PR is correct.

I was not able to build the docs locally.

```log
frederik@frederik-laptop:/srv/libraries/php-doc-en$ make
docker run --rm -v .:/var/www/en -w /var/www -u 1000:1000 php/doc-en
configure.php: $Id$
PHP version: 8.2.26

Checking for source directory... 
error: Source directory doesn't exist or can't be written to.
make: *** [Makefile:22: xhtml] Error 1
```

2024-11-22 23:21 UTC, Girgias commented
The doc directory must be `en` and NOT `doc-en`, the build script is very picky about the name for the folder.

2024-11-22 23:24 UTC, Girgias requested changes
XML markup changes, to mimic in the other new file.

2024-11-22 23:24 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +    <varlistentry>
Remove the wrapping para tag it is unnecessary.

2024-11-22 23:24 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +  </para>
New manual code style requires `<simpara>` instead of `<para>` when possible.

2024-11-22 23:24 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +       as parameter to the callback, they are arrays containing the matched dom nodes.
Semantic line breaks
```suggestion
       The PHP function to call when the Xpath function gets called within the Xpath expression.
       When a node list is passed as parameter to the callback,
       they are arrays containing the matched dom nodes.
```

2024-11-22 23:24 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   <example>
No need for the wrapping para tag.

2024-11-22 23:24 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +    <member><methodname>DOMXPath::registerNamespace</methodname></member>
Ditto no wrapping para tag.

2024-11-23 10:12 UTC, nielsdos requested changes
Thanks for tackling this, apart from Girgias's markup comments I also have 2 content-wise comments, but looks mostly good!

2024-11-23 10:12 UTC, nielsdos commented on reference/dom/domxpath/registerphpfunctionns.xml
> +    <title><methodname>DOMXPath::registerPHPFunctions</methodname> with <literal>php:functionString</literal></title>
The title of this example is wrong

2024-11-23 10:12 UTC, nielsdos commented on reference/dom/domxpath/registerphpfunctionns.xml
> +// Register the php: namespace (required)
This comment is wrong

2024-11-25 08:59 UTC, frederikbosch commented
Hopefully I have resolved both your remarks.

2024-11-25 13:54 UTC, Girgias requested changes

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   This method enables the ability to use a PHP function as a namespaced XPath function inside Xpath expressions.
Missing word? Also line break as we usually try to keep lines under 80 char.
```suggestion
   This method enables the ability to use a PHP function as a namespaced XPath function
   inside a Xpath expressions.
```

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   <example>
Still hasn't been addressed.

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The URI of the namespace.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The local function name inside the namespace.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The PHP function to call when the Xpath function gets called within the Xpath expression.
      When a node list is passed as parameter to the callback,
      they are arrays containing the matched dom nodes.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +  </para>
```suggestion
  <simpara>
   &return.void;
  </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The URI of the namespace.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> + <refsect1 role="parameters">
Nit:
```suggestion
 </refsect1>

 <refsect1 role="parameters">
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The local function name inside the namespace.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +     </para>
```suggestion
     <simpara>
      The PHP function to call when the XSL function gets called within the stylesheet.
      When a node list is passed as parameter to the callback,
      the argument becomes an array containing the matched dom nodes.
     </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +  </para>
```suggestion
  <simpara>
   &return.void;
  </simpara>
```

2024-11-25 13:54 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +    <programlisting role="php"><![CDATA[<?php
Ditto, the wrapping `<para>` tag around the `<example>` tag is useless, please remove.

2024-11-25 16:53 UTC, nielsdos commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   This method enables the ability to use a PHP function as a namespaced XPath function inside Xpath expressions.
Actually should be "an XPath" instead of "a Xpath" (mind the a vs an, and capitalization)

2025-02-19 21:18 UTC, nielsdos commented
I'll take over this PR this weekend or so, to move this forward, as not much work is needed anymore to get this to a finished state.

2025-02-20 20:22 UTC, nielsdos approved these changes
Looks good, thanks for this!
I'll leave it open a bit to see if @Girgias still has comments.

2025-02-21 19:28 UTC, Girgias reviewed
Minor final remarks

2025-02-21 19:28 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      The PHP function to call when the Xpath function gets called within the Xpath expression.
Is Xpath capitalized this way? I though the spec calls it "XPath". @nielsdos ?

2025-02-21 19:28 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   <title>Register a namespaced Xpath function and call it from the Xpath expression</title>
Ditto XPath remark

2025-02-21 19:28 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +$xpath->registerPHPFunctionNS('urn:my.ns', 'substring', fn (array $arg1, int $start, int $length) => substr($arg1[0]->textContent, $start, $length));
Ease readability.
```suggestion
$xpath->registerPHPFunctionNS(
    'urn:my.ns',
    'substring',
    fn (array $arg1, int $start, int $length) => substr($arg1[0]->textContent, $start, $length)
);
```

2025-02-21 19:28 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +   <programlisting role="php"><![CDATA[<?php
```suggestion
   <programlisting role="php">
<![CDATA[
<?php
```

2025-02-21 19:28 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> +?>]]></programlisting>
```suggestion
?>
]]>
   </programlisting>
```

2025-02-21 19:29 UTC, Girgias commented on reference/xsl/xsltprocessor/registerphpfunctionns.xml
> + </refsect1>
```suggestion
   </programlisting>
  </example>
 </refsect1>
```

2025-02-21 19:45 UTC, nielsdos commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      The PHP function to call when the Xpath function gets called within the Xpath expression.
Right, it's indeed capitalized XPath in both spec and PHP, good find.

2025-02-21 19:56 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   inside Xpath expressions.
```suggestion
   inside XPath expressions.
```

2025-02-21 19:56 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      The PHP function to call when the Xpath function gets called within the Xpath expression.
```suggestion
      The PHP function to call when the XPath function gets called within the Xpath expression.
```

2025-02-21 19:56 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      they are arrays containing the matched dom nodes.
@nielsdos should this be "DOM nodes"?

2025-02-21 19:56 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +   <title>Register a namespaced Xpath function and call it from the Xpath expression</title>
```suggestion
   <title>Register a namespaced XPath function and call it from the XPath expression</title>
```

2025-02-21 19:57 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      The PHP function to call when the XPath function gets called within the Xpath expression.
```suggestion
      The PHP function to call when the XPath function gets called within the XPath expression.
```

2025-02-21 20:16 UTC, nielsdos commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      they are arrays containing the matched dom nodes.
I missed this question, sorry.
Normally we capitalize DOM yes

2025-02-22 02:19 UTC, Girgias commented on reference/dom/domxpath/registerphpfunctionns.xml
> +      they are arrays containing the matched dom nodes.
```suggestion
      they are arrays containing the matched DOM nodes.
```

2025-02-22 02:19 UTC, Girgias approved these changes

2025-02-22 03:25 UTC, merged