ext/bcmath - Added `bcceil`, `bcfloor`, `bcround` and `bcdivmod`
php/doc-en pull request #4132
Opened 2024-11-23 04:39 UTC by SakiTakamachi

RFC:
https://wiki.php.net/rfc/adding_bcround_bcfloor_bcceil_to_bcmath
https://wiki.php.net/rfc/add_bcdivmod_to_bcmath

I found an error in the existing documentation regarding `bcdiv` and `bcmod`.
But instead of this PR, I'll follow it up with another PR.

Regarding errors/exceptions, I will add everything except `bcdivmod` later.

2024-11-23 10:20 UTC, nielsdos commented
I will wait for reviewing this when the other 2 PRs are reviewed, as some similar markup mistakes are in this PR.

2024-11-23 10:29 UTC, SakiTakamachi commented
done

2024-11-23 10:32 UTC, SakiTakamachi commented
Oh, no, there's more

2024-11-23 12:13 UTC, SakiTakamachi commented
done!

2024-11-24 01:32 UTC, Girgias requested changes

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcceil.xml
> +  </para>
simpara

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcceil.xml
> +     <para>
simpara

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcceil.xml
> +  </para>
```suggestion
  <simpara>
   Returns a BCMath string number representing <parameter>num</parameter> rounded up to the nearest integer.
  </simpara>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcceil.xml
> +   <title><function>ceil</function> example</title>
```suggestion
   <title><function>bcceil</function> example</title>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcdivmod.xml
> +  </para>
```suggestion
  <simpara>
   Get the quotient and remainder of dividing <parameter>num1</parameter> by
   <parameter>num2</parameter>.
  </simpara>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcdivmod.xml
> +     </para>
```suggestion
     <simpara>
      The dividend, as a string.
     </simpara>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcdivmod.xml
> +     </para>
```suggestion
     <simpara>
      The divisor, as a string.
     </simpara>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcdivmod.xml
> +  </para>
```suggestion
  <simpara>
   Returns an indexed <type>array</type> where the first element is the quotient as a <type>string</type>
   and the second element is the remainder as a <type>string</type>.
  </simpara>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcfloor.xml
> + </refsect1>
Adapt the wording from bcceil

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcfloor.xml
> +   <title><function>ceil</function> example</title>
Wrong function name

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +  </para>
simpara

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +   </varlistentry>
Is this taken from `round()` ? If yes, use an XInclude.

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +  </para>
Addapt wording from bcceil

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +   <title><parameter>precision</parameter> examples</title>
```suggestion
   <title>
    Example of using <function>bcround</function> with different <parameter>precision</parameter> values
   </title>
```

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +   <title><parameter>mode</parameter> examples</title>
Similar title change as previous one for precision

2024-11-24 01:32 UTC, Girgias commented on reference/bc/functions/bcround.xml
> +   <title><parameter>mode</parameter> with <parameter>precision</parameter> examples</title>
Ditto

2024-11-24 13:24 UTC, nielsdos requested changes

2024-11-24 13:24 UTC, nielsdos commented on reference/bc/functions/bcceil.xml
> +  <refpurpose>Round arbitrary precision number fractions up</refpurpose>
I find the description very weird sounding, this doesn't really read like a proper sentence. Similar for the other functions.

2024-11-24 13:24 UTC, nielsdos commented on reference/bc/functions/bcceil.xml
> +   Returns a BCMath string number representing <parameter>num</parameter> rounded up to the nearest integer.
```suggestion
   Returns a numeric string representing <parameter>num</parameter> rounded up to the nearest integer.
```

2024-11-24 13:24 UTC, nielsdos commented on reference/bc/functions/bcfloor.xml
> +   Returns a BCMath string number representing <parameter>num</parameter> rounded down to the nearest integer.
```suggestion
   Returns a numeric string representing <parameter>num</parameter> rounded down to the nearest integer.
```

2024-11-24 13:24 UTC, nielsdos commented on reference/bc/functions/bcround.xml
> +   Returns a BCMath string number representing <parameter>num</parameter> rounded to the given precision.
```suggestion
   Returns a numeric string representing <parameter>num</parameter> rounded to the given precision.
```

2024-11-24 13:31 UTC, SakiTakamachi commented on reference/bc/functions/bcceil.xml
> +  <refpurpose>Round arbitrary precision number fractions up</refpurpose>
How about 'Round up the decimal part of an arbitrary precision number' ?

2024-11-24 14:14 UTC, nielsdos commented on reference/bc/functions/bcceil.xml
> +  <refpurpose>Round arbitrary precision number fractions up</refpurpose>
Why not just "Round up arbitrary precision number" ?

2024-11-24 14:31 UTC, nielsdos approved these changes
For me this is fine now

2024-11-24 20:13 UTC, Girgias reviewed
One minor comment about showing the output of examples, but otherwise LGTM

2024-11-24 20:13 UTC, Girgias commented on reference/bc/functions/bcfloor.xml
> +   </programlisting>
I would prefer to use `var_dump()` and show the result of the example via a `<screen>` tag rather than a comment.

2024-11-24 23:09 UTC, SakiTakamachi commented on reference/bc/functions/bcfloor.xml
> +   </programlisting>
Thanks, fixed it in https://github.com/php/doc-en/pull/4132/commits/501f4d9f7eb50509c19a4e979addf73670778916

2024-11-25 13:58 UTC, Girgias approved these changes

2024-11-25 13:59 UTC, merged

2024-11-25 22:15 UTC, SakiTakamachi commented
Thanks!