[PHP 8.4] sockets constant list update
php/doc-en pull request #4154
Opened 2024-11-25 18:44 UTC by devnexen

2024-11-26 00:26 UTC, Girgias requested changes
Please double-check that there are no tab characters used

2024-11-26 00:26 UTC, Girgias commented on reference/sockets/constants.xml
> +     Available as of PHP 8.4.0 (NetBSD only)
Please add a full stop at the end of the "Available as of PHP 8.4.0." for all the constants
```suggestion
     Available as of PHP 8.4.0. (NetBSD only)
```

2024-11-26 00:26 UTC, Girgias commented on reference/sockets/constants.xml
> +     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
Tabs usage?
```suggestion
     Set the port range used for selecting a local port number.
     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
```

2024-11-26 00:26 UTC, Girgias commented on reference/sockets/constants.xml
> +     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
Ditto tabs
```suggestion
     Use the default range of port values.
     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
```

2024-11-26 00:26 UTC, Girgias commented on reference/sockets/constants.xml
> +     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
```suggestion
     Use a low range of port values.
     Available as of PHP 8.4.0 (FreeBSD/NetBSD/OpenBSD only)
```

2024-11-30 10:23 UTC, closed without merging

2024-12-01 12:44 UTC, Girgias commented
Why was this closed?

2024-12-01 12:46 UTC, devnexen commented
I think that was an accident "wrong tab" thing ...

2024-12-01 12:47 UTC, devnexen commented
Reopening