[PHP 8.4] intl changes.
php/doc-en pull request #4160
Opened 2024-11-26 18:22 UTC by devnexen

2024-11-26 18:25 UTC, devnexen commented
for #3872

2024-11-26 19:35 UTC, nielsdos requested changes

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/dateformatter/create.xml
> +       <entry>8.4.0</entry>
Should also be in the error section of the page

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/dateformatter/create.xml
> +         A <classname>Value</classname> is thrown if
```suggestion
         A <exceptionname>ValueError</exceptionname> is thrown if
```

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/numberformatter/create.xml
> +     <row>
Same remarks as for dateformatter

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/dateformatter/create.xml
> +        <para>
Please use simpara

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/resourcebundle/get.xml
> +        <para>
simpara please
Also add this to the error section of the page

2024-11-26 19:35 UTC, nielsdos commented on reference/intl/resourcebundle/get.xml
> +         A <classname>TypeError</classname> is thrown if
Use exceptionname instead of classname in these descriptions

2024-11-26 20:05 UTC, nielsdos commented on reference/intl/dateformatter/create.xml
> +         A <classname>Value</classname> is thrown if
Not addressed yet (notice Value**Error**) and mistake copied in error section (check all places for this mistake)

2024-11-27 18:08 UTC, Girgias requested changes
Thank you, XML markup nits

2024-11-27 18:08 UTC, Girgias commented on reference/intl/dateformatter/create.xml
> +  </para>
```suggestion
  <simpara>
   A <exceptionname>ValueError</exceptionname> is thrown if
   <parameter>locale</parameter> is invalid.
  </simpara>
```

2024-11-27 18:08 UTC, Girgias commented on reference/intl/numberformatter/create.xml
> +  </para>
```suggestion
  <simpara>
   A <exceptionname>ValueError</exceptionname> is thrown if
   <parameter>locale</parameter> is invalid.
  </simpara>
```

2024-11-27 18:08 UTC, Girgias commented on reference/intl/resourcebundle/get.xml
> +  <para>
I don't think we have a consistent style tbh, I have used multiple `<simpara>` tags in general. But I don't mind either style.

2024-11-27 18:08 UTC, Girgias commented on reference/intl/resourcebundle/get.xml
> +   <informaltable>
The wrapping `<para>` tag here is useless.

2024-11-27 18:08 UTC, Girgias commented on reference/intl/resourcebundle/get.xml
>   <refsect1 role="examples">
Nit:
```suggestion
 </refsect1>

 <refsect1 role="examples">
```

2024-11-27 20:45 UTC, nielsdos approved these changes
I don't see problems anymore

2024-11-28 11:34 UTC, merged