ext/bcmath: Correctly modified an existing document
php/doc-en pull request #4163
Opened 2024-11-27 05:37 UTC by SakiTakamachi

Fixed and added exception behavior.
Also added a `<literal>` tag.

2024-11-27 18:12 UTC, Girgias requested changes

2024-11-27 18:12 UTC, Girgias commented on reference/bc/functions/bcmul.xml
> + </refsect1>
Considering how often this is repeated I would use XIncludes to avoid the repetition

2024-11-28 02:12 UTC, SakiTakamachi commented
fixed

2024-11-29 15:24 UTC, Girgias commented
@SakiTakamachi I pushed a bunch of wording fixes and docs fixes which are existing issues, as I wanted to check locally that everything renders somewhat as expected.

2024-11-30 10:26 UTC, nielsdos approved these changes
Small nits,  otherwise ok

2024-11-30 10:26 UTC, nielsdos commented on reference/bc/functions/bcadd.xml
> +     is not a well-formed BCMath numeric string
```suggestion
     is not a well-formed BCMath numeric string.
```

2024-11-30 10:26 UTC, nielsdos commented on reference/bc/functions/bcadd.xml
> +     <parameter>scale</parameter> is outside the valid range
```suggestion
     <parameter>scale</parameter> is outside the valid range.
```

2024-11-30 10:26 UTC, nielsdos commented on reference/bc/functions/bcround.xml
> +    <member><parameter>num</parameter> is not a well-formed BCMath numeric string</member>
```suggestion
    <member><parameter>num</parameter> is not a well-formed BCMath numeric string.</member>
```

2024-11-30 10:26 UTC, nielsdos commented on reference/bc/functions/bcround.xml
> +    <member><parameter>scale</parameter> is outside the valid range</member>
```suggestion
    <member><parameter>scale</parameter> is outside the valid range.</member>
```

2024-12-01 12:48 UTC, Girgias commented on reference/bc/functions/bcmul.xml
> +    Prior to PHP 7.3.0 <function>bcmul</function> may return a result with fewer digits after the
```suggestion
    Prior to PHP 7.3.0, <function>bcmul</function> may return a result with fewer digits after the
```

2024-12-01 12:49 UTC, Girgias commented on language-snippets.ent
> +  </para>
```suggestion
  <simpara>
   This parameter is used to set the number of digits after the decimal place in the result.
   If &null;, it will default to the default scale set with <function>bcscale</function>,
   or fallback to the value of the
   <link linkend="ini.bcmath.scale"><literal>bcmath.scale</literal></link> INI directive.
  </simpara>
```

2024-12-01 12:51 UTC, merged

2024-12-01 16:49 UTC, cmb69 commented
Hmm, the commit breaks `configure` for me (Windows, libxml2 2.10.3), due to "nested" xincludes. bcdivmod xincludes the error section from bcdiv which in turn xincludes the contents of the bcadd error section. The latter xinclude is not resolved here, so validation complains. I don't know whether that is a libxml2 issue, or Windows related, or whether I'm doing something wrong.

2024-12-01 18:30 UTC, leonardolara commented
The same happens for me (Suse Linux, libxml 2.10.3). It is not processing nested xincludes. I processed locally repeating the `$dom->xinclude();` (lines 780-787 in configure.php) and it builds successfully.
However it does not build in Github.

2024-12-01 19:05 UTC, cmb69 commented
Hmm, from https://discourse.gnome.org/t/libxml2-2-11-0-released/15123:

> The XInclude engine has been reworked to properly support nested includes.

Confused.

2024-12-01 19:20 UTC, cmb69 commented
Indeed, works (for me) with libxml2 2.11.9; is our CI running libxml2 2.11, since the [nested includes have been processed properly](https://github.com/php/doc-en/actions/runs/12105605404/job/33750407433)?

> However it does not build in Github.

Well, apparently it does for this repo.

Still, I don't think we can require libxml2 2.11 (even php-src master still supports >= 2.9.4).

2024-12-01 19:25 UTC, leonardolara commented
I meant I could not build the pt_BR repo in Github.
Locally, neither `en` nor 'pt_BR' build correctly.

I've just downgraded to libxml2 2.9.14 to match the repo config, but I get the same errors.

2024-12-02 10:53 UTC, alfsb commented
Just a heads up. I'm doing a *big* change on `cofigure.php`, that touchs XIncludes by `xml:id`s, and, indirectly, in duplicated IDs. It not handles recursive XInclude as now, but it seems necessary anyways. I will push a new version soon, that will delay (again) it's merging. And try to come up for a solution for recursive XIndludes in the following days.

The looping `xinclude()` solves it in all languages that normally builds? (I stopped testing `doc-it` and `doc-ro`, as they appear to be dead for more than six months).

2024-12-02 11:05 UTC, leonardolara commented
I tried a looping `xinclude()` that works for almost all languages that are built normally, except for `ja`, in which case it generates a XPointer issue that didn't exist before. So I gave up for now, it is a little beyond my understanding.

2024-12-02 12:39 UTC, Girgias commented
> Still, I don't think we can require libxml2 2.11 (even php-src master still supports >= 2.9.4).

Why could we not? I don't see really an issue with the doc repo requiring a certain version of libxml, they fix (and break) stuff all the time so needing to support a whole range of versions is going to be impossible.

2024-12-02 12:44 UTC, SakiTakamachi commented
By the way, my local version is 2.9.4, but for some reason there are no problems...

2024-12-02 12:51 UTC, cmb69 commented
@Girgias, libxml2 2.11 is pretty new, so that might break builds for many users. Even [Ubuntu 24.04 ships libxml2 2.9.14 by default](https://launchpad.net/ubuntu/noble/+package/libxml2). And you would have to ask @derickr (or someone else) to update the build machines. Might also be an issue for CHM building.

2024-12-02 12:53 UTC, Girgias commented
It seems the issue is just present in libxml 2.10, if Saki is able to build with 2.9, soooo.

2024-12-02 13:12 UTC, cmb69 commented
From https://github.com/php/doc-en/pull/4163#issuecomment-2510217691:

> I've just downgraded to libxml2 2.9.14 to match the repo config, but I get the same errors.

Apparently, it sometimes works with libxml2 < 2.11, but sometimes it doesn't.

2024-12-02 13:20 UTC, alfsb commented
> Apparently, it sometimes works with libxml2 < 2.11, but sometimes it doesn't.

I opened https://github.com/php/doc-base/pull/194 , that patchs part the problem for translations (it's not related with recursive calls, but with failed XIncludes, that exacerbate the problem). It does *not* include looping over `xinclude()`, but local tests showed this is viable workaround for where libxml is failing to recurse.

2024-12-02 14:11 UTC, alfsb commented
Included on doc-base PR 194 above both fixes: tor recursive XIncludes (all languages) and failing XIncludes (all translations). Let me know it this fixes the two separate problems one go. @SakiTakamachi @cmb69 @leonardolara