Synchronize manual with stubs for PHP 8.4 - part 2
php/doc-en pull request #4178
Opened 2024-11-27 20:13 UTC by kocsismate

Apparently, all the affected mysqli and Phar methods were always returning `true`.

2024-11-28 10:48 UTC, cmb69 approved these changes
Thank you!

2024-11-28 11:39 UTC, Girgias requested changes

2024-11-28 11:39 UTC, Girgias commented on reference/datetime/dateinterval/createfromdatestring.xml
> +  </para>
There is an entity IIRC for procedural return false for failure, which needs to be used.

2024-11-28 11:39 UTC, Girgias commented on reference/datetime/datetime/modify.xml
>    </para>
Ditto procedurally, this still returns false.

2024-11-28 11:39 UTC, Girgias commented on reference/phar/PharFileInfo/delMetadata.xml
>     a phar, the <link linkend="ini.phar.readonly">phar.readonly</link> INI variable
```suggestion
   &return.true.always;
   As with all functionality that modifies the contents of
   a phar, the <link linkend="ini.phar.readonly">phar.readonly</link> INI variable
```

2024-11-28 14:11 UTC, kamil-tekiela approved these changes
The mysqli changes are fine.

2024-11-29 21:46 UTC, kocsismate commented on reference/datetime/dateinterval/createfromdatestring.xml
> +  </para>
Yes, I found it at last

2024-12-01 12:02 UTC, Girgias approved these changes

2024-12-01 12:02 UTC, merged