Synchronize manual with stubs for PHP 8.4 - part 3
php/doc-en pull request #4179
Opened 2024-11-27 20:26 UTC by kocsismate

2024-11-28 10:50 UTC, cmb69 reviewed
Thank you!

2024-11-28 10:50 UTC, cmb69 approved these changes

2024-11-28 11:42 UTC, Girgias requested changes

2024-11-28 11:42 UTC, Girgias commented on reference/dir/directory.xml
> +      </row>
Incorrect this is part of https://wiki.php.net/rfc/directory-opaque-object which is PHP 8.5.

Please use a worktree and the stubs from PHP-8.4 to do these changes.

2024-11-28 11:42 UTC, Girgias commented on reference/zip/ziparchive.xml
> +    </fieldsynopsis>
This needs a description below, also available as of PHP 8.4.0. (refer back to the issue tracking these changes)

2024-11-28 11:42 UTC, Girgias commented on reference/soap/soapclient.xml
> +    <varlistentry xml:id="soapclient.props.soap-fault">
Not sure if those soap changes are correct, I'm pretty sure you are breaking links with this rn.

2024-11-28 13:44 UTC, kocsismate commented on reference/zip/ziparchive.xml
> +    </fieldsynopsis>
The description has already been added previously :)

2024-11-28 13:50 UTC, kocsismate commented on reference/dir/directory.xml
> +      </row>
Ah, I forgot that this was voted for PHP 8.5. Problem with using an older branch when generating the manual pages is that gen_stub.php usually receives improvements in master only, therefore I usually just disregard the stub changes that are not yet relevant.

2024-11-28 13:50 UTC, kocsismate commented on reference/zip/ziparchive.xml
> +    </fieldsynopsis>
https://www.php.net/manual/en/zip.constants.php#ziparchive.constants.er-truncated-zip for reference

2024-11-28 15:57 UTC, Girgias commented on reference/zip/ziparchive.xml
> +    </fieldsynopsis>
Okay so this item is actually done, surprising.

2024-11-28 15:58 UTC, Girgias commented on reference/soap/soapclient.xml
> +    <varlistentry xml:id="soapclient.props.soap-fault">
Can you check if those IDs are used in a `linken` attribute or not? But in the same vein, you should remove the single hyphen from the constants below.

2024-11-28 15:59 UTC, Girgias commented on reference/dir/directory.xml
> +      </row>
But you could use the stub files from PHP-8.4 with master gen_stub, no?

2024-11-29 21:58 UTC, kocsismate commented on reference/soap/soapclient.xml
> +    <varlistentry xml:id="soapclient.props.soap-fault">
I found no collision. In the same time, I removed the leading single hyphens.

2024-12-01 12:18 UTC, Girgias approved these changes

2024-12-01 12:18 UTC, merged