Synchronize manual with stubs for PHP 8.4 - part 4
php/doc-en pull request #4186
Opened 2024-11-28 22:57 UTC by kocsismate

2024-11-29 00:01 UTC, cmb69 reviewed
Thank you! Looks good to me, besides the comment below.

2024-11-29 07:59 UTC, nielsdos reviewed
Ok for me, but please fix cmb's comment and CI

2024-11-29 14:30 UTC, Girgias requested changes
A lot of text is being repeated (even if it was the case previously) where it would be better to use an XML entity or XIncludes.

The 2 things I notices are for the statement param, and the return an ODBC object or false on failure.

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
Is this true? If yes it should still be documented (which doesn't seem to be the case yet)

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-fetch-array.xml
>   </refsect1>
The `$statement` param still mentions resource, either create a new entity or use an XInclude as I imagine this is going to be repeated quite a bit.

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-fetch-into.xml
> +       <parameter>row</parameter> is nullable now.
```suggestion
       <parameter>row</parameter> is now nullable.
```

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-fetch-array.xml
> +       <parameter>row</parameter> is nullable now.
```suggestion
       <parameter>row</parameter> is now nullable.
```

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-fetch-object.xml
> +       <parameter>row</parameter> is nullable now.
```suggestion
       <parameter>row</parameter> is now nullable.
```

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-field-len.xml
>   <refsect1 role="seealso">
Nit:
```suggestion
 </refsect1>

 <refsect1 role="seealso">
```

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-foreignkeys.xml
>    </para>
This is also repeated quite often, and feels like it can be an entity too.

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-gettypeinfo.xml
>    </para>
Use a new entity here, as this repeated a lot

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-num-rows.xml
>   <refsect1 role="notes">
Nit:
```suggestion
 </refsect1>

 <refsect1 role="changelog">
  &reftitle.changelog;
  <informaltable>
   <tgroup cols="2">
    <thead>
     <row>
      <entry>&Version;</entry>
      <entry>&Description;</entry>
     </row>
    </thead>
    <tbody>
     &odbc.changelog.result-param;
    </tbody>
   </tgroup>
  </informaltable>
 </refsect1>

 <refsect1 role="notes">
```

2024-11-29 14:30 UTC, Girgias commented on reference/uodbc/functions/odbc-setoption.xml
> +     </row>
Can't you use `&odbc.changelog.connection-param;` ?

2024-11-29 14:31 UTC, Girgias commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
If it is true, it is fine to move this to a new issue and follow-up PR.

2024-11-29 22:04 UTC, kocsismate commented on reference/uodbc/functions/odbc-result.xml
> +   <methodparam><type>Odbc\Result</type><parameter>statement</parameter></methodparam>
Yes, even though I tried to cleanup all the mentions of `resource` within the manual for ODBC, a few of them remained. I'll remove them with my latest commit.

2024-11-29 22:13 UTC, kocsismate commented on reference/uodbc/functions/odbc-fetch-into.xml
> +       <parameter>row</parameter> is nullable now.
Is this the preferred way to phase this? Somehow is nullable now has a bit more usages, so I'm a bit hesitant

2024-11-30 08:51 UTC, kocsismate commented on reference/uodbc/functions/odbc-setoption.xml
> +     </row>
Hm, no, because it has a `Odbc\Connection|Odbc\Result` param type

2024-12-01 12:05 UTC, Girgias commented on reference/uodbc/functions/odbc-fetch-into.xml
> +       <parameter>row</parameter> is nullable now.
That's odd, "is nullable now" is very odd English. In any case this would be better handled with PIs.... need to get round to that...

2024-12-01 12:12 UTC, Girgias reviewed
Mostly good, still some questions about the existing docs.

2024-12-01 12:12 UTC, Girgias commented on reference/uodbc/functions/odbc-binmode.xml
>         If <parameter>statement</parameter> is <literal>0</literal>, the
I don't understand what the paragraph here even means

2024-12-01 12:12 UTC, Girgias commented on reference/uodbc/setup.xml
> +   This extension defined two resource types until PHP 8.4: an ODBC connection identifier
```suggestion
   Prior to PHP 8.4.0, this extension defined two resource types: an ODBC connection identifier
```

2024-12-01 12:35 UTC, cmb69 commented on reference/uodbc/functions/odbc-binmode.xml
>         If <parameter>statement</parameter> is <literal>0</literal>, the
This is no longer relevant as of PHP 7.0.0. Previously, passing `0` as `$statement` would change the defaults:

https://heap.space/xref/PHP-5.6/ext/odbc/php_odbc.c?r=82637e81#926

We should remove this paragraph.

2024-12-02 12:51 UTC, Girgias commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
Only remaining comment is this one.

2024-12-02 13:32 UTC, kocsismate commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
I found it! Actually, I removed it ^^ https://github.com/php/php-src/commit/9b50fd2626277296b4ad47a508fbc9015eb01d91#diff-b491d14be46a424b441ce330165556a626fdb90a52cfc64f8553945bd28a3e2fR395

2024-12-02 13:33 UTC, kocsismate commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
It was unused... Does it really have to be documented in this case?

2024-12-02 13:52 UTC, Girgias commented on reference/uodbc/functions/odbc-execute.xml
> +     </row>
Then please change the changelog to something like:

```suggestion
     <row>
      <entry>8.0.0</entry>
      <entry>
       The unused <parameter>flags</parameter> parameter was removed.
      </entry>
     </row>
```

As otherwise there is lack of information of what this param did (or in this case did not)

2024-12-02 13:55 UTC, Girgias approved these changes

2024-12-02 14:40 UTC, merged