ext/bcmath: `BcMath\Number` class
php/doc-en pull request #4187
Opened 2024-11-29 02:04 UTC by SakiTakamachi

RFCs:
https://wiki.php.net/rfc/support_object_type_in_bcmath
https://wiki.php.net/rfc/fix_up_bcmath_number_class

stub:
https://github.com/php/php-src/blob/master/ext/bcmath/bcmath.stub.php

2024-11-29 14:49 UTC, Girgias requested changes
Partial review as there is already a bunch that needs fixing across the board.

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +   </para>
```suggestion
   <simpara>
    A class for an arbitrary precision number.
    These objects support overloaded
    <link linkend="language.operators.arithmetic">arithmetic</link> and
    <link linkend="language.operators.comparison">comparison</link> operators.
   </simpara>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +   </note>
Also don't use `<parameter>` for an INI setting but literal with a link tag to link to it.
```suggestion
   <note>
    <simpara>
     This class is not affected by <parameter>bcmath.scale</parameter> in &php.ini;.
    </simpara>
   </note>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +     </listitem>
```suggestion
      <simpara>
       The scale value currently set on the object.
      </simpara>
     </listitem>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +     </listitem>
```suggestion
      <simpara>
       A string representation of an arbitrary precision number.
      </simpara>
     </listitem>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +    </simpara>
```suggestion
    <simpara>
     The behavior of an overloaded operator is that of the corresponding method.
    </simpara>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> +
Please do not add new refsects to methods. This behaviour should be described on the class page.

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/compare.xml
> +   this object is larger than the <parameter>num</parameter>, <literal>-1</literal> otherwise.
```suggestion
   Returns <literal>0</literal> if the two numbers are equal,
   <literal>1</literal> if <varname>$this</varname> is greater than <parameter>num</parameter>,
   <literal>-1</literal> otherwise.
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/construct.xml
> +      The <property>BcMath\Number::scale</property> is automatically set by parsing the string.
```suggestion
      An <type>int</type> or <type>string</type> value.
      If <parameter>num</parameter> is a  <type>int</type>,
      the <property>BcMath\Number::scale</property> is always set to <literal>0</literal>.
      If <parameter>num</parameter> is a <type>string</type>, it must be a valid number,
      and the <property>BcMath\Number::scale</property> is automatically set by parsing the string.
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> + </refsect1>
This is useless
```suggestion
  </simpara>
 </refsect1>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> + </refsect1>
This is useless/implied anyway.
```suggestion
  </para>
 </refsect1>
```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/tostring.xml
> +
```suggestion
 <refsect1 role="parameters">
  &reftitle.parameters;
  &no.function.parameters;
 </refsect1>

```

2024-11-29 14:49 UTC, Girgias commented on reference/bc/bcmath/number/sub.xml
> +    <classname>BcMath\Number</classname> can perform subtraction using operators. The calculation with
Ditto no new refsects.

2024-11-29 14:58 UTC, SakiTakamachi commented on reference/bc/bcmath/number/add.xml
> +
@Girgias 
Hmm...
This behavior varies by method, should it be mentioned on the class page?
I don't mind placing it under other sections, so it would be nice if I could explain it on the method page...

2024-11-29 15:25 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> +
For which methods does this not apply?

2024-11-29 16:17 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> +
I would describe the auto scaling concept on the class page and then say how it is used in the return value section for the methods.

2024-12-02 04:08 UTC, SakiTakamachi commented
@Girgias 
Fixed!

2024-12-02 04:24 UTC, SakiTakamachi commented
Hmm. I don't understand why CI turns red...
No problems occur in my local

2024-12-10 16:17 UTC, Girgias reviewed
Some comments, the only concern is with the XIncludes, where I think waiting for @alfsb's PR to be merged might make more sense.

2024-12-10 16:17 UTC, Girgias commented on language-snippets.ent
> +result will be set automatically.</simpara></listitem></varlistentry>'>
No need to put this on a single line.
```suggestion
<!ENTITY bc.number.scale.description '<varlistentry xmlns="http://docbook.org/ns/docbook">
 <term>
  <parameter>scale</parameter>
 </term>
 <listitem>
  <simpara>
   <parameter>scale</parameter> explicitly specified for calculation results.
   If &null;, the <parameter>scale</parameter> of the calculation result will be set automatically.
  </simpara>
 </listitem>
</varlistentry>'>
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +     in &php.ini;.
```suggestion
     This class is not affected by the
     <link linkend="ini.bcmath.scale">bcmath.scale</link>
     INI directive set in &php.ini;.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +     <parameter>scale</parameter> parameter in the corresponding method.
```suggestion
     <parameter>scale</parameter> parameter on the corresponding method.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath.number.xml
> +       specify the <parameter>scale</parameter> parameter in the calculation method.
```suggestion
       For objects resulting from calculations, this value is automatically computed and set,
       unless the <parameter>scale</parameter> parameter was set in the calculation method.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/compare.xml
> +   This method behaves similar to the spaceship operator.
Add a link to it?

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/construct.xml
> +      If <parameter>num</parameter> is a <type>string</type>, it must be a valid number,
Mayb:
```suggestion
      If <parameter>num</parameter> is a <type>string</type>, it must be a valid numeric string,
```
And add a link?

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/div.xml
> +   Expansion is done only as needed, up to a maximum of +<literal>10</literal>.
```suggestion
   Expansion is done only as needed, up to a maximum of <literal>+10</literal>.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/div.xml
> +    +<literal>10</literal>.
Ditto

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/div.xml
> +    BcMath\Number::scale</property> is reduced by that amount.
```suggestion
    A <literal>0</literal> at the end of the result is considered not to need expansion, so the
    <property>BcMath\Number::scale</property> is reduced by that amount.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/div.xml
> +    </property> before expansion.
```suggestion
    The <property>BcMath\Number::scale</property> will never be less than the
    <property>BcMath\Number::scale</property> before expansion.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/div.xml
> +   <programlisting role="php">
Move the example to the corresponding section, if you want to point it out in the return value you can add an xml:id and link tag

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/mod.xml
> +  <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('bcmath-number.div')/db:refsect1[@role='errors']/db:simpara[1])" />
It might be better to wait for https://github.com/php/doc-base/pull/198 to be merged than using XIncludes with indices

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/pow.xml
> +       but is at least <literal>-2147483648</literal> to <literal>2147483647</literal>.
```suggestion
       but it is at least <literal>-2147483648</literal> to <literal>2147483647</literal>.
```

2024-12-10 16:17 UTC, Girgias commented on reference/bc/bcmath/number/powmod.xml
> +       The exponent, as an non-negative and integral (i.e. the scale has to be zero).
Use the same wording as in the `pow` method?

2024-12-16 12:16 UTC, alfsb commented on reference/bc/bcmath/number/mod.xml
> +  <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('bcmath-number.div')/db:refsect1[@role='errors']/db:simpara[1])" />
It was merged a few days ago, and I think there are already published manuals under it. So it's probably safe to start using it now.

2024-12-16 15:25 UTC, SakiTakamachi commented on reference/bc/bcmath/number/powmod.xml
> +       The exponent, as an non-negative and integral (i.e. the scale has to be zero).
No, `pow` accepts the negative exponent

2024-12-16 15:30 UTC, SakiTakamachi commented on reference/bc/bcmath/number/construct.xml
> +      If <parameter>num</parameter> is a <type>string</type>, it must be a valid number,
Do you mean this?
https://www.php.net/manual/en/language.types.numeric-strings.php

If so, BCMath does not accept scientific notation, so it may be inappropriate.
(This is one of the things I would like to improve)

2024-12-16 16:03 UTC, SakiTakamachi commented on language-snippets.ent
> +result will be set automatically.</simpara></listitem></varlistentry>'>
Fixed in https://github.com/php/doc-en/pull/4187/commits/60a76f1a190876f5457ef85b89dfd5bea1cc8e72

2024-12-16 16:03 UTC, SakiTakamachi commented on reference/bc/bcmath/number/compare.xml
> +   This method behaves similar to the spaceship operator.
Added a link in https://github.com/php/doc-en/pull/4187/commits/10b03c470f47d0d444bbba07a779a8060b4a439b

2024-12-16 16:04 UTC, SakiTakamachi commented on reference/bc/bcmath/number/div.xml
> +   Expansion is done only as needed, up to a maximum of +<literal>10</literal>.
Fixed in https://github.com/php/doc-en/pull/4187/commits/6411e68fc0e4d058c87aa8982624e4272ae5d1ab

2024-12-16 16:04 UTC, SakiTakamachi commented on reference/bc/bcmath/number/div.xml
> +    +<literal>10</literal>.
Ditto, fixed in https://github.com/php/doc-en/pull/4187/commits/6411e68fc0e4d058c87aa8982624e4272ae5d1ab

2024-12-16 16:04 UTC, SakiTakamachi commented on reference/bc/bcmath/number/div.xml
> +   <programlisting role="php">
Moved in https://github.com/php/doc-en/pull/4187/commits/57d7592159e523b08942ec0c1ff98a0c1a740799

2024-12-16 16:34 UTC, alfsb commented on reference/bc/bcmath/number/add.xml
> +   <varlistentry>
This `<varlistentry>` can receive an xml:id attribute like "bcmath-number.add..parameters.scale" (see https://github.com/alfsb/doc-base/blob/master/docs/structure.md#xmlid-structure), and so...

2024-12-16 16:34 UTC, alfsb commented on reference/bc/bcmath/number/div.xml
> +   <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('bcmath-number.add')/db:refsect1[@role='parameters']/descendant::db:varlistentry[2])" />
... so any XInclude from there can be a simple:
```
<xi:include xpointer="bcmath-number.add..parameters.scale"/>
```

2024-12-16 16:35 UTC, SakiTakamachi commented on reference/bc/bcmath/number/add.xml
> +   <varlistentry>
Indeed!

2024-12-27 04:15 UTC, SakiTakamachi commented
I thought I'd commented, but it seems I didn't....

I've fixed everything that needed to be fixed.

2025-01-14 12:47 UTC, Girgias commented on reference/bc/bcmath/number/add.xml
> +   <varlistentry>
Seems like this hasn't been done?

2025-01-14 12:48 UTC, Girgias approved these changes
I think the structural IDs and XInclude stuff can wait for a follow-up

2025-01-14 12:49 UTC, merged

2025-01-29 08:36 UTC, SakiTakamachi commented on reference/bc/bcmath/number/add.xml
> +   <varlistentry>
I forgot it...