[PHP 8.3] `opcache.preload_user` is not required when run as root
php/doc-en pull request #4231
Opened 2024-12-03 15:58 UTC by alexandre-daubois

Part of #2796

2024-12-04 16:54 UTC, arnaud-lb approved these changes
Thank you!

2024-12-04 20:11 UTC, jimwins requested changes

2024-12-04 20:11 UTC, jimwins commented on reference/opcache/ini.xml
> +        by the preloading to be set when running as root.
```suggestion
        As of PHP 8.3.0, this directive does not need to be set in order to allow preloading while
        running as root when using the &cli.sapi; or <link linkend="book.phpdb">phpdbg SAPI</link>.
```

Maybe we don't even need to bump this out as a `<note>` but just add the sentence to the preceding paragraph.

2024-12-05 18:11 UTC, jimwins approved these changes

2024-12-05 18:11 UTC, jimwins commented on reference/opcache/ini.xml
> +      <link linkend="book.phpdb">phpdbg SAPI</link>.
You should start the sentence on a line of its own. (It's a convention called "[semantic line breaks](https://sembr.org/)" that should help with keeping down formatting churn for translations.)

LGTM with that change.

2024-12-06 08:44 UTC, alexandre-daubois commented on reference/opcache/ini.xml
> +      <link linkend="book.phpdb">phpdbg SAPI</link>.
I wasn't aware this had a name. Thank you Jim, it's updated!

2024-12-06 20:42 UTC, merged