Adds a note about hooks + constructor property promotion
php/doc-en pull request #4264
Opened 2024-12-06 14:15 UTC by weierophinney

Per a conversation with @crell, added a note to detail behavior of hooks
when the set hook allows more types than the property, and is used with
constructor property promotion.

2024-12-06 18:17 UTC, kamil-tekiela commented on language/oop5/property-hooks.xml
> +    as that is the type associated with the property.
Did you mean "parameter" instead of "property"

2024-12-06 18:18 UTC, kamil-tekiela commented on language/oop5/property-hooks.xml
> +    If you need to allow this kind of behavior from the constructor, you
Why is this a separate paragraph?

2024-12-06 21:25 UTC, Girgias requested changes

2024-12-06 21:25 UTC, Girgias commented on language/oop5/property-hooks.xml
> +    regardless of what the <literal>set</literal> hook might allow.
Link on its own line
```suggestion
    Hooks can be defined when using
    <link linkend="language.oop5.decon.constructor.promotion">constructor property promotion</link>.
    However, when doing so, values provided
    to the constructor must match the type associated with the property,
    regardless of what the <literal>set</literal> hook might allow.
```

2024-12-06 21:25 UTC, Girgias commented on language/oop5/property-hooks.xml
> +    values, but the constructor will only allow <literal>DateTimeInterface<literal>,
```suggestion
    allow either <type>string</type> or <interfacename>DateTimeInterface</interfacename>
    values, but the constructor will only allow <interfacename>DateTimeInterface<interfacename>,
```

2024-12-06 21:25 UTC, Girgias commented on language/oop5/property-hooks.xml
> +    If you need to allow this kind of behavior from the constructor, you
The manual style guide bans personalization (i.e. usage of "you").

2024-12-11 16:51 UTC, weierophinney commented on language/oop5/property-hooks.xml
> +    as that is the type associated with the property.
That's the crux of the problem: it's both.

The property has a defined type of `DateTimeInterface`, but it's _set_ hook allows either string or `DateTimeInterface`. Because it's defined using constructor property promotion, the property type is used for the parameter type, regardless of what the set hook allows.

2024-12-11 16:51 UTC, weierophinney commented on language/oop5/property-hooks.xml
> +    If you need to allow this kind of behavior from the constructor, you
To call out the action needed by the developer.

2024-12-11 16:55 UTC, weierophinney commented on language/oop5/property-hooks.xml
> +    If you need to allow this kind of behavior from the constructor, you
Fixed

2024-12-11 16:58 UTC, weierophinney commented on language/oop5/property-hooks.xml
> +    as that is the type associated with the property.
I've pushed an update to make this more clear.

2024-12-11 19:16 UTC, kamil-tekiela commented on language/oop5/property-hooks.xml
> +    If you need to allow this kind of behavior from the constructor, you
Well, there should be no "you" there to begin with. It's also a continuation of the previous thought so it should be in the same paragraph.

2024-12-12 03:47 UTC, Crell commented
The text looks good to me, but there's some linting issues.  Once those are resolved I think we can merge this.

2024-12-12 16:03 UTC, weierophinney commented
I _think_ I've resolved the linting issues, but the build chain does not work currently (I get errors on `make` detailing `detected dubious ownership in repository at '/var/www/doc-base'`). Will need somebody to approve the workflow to validate.

2024-12-13 17:45 UTC, Crell commented
All clear now.  @Girgias do you want to clear your change request and merge?

2024-12-13 18:04 UTC, Girgias approved these changes

2024-12-13 18:05 UTC, merged