Document touch() doesn't clear the stat cache.
php/doc-en pull request #4301
Opened 2024-12-13 04:48 UTC by Crell

Thanks to @derickr for pointing this out to me.  It drove me batty for days. :smile:

2024-12-13 11:15 UTC, TimWolla requested changes
This is not unique about `touch()`. None of the file operations clear the stat cache:

```
<?php
var_dump(filemtime('/tmp/foo.txt'), filesize('/tmp/foo.txt'));
file_put_contents('/tmp/foo.txt', str_repeat('x', random_int(0, 999)));
clearstatcache();
var_dump(filemtime('/tmp/foo.txt'), filesize('/tmp/foo.txt'));
```

2024-12-13 17:41 UTC, Crell commented
Seems like we should add the same warning to other functions, then.  Is it worth making an entity out of it, or just copy-paste-tweak?

2024-12-13 18:15 UTC, Girgias commented
We already have the `note.clearstatcache` entity. Is that insufficient?

2024-12-13 18:15 UTC, Girgias commented on reference/filesystem/functions/touch.xml
> +  </para>
```suggestion
  &reftitle.seealso;
  <simplelist>
   <member><function>clearstatcache</function></member>
   <member><function>fileatime</function></member>
   <member><function>filemtime</function></member>
  </simplelist>
```

2024-12-14 04:47 UTC, Crell commented
What is insufficient is my awareness that entity already exists. :smile: Switched to using that, and added `touch` to the list on the `clearstatcache` page, which was missing.

2024-12-14 08:58 UTC, TimWolla commented on reference/filesystem/functions/clearstatcache.xml
> +   <function>touch</function>.
This change is wrong. This list lists the functions that _read_ from the stat cache. `touch()` is a _setter_.

2024-12-14 09:01 UTC, TimWolla commented on reference/filesystem/functions/touch.xml
> +  &note.clearstatcache;
And likewise is this change wrong.

2024-12-14 09:01 UTC, TimWolla commented on reference/filesystem/functions/touch.xml
> +  &reftitle.seealso;
This should probably list `filemtime` first, because the mtime is the relevant field that is modified by `touch`.

2024-12-16 04:36 UTC, Crell commented on reference/filesystem/functions/touch.xml
> +  &reftitle.seealso;
touch can modify both properties, so I listed them in alphabetical order.

2024-12-16 04:38 UTC, Crell commented on reference/filesystem/functions/touch.xml
> +  &note.clearstatcache;
Then do we need a new entity for statcache impacting write functions?  Because the root issue is I didn't realize touch didn't reset the cache, so couldn't understand why my touch() call didn't seem to do anything.  So I want *something* on the touch page to indicate that.  You and @Girgias figure out what you want there, I've already made two proposals and both of them someone has objected to.

2024-12-16 04:39 UTC, Crell commented on reference/filesystem/functions/clearstatcache.xml
> +   <function>touch</function>.
The description says nothing about read/  It just says "Affected."

2024-12-16 08:38 UTC, TimWolla commented on reference/filesystem/functions/clearstatcache.xml
> +   <function>touch</function>.
The context is:

> When you use stat(), lstat(), or any of the other functions listed in the affected functions list (below), PHP caches the information those functions return in order to provide faster performance.

`touch()` is not an affected function, because it does not interact with the stat cache at all. It does not (need to) know about it.

2024-12-16 08:43 UTC, TimWolla commented on reference/filesystem/functions/touch.xml
> +  &note.clearstatcache;
> Then do we need a new entity for statcache impacting write functions?

None of them impact the stat*cache* (except for `unlink()`, which automatically clears it according to the manual). But virtually all of them impact the stat*data*, because writes implicitly affect the mtime (and usually also the file size).

Note that `exec()` and friends might also affect the stat*data*, because you could `exec('touch foo.txt')`. `Dom\HTMLDocument::saveHtml()` does as well.

I do not see a value-add in adding a reference to the stat*cache* to every function that possibly affects the stat*data* and as far as I can tell all the functions reading from the statcache have the note already.

2026-08-28 12:03 UTC, lacatoire commented
Closing as obsolete

2026-08-28 12:03 UTC, closed without merging