Clarify that Exception::getPrevious may return a Throwable
php/doc-en pull request #463
Opened 2021-02-25 15:21 UTC by M1ke

Spotted this when using PhpStorm's documentation (which copies the PHP docs) which incorrectly typehints an Exception - use of this as Exception could cause a TypeError if a non-Exception Throwable is returned. The definitions here for return params of this method are correct so its just the top line description that needs to change.

2021-02-25 15:57 UTC, Girgias requested changes

2021-02-25 15:57 UTC, Girgias commented on language/predefined/exception/getprevious.xml
> +   Returns previous throwable (which may be an exception or error, passed as the third parameter of <methodname>Exception::__construct</methodname>).
```suggestion
   Returns previous <classname>Throwable</classname> (which may be an <classname>Exception</classname> or <classname>Error</classname, passed as the third parameter of <methodname>Exception::__construct</methodname>).
```

Also can you add a line break in that line so it's less than 80 characters? (it's not a hard rule but helps with looking at diffs in a terminal)

2021-02-25 16:03 UTC, cmb69 commented on language/predefined/exception/getprevious.xml
> +   Returns previous throwable (which may be an exception or error, passed as the third parameter of <methodname>Exception::__construct</methodname>).
IMO there's no need to explicitly tell that a Throwable is an Exception or Error, here.

2021-03-23 13:07 UTC, cmb69 commented
Thank you for the PR. I'm going to apply a slightly modified variant.

2021-03-23 13:07 UTC, closed without merging