[80766] Add changelog about defining custom assert
php/doc-en pull request #473
Opened 2021-03-04 18:45 UTC by deleugpn

Added changelog notes to `assert` about it no longer being possible to declare a custom function.

2021-03-04 22:34 UTC, Girgias requested changes

2021-03-04 22:34 UTC, Girgias commented on reference/info/functions/assert.xml
> +       <entry>8.0</entry>
```suggestion
       <entry>8.0.0</entry>
```

2021-03-10 20:49 UTC, afilina commented
I'm not sure what you mean by "Defining a custom assert function". If you mean using a custom handler, then there is no deprecation warning in 7.3.0: https://3v4l.org/a3QB8

There is a deprecation warning for calling `assert` with a string argument though, maybe that's what you meant in the second changelog? https://3v4l.org/maNfU

2021-03-10 21:16 UTC, deleugpn commented
By "defining a custom assert function" I mean defining your own assert function.

https://3v4l.org/vlNfn

2021-03-10 21:58 UTC, cmb69 commented
Defining a custom assert() function in the global namespace never worked, see https://3v4l.org/vlNfn (normal PHP behavior, not to allow redefinition functions). The deprecation/prohibition is actually about custom assert() functions in namespaces, see https://3v4l.org/XTtAh. Could you please clarify that in the changelog entries?

2021-03-18 23:59 UTC, cmb69 requested changes
Please address my comment above. :)

2021-04-14 11:27 UTC, cmb69 commented
I'm closing this in favor of #526.

2021-04-14 11:27 UTC, closed without merging