[80538] Shorthand syntax for array destruction
php/doc-en pull request #477
Opened 2021-03-04 23:04 UTC by deleugpn

This pull request updates the return value documentation for functions to reflect newer syntax provided by PHP as reported in https://bugs.php.net/bug.php?id=80538

2021-03-04 23:21 UTC, Girgias commented on language/functions.xml
> +// For PHP 7.0 or lower
This comment doesn't make much sense, we don't document PHP 5 any more, so something more along the way of this being a "functional" (by using a function-style construct) way is probably better.

2021-03-08 15:33 UTC, cmb69 commented on language/functions.xml
> +// For PHP 7.0 or lower
Array destructoring is only available as of PHP 7.1.0, though, so it makes sense to mention that here. :)

2021-03-08 15:38 UTC, deleugpn commented on language/functions.xml
> +// For PHP 7.0 or lower
That was precisely my intention - to mention an alternative for versions that don't have Array destruction yet.

2021-03-08 15:44 UTC, cmb69 commented on language/functions.xml
> +// For PHP 7.0 or lower
The usual wording in the manual is `prior to PHP 7.1.0` (or `as of PHP 7.1.0`), though.

2021-07-17 13:03 UTC, kamil-tekiela requested changes

2021-07-17 13:03 UTC, kamil-tekiela commented on language/functions.xml
> +// Array destruction will collect each member of the array individually
```suggestion
// Array destructuring will collect each member of the array individually
```

2021-08-17 14:41 UTC, kamil-tekiela approved these changes
LGTM

2021-08-17 16:10 UTC, merged