Stringable
php/doc-en pull request #478
Opened 2021-03-04 23:14 UTC by Crell

I think that covers it, but please make sure I didn't miss a step...

2021-03-08 15:28 UTC, cmb69 reviewed
Thank you! I think it is okay, but consider my comments.

2021-03-08 15:28 UTC, cmb69 commented on language/predefined/stringable.xml
> +    The <classname>Stringable</classname> interface denotes an object as
nit: 
```suggestion
    The <classname>Stringable</classname> interface denotes a class as
```

2021-03-08 15:28 UTC, cmb69 commented on language/predefined/stringable.xml
> +    </xi:include>
I think this will yield warnings (that's a known issue), since there is no constructor-/methodsysnopsis, so better comment these lines out.

2021-03-08 15:28 UTC, cmb69 commented on language/predefined/stringable.xml
> +?>
Maybe, just maybe, extend the example to show the use of `string|Stringable`?

2021-03-08 15:59 UTC, cmb69 approved these changes

2021-03-08 20:19 UTC, cmb69 commented on language/predefined/stringable.xml
> + &language.predefined.stringable.tostring;
Did you forget to push this file?

2021-03-08 21:47 UTC, cmb69 requested changes
Besides the missing stringable/tostring.xml, there are more issues:

- commenting out the xi:includes accidentially commented out the `</classsynopsis>` tag
- the stringable page needs to be added to languages/predefined/interfaces.xml (and then the methodsynopses should be included again (i.e. only comment out the contructorsysnopses)
- there should be an entry in languages/predefined/versions.xml

Could you please take a look, @Crell?

2021-04-01 21:25 UTC, cmb69 approved these changes

2021-04-01 21:26 UTC, merged

2021-11-10 17:53 UTC, jmikola commented
@cmb69: I just came across https://www.php.net/stringable and looking for a reason that the `__toString()` method was not documented as an interface method led me back to this PR. Was that intentional?

I noted you referred to "commenting out the xi:includes" in your previous comment but it still wasn't clear to me what you meant by that, as I didn't find discussion about commenting that out in any previously resolved  comments.

2021-11-10 18:08 UTC, cmb69 commented
> […] and looking for a reason that the __toString() method was not documented as an interface method […]

That documentation needs yet to be written (the [PR has a respective comment](https://github.com/php/doc-en/pull/478/files#diff-aca9a13102a64cc8a3a838403b3537cfe717134b6bd449416f396b4ed85e7790R45)); until this file is in place, the `<xi:include>` should be commented out, because otherwise the build system shows an error message (this should be fixed at some point, if possible). The linking to the magic methods doesn't work (I've overlooked that when approving), because `<function>__toString</function>` is not recognized by the build system; that should have been `<link linkend="object.tostring">__toString()</link>` instead.

Anyhow, a PR would be welcome!