[80502] Document 0 < (empty string)
php/doc-en pull request #480
Opened 2021-03-04 23:25 UTC by deleugpn

As mentioned in https://bugs.php.net/bug.php?id=80502 the comparison between `0 < ''` has changed in PHP 8.0.0 due to saner string comparison RFC.

2021-03-08 15:22 UTC, cmb69 requested changes
Thanks for the PR! I think having a single example, and highlighting the differences there would be more beneficial than two examples, though.

2021-03-08 15:36 UTC, deleugpn commented
I'll try to make a table with `Expression | Result (< 7.4) | Result (> 8.0)`

2022-12-22 16:16 UTC, afilina commented
@deleugpn Pinging author.

2023-01-25 10:54 UTC, kamil-tekiela commented
This has already been merged. If you would like to improve it, please open a fresh PR.

2023-01-25 10:54 UTC, closed without merging