Update Swoole ini
php/doc-en pull request #486
Opened 2021-03-11 01:54 UTC by sy-records

2021-03-11 13:25 UTC, cmb69 requested changes
Thank you very much! Please address my comment. :)

2021-03-11 13:25 UTC, cmb69 commented on reference/swoole/ini.xml
> +      <entry><!-- leave empty, this will be filled by an automatic script --></entry>
Unfortunately, that's not true. There is no automatic script which fills the changelog column. Could you please manually add availability information? I mean something like: `Available as of swoole x.y.z` (of course, replacing x.y.z with the version number where the INI setting has been added).

2021-03-11 13:28 UTC, sy-records commented on reference/swoole/ini.xml
> +      <entry><!-- leave empty, this will be filled by an automatic script --></entry>
Sure, I'll add it later.

2021-03-15 10:23 UTC, sy-records commented on reference/swoole/ini.xml
> +      <entry><!-- leave empty, this will be filled by an automatic script --></entry>
done.

2021-03-15 10:53 UTC, cmb69 approved these changes
Thank you!

2021-03-15 11:15 UTC, closed without merging