Proposal - explain the fail more concrete for __set_state
php/doc-en pull request #489
Opened 2021-03-15 10:52 UTC by AlexandrErohin

It is proposal to explanation more concrete the type of the fail after re-importing objects from var_export.
That it is not only would not be re-imported - but also causes fatal error

2021-08-05 18:24 UTC, afilina commented on language/oop5/magic.xml
> +     implemented by the object's class, so re-importing such objects will result in a Fatal Error,
Is this true for all PHP versions, or does this have a different result based on the version?

2021-08-06 15:18 UTC, AlexandrErohin commented
@afilina 
Yes - it results with Fatal error since version 5.1.0
https://3v4l.org/C6SrZ

2021-08-06 15:31 UTC, cmb69 commented
Actually, that is an `Error` exception as of PHP 7.0.0 (older versions are no longer relevant for the manual).

2021-08-06 16:27 UTC, afilina requested changes

2021-08-06 16:27 UTC, afilina commented on language/oop5/magic.xml
> +     implemented by the object's class, so re-importing such objects will result in a Fatal Error,
```suggestion
     implemented by the object's class, so re-importing such objects will result in an <classname>Error</classname> exception,
```

2021-08-09 20:17 UTC, AlexandrErohin commented on language/oop5/magic.xml
> +     implemented by the object's class, so re-importing such objects will result in a Fatal Error,
@afilina Thank you!

2021-08-10 14:24 UTC, afilina approved these changes

2021-08-17 16:37 UTC, cmb69 commented on language/oop5/magic.xml
> +     as __set_state() is undefined. Particularly, this affects some
```suggestion
     implemented by the object's class, so re-importing objects will result in an <classname>Error</classname> exception,
     if __set_state() is not implemented. Particularly, this affects some
```

2021-08-17 20:35 UTC, cmb69 approved these changes
Thank you!

2021-08-17 20:39 UTC, merged