Generate ext/pdo methodsynopses based on stubs
php/doc-en pull request #494
Opened 2021-03-19 09:29 UTC by kocsismate

2021-03-19 09:30 UTC, kocsismate commented on reference/pdo/pdostatement/fetchall.xml
>    <methodsynopsis>
As far as I saw this is the only signature change which is worth a mention via a changelog. I added one, although I couldn't come up with a description good enough for the variadic `$args` parameter in the parameter description section.

2021-03-19 11:56 UTC, cmb69 commented on reference/pdo/pdostatement/fetchall.xml
>    <methodsynopsis>
I think it's okay.

2021-03-19 11:56 UTC, cmb69 commented on reference/pdo/pdostatement/fetchall.xml
>       <term><parameter>ctor_args</parameter></term>
I think this should be
```suggestion
     <term><parameter>args</parameter></term>
```

2021-03-19 11:56 UTC, cmb69 commented on reference/pdo/pdostatement/fetchall.xml
> +        <parameter>Args</parameter> is now a variadic parameter.
```suggestion
        <parameter>args</parameter> is now a variadic parameter.
```

2021-03-25 12:52 UTC, kamil-tekiela commented on reference/pdo/pdostatement/bindcolumn.xml
> +   <methodparam choice="opt"><type>int</type><parameter>type</parameter><initializer>0</initializer></methodparam>
Default should be PDO_PARAM_STR not 0

2021-03-25 18:38 UTC, kocsismate commented on reference/pdo/pdostatement/bindcolumn.xml
> +   <methodparam choice="opt"><type>int</type><parameter>type</parameter><initializer>0</initializer></methodparam>
Nice catch! Thanks! I've fixed it in this PR as well as in php-src itself.

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdo/query.xml
> +   <modifier>public</modifier> <type class="union"><type>PDOStatement</type><type>false</type></type><methodname>PDO::query</methodname>
I think you should manually revert the changes here. The first signature should have only 2 arguments. The other 3 should stay as they were, but you can add nullability to the second argument. The point is that there really are 4 signatures for this method. We can't express this in stub files, but we should put it in the manual.

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdo/setattribute.xml
> +   <methodparam><type class="union"><type>array</type><type>int</type></type><parameter>value</parameter></methodparam>
I think that's a mistake in the stub file. There should be 3: int, array, bool.

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/bindcolumn.xml
> +   <methodparam choice="opt"><type>mixed</type><parameter>driverOptions</parameter><initializer>&null;</initializer></methodparam>
I believe this one should be nullable.

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/bindparam.xml
> +   <methodparam choice="opt"><type>mixed</type><parameter>driverOptions</parameter><initializer>&null;</initializer></methodparam>
Same here, nullable

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/debugdumpparams.xml
> +   <modifier>public</modifier> <type class="union"><type>bool</type><type>null</type></type><methodname>PDOStatement::debugDumpParams</methodname>
This is not documented yet. According to the manual this method is void

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/errorcode.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>null</type></type><methodname>PDOStatement::errorCode</methodname>
I think this might be a bug. How can this function return null?

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
Incorrect. The default is NULL. Bug in stubs?

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +   <methodparam rep="repeat"><type>mixed</type><parameter>args</parameter></methodparam>
Where did this change come from? What happened to the third argument? I can't see any change in the code. The old signature is correct.

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +        <parameter>args</parameter> is now a variadic parameter.
It's really not. 
> ArgumentCountError: PDOStatement::fetchAll() expects at most 3 arguments, 5 given

2021-04-21 23:37 UTC, kamil-tekiela commented on reference/pdo/pdostatement/setfetchmode.xml
> +   <methodparam rep="repeat"><type>mixed</type><parameter>args</parameter></methodparam>
Same as my first comment. This needs to be manually adjusted to what it was before

2021-04-24 10:25 UTC, kocsismate commented on reference/pdo/pdo/setattribute.xml
> +   <methodparam><type class="union"><type>array</type><type>int</type></type><parameter>value</parameter></methodparam>
I believe `mixed` is correct, since any type is accepted, and there is no notice or warning when providing a different type than int/array/bool.

2021-04-24 10:26 UTC, kocsismate commented on reference/pdo/pdostatement/bindcolumn.xml
> +   <methodparam choice="opt"><type>mixed</type><parameter>driverOptions</parameter><initializer>&null;</initializer></methodparam>
It is `mixed`, so by definition nullable :)

2021-04-24 10:29 UTC, kamil-tekiela commented on reference/pdo/pdo/setattribute.xml
> +   <methodparam><type class="union"><type>array</type><type>int</type></type><parameter>value</parameter></methodparam>
`mixed` is also fine. Either `mixed` or 3-way union.

2021-04-24 10:43 UTC, kocsismate commented on reference/pdo/pdostatement/errorcode.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>null</type></type><methodname>PDOStatement::errorCode</methodname>
I'm not sure what this exactly does:
```
if (stmt->error_code[0] == '\0') {
    RETURN_NULL();
}
```

but it was added in https://github.com/php/php-src/commit/9334bbd650c65f34c2f7cb5e96e12ba0518f119b#diff-cedda5e61bbd718fe650fa21c5c402d39868708b19ad317a8e3c68b001128357R1781

2021-04-24 10:46 UTC, kocsismate commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
are you sure? As far as I see it's defined as `zend_long how = PDO_FETCH_USE_DEFAULT;` Or which parameter do you mean?

2021-04-24 11:02 UTC, kocsismate commented on reference/pdo/pdostatement/fetchall.xml
> +   <methodparam rep="repeat"><type>mixed</type><parameter>args</parameter></methodparam>
Have you updated your PHP-8.0 branch? It looks like yours is out of sync. Nevertheless it came from https://github.com/php/php-src/commit/cfaa270da5b511e2821aa0a5e036ef5879a56bed

2021-04-24 11:18 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
If you provide `PDO::FETCH_BOTH` you overwrite the default. To have the default you need to pass null.

2021-04-24 11:26 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +   <methodparam rep="repeat"><type>mixed</type><parameter>args</parameter></methodparam>
So the problem here is that we can't represent the signature correctly in the stub file. We have 3 overloads for this function, same as with query and setFetchMode. We can't remove this information from the manual, so we have to leave the manual as it was before.

2021-04-24 11:27 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +        <parameter>args</parameter> is now a variadic parameter.
Yeah, let's not add the changelog here. The arguments didn't change. The stub file is misrepresenting it.

2021-04-24 11:40 UTC, cmb69 commented on reference/pdo/pdostatement/fetchall.xml
> +   <methodparam rep="repeat"><type>mixed</type><parameter>args</parameter></methodparam>
While `PDO::query()` is documented with overloaded signatures, `PDOStatement::fetchAll()` is not yet, but it should be done.

2021-04-25 13:54 UTC, kamil-tekiela commented on reference/pdo/pdostatement/errorcode.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>null</type></type><methodname>PDOStatement::errorCode</methodname>
NVM, it turns out this is the intended behaviour

2021-05-02 11:46 UTC, kocsismate commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
I've just realized that `PDO_FETCH_USE_DEFAULT != PDO::FETCH_BOTH`. But I still don't understand how `null` is related, since the parameter doesn't accept it (officially).

2021-05-02 11:57 UTC, kocsismate commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
Although... there is this line: `dbh->default_fetch_type = PDO_FETCH_BOTH;` in `pdo_dhb.c`. So no matter if you provide `0` (which is `PDO_FETCH_USE_DEFAULT `) to the `$mode` param of `PDOStatement::fetch()` or `PDO::FETCH_BOTH`, the `how` param ends up being `PDO_FETCH_BOTH` due to this piece of code in `do_fetch()` in `pdo_stmt.c`:

```
if (how == PDO_FETCH_USE_DEFAULT) {
	how = stmt->default_fetch_type;
}
```

Or am I missing something?

2021-05-02 12:39 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
If I understand it correctly if you don't provide a param then the default is used which could have been changed in the constructor arguments or using `setFetchMode()` method. It's never guaranteed that the default is `PDO_FETCH_BOTH`.

2021-05-02 16:59 UTC, kocsismate commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
OK, I see it now! I missed that this default can be changed. Thanks for the explanation!

2021-05-04 10:13 UTC, kocsismate commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
I've pushed an update. Hopefully it fixes all the review suggestions

2021-05-04 10:39 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +       (which defaults to <constant>PDO::FETCH_DEFAULT</constant>)
😄 The default defaults to FETCH_BOTH. It was correct as it was. Please don't change this line

2021-05-04 10:39 UTC, kamil-tekiela commented on reference/pdo/constants.xml
> +     Specifies that the default fetch method shall be used.
Fetch mode is better than fetch method

2021-05-04 10:39 UTC, kamil-tekiela commented on reference/pdo/pdo/query.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>fetchMode</parameter><initializer>&null;</initializer></methodparam>
Correct me if I'm wrong but I think this should be exactly the same as setfetchmodea and fetchall. Instead of Null show the overloaded signature.

2021-05-04 10:57 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetch.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>PDO::FETCH_BOTH</initializer></methodparam>
This signature hasn't been updated. It should say PDO::FETCH_DEFAULT instead of PDO::FETCH_BOTH as you have changed it.

2021-05-04 10:59 UTC, kocsismate commented on reference/pdo/pdostatement/fetchall.xml
> +       (which defaults to <constant>PDO::FETCH_DEFAULT</constant>)
Ah, yes.. :D

2021-05-04 11:00 UTC, kocsismate commented on reference/pdo/pdo/query.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>fetchMode</parameter><initializer>&null;</initializer></methodparam>
No, I also agree!

2021-05-04 11:24 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchobject.xml
> +   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>ctorArgs</parameter><initializer>&null;</initializer></methodparam>
The argument is not nullable. 

>Uncaught TypeError: PDOStatement::fetchObject(): Argument #2 ($ctorArgs) must be of type array, null given

2021-05-04 11:24 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
>   </refsect1>
I think fetchAll should be documented exactly the same way as setFetchMode with the 4 overloads. The second PDO::FETCH_DEFAULT isn't helpful here

2021-05-04 11:24 UTC, kamil-tekiela commented on reference/pdo/pdostatement/setfetchmode.xml
> +     <term><parameter>args</parameter></term>
The name changes need to be reverted, too.

2021-05-04 11:26 UTC, kamil-tekiela commented on reference/pdo/pdo/setattribute.xml
> +   <methodparam><type class="union"><type>array</type><type>int</type></type><parameter>value</parameter></methodparam>
What's the status on this one? Will you change it back to mixed?

2021-05-04 11:33 UTC, kocsismate commented on reference/pdo/pdostatement/fetchobject.xml
> +   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>ctorArgs</parameter><initializer>&null;</initializer></methodparam>
Fantastic! Another stub issue :/

2021-05-04 11:33 UTC, kocsismate commented on reference/pdo/pdostatement/fetchobject.xml
> +   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>ctorArgs</parameter><initializer>&null;</initializer></methodparam>
(But nice catch!)

2021-05-04 13:13 UTC, kocsismate commented on reference/pdo/pdostatement/fetchobject.xml
> +   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>ctorArgs</parameter><initializer>&null;</initializer></methodparam>
Proposed: https://github.com/php/doc-en/pull/494

2021-05-05 21:51 UTC, kamil-tekiela requested changes

2021-05-05 21:51 UTC, kamil-tekiela commented on reference/pdo/pdo/query.xml
> +   <methodparam><type>array</type><parameter>ctor_args</parameter></methodparam>
```suggestion
   <methodparam><type>array</type><parameter>constructorArgs</parameter></methodparam>
```

2021-05-05 21:51 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
>   </refsect1>
Is this still WIP? If not, I'd like to remind that you copied too much. The name of the function and return parameters changed too. Also, the first signature is missing `= PDO::FETCH_DEFAULT`

2021-05-05 21:51 UTC, kamil-tekiela commented on reference/pdo/pdostatement/fetchall.xml
> +       <parameter>args</parameter> parameter.
```suggestion
       <parameter>colno</parameter> parameter.
```
We removed the args variadic signature now

2021-05-05 21:51 UTC, kamil-tekiela commented on reference/pdo/pdostatement/setfetchmode.xml
> +     <term><parameter>args</parameter></term>
```suggestion
     <term><parameter>object</parameter></term>
```
revert back

2021-05-06 11:21 UTC, kocsismate commented on reference/pdo/pdo/query.xml
> +   <methodparam><type>array</type><parameter>ctor_args</parameter></methodparam>
Thanks for all these findings. I came to the conclusion that I really hate these overloaded functions/methods :D So I'll definitely propose an RFC next time to deprecate them whenever possible (an example: https://github.com/php/php-src/pull/6754).

2021-05-06 11:44 UTC, kocsismate commented on reference/pdo/pdostatement/fetchall.xml
>   </refsect1>
Gosh, no, it wasn't supposed to be WIP.. I'm just inattentive :/

2021-05-06 11:56 UTC, kocsismate commented on reference/pdo/pdostatement/fetchall.xml
>   </refsect1>
I really hope that I managed to got it right this time

2021-05-06 12:07 UTC, kamil-tekiela approved these changes
This looks ok to me now. I still have a feeling we missed something. @cmb69  What's your opinion?

2021-05-06 12:20 UTC, cmb69 commented
From a quick look, this looks okay. Of course, there is the issue that some of these methods may not return false on failure for ERRMODE_EXCEPTION, but I don't think it's worth to explicitly document that (IMHO, letting clients choose how issues are reported is a bad idea in the first place).

2021-05-06 12:26 UTC, kamil-tekiela commented
@cmb69 Yeah, I noticed that too, but I think we can make a separate PR for that. The return values will have to be adjusted for the new signatures.

2021-05-06 12:44 UTC, cmb69 approved these changes

2021-05-06 12:50 UTC, merged

2021-05-12 05:09 UTC, jonaslinn commented on reference/pdo/constants.xml
> +  </varlistentry>
Hello, just stumbled over this constant. As nice as it would be, it does not exists (8.0.6). Or is this planned?
`Fatal error: Uncaught Error: Undefined constant PDO::FETCH_DEFAULT`

2021-05-12 18:11 UTC, kocsismate commented on reference/pdo/constants.xml
> +  </varlistentry>
We documented it a bit prematurely... since the constant has just been added by https://github.com/php/php-src/pull/6937, it's going to be available in the next patch release

2021-05-12 21:03 UTC, cmb69 commented on reference/pdo/constants.xml
> +  </varlistentry>
Please add that info ("Available as of PHP 8.0.7.")

2021-05-12 21:58 UTC, kocsismate commented on reference/pdo/constants.xml
> +  </varlistentry>
Submitted: https://github.com/php/doc-en/pull/597 Although I'm wondering if this information should be added to the usages of the constant?