Add swoole_error_log for swoole
php/doc-en pull request #505
Opened 2021-03-29 09:22 UTC by sy-records

2021-03-29 12:01 UTC, cmb69 commented on reference/swoole/functions/swoole-error-log.xml
> +<refentry xml:id="function.swoole-version" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```suggestion
<refentry xml:id="function.swoole-error-log" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2021-03-29 12:04 UTC, sy-records commented on reference/swoole/functions/swoole-error-log.xml
> +<refentry xml:id="function.swoole-version" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
done

2021-03-30 10:42 UTC, cmb69 commented on reference/swoole/functions/swoole-error-log.xml
> +<refentry xml:id="function.swoole-version" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
Thanks!

2021-03-30 10:55 UTC, cmb69 requested changes
Thank you for the PR! However, it would be good to actually document the function, i.e. to describe the general purpose, the parameters (especially the `$level`; are there constant defined in swoole for that purpose?). Also, there should be return value section (see https://github.com/php/doc-en/pull/507/files#r603979680). If that is not possible, add the `&warn.undocumented.func;` entity reference, like shown below.

Furthermore, there should be an entry for the function in https://github.com/php/doc-en/blob/master/reference/swoole/versions.xml, which states the availability of this function (i.e. in which version of swoole it has been added).

2021-03-30 10:55 UTC, cmb69 commented on reference/swoole/functions/swoole-error-log.xml
> +
If it is not possible to document the function for now, please add:
```suggestion
  &warn.undocumented.func;
```

2021-03-31 01:45 UTC, sy-records commented
@cmb69 I modified it, can you review it again?

2021-03-31 11:30 UTC, cmb69 commented
Thanks you, especially for also documenting the constants! I'm going to add availability info to these, and will apply the patch.

2021-03-31 11:31 UTC, cmb69 commented
Applied as f03dfae1dcaf64d695189673e6db82aa3b7659a1.

2021-03-31 11:31 UTC, closed without merging