Add swoole-clear-error for swoole
php/doc-en pull request #507
Opened 2021-03-30 01:38 UTC by sy-records

2021-03-30 10:40 UTC, cmb69 requested changes
Thank you for the PR! I left some comments below.

2021-03-30 10:40 UTC, cmb69 commented on reference/swoole/functions/swoole-clear-error.xml
> +  </para>
```suggestion
  &return.void;
```

2021-03-30 10:40 UTC, cmb69 commented on reference/swoole/functions/swoole-clear-error.xml
> +
Please describe the function here; at the very least duplicate the refpurpose:
```suggestion
   Clear errors in the socket or on the last error code.
```

2021-03-31 00:47 UTC, sy-records commented
Thanks~

2021-03-31 11:05 UTC, cmb69 commented
Thank you! I gave bad advice regarding `&return.void`; this needs to be enclosed in a `<para>`. I'm going to fix this, and apply the patch.

2021-03-31 11:05 UTC, closed without merging