Fix #74284: Update runtime configuration page for memcached
php/doc-en pull request #53
Opened 2020-03-02 12:24 UTC by jboulen

I based my work on [php-memcached/memcached.ini](https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini).

It should also [fix this issue](https://bugs.php.net/bug.php?id=74284).

2020-03-10 20:44 UTC, TysonAndre commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
This should continue to be `php` - PHP is the default. igbinary can only be used if the ini setting is changed, and the igbinary extension is installed.

2020-03-11 09:30 UTC, jboulen commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
The comment on [default memcached.ini](https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini#L127) indicates : 
> ; The default is igbinary if available, then msgpack if available, then php otherwise.
> ;memcached.serializer = "igbinary"

So I will update [this line](https://github.com/php/doc-en/pull/53/files#diff-e55e997e08f9c83bde010c4b38f96056L300) too.
> The default is igbinary if available and php otherwise.

But what default value should we display in documentation ?

2020-03-11 10:00 UTC, cmb69 commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
I think using "php" as default, but explaining that it depends on compile time (options), might be best.

2020-03-11 10:02 UTC, cmb69 commented
I can't really comment on memcached, but please note that the PHP manual is supposed to document also older versions. So if some of these changes would have been introduced only in recent versions, respective changelog entries should be added (or be documented otherwise).

2020-03-11 10:14 UTC, jboulen commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
Can I use _changelog_ column or it's better to let explanation in [settings description](https://www.php.net/manual/en/memcached.configuration.php#ini.memcached.serializer) ?

2020-03-11 10:18 UTC, jboulen commented
I will try to fill _changelog_ column. Thank you for feedback.

2020-03-11 13:46 UTC, TysonAndre commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
I'm sorry. I was mistaken, this was right -- I didn't expect igbinary and msgpack to be the default and thought it'd be opt-in.

If igbinary is available, it's igbinary, if msgpack is available, it's msgpack, and otherwise, it's php.

```
#if defined(HAVE_MEMCACHED_IGBINARY)
# define SERIALIZER_DEFAULT SERIALIZER_IGBINARY
# define SERIALIZER_DEFAULT_NAME "igbinary"
#elif defined(HAVE_MEMCACHED_MSGPACK)
# define SERIALIZER_DEFAULT SERIALIZER_MSGPACK
# define SERIALIZER_DEFAULT_NAME "msgpack"
#else
# define SERIALIZER_DEFAULT SERIALIZER_PHP
# define SERIALIZER_DEFAULT_NAME "php"
#endif /* HAVE_MEMCACHED_IGBINARY / HAVE_MEMCACHED_MSGPACK */
```

2020-03-11 13:50 UTC, TysonAndre commented on reference/memcached/ini.xml
> +      <entry>igbinary</entry>
https://github.com/php-memcached-dev/php-memcached/commit/abd0cae8de0016ef3482a65bda9c4488a75115be#diff-af2b8e0bfbc900b4a13b10a7af197df3 - It seems like igbinary's been the default if available since 1.0.1, as far as I can tell (commit was December 29th, 2009) - https://pecl.php.net/package/memcached

2020-03-19 10:58 UTC, jboulen commented
I tried to update information about availability or deprecation of each variable.

If someone can review this PR, it will be great !

2020-03-19 11:10 UTC, cmb69 commented
@sodabrew, since you seem to be the current lead maintainer, could you please review?

2021-01-07 20:11 UTC, afilina commented
Pinging @sodabrew since this PR seems to have fell through the cracks.

2021-01-08 23:39 UTC, sodabrew commented
Thanks for the nudge, this is great. Needs to be rebased, I'll take care of that.

2021-01-08 23:44 UTC, sodabrew approved these changes
To the maintainers: please do rebase/merge this, it looks good!

2021-01-09 00:42 UTC, Girgias commented on reference/memcached/ini.xml
> +      <entry>Available since memcached 0.1.0.</entry>
```suggestion
      <entry>Available as of memcached 0.1.0.</entry>
```
Please do the following change for all other entries

2021-01-09 00:43 UTC, Girgias commented on reference/memcached/ini.xml
> +      <type>boolean</type>
```suggestion
      <type>bool</type>
```

2021-01-09 00:43 UTC, Girgias commented on reference/memcached/ini.xml
> +      <type>boolean</type>
```suggestion
      <type>bool</type>
```

2021-01-09 00:43 UTC, Girgias commented on reference/memcached/ini.xml
> +      <type>boolean</type>
```suggestion
      <type>bool</type>
```

2021-01-09 00:43 UTC, Girgias commented on reference/memcached/ini.xml
> +      <type>boolean</type>
```suggestion
      <type>bool</type>
```

2021-01-09 00:44 UTC, Girgias commented on reference/memcached/ini.xml
> +      <type>integer</type>
```suggestion
      <type>int</type>
```Apply this change to everything below

2021-01-09 00:45 UTC, Girgias requested changes
Types should be ``int`` or ``bool`` and user ``as of`` instead of ``since``

2021-01-09 12:40 UTC, cmb69 commented
Thank you!

2021-01-09 12:42 UTC, closed without merging