Wouldn't it be more readable if we had a list?
php/doc-en pull request #542
Opened 2021-04-21 13:30 UTC by shaedrich

2021-04-21 13:33 UTC, kamil-tekiela commented
Maybe it would be a good idea to make it into a list, but I see that you only added numbers. Could you actually transform it into a proper numbered list?

2021-04-21 13:43 UTC, cmb69 requested changes
Thanks for the PR, but as is, that wouldn't look like you expect it to.

2021-04-21 13:43 UTC, cmb69 commented on language/predefined/typeerror.xml
> +    to a built-in PHP function (strict mode only).
That could be something like:
```suggestion
    <simplelist>
     <member>
      The argument type being passed to a function does not match
      its corresponding declared parameter type.
     </member>
     <member>  
      A value being returned from a function does not match the
      declared function return type.
     </member>
     <member> 
      The third is where an invalid number of arguments are passed
      to a built-in PHP function (strict mode only).
     </member>
    </simplelist>  
```
Not sure whether that would be an improvement, though.

2021-04-22 09:10 UTC, shaedrich commented on language/predefined/typeerror.xml
> +    to a built-in PHP function (strict mode only).
Ah, thanks for that hint. Why do you think, it might not be an improvement? Of course, it doesn't do anything but increasing the readability.

2021-04-22 11:15 UTC, cmb69 commented
That now looks like this:
![Screenshot 2021-04-22 131322](https://user-images.githubusercontent.com/2306138/115705288-a67df480-a36c-11eb-885b-d2df4d07f6bb.gif)

I think this is a nice improvement, but the third item shouldn't start with "The third is where".

2021-04-22 14:04 UTC, shaedrich commented
Oh, right. I missed that.

2021-04-22 14:10 UTC, cmb69 approved these changes

2021-04-22 14:10 UTC, cmb69 commented
Thank you!

2021-04-22 14:11 UTC, merged

2021-04-24 21:15 UTC, shaedrich commented
You're welcome!