Remove PHP 5, 7 references
php/doc-en pull request #565
Opened 2021-04-30 13:08 UTC by saundefined

Sections:

- stream
- stomp
- sqlsrv
- sqlite3
- spl
- solr
- sockets
- snmp
- simplexml
- session
- seaslog
- posix
- sem
- phar
- reflectionclass
- rrd
- oci8
- pgsql
- network
- curl

ref #557

2021-05-04 17:19 UTC, Girgias requested changes
I think it's better to split the OCI8 changes so the folks at Oracle can have a look, as I don't know if it makes a lot of sense to refer to ancient PECL releases either.

Otherwise mostly fine with some suggestions

2021-05-04 17:19 UTC, Girgias commented on reference/simplexml/simplexmlelement/children.xml
>     may be used instead.
This whole note may need to be rewritten

2021-05-04 17:19 UTC, Girgias commented on reference/sqlite3/configure.xml
>   <note>
Remove the note that this was available as a PECL extension.

2021-05-04 17:19 UTC, Girgias commented on reference/sqlsrv/configure.xml
> +  download comes 8 driver files, four of which are for PDO support.
```suggestion
  download comes with 8 driver files, four of which are for PDO support. 
```

2021-05-04 17:19 UTC, Girgias commented on reference/sqlsrv/configure.xml
> +  <link xlink:href="&url.sqlsrv;">SQLSRV 4.0 download</link>.
There seems to be a version 5.9 of the driver available on PECL, and it's split for PDO it seems too: https://pecl.php.net/package/sqlsrv ; https://pecl.php.net/package/pdo_sqlsrv

2021-05-04 17:19 UTC, Girgias commented on reference/sqlsrv/setup.xml
> +  <link xlink:href="&url.sqlsrv;">SQLSRV 4.0 download</link>.
Same comment as for the configure file

2021-05-04 17:19 UTC, Girgias commented on reference/stream/functions/stream-context-get-default.xml
>        </note>
Maybe remove this note and add the function to the see also section, wdyt @cmb69 ?

2021-05-04 17:31 UTC, cmb69 commented on reference/network/functions/ip2long.xml
> -  </note>
I think -1 is still returned.

2021-05-04 17:32 UTC, cmb69 commented on reference/phar/setup.xml
>     of iteration and array access to a Phar's file contents.  The <literal>phar</literal>
SPL is always available as of PHP 5.3.0.

2021-05-04 17:35 UTC, cmb69 commented on reference/sqlsrv/configure.xml
> +  <link xlink:href="&url.sqlsrv;">SQLSRV 4.0 download</link>.
Yep, should drop the version.

2021-05-04 17:35 UTC, cmb69 commented on reference/stream/functions/stream-context-get-default.xml
>        </note>
Yes, good idea!

2021-05-05 09:09 UTC, saundefined commented on reference/phar/setup.xml
>     of iteration and array access to a Phar's file contents.  The <literal>phar</literal>
@Girgias maybe replace this paragraph with `&no.requirement;` in this case?

2021-05-05 09:10 UTC, saundefined commented on reference/phar/setup.xml
> -  </para>
@Girgias, the configuration option `--enable-zend-multibyte` was removed in 5.4.0,
so I thought it might be possible to remove this paragraph

2021-05-05 12:11 UTC, Girgias commented on reference/phar/setup.xml
> -  </para>
Yes the config option has been removed but `zend.detect_unicode` still exists as an INI option, so the information that Phar is dependent on it should probably be kept.

2021-05-05 12:12 UTC, Girgias commented on reference/phar/setup.xml
>     of iteration and array access to a Phar's file contents.  The <literal>phar</literal>
No, because the paragraph below indicates that some feature require the OpenSSL extension, but this paragraph can indeed be removed.

2021-05-05 12:18 UTC, cmb69 commented on reference/phar/setup.xml
> -  </para>
Then we should also fix the name of the option, and link it.

2021-05-05 12:51 UTC, saundefined commented on reference/simplexml/simplexmlelement/children.xml
>     may be used instead.
>`<methodname>SimpleXMLElement::children</methodname>` returns a node object no matter if the current node has children or not. Use `<methodname>SimpleXMLElement::count</methodname>` to see if there are any children.

But, maybe remove it at all?
The note about returning the object, if there are no children contains the `Return Values` section,
`<methodname>SimpleXMLElement::count</methodname>` listed in `See Also`.

2021-05-11 17:20 UTC, saundefined commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
@cmb69 what do you think about the following?
```suggestion
   If <link linkend="ini.zend.multibyte">zend.multibyte</link> is enable, <link linkend="book.phar">phar</link> depends on <link linkend="ini.zend.detect-unicode">zend.detect_unicode</link>.
```

2021-05-11 17:44 UTC, kamil-tekiela commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
*is enabled

2021-05-11 18:29 UTC, saundefined commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
Thank you!

2021-05-12 06:23 UTC, saundefined commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
@cmb69, then maybe can simplify to "zend.detect_unicode must be enabled." 🤔 
Since this option is available only in multibyte mode.

2021-05-12 09:18 UTC, cmb69 commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
Yes, makes sense.

2021-05-12 09:56 UTC, cmb69 commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
No, that doesn't make sense. Sorry! That would imply that phar requires zend.multibyte, what it does not. Only if zend.multibyte is enabled, zend.detect_unicode needs to be enabled as well.

(And if I'm not mistaken, this is likely only needed to detect `HALT_COMPILER();`, i.e. for executable Phars, but not for PharData. This info can be added later, if needed.)

2021-05-12 09:57 UTC, cmb69 reviewed
Thank you for the PR! LGTM, except for that phar/multibyte issue, where I gave bad advice.

2021-05-12 11:06 UTC, saundefined commented on reference/phar/setup.xml
> +   PHP configured with <literal>--enable-zend-multibyte</literal> makes <link linkend="book.phar">phar</link> dependant on the ini option <literal>detect_unicode</literal>.
@cmb69 thank you!  Updated

2021-05-12 11:12 UTC, cmb69 approved these changes
Thanks!

2021-05-12 11:49 UTC, merged