Cleanup reference/zmq documentation.
php/doc-en pull request #566
Opened 2021-04-30 13:25 UTC by thinkverse

This PR cleans up [reference/zmq](https://github.com/php/doc-en/tree/master/reference/zmq) by re-ordering the `returnvalues` section into the proper place and also adding default `parameters` sections to documents that don't have it. 

The given issues this pull request fixes were found by the following script: [section-order.php](https://gist.github.com/Girgias/885fa1622511fc72afec3dd026748e5b).

2021-04-30 13:31 UTC, Girgias requested changes
I didn't inline the comment for each page, but if a function/method throws this information should be in an error section and not a return value section.

2021-04-30 13:31 UTC, Girgias commented on reference/zmq/zmqcontext/construct.xml
> +
This should actually be an error section and not a return value one.

2021-04-30 13:31 UTC, Girgias commented on reference/zmq/zmqcontext/getsocket.xml
> +  </para>
The throw bit should be in an error section.

2021-04-30 13:31 UTC, Girgias commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
Ditto throw in error section

2021-04-30 13:38 UTC, thinkverse commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
So then they should be change to the void parameters and added to `errors` instead?

2021-04-30 13:41 UTC, thinkverse commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
Just an FYI the return values weren't added, they were just moved to their correct order, but will change it to void parameters and `errors` then?

2021-04-30 13:46 UTC, thinkverse commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
I think it returns some sort of ZMQ context on success, but I don't have ZMQ so I don't know the correct return types sadly.

2021-04-30 13:50 UTC, cmb69 commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
I'm not sure whether the additional work makes sense in this case; the [package](https://pecl.php.net/package/zmq) looks somewhat abandoned.

2021-04-30 13:54 UTC, thinkverse commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
Might very well be true. But I think it's better to just get these fixes done once and for all. Makes the whole documentation less disorganized which is a good thing IMHO.

2021-04-30 13:57 UTC, cmb69 commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
I was particularly referring to splitting the errors from the return value section. The reordering is already done, apparently. :)

2021-04-30 14:00 UTC, thinkverse commented on reference/zmq/zmqpoll/poll.xml
> +  </para>
Ooh, well, the splitting is also done now so. 😂&nbsp; I've already pushed it to the PR, updated it to the best of my abilities.

2021-05-04 17:38 UTC, Girgias requested changes

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqcontext/construct.xml
> +   Throws ZMQContextException if context initialization fails.
```suggestion
   Throws <classname>ZMQContextException</classname> if context initialization fails.
```
This generates a link automatically

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqcontext/getsocket.xml
> +   Throws ZMQSocketException on error.
Ditto

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqpoll/poll.xml
> +   Throws ZMQPollException on error.
Ditto

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqpoll/poll.xml
> +   Returns an integer representing amount of items with activity.
```suggestion
   Returns an integer representing the amount of items with activity.
```
While we're at it

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqsocket/connect.xml
> +  </para>
Split into error section for the error.

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqsocket/construct.xml
> +   Throws ZMQSocketException on error.
Ditto use <classname> around classes.

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqsocket/construct.xml
>  }
Whitespace noise, please revert

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqsocket/construct.xml
This shouldn't be a note, but inline into the parameter section with the respective parameter, look at some other function documentation on the markup for callback functions.

2021-05-04 17:38 UTC, Girgias commented on reference/zmq/zmqsocket/recv.xml
> +  </para>
Split the error condition into its own section

2021-05-04 18:24 UTC, thinkverse commented on reference/zmq/zmqsocket/construct.xml
Took a look at [usort](https://www.php.net/manual/en/function.usort.php), which uses `<methodsynopsis>` after the `<para>` to display the callback signature, guessing that is the correct choice there? If not I'll look further.

2021-05-04 18:25 UTC, thinkverse commented
With so many commits, is a squash needed or can that be done with merge later?

2021-05-04 21:05 UTC, cmb69 commented on reference/zmq/zmqsocket/construct.xml
Yes, I think that's good.

2021-05-04 21:06 UTC, cmb69 commented
I think it's fine to press the "squash and merge" button and to edit the commit message.

2021-05-07 13:15 UTC, cmb69 reviewed
Thank you! I left some comments. @Girgias may want to re-review.

2021-05-07 13:15 UTC, cmb69 commented on reference/zmq/zmqcontext/construct.xml
> + </refsect1>
Return value sections for constructors are useless (and actually wrong). Please just remove it.

2021-05-07 13:15 UTC, cmb69 commented on reference/zmq/zmqcontext/getsocket.xml
> +   Returns a <classname>ZMQSocket</classname> object on success.
Certainly debatable how to document methods which return on success, and throw on failure, but I think it's common the omit the "on success".

2021-05-07 13:15 UTC, cmb69 commented on reference/zmq/zmqsocket/recv.xml
> +   is used and the operation would block &boolean; false shall be returned.
```suggestion
   is used and the operation would block &false; shall be returned.
```

2021-05-07 13:15 UTC, cmb69 commented on reference/zmq/zmqsocket/recv.xml
> +   Throws <classname>ZMQSocketException</classname> in error.
```suggestion
   Throws <classname>ZMQSocketException</classname> on error. 
```

2021-05-11 14:13 UTC, Girgias commented on reference/zmq/zmqcontext/getsocket.xml
> +   Returns a <classname>ZMQSocket</classname> object on success.
Yeah I would drop the "on success" too.

2021-05-11 14:14 UTC, Girgias reviewed
Needs to apply the nits already mentioned but should be good to go afterwards.

2021-05-24 12:55 UTC, thinkverse commented on reference/zmq/zmqcontext/construct.xml
> + </refsect1>
The section has been removed.

2021-05-24 12:55 UTC, thinkverse commented on reference/zmq/zmqcontext/getsocket.xml
> +   Returns a <classname>ZMQSocket</classname> object on success.
"on success" has been dropped.

2021-05-24 12:55 UTC, thinkverse commented on reference/zmq/zmqsocket/recv.xml
> +   is used and the operation would block &boolean; false shall be returned.
Fix has been pushed.

2021-05-24 12:55 UTC, thinkverse commented on reference/zmq/zmqsocket/recv.xml
> +   Throws <classname>ZMQSocketException</classname> in error.
Fix has been pushed.

2021-05-24 12:56 UTC, thinkverse commented
> Needs to apply the nits already mentioned but should be good to go afterwards.

Sorry for the late response but the changes have been pushed. 👍

2021-05-24 13:07 UTC, merged

2021-05-24 13:07 UTC, cmb69 commented
Thank you!