Clean up reference/yaf documentation.
php/doc-en pull request #569
Opened 2021-04-30 15:23 UTC by thinkverse

This PR fixes some small issues on **reference/yaf** documentation, some `return values` sections were out-of-order or had completely blank `<para>`s. Fixed to the best of my knowledge after reading up and peeking at the `yaf` source. Also combined a duplicate `seealso` into a single.

Is there a warnings section or something that can be added warning about documentation possibly being out-of-date? Looking at the [repository](https://github.com/laruence/yaf) for `yaf` the current version is `3.3.2`, docs target everything from `1.0.0` to `2.2.0`.

The given issues this pull request fixes were found by the following script: [section-order.php](https://gist.github.com/Girgias/885fa1622511fc72afec3dd026748e5b).

2021-04-30 15:55 UTC, Girgias requested changes

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_controller_abstract/forward.xml
> +    return FALSE on failure
```suggestion
    Return &false; on failure.
```
But I think we might have an entity which has this text already in language-snippets.ent.

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_regex/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_rewrite/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_simple/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_static/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_supervar/assemble.xml
> +   Returns string on success.
```suggestion
   Returns &string; on success.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_route_supervar/assemble.xml
> +   Throws <classname>Exception</classname> when <parameter>$info</parameter> key ':c' is not set.
```suggestion
   Throws <classname>Exception</classname> when <parameter>$info</parameter>
   key <literal>':c'</literal> is not set.
```

2021-04-30 15:55 UTC, Girgias commented on reference/yaf/yaf_view_simple/construct.xml
> +  </para>
Void? Or look what other constructors do

2021-04-30 16:02 UTC, cmb69 commented on reference/yaf/yaf_view_simple/construct.xml
> +  </para>
Constructors don't return; IMHO return value section should be omitted for these (unless aliased like DateTime::__construct()).

2021-04-30 16:08 UTC, thinkverse commented on reference/yaf/yaf_controller_abstract/forward.xml
> +    return FALSE on failure
That might be the case, `yaf` is written in C, so I'm having a difficult time trying to figure it out, but according to the [source](https://github.com/laruence/yaf/blob/master/yaf_controller.c#L719), at least the master, it returns a `bool`, either `true` or `false`. 🤔

2021-04-30 16:09 UTC, thinkverse commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns string on success.
I'll fix the `&string;` ones in a batch instead of committing the suggestion for each, simpler that way.

2021-04-30 16:13 UTC, cmb69 commented on reference/yaf/yaf_view_simple/construct.xml
> +  </para>
And if we'd get bored some time, we might write a script to check existing construct.xml (without aliases) for return value sections. :)

2021-04-30 16:21 UTC, cmb69 commented on reference/yaf/yaf_controller_abstract/forward.xml
> +    return FALSE on failure
Indeed; in that case just use `&return.success;` (and fix the return type in the signature, please).

2021-04-30 16:24 UTC, thinkverse commented on reference/yaf/yaf_controller_abstract/forward.xml
> +    return FALSE on failure
For the signature is that the `<type>` next to the `<modifier>`? If so, is it just to change `<type>void</type>` to `<type>bool</type>`?

2021-04-30 16:30 UTC, thinkverse commented on reference/yaf/yaf_controller_abstract/forward.xml
> +    return FALSE on failure
Fixes have been pushed. 👍

2021-05-03 10:11 UTC, cmb69 requested changes
Thank you! Basically good, but I think the "returns &string; on success" should be clarified/improved.

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns &string; on success.
What is returned on failure? The function signature says the method returns string.

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_regex/assemble.xml
> +   Returns &string; on success.
Same as above.

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_rewrite/assemble.xml
> +   Returns &string; on success.
ditto

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_simple/assemble.xml
> +   Returns &string; on success.
ditto

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_static/assemble.xml
> +   Returns &string; on success.
ditto

2021-05-03 10:11 UTC, cmb69 commented on reference/yaf/yaf_route_supervar/assemble.xml
> +   Returns &string; on success.
If the function either throws, or returns a string, I don't think that we need "on success" here (maybe just "Returns a &string;.")

2021-05-03 13:53 UTC, thinkverse commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns &string; on success.
Will look further into the source to find out. 👍

2021-05-04 19:44 UTC, thinkverse commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns &string; on success.
It throws `ArgumentCountError` if the first value isn't set, don't think that needs to be documented since it's PHPs built-in behavior. But it gets trickier if the first argument is set to an empty array because the error thrown `Yaf_Exception_TypeError` has different messages depending on whether the class itself has its first argument set to `false` or `true` upon initialization.

#### Senarios

##### Senario one.

```php
$router = new Yaf_Router();
$route  = new Yaf_Route_Map();

$router->addRoute('map', $route);
$router->getRoute('map')->assemble([]);
```

This will throw with the message "Undefined the 'controller' parameter for the 1st parameter" because the array is missing the key `:c`, the route map is initialized to use controllers, thus this key is needed in the array.

##### Senario two.

```php
$router = new Yaf_Router();
$route  = new Yaf_Route_Map(true);

$router->addRoute('map', $route);
$router->getRoute('map')->assemble([]);
```

This will throw with the message "Undefined the 'action' parameter for the 1st parameter" because the route map is now using actions, thus looking for the `:a` key in the array instead.

If an empty string is the value to either key, `null` will be returned, but if the value is set to `null` or `0` the corresponding `Yaf_Exception_TypeError` is thrown.

Not sure how to go about documenting that behavior.

2021-05-04 20:09 UTC, thinkverse commented on reference/yaf/yaf_route_regex/assemble.xml
> +   Returns &string; on success.
This one's also a bit tricky. If the class has the argument `reverse` set, it returns whatever `reverse` is set to, and any transformed values it finds. If it's not set, which is the default behavior, assemble seems to always return `null`.

```php
$route = new Yaf_Route_Regex("#^/product/([^/]+)/([^/])+#", ['controller' => 'product']);

$assemble = $router->getRoute('map')->assemble([]);
var_dump($assemble); // null
```

```php
$route = new Yaf_Route_Regex("#^/product/([^/]+)/([^/])+#", ['controller' => 'product'], [], [], '');

$assemble = $router->getRoute('map')->assemble([]);
var_dump($assemble); // string(0) ""
```

```php
$route = new Yaf_Route_Regex("#^/product/([^/]+)/([^/])+#", ['controller' => 'product'], [], [], 'product');

$assemble = $router->getRoute('map')->assemble([]);
var_dump($assemble); // string(7) "product"
```

```php
$route = new Yaf_Route_Regex("#^/product/([^/]+)/([^/])+#", ['controller' => 'product'], [], [], 'product/:a');

$assemble = $router->getRoute('map')->assemble([':a' => 'action']);
var_dump($assemble); // string(14) "product/action"
```

Creating the router and attaching the route map to the router have been omitted from the examples.

Is it safe to assume this can be a return string on success and null on failure? 🤔&nbsp; Seems the default behavior is to return null unless the `reverse` argument is set.

2021-05-04 20:13 UTC, thinkverse commented on reference/yaf/yaf_route_rewrite/assemble.xml
> +   Returns &string; on success.
This one returns the original URL argument passes to `Yaf_Route_Rewrite` on creation even on failure. Cannot find a case where it doesn't return anything but a string.

2021-05-04 20:22 UTC, thinkverse commented on reference/yaf/yaf_route_simple/assemble.xml
> +   Returns &string; on success.
This one will throw `Yaf_Exception_TypeError` if either `:c` or `:a` key is missing from the info array, otherwise it'll return a string.

```php
$route  = new Yaf_Route_Simple('m', 'c', 'a');

$assemble = $router->getRoute('simple')->assemble([
    ':a' => '',
    ':c' => ''
]);

var_dump($assemble); // string(6) "?c=&a=" 
```

```php
$route  = new Yaf_Route_Simple('m', 'c', 'a');

$assemble = $router->getRoute('simple')->assemble([
    ':a' => '',
]);
```

This will throw a `Yaf_Exception_TypeError` with either of two messages. _You need to specify the controller by ':c'_, or _You need to specify the action by ':a'_ depending on which key is missing from the array.

Seems each route class handles itself a bit differently depending on how the class is created and what is sent to the `assemble` method.

But this one seems to only return either a `string` or it `throws`.

2021-05-04 20:30 UTC, thinkverse commented on reference/yaf/yaf_route_static/assemble.xml
> +   Returns &string; on success.
This one is similar to `Yaf_Route_Simple` and `Yaf_Route_Map` where it returns either a string or throws `Yaf_Exception_TypeError` if `:a` or `:c` key is missing from the argument array, it needs those two keys otherwise it'll throw.

So maybe this as an error section?
```xml
<para>
 Throws <classname>Yaf_Exception_TypeError</classname> if; <literal>':c'</literal>' 
 and <literal>':a'</literal> keys are missing from <parameter>info</parameter>.
</para>
```

2021-05-04 20:35 UTC, thinkverse commented on reference/yaf/yaf_route_supervar/assemble.xml
> +   Returns &string; on success.
Need to update the `errors` on this one, also throws `Yaf_Exception_TypeError`  if key `:a` isn't set.

2021-05-04 20:39 UTC, thinkverse commented on reference/yaf/yaf_route_supervar/assemble.xml
> +   Returns &string; on success.
Could add the same error as for `Yaf_Route_Static` to this one, since both requires `:c` and `:a` keys to be set.

```xml
<para>
 Throws <classname>Yaf_Exception_TypeError</classname> if; <parameter>info</parameter> 
 keys <literal>':c'</literal> and <literal>':a'</literal> are not set.
</para>
```

2021-05-07 12:45 UTC, cmb69 commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns &string; on success.
Thanks for the thorough investigation! The behavior is apparently rather contrieved. Anyhow, maybe document that the method returns string on success, and null on failure, and add a error/exception section that the method may throw `Yaf_Exception_TypeError`.

2021-05-07 12:53 UTC, cmb69 commented on reference/yaf/yaf_route_regex/assemble.xml
> +   Returns &string; on success.
> Is it safe to assume this can be a return string on success and null on failure?

Let's say, yes. ;) Please also change the function signature.

2021-05-07 13:05 UTC, cmb69 commented on reference/yaf/yaf_route_rewrite/assemble.xml
> +   Returns &string; on success.
Well, then just `Returns &string;`.

2021-05-07 13:06 UTC, cmb69 commented on reference/yaf/yaf_route_simple/assemble.xml
> +   Returns &string; on success.
Then please remove the "on success", and add a short error/exception section.

2021-05-24 12:48 UTC, thinkverse commented on reference/yaf/yaf_route_map/assemble.xml
> +   Returns &string; on success.
Sorry for the long delay. I've pushed the necessary changes, which should be good for a re-review. 👍

2021-05-24 12:57 UTC, cmb69 commented
Thank you!

2021-05-24 12:58 UTC, merged