Reflection deprecation
php/doc-en pull request #578
Opened 2021-04-30 20:14 UTC by Crell

Considerable chunks of the ReflectionParameter class are marked as deprecated with no indication of what to do instead.  After some experimentation (while trying to remove the deprecated stuff from TYPO3), I offer the following "do this instead" options.  And some other commentary and improvement along the way.

I'm not 100% sure my XML structuring is right.  Let me know what I should do instead and I'll adjust accordingly.

2021-04-30 20:17 UTC, azjezz commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): bool {
```suggestion
function getAllTypes(ReflectionParameter $reflectionParameter): array {
```

2021-04-30 20:17 UTC, Crell commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): bool {
Copy pasta FTW.  Fixed.

2021-04-30 20:18 UTC, azjezz commented on reference/reflection/reflectionparameter/isarray.xml
> +    if (!$reflectionType) return false;
If it's untyped, it allows array :) 

```suggestion
    if (!$reflectionType) return true;
```

2021-04-30 20:18 UTC, azjezz commented on reference/reflection/reflectionparameter/iscallable.xml
> +    if (!$reflectionType) return false;
same
```suggestion
    if (!$reflectionType) return true;
```

2021-04-30 20:19 UTC, Crell commented on reference/reflection/reflectionparameter/isarray.xml
> +    if (!$reflectionType) return false;
Hm.  Valid point, but also subtle difference from `isArray()`.  If it's untyped, then `isArray()` would have returned false.

By the same token, should this also check for `mixed`, to make it truely a user-space version of the type check, or should it be strictly "does it explicitly allow for array" and then rename the function?  (Same question applies for the `callable` version.)

2021-04-30 20:21 UTC, thinkverse commented on reference/reflection/reflectionparameter/gettype.xml
> +     objects.  The following function will return an array of 0 or more <classname>ReflectionNamedType</classname>
```suggestion
     objects. The following function will return an array of 0 or more <classname>ReflectionNamedType</classname>
```

Extra space there that's not needed.

2021-04-30 20:21 UTC, thinkverse commented on reference/reflection/reflectionparameter/gettype.xml
> +     a <classname>ReflectionUnionType</classname> instance.  The latter is a collection of the former.
```suggestion
     a <classname>ReflectionUnionType</classname> instance. The latter is a collection of the former.
```

Extra space.

2021-04-30 20:22 UTC, azjezz commented on reference/reflection/reflectionparameter/isarray.xml
> +    if (!$reflectionType) return false;
>  should this also check for mixed

untyped is the same as mixed, unless you are talking about `@param` annotations, which we should really bother with here;

2021-04-30 20:25 UTC, cmb69 requested changes
I left some comments; maybe the build error is related to the `<section>`s, but I'm not sure.

2021-04-30 20:25 UTC, cmb69 commented on reference/reflection/reflectionnamedtype/isbuiltin.xml
> +   Checks if the type is a built-in type in PHP. A built-in type is any type that is not a class.
Line might be broken as well, but more importantly, not all interfaces are built-in.

2021-04-30 20:25 UTC, cmb69 commented on reference/reflection/reflectionparameter/gettype.xml
> +     objects.  The following function will return an array of 0 or more <classname>ReflectionNamedType</classname>
```suggestion
     objects.  The following function will return an array of <literal>0</literal> or more <classname>ReflectionNamedType</classname>
```

2021-04-30 20:25 UTC, cmb69 commented on reference/reflection/reflectionparameter/isarray.xml
> + </section>
Same as above (i.e. don't introduce `<section>`s in `<refentries>`).

2021-04-30 20:25 UTC, cmb69 commented on reference/reflection/reflectionparameter/iscallable.xml
> + </section>
Again. :)

2021-04-30 20:41 UTC, cmb69 commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): array {
I like 1tbs, but docs still mandate PEAR CS …

2021-04-30 20:46 UTC, Crell commented on reference/reflection/reflectionparameter/isarray.xml
> +    if (!$reflectionType) return false;
Semantically, yes.  Reflection would distinguish.  As written, this code would return false for a type declaration of `mixed` as well as omitted.  Which... is consistent with the old `isArray()` method, but not necessarily what you want.  I'm not sure of the best way to represent that distinction.

2021-04-30 20:46 UTC, thinkverse commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): array {
Not sure if @Crell knows or have found the doc style guide, I had a very hard time finding it myself, so I'm just gonna leave this here: http://doc.php.net/tutorial/style.php

2021-04-30 20:54 UTC, Girgias commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): array {
I mean we don't really enforce the code style, it's all over the place in the manual

2021-04-30 20:55 UTC, Girgias commented on reference/reflection/reflectionfunctionabstract/getparameters.xml
> +  in the order in which they are defined in the source.
Nit: Missing indent for text.

2021-04-30 20:59 UTC, cmb69 commented on reference/reflection/reflectionparameter/gettype.xml
> +function getAllTypes(ReflectionParameter $reflectionParameter): array {
Another idea for a script: sniff all code examples for CS.

2021-05-05 14:26 UTC, cmb69 approved these changes

2021-05-06 00:53 UTC, sy-records approved these changes

2021-05-06 00:57 UTC, merged