[80671] Update `mb_convert_encoding`.
php/doc-en pull request #582
Opened 2021-05-01 14:02 UTC by thinkverse

`mb_convert_encoding` now throws `ValueError` if either `$to_encoding` or `$from_encoding` are passed an invalid encoding. Looking at other changelogs, I'm guessing this is the correct way to add multiple changes to one version?

Should I retcon `mb_convert_encoding`s earlier functionality by adding a changelog entry for `4.3.0`, that's about as early as [3v4l](https://3v4l.org/5cErI) found the older emitted `E_WARNING` was caught.

Also, should I add a new `errors` section, since technically this function now throws errors?

2021-05-01 16:43 UTC, Girgias requested changes
Also check the line is less then 80 characters as it makes for easier diffs in CLI.

2021-05-01 16:43 UTC, Girgias commented on reference/mbstring/functions/mb-convert-encoding.xml
> +   <parameter>to_encoding</parameter> and or <parameter>from_encoding</parameter>
```suggestion
   <parameter>to_encoding</parameter> or <parameter>from_encoding</parameter> 
```
Or is inclusive.

2021-05-01 16:43 UTC, Girgias commented on reference/mbstring/functions/mb-convert-encoding.xml
> + </refsect1>
```suggestion
   As of PHP 8.0.0, a <classname>ValueError</classname> is thrown if the; value of
   <parameter>to_encoding</parameter> and or <parameter>from_encoding</parameter>
   is an invalid encoding.
   Prior to PHP 8.0.0, a <constant>E_WARNING</constant> was emitted instead.
  </para>
 </refsect1>
```

2021-05-01 16:47 UTC, thinkverse commented on reference/mbstring/functions/mb-convert-encoding.xml
> + </refsect1>
Have to add this change manually, pressed the wrong button.

2021-05-01 16:51 UTC, thinkverse commented
@Girgias is that change better?

2021-05-01 18:19 UTC, Girgias approved these changes
After those nits, this LGTM

2021-05-01 18:19 UTC, Girgias commented on reference/mbstring/functions/mb-convert-encoding.xml
> +   As of PHP 8.0.0, a <classname>ValueError</classname> is thrown if the;
```suggestion
   As of PHP 8.0.0, a <classname>ValueError</classname> is thrown if the
```

2021-05-01 18:19 UTC, Girgias commented on reference/mbstring/functions/mb-convert-encoding.xml
> +       <function>mb_convert_encoding</function> will now throw
```suggestion
       <function>mb_convert_encoding</function> will now throw a
```

2021-05-01 18:19 UTC, Girgias commented on reference/mbstring/functions/mb-convert-encoding.xml
> +       <function>mb_convert_encoding</function> will now throw
```suggestion
       <function>mb_convert_encoding</function> will now throw a
```

2021-05-03 08:51 UTC, cmb69 commented
Thank you!

2021-05-03 08:52 UTC, merged