Document Memcached::OPT_NOREPLY
php/doc-en pull request #584
Opened 2021-05-04 18:26 UTC by TysonAndre

This was added in 2009.
A lot of other constants were also added.
See http://docs.libmemcached.org/memcached_behavior.html

2021-05-07 12:30 UTC, cmb69 requested changes
Thank you!

2021-05-07 12:30 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Enable this to specify that you really don’t care about the result from your storage commands
Ah, you're using the proper `’`; mostly the manual uses the typographically incorrect ASCII `'`. I wonder whether we want to change it throughout the manual, or maybe to avoid contractions at all (the [style guide](http://doc.php.net/tutorial/style.php) says "Contractions should be used appropriately", whatever that means). cc @Girgias 

Even minor nit: I think it's better to have a line break after `<para>` (at least for multi-line paragraphs).

2021-05-07 12:30 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Type: <literal>boolean</literal>, default: &false;.</para>
```suggestion
    <para>Type: &bool;, default: &false;.</para>
```
That doesn't add proper markup to bool, but that's a general PhD issue.

2021-05-07 12:34 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Enable this to specify that you really don’t care about the result from your storage commands
Huh I didn't know there was a proper apostrophe, it might make more sense to use `'` as I think the ship for accurate typography has sailed long ago in the internet age, but I don't mind either way other then changing it everywhere in the manual will probably need to be done carefully and wait until rev-check can skip a revision

2021-05-07 12:34 UTC, Girgias commented on reference/memcached/constants.xml
> +    <para>Enable this to specify that you really don’t care about the result from your storage commands
Also agree with the nit, a line break is batter for long paragraphs IMHO

2021-05-07 12:43 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Enable this to specify that you really don’t care about the result from your storage commands
Good point regarding revcheck! And on a second look there should be no "you" here anyway. Can you please rephrase using passive voice?

2021-05-07 13:36 UTC, TysonAndre commented
A lot of the command documentation elsewhere was based on libmemcached docs, such as http://docs.libmemcached.org/memcached_behavior.html#MEMCACHED_BEHAVIOR_RCV_TIMEOUT - I assume we shouldn't have done this initially, but now that it's already translated, it's too late to change the `<literal>boolean</literal>` and use of `you`

2021-05-07 13:38 UTC, TysonAndre commented on reference/memcached/constants.xml
> +    <para>Type: <literal>boolean</literal>, default: &false;.</para>
```
ERROR (file:////home/runner/work/doc-en/doc-en/en/reference/memcached/constants.xml:228:23)
    <para>Type: &bool;, default: &false;.</para>
-----------------------^
 Entity 'bool' not defined


Previous errors too severe. Stopping here.
```

2021-05-07 13:39 UTC, TysonAndre commented on reference/memcached/constants.xml
> +    <para>Enable this to specify that you really don’t care about the result from your storage commands
Done

2021-05-07 13:44 UTC, TysonAndre commented on reference/memcached/constants.xml
>     </listitem>
```
    <para>Enables or disables asynchronous I/O. This is the fastest transport
     available for storage functions.</para>
    <para>Type: <literal>boolean</literal>, default: &false;.</para>
```


i.e. there'll be a mix of `boolean` and `bool` - does the translation system have issues with replacing literals?

2021-05-07 13:45 UTC, cmb69 commented on reference/memcached/constants.xml
> +    <para>Type: <literal>boolean</literal>, default: &false;.</para>
Oh, right, that still needs to be `&boolean;` (or `<type>bool</type>`). We should probably define `&bool;` as alias of `&boolean;`.

2021-05-07 13:47 UTC, cmb69 commented on reference/memcached/constants.xml
>     </listitem>
It does not replace literals at all (it's just about the markup).

2021-08-17 15:20 UTC, cmb69 reviewed
I'm going to slightly change the wording to better match the rest of the page, and I'm going to change all type markup.

Thanks for the PR! And thanks for the reminder!

2021-08-17 15:20 UTC, closed without merging