Added ReflectionAttribute related Documentation.
php/doc-en pull request #588
Opened 2021-05-06 03:11 UTC by mumumu

Documented `ReflectionAttribute` based on RFC and implementation.

- https://wiki.php.net/rfc/attributes_v2
- https://github.com/php/php-src/blob/php-8.0.0/ext/reflection/php_reflection.stub.php
- https://github.com/php/php-src/blob/php-8.0.0/ext/reflection/php_reflection.c

2021-06-03 02:57 UTC, Girgias commented
@beberlei can you review this?

2021-06-03 17:53 UTC, beberlei requested changes
This is really great work, thank you so very much! I have added just a few comments on better descriptions for methods and then this is good to ship from my POV.

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionattribute/isrepeated.xml
> +   Gets whether attribute is used repeatedly.
```suggestion
   Returns weather the attribute of this name could occur repeatedly on a code element.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionattribute/isrepeated.xml
> +  <refpurpose>Gets whether attribute is used repeatedly.</refpurpose>
```suggestion
  <refpurpose>Returns weather the attribute of this name could occur repeatedly on a code element.</refpurpose>
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionattribute/newinstance.xml
> +  <refpurpose>Creates a new ReflectionAttribute instance.</refpurpose>
```suggestion
  <refpurpose>Instantiates the attribute class represented by this ReflectionAttribute class and arguments.</refpurpose>
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionattribute/newinstance.xml
> +   Creates a new instance of the attribute.
```suggestion
   Instantiates the attribute class represented by this ReflectionAttribute class and arguments.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionclass/getattributes.xml
> +   Get the attributes as an array of <type>ReflectionAttribute</type>.
```suggestion
   Returns all attributes declared on this class as an array of <type>ReflectionAttribute</type>.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionclassconstant/getattributes.xml
> +   Get the attributes as an array of <type>ReflectionAttribute</type>.
```suggestion
   Returns all attributes declared on this class constant as an array of <type>ReflectionAttribute</type>.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionfunctionabstract/getattributes.xml
> +   Get the attributes as an array of <type>ReflectionAttribute</type>.
```suggestion
   Returns all attributes declared on this function or method as an array of <type>ReflectionAttribute</type>.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionparameter/getattributes.xml
> +   Get the attributes as an array of <classname>ReflectionAttribute</classname>.
```suggestion
   Returns all attributes declared on this parameter as an array of <type>ReflectionAttribute</type>.
```

2021-06-03 17:53 UTC, beberlei commented on reference/reflection/reflectionproperty/getattributes.xml
> +   Get the attributes as an array of <classname>ReflectionAttribute</classname>.
```suggestion
   Returns all attributes declared on this class property as an array of <type>ReflectionAttribute</type>.
```

2021-06-04 08:46 UTC, mumumu commented
@beberlei Thank you very much! I modified this PR in accordance with your suggestions.

2021-06-04 11:16 UTC, cmb69 approved these changes
Thank you!

While I don't like to see `&warn.undocumented.func;` in the manual, it's better than no documentation at all. :)

2021-06-04 11:20 UTC, merged

2021-06-05 12:45 UTC, mumumu commented
> While I don't like to see &warn.undocumented.func; in the manual, it's better than no documentation at all. :)

Yeah, I'll resolve `&warn.undocumented.func;` issue on #659.