Documenting the changes to syslog.filter
php/doc-en pull request #589
Opened 2021-05-06 17:31 UTC by SvenRtbg

https://github.com/php/php-src/pull/4265 restored the previous handling of multi-line log messages by adding `syslog.filter=raw`.

Relates to https://bugs.php.net/bug.php?id=77913

2021-05-07 12:36 UTC, cmb69 requested changes
Thank you!

2021-05-07 12:36 UTC, cmb69 commented on reference/errorfunc/ini.xml
> +        <simpara><literal>raw</literal> – all characters, newlines will not trigger additional log lines (identical behaviour prior to PHP 7.3)</simpara>
This should also mention that `raw` is available as of PHP 7.3.8 and PHP 7.4.0, respectively. Also better to split the long line. Maybe:
```suggestion
        <simpara>
         <literal>raw</literal> – all characters, newlines will not trigger additional log lines
         (identical behaviour prior to PHP 7.3.0).
         Available as of PHP 7.3.8 and PHP 7.4.0, respectively.
        </simpara>
```

2021-05-07 14:16 UTC, SvenRtbg commented on reference/errorfunc/ini.xml
> +        <simpara><literal>raw</literal> – all characters, newlines will not trigger additional log lines (identical behaviour prior to PHP 7.3)</simpara>
I wanted to highlight the fact that line splitting is happening in basically all other modes, which annoyed me very much. Wasn't expecting it when the filter is only talking about ... well ... filtering characters. It effectively destroys the logging context.

Line length has been shortened.

I do want to add a link from "syslog()" to here to highlight there is a setting affecting the syslog calls.

2021-05-07 14:38 UTC, SvenRtbg commented
I hope this does not mess up anything unexpectedly. I was trying to recreate what other places use for the same effect. :)

2021-05-10 16:14 UTC, cmb69 approved these changes
´Thanks!

2021-05-10 16:19 UTC, merged