Provide documentation for many ext/sodium functions
php/doc-en pull request #592
Opened 2021-05-10 14:49 UTC by paragonie-security

This provides the rudimentary documentation that was missing for many of the core libsodium functions. It still needs more example code, etc. before it's complete.

Some parameters are renamed. See https://github.com/php/php-src/pull/6969 for the corresponding php-src PR.

2021-05-11 01:55 UTC, paragonie-security commented
This is tentatively ready for review. Barring extra example snippets, feel free to suggest any changes you think would be helpful to readers or translators.

2021-05-11 11:53 UTC, Girgias approved these changes
LGTM other then the couple of nits/questions

2021-05-11 11:53 UTC, Girgias commented on reference/sodium/functions/sodium-compare.xml
> +  </para>
```suggestion
   Returns <literal>-1</literal> if <parameter>string1</parameter> is less than <parameter>string2</parameter>.
  </para>
  <para>
   Returns <literal>1</literal> if <parameter>string1</parameter> is greater than <parameter>string2</parameter>.
  </para>
```
Might as well while you're at it.

2021-05-11 11:53 UTC, Girgias commented on reference/sodium/functions/sodium-crypto-box-seal-open.xml
> +<?php
```suggestion
<![CDATA[
<?php
```

Openning CDATA element shouldn't have indentation (present else where)

2021-05-11 11:53 UTC, Girgias commented on reference/sodium/functions/sodium-crypto-generichash-init.xml
>  </refentry>
Could you drop files which only have whitespace changes? It makes it slightly harder for translations to keep their version of the manual up to date

2021-05-11 11:53 UTC, Girgias commented on reference/sodium/functions/sodium-crypto-kx-client-session-keys.xml
> +      <type>string</type>; A crypto_kx public key.
Does `kx` mean key-exchange?

2021-05-12 00:35 UTC, paragonie-security commented on reference/sodium/functions/sodium-crypto-kx-client-session-keys.xml
> +      <type>string</type>; A crypto_kx public key.
Yes

2021-05-27 14:42 UTC, Girgias approved these changes
Sorry for the delay, other than the nit this is fine.
Do you have push access on doc-en?

2021-05-27 14:42 UTC, Girgias commented on reference/sodium/functions/sodium-crypto-pwhash-scryptsalsa208sha256.xml
> +      </para>
Nit: this re-indentation is not needed

2021-05-27 14:42 UTC, Girgias commented on reference/sodium/functions/sodium-memcmp.xml
> +   Returns <literal>0</literal> if both strings are equal; <literal>-1</literal> otherwise.
Unrelated, but this cannot return `+1`?

2021-06-01 08:14 UTC, paragonie-security commented on reference/sodium/functions/sodium-memcmp.xml
> +   Returns <literal>0</literal> if both strings are equal; <literal>-1</literal> otherwise.
No, it returns `-1` according to the upstream docs.

2021-06-01 08:14 UTC, paragonie-security commented on reference/sodium/functions/sodium-crypto-pwhash-scryptsalsa208sha256.xml
> +      </para>
Okay.

2021-06-01 13:09 UTC, Girgias commented
Seems like an ID is reused in the XML (`sodium-crypto-box-seal.example.basic`), apologies for the delay forgot that maintainers need to manually run CI now

2021-06-01 13:18 UTC, cmb69 commented
> forgot that maintainers need to manually run CI now

That's only for first-time-contributors, AFAIK.

2021-06-02 10:49 UTC, cmb69 requested changes
There are at least two issues left. Can you please fix these?

2021-06-02 10:49 UTC, cmb69 commented on reference/sodium/functions/sodium-crypto-kdf-keygen.xml
> +   Generates a random key suitable for serving as the root key for <sodium>sodium_crypto_kdf_derive_from_key</sodium>.
```suggestion
   Generates a random key suitable for serving as the root key for <function>sodium_crypto_kdf_derive_from_key</function>.
```

2021-06-02 10:49 UTC, cmb69 commented on reference/sodium/functions/sodium-crypto-secretstream-xchacha20poly1305-init-push.xml
> +  </varlistentry>
```suggestion
  <simplelist>
   <member>The secretstream state, needed for further pushes</member>
   <member>The secretstream header, which needs to be provided to the recipient so they can pull data</member>
  </simplelist>
```

2021-06-04 09:09 UTC, cmb69 commented on reference/sodium/functions/sodium-crypto-secretstream-xchacha20poly1305-pull.xml
> +   </varlistentry>
```suggestion
   <itemizedlist>
    <listitem><type>string</type>; The decrypted chunk</listitem>
    <listitem>
     <type>int</type>; An optional tag (if provided during push). Possible values:
     <simplelist>
      <member>
       <constant>SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_MESSAGE</constant>:
       the most common tag, that doesn't add any information about the nature of the message.
      </member>
      <member>
       <constant>SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_FINAL</constant>:
       indicates that the message marks the end of the stream, and erases the secret key used to encrypt the previous sequence.
      </member>
      <member>
       <constant>SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_PUSH</constant>:
       indicates that the message marks the end of a set of messages, but not the end of the stream.
       For example, a huge JSON string sent as multiple chunks can use this tag to indicate to the application that the
       string is complete and that it can be decoded. But the stream itself is not closed, and more data may follow.
      </member>
      <member>
       <constant>SODIUM_CRYPTO_SECRETSTREAM_XCHACHA20POLY1305_TAG_REKEY</constant>:
       "forget" the key used to encrypt this message and the previous ones, and derive a new secret key.
      </member>
     </simplelist>
    </listitem>
   </itemizedlist>
```

2021-06-04 11:10 UTC, cmb69 commented
Thank you for the PR!

2021-06-04 11:10 UTC, closed without merging