Fold comments into interfaces page
php/doc-en pull request #594
Opened 2021-05-10 19:44 UTC by Crell

I deleted nearly all of the comments on this page and replaced them with this PR.  Most changes are based on comments that I felt were worth mentioning in some way, but not as a comment.  There's also one or two that may have been true in PHP 5.1 but are no longer true now, like the constructor mention, or coding style conventions.

2021-05-10 21:23 UTC, kamil-tekiela requested changes

2021-05-10 21:28 UTC, kamil-tekiela requested changes

2021-05-10 21:28 UTC, kamil-tekiela commented on language/oop5/interfaces.xml
> +    in interfaces is strongly discouraged. That greatly reduces the flexibility of an object implementing the
```suggestion
    in interfaces is strongly discouraged. Doing so significantly reduces the flexibility of the object implementing the
```
Isn't this better?

2021-05-10 21:28 UTC, kamil-tekiela commented on language/oop5/interfaces.xml
> +    interface.  Additionally, constructors are not enforced by inheritance rules, leading to possibly inconsistent
```suggestion
    interface.  Additionally, constructors are not enforced by inheritance rules, which can cause inconsistent
```

2021-05-10 22:34 UTC, Crell commented on language/oop5/interfaces.xml
> +   not use the same name.
Why?

2021-05-11 16:50 UTC, Crell commented on language/oop5/interfaces.xml
> +   not use the same name.
```suggestion
   implemented.  Interfaces share a namespace with classes and traits, so they may
   not use the same name.
```

2021-05-11 17:09 UTC, kamil-tekiela approved these changes

2021-05-11 17:43 UTC, kamil-tekiela commented
Did I not approve it correctly? Why did you rerequest review?

2021-05-11 20:38 UTC, cmb69 commented on language/oop5/interfaces.xml
> +    To allow developers to create multiple objects that may be used interchangeably
Isn't that true for classes as well? Maybe "create objects of different classes"?

2021-05-11 20:40 UTC, cmb69 commented on language/oop5/interfaces.xml
> +// It must not re-define the interface methods.
Wouldn't that mean that implementing any interface method is not allowed?

2021-05-11 21:23 UTC, Crell commented on language/oop5/interfaces.xml
> +// It must not re-define the interface methods.
No.  If you have an interface with 2 methods, and an abstract class that implements it, that abstract class can implement zero, one or two of those methods.  However, it may not re-specify as abstract one of the methods from the interface.  That's redundant, and apparently the linter complains about it.

2021-05-11 21:24 UTC, Crell commented on language/oop5/interfaces.xml
> +    To allow developers to create multiple objects that may be used interchangeably
```suggestion
    To allow developers to create objects of different classes that may be used interchangeably
```

2021-05-11 23:31 UTC, cmb69 commented on language/oop5/interfaces.xml
> +// It must not re-define the interface methods.
It's about the wording. I've learned that "must" means "has to", but "must not" means "is not allowed to" – that might be wrong, though.

2021-05-12 14:40 UTC, Crell commented on language/oop5/interfaces.xml
> +// It must not re-define the interface methods.
Hm.  A previous comment and my earlier (perhaps wrong) testing implied it really was a "is not allowed to."  I just tested again, though, and it appears that's not the case, at least not in current versions: https://3v4l.org/M0oAr

I'll remove that part of the comment.

2021-05-12 14:52 UTC, merged