Update ext/oci8 methodsynopses based on stubs
php/doc-en pull request #601
Opened 2021-05-13 22:13 UTC by kocsismate

2021-05-15 02:45 UTC, Girgias requested changes
Looks mostly good to me other than a couple of changes, but I haven't really followed all the stub changes discussions.

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/OCI-Lob/close.xml
> -  <methodsynopsis role="oop">
Why is the role removed here? (reason I'm asking is that it's not consistent across files)

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-bind-array-by-name.xml
>        </para>
Well this is wrong if it's not just an array but mixed

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-bind-by-name.xml
> +    Do not use <link linkend="ini.magic-quotes-gpc">magic_quotes_gpc</link> or
If you're touching this... might as well remove the mention of magic quotes

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-close.xml
> +   <type class="union"><type>bool</type><type>null</type></type><methodname>oci_close</methodname>
Amend return value section for null on failure, or rather explain when null can be returned?

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-fetch-object.xml
> +   <type class="union"><type>stdClass</type><type>null</type><type>false</type></type><methodname>oci_fetch_object</methodname>
When does this return null? Needs to be added to return section

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-free-descriptor.xml
> +   <methodparam><type>OCILob</type><parameter>lob</parameter></methodparam>
Changelog entry about resource to object conversion?

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-new-descriptor.xml
> +   <type class="union"><type>OCILob</type><type>null</type></type><methodname>oci_new_descriptor</methodname>
Amend return value section to say null on error instead of false

2021-05-15 02:45 UTC, Girgias commented on reference/oci8/functions/oci-password-change.xml
> +   <type class="union"><type>resource</type><type>bool</type></type><methodname>oci_password_change</methodname>
Return section needs to be amended, because there is no indication as to what is being returned and that type signature is confusing

2021-05-15 02:46 UTC, Girgias commented on reference/oci8/functions/oci-free-descriptor.xml
> +   <methodparam><type>OCILob</type><parameter>lob</parameter></methodparam>
Oh wait, this did use to return `OCI-Lob` previously? Just wasn't amended in the docs? In that case ignore the changelog entry (or it should be done for all other functions which went from `OCI-Lob` to `OCILob`)

2021-05-15 09:59 UTC, cmb69 commented on reference/oci8/functions/oci-free-descriptor.xml
> +   <methodparam><type>OCILob</type><parameter>lob</parameter></methodparam>
The OCILob methods already have such changelog entries; if this param is indeed of type OCILob, there should be a changelog entry on this page.

2021-05-15 10:03 UTC, kocsismate commented on reference/oci8/functions/oci-bind-by-name.xml
> +    Do not use <link linkend="ini.magic-quotes-gpc">magic_quotes_gpc</link> or
sure, I'm pleased to do so :D

2021-05-15 10:11 UTC, kocsismate commented on reference/oci8/functions/oci-free-descriptor.xml
> +   <methodparam><type>OCILob</type><parameter>lob</parameter></methodparam>
Oh, I believe this is simply a bug in the docs, the `OCILob` (aka `OCI-Lob`) has been around ages: I haven't checked it properly, but `oci_free_descriptor()` uses it at least since 2014.

2021-05-16 12:39 UTC, kocsismate commented on reference/oci8/OCI-Lob/close.xml
> -  <methodsynopsis role="oop">
`role="oop"` is only really needed when the method is the alias of a function. As It's not the case now, `gen_stub` removed this. However, now I see that `reference/oci8/OCI-Lob.xml` needs this role for the method list, so I'll revert this change.

2021-05-16 12:45 UTC, kocsismate commented on reference/oci8/functions/oci-bind-array-by-name.xml
>        </para>
Apparently the stub is wrong :(

2021-05-16 13:04 UTC, kocsismate commented on reference/oci8/functions/oci-fetch-object.xml
> +   <type class="union"><type>stdClass</type><type>null</type><type>false</type></type><methodname>oci_fetch_object</methodname>
Nice catch! It seems to me that it can't return null.

2021-05-16 13:17 UTC, kocsismate commented on reference/oci8/functions/oci-password-change.xml
> +   <type class="union"><type>resource</type><type>bool</type></type><methodname>oci_password_change</methodname>
Makes sense! Also, the overloaded signature has to be retained. :(

2021-05-16 13:43 UTC, kocsismate commented on reference/oci8/functions/oci-close.xml
> +   <type class="union"><type>bool</type><type>null</type></type><methodname>oci_close</methodname>
@cjbj Ehen working on this, I found oci8.old_oci_close_semantics (https://www.php.net/manual/en/oci8.configuration.php#ini.oci8.old-oci-close-semantics). Could I add it to the 8.1 deprecations RFC (https://wiki.php.net/rfc/deprecations_php_8_1)?

2021-05-17 10:52 UTC, cjbj commented on reference/oci8/functions/oci-close.xml
> +   <type class="union"><type>bool</type><type>null</type></type><methodname>oci_close</methodname>
@kocsismate that sounds like a plan; it's time for it to go.

(And thanks everyone for this PR)

2021-07-18 14:30 UTC, kocsismate commented
@Girgias Can you please take another look?

2021-08-17 22:04 UTC, cmb69 reviewed
From a cursory look, this seems to be okay. I don't have any experience with OCI, and I don't have the time to check PHP 7 implementation regarding potential changes. Maybe @cjbj wants to have look?

2021-08-20 07:13 UTC, cjbj commented
Gotta love the PHP community for being active on this!  Thanks all.


Visually it seemed OK but my long-working build command `php ../doc-base/configure.php && phd -o mydocs -f xhtml -P PHP -p book.oci8 -d ../doc-base/.manual.xml` failed  with
```
ERROR (/Users/cjones/p/phpdoc/doc-base/manual.xml:487:0)
End:
^
 XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook)
 xpointer(id('ingres.configuration.list')/*)

ERROR (/Users/cjones/p/phpdoc/doc-base/manual.xml:unknown)
 XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook)
 xpointer(id('mongo.configuration.list')/*)
failed.

The document didn't validate, here are the errors I got:
(If this isn't enough information, try again with --enable-xml-details)
 IDREF attribute linkend references an unknown ID "book.filepro"
 IDREF attribute linkend references an unknown ID "book.filepro"
 IDREF attribute linkend references an unknown ID "book.filepro"
[... and a bunch more]
```

Hints anyone?

2021-08-20 07:53 UTC, cmb69 commented
@cjbj, I think you need to rebase this PR onto HEAD of master (also update doc-base and phd if not already done).

2021-08-25 08:05 UTC, cjbj requested changes
> @cjbj, I think you need to rebase this PR onto HEAD of master (also update doc-base and phd if not already done).

Good call.

2021-08-25 08:05 UTC, cjbj commented on reference/oci8/functions/oci-fetch-all.xml
> +   <methodparam choice="opt"><type>int</type><parameter>flags</parameter><initializer>0</initializer></methodparam>
I don't think showing the default as 0 is helpful to readers

2021-08-25 08:13 UTC, cmb69 commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
Yes, this is supported (e.g. https://www.php.net/manual/en/function.abs.php). You likely need to fetch latest master of PhD.

2021-08-25 10:40 UTC, cjbj commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
Is it time for a new phd release?! http://doc.php.net/phd.php

2021-08-25 11:23 UTC, cmb69 commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
Not sure if we want to do that at all (for time reasons). The PhD packagist has been removed from packagist and PEAR AFAIK, and users can just use HEAD of master (which is used for the php.net doc builds anyway). A more elaborate variant of https://github.com/php/doc-en/pull/877 might be helpful as well.

2021-08-25 12:36 UTC, nikic commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
Should probably update that doc.php.net page though, to point to the master tarball on GitHub instead of releases?

2021-08-25 12:42 UTC, cmb69 commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
IMO, yes.

2021-08-25 13:12 UTC, salathe commented on reference/oci8/OCI-Collection/getElem.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>float</type><type>null</type><type>false</type></type><methodname>OCICollection::getElem</methodname>
> The PhD packagist has been removed from packagist and PEAR AFAIK…

I deleted the composer/packagist package a little while go.  The released packages are still available in PEAR via the doc.php.net channel: that has not yet been decommissioned.

> … and users can just use HEAD of master

That's what we've been informally encouraging people to do: check out PhD from Git and use that.  
It sounds like we agree that this is the way forward and can/should update documentation/websites/etc. accordingly.

2021-08-30 07:55 UTC, cjbj commented on reference/oci8/OCI-Collection/assign.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>OCICollection::assign</methodname>
That new PR doesn't seem to add the public modifier to OCICollection::assignElem ?

2021-08-30 11:53 UTC, kocsismate commented on reference/oci8/OCI-Collection/assign.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>OCICollection::assign</methodname>
No, the new PR is unrelated from `<modifier>public</modifier>`. It is only added because the script always generates the access modifiers for methods, while `OCICollection::assign()` didn't have it previously.

2021-08-30 14:29 UTC, kocsismate commented on reference/oci8/OCI-Lob/erase.xml
> +    <member><xref linkend="oci-lob.truncate"/></member>
What do you miss from `Lob::truncate()`? It looks good for me.

2021-08-30 14:32 UTC, kocsismate commented on reference/oci8/functions/oci-fetch-all.xml
> +   <methodparam choice="opt"><type>int</type><parameter>flags</parameter><initializer>0</initializer></methodparam>
Nice catch! I'll fix it in php-src as well

2021-08-30 14:46 UTC, kocsismate commented on reference/oci8/functions/oci-fetch-all.xml
> +   <methodparam choice="opt"><type>int</type><parameter>flags</parameter><initializer>0</initializer></methodparam>
Submitted https://github.com/php/php-src/pull/7429

2021-08-31 00:58 UTC, cjbj commented on reference/oci8/OCI-Collection/assign.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>OCICollection::assign</methodname>
Yay for tidy-ups!  Will you update this (601) PR with `<modifier>` for OCICollection::assignElem, Lob::truncate, getBuffering and setBuffering, and writeTemporary?

2021-08-31 19:15 UTC, kocsismate commented on reference/oci8/OCI-Collection/assign.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>OCICollection::assign</methodname>
Yes, I've just pushed all the changes. In the meanwhile, I found out why `OCILob::truncate()` wasn't autogenerated: https://github.com/php/doc-en/pull/601/commits/c3978deacfc1916860ff3cfa7bfe3d6ca601f723#diff-1ef7c5160d41789c5faf14de56219ac73b3039795ebbac6da6ebaa716cdd8d21L12 :D It's fixed now.

2021-09-14 07:39 UTC, kocsismate commented
Can I get a (hopefully) final review?

2021-09-14 11:54 UTC, Girgias requested changes
Other than the minor nit in how the changelog is written (which well we're already inconsistent about so not that important), LGTM but then I don't know anything about OCI8

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/OCI-Lob/erase.xml
> +       <parameter>offset</parameter> and <parameter>length</parameter> are nullable now.
```suggestion
       <parameter>offset</parameter> and <parameter>length</parameter> are now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/OCI-Lob/export.xml
> +       <parameter>offset</parameter> and <parameter>length</parameter> are nullable now.
```suggestion
       <parameter>offset</parameter> and <parameter>length</parameter> are now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/OCI-Lob/write.xml
> +       <parameter>length</parameter> is nullable now.
```suggestion
       <parameter>length</parameter> is now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/functions/oci-new-collection.xml
> +       <parameter>schema</parameter> is nullable now.
```suggestion
       <parameter>schema</parameter> is now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/functions/oci-lob-copy.xml
> +       <parameter>length</parameter> is nullable now.
```suggestion
       <parameter>length</parameter> is now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/functions/oci-error.xml
> +       <parameter>connection_or_statement</parameter> is nullable now.
```suggestion
       <parameter>connection_or_statement</parameter> is now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/functions/oci-connect.xml
> +       <parameter>connection_string</parameter> is nullable now.
```suggestion
       <parameter>connection_string</parameter> is now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/OCI-Lob/writeToFile.xml
> +       <parameter>offset</parameter> and <parameter>length</parameter> are nullable now.
```suggestion
       <parameter>offset</parameter> and <parameter>length</parameter> are now nullable.
```

2021-09-14 11:54 UTC, Girgias commented on reference/oci8/functions/oci-new-connect.xml
> +       <parameter>connection_string</parameter> is nullable now.
```suggestion
       <parameter>connection_string</parameter> is now nullable.
```

2021-09-22 20:56 UTC, kocsismate commented
I rebased + added a new commit (https://github.com/php/doc-en/pull/601/commits/964cbcd79331970afab871b7b8dc489e602a5b21) which fixes a few minor things (+ an overloaded signature).

I'd love if I could merge this PR soon, after 4 months. :/

2021-09-23 08:04 UTC, cjbj commented
@cmb69 @Girgias are you OK with this?  Can it be merged?

2021-09-23 12:51 UTC, Girgias approved these changes

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-name.xml
> +   Returns the name as a string, or &false; on failure.
```suggestion
   Returns the name as a string,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-client-version.xml
> +   Returns the version number as a <type>string</type>.
```suggestion
   Returns the version number as a &string;.
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-precision.xml
> +   Returns the precision as an integer, or &false; on failure.
```suggestion
   Returns the precision as an integer,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-scale.xml
> +   Returns the scale as an integer, or &false; on failure.
```suggestion
   Returns the scale as an integer,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-size.xml
>     errors.
```suggestion
   Returns the size of a <parameter>column</parameter> in bytes,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-type-raw.xml
> +   Returns Oracle's raw data type as a number, or &false; on failure.
```suggestion
   Returns Oracle's raw data type as a number,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-field-type.xml
> +   Returns the field data type as a <type>string</type> or <type>int</type>, or &false; on failure.
```suggestion
   Returns the field data type as a &string; or an &integer;,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-num-rows.xml
> +   Returns the number of rows affected as an integer, or &false; on failure.
```suggestion
   Returns the number of rows affected as an integer,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-password-change.xml
> +   the connection resource on success, or &false; on failure.
```suggestion
   the connection resource on success,&return.falseforfailure;
```

2021-09-23 12:51 UTC, Girgias commented on reference/oci8/functions/oci-password-change.xml
> +   or &false; on failure. When <parameter>connection</parameter> is provided, <function>oci_password_change</function> returns
```suggestion
   &return.falseforfailure; When <parameter>connection</parameter> is provided, <function>oci_password_change</function> returns
```

2021-09-23 12:55 UTC, merged

2021-09-23 12:57 UTC, kocsismate commented
Thank you, @Girgias !

2021-09-27 04:39 UTC, cjbj commented
Thanks _everyone_!