Generate ext/spl methodsynopses based on stubs
php/doc-en pull request #624
Opened 2021-05-23 17:11 UTC by kocsismate

2021-06-18 18:12 UTC, Girgias requested changes
Common issue is that if the return type of a function changes then this its section usually needs updating, either that or the stubs are wrong.

ArrayObject/ArrayIterator is a mess because of the whole sort functions and ArrayAccess interface shenanigans so it might make sense to split this part of.

Otherwise, except where comments are LGTM.

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getmtime.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>SplFileInfo::getMTime</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getowner.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>SplFileInfo::getOwner</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getpathinfo.xml
> +   <modifier>public</modifier> <type class="union"><type>SplFileInfo</type><type>null</type></type><methodname>SplFileInfo::getPathInfo</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getpathinfo.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>class</parameter><initializer>&null;</initializer></methodparam>
What happens when this is null?

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getperms.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>SplFileInfo::getPerms</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/getsize.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>SplFileInfo::getSize</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileinfo/gettype.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>false</type></type><methodname>SplFileInfo::getType</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileobject/current.xml
> +   <modifier>public</modifier> <type class="union"><type>string</type><type>array</type><type>false</type></type><methodname>SplFileObject::current</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileobject/fscanf.xml
> +   <modifier>public</modifier> <type class="union"><type>array</type><type>int</type><type>false</type><type>null</type></type><methodname>SplFileObject::fscanf</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileobject/getchildren.xml
> +   <modifier>public</modifier> <type>null</type><methodname>SplFileObject::getChildren</methodname>
One must love SPL, truly, but again:
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splfileobject/setcsvcontrol.xml
> +   <modifier>public</modifier> <type class="union"><type>bool</type><type>null</type></type><methodname>SplFileObject::setCsvControl</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splheap/insert.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>SplHeap::insert</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splheap/recoverfromcorruption.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>SplHeap::recoverFromCorruption</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splobjectstorage/addall.xml
> +   <modifier>public</modifier> <type>int</type><methodname>SplObjectStorage::addAll</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splobjectstorage/count.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer><constant>COUNT_NORMAL</constant></initializer></methodparam>
Param section needs to be updated, also isn't this a recent bug fix? In which case a changelog entry needs to be added

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splpriorityqueue/recoverfromcorruption.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>SplPriorityQueue::recoverFromCorruption</methodname>
Return value section needs to be updated

2021-06-18 18:12 UTC, Girgias commented on reference/spl/splpriorityqueue/setextractflags.xml
> +   <modifier>public</modifier> <type>int</type><methodname>SplPriorityQueue::setExtractFlags</methodname>
Return value section needs to be updated

2021-07-03 21:19 UTC, kocsismate commented on reference/spl/arrayiterator/asort.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>ArrayIterator::asort</methodname>
Yeah, as far as I saw, asort()  is called via `call_user_function()` :D

2021-07-03 21:31 UTC, kocsismate commented on reference/spl/arrayiterator/offsetexists.xml
> +   <methodparam><type class="union"><type>string</type><type>int</type></type><parameter>key</parameter></methodparam>
That's right, thanks for pointing out!

2021-07-03 21:37 UTC, kocsismate commented on reference/spl/directoryiterator/key.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>DirectoryIterator::key</methodname>
I have no idea if `if (intern->u.dir.dirp) {` can ever be `false`

2021-07-03 22:03 UTC, kocsismate commented on reference/spl/recursiveiteratoriterator/construct.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer>self::LEAVES_ONLY</initializer></methodparam>
Dunno, it simply comes from the stub (but i'll retain the original value)

2021-07-03 22:07 UTC, kocsismate commented on reference/spl/spldoublylinkedlist/offsetexists.xml
> +   <methodparam><type>int</type><parameter>index</parameter></methodparam>
Are you really referring to the param type or thereturn type? The param typeis `int`.

2021-07-03 22:09 UTC, kocsismate commented on reference/spl/spldoublylinkedlist/offsetset.xml
> +   <methodparam><type class="union"><type>int</type><type>null</type></type><parameter>index</parameter></methodparam>
Based on the related code comment: `/* $obj[] = ... */`

2021-07-04 02:08 UTC, Girgias commented on reference/spl/spldoublylinkedlist/offsetexists.xml
> +   <methodparam><type>int</type><parameter>index</parameter></methodparam>
Misread the diff... ignore me

2021-07-04 19:55 UTC, kocsismate commented on reference/spl/splfileinfo/getfileinfo.xml
> +   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>class</parameter><initializer>&null;</initializer></methodparam>
The default class is used ^^  which is `SplFileInfo`

2021-07-04 20:28 UTC, kocsismate commented on reference/spl/splfileobject/getchildren.xml
> +   <modifier>public</modifier> <type>null</type><methodname>SplFileObject::getChildren</methodname>
Also, this return type needs to be fixed :D

2021-07-04 20:40 UTC, kocsismate commented on reference/spl/splfileobject/setcsvcontrol.xml
> +   <modifier>public</modifier> <type class="union"><type>bool</type><type>null</type></type><methodname>SplFileObject::setCsvControl</methodname>
Actually, I believe it has a void return type

2021-07-04 20:48 UTC, kocsismate commented on reference/spl/splheap/recoverfromcorruption.xml
> +   <modifier>public</modifier> <type>bool</type><methodname>SplHeap::recoverFromCorruption</methodname>
If only we could simply use this method against corruption in my country :D

2021-07-04 20:53 UTC, kocsismate commented on reference/spl/splobjectstorage/count.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer><constant>COUNT_NORMAL</constant></initializer></methodparam>
Hmm, I can't remember about any bug like that. What do you mean?

2021-07-04 21:22 UTC, kocsismate commented on reference/spl/arrayiterator/offsetexists.xml
> +   <methodparam><type class="union"><type>string</type><type>int</type></type><parameter>key</parameter></methodparam>
Filed https://github.com/php/php-src/pull/7215

2021-07-17 09:51 UTC, kocsismate commented
I've just incorporated our latest stub fixes. @Girgias can you please take another look?

2021-08-11 14:50 UTC, Girgias requested changes
Mostly good other than two nits/clarifications.

Also it might be better to use the &falseonfailure; (or whatever its actual name is) for many of the false returns instead of writing it out by hand each time, but that's an aside.

2021-08-11 14:50 UTC, Girgias commented on reference/spl/splobjectstorage/count.xml
> +   <methodparam choice="opt"><type>int</type><parameter>mode</parameter><initializer><constant>COUNT_NORMAL</constant></initializer></methodparam>
Don't know what I thought, this behaviour exists since forever just wasn't documented. :|

2021-08-11 14:50 UTC, Girgias commented on reference/spl/splfileinfo/getpathinfo.xml
>         Name of an <classname>SplFileInfo</classname> derived class to use.
```suggestion
       Name of an <classname>SplFileInfo</classname> derived class to use, or itself if &null;.
```
Something along those lines maybe?

2021-08-11 14:50 UTC, Girgias commented on reference/spl/directoryiterator/key.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>DirectoryIterator::key</methodname>
I don't think it can be false, it either throws or returns an int, must have returned false prior to throwing

2021-08-11 21:10 UTC, kocsismate commented on reference/spl/splfileinfo/getpathinfo.xml
>         Name of an <classname>SplFileInfo</classname> derived class to use.
Yeah, works for me

2021-08-11 21:40 UTC, Girgias approved these changes

2021-08-11 21:44 UTC, merged