[80738] WIP: Update MB string functions
php/doc-en pull request #630
Opened 2021-05-25 09:07 UTC by thinkverse

This PR aims to fix the currently missing "_`needle` argument can now be empty_" changelogs in some `mb_*` functions.

If the wording in the changelog is acceptable, it will be added to the rest of the function, namely `mb_strpos`, `mb_strrpos`, `mb_strstr`, `mb_stristr`, `mb_strchr` and `mb_strichr`.

Potentially by creating a new entity `&mbstring.changelog.needle-empty;` to avoid duplication.

2021-08-23 18:35 UTC, kamil-tekiela requested changes
I see no other comments have been made in regards to this. The wording looks ok, but I would keep it simple without the literal example of an empty string. I think everyone knows how an empty string looks like.

2021-08-23 18:35 UTC, kamil-tekiela commented on reference/mbstring/functions/mb-stripos.xml
> +       <parameter>needle</parameter> now accepts <literal>""</literal> (empty string).
```suggestion
       <parameter>needle</parameter> now accepts empty string.
```

2021-08-24 11:00 UTC, kamil-tekiela commented on language-snippets.ent
> +  <parameter>needle</parameter> now accepts empty string.
```suggestion
  <parameter>needle</parameter> now accepts an empty string.
```

I think article `an` needs to be there.

2021-08-24 11:03 UTC, thinkverse commented on language-snippets.ent
> +  <parameter>needle</parameter> now accepts empty string.
Suggestion has been commited. 👍

2021-08-24 11:23 UTC, kamil-tekiela approved these changes

2021-09-17 19:53 UTC, merged

2021-09-17 19:53 UTC, kamil-tekiela commented
Thanks.