Remove old install docs
php/doc-en pull request #662
Opened 2021-06-06 03:42 UTC by Girgias

This should cover the instal/ folder with #661

2021-06-11 15:59 UTC, jhdxr requested changes

2021-06-11 15:59 UTC, jhdxr commented on install/fpm/configuration.xml
> +     PHP settings can also possible to be set in the webserver.
hmm, I think it should be `PHP settings can be set in the webserver.` if you look at grammar.

2021-06-11 15:59 UTC, jhdxr commented on install/pecl.xml
> +   package, such as unreleased extensions from git or SVN.  If you need to build such
Git

2021-06-11 16:06 UTC, cmb69 commented on install/fpm/configuration.xml
> +     PHP settings can also possible to be set in the webserver.
Much better, but stills feelsnot quit right. Maybe "PHP settings can be set in the webserver configuration"?

2021-08-06 12:33 UTC, afilina commented on install/fpm/configuration.xml
> +     PHP settings can also possible to be set in the webserver.
```suggestion
     PHP settings can be set in the webserver configuration.
```

2021-08-06 12:43 UTC, afilina commented
@Girgias The module identifier was renamed in PHP 8, so I resolved the merge conflict to `php_module` instead of `php8_module`. I also added the comment as a mergeable suggestion, so after this is done, the PR looks ready to go.

2021-09-21 15:55 UTC, mumumu commented on install/pecl.xml
> +   package, such as unreleased extensions from git or SVN.  If you need to build such
```suggestion
   package, such as unreleased extensions from git.  If you need to build such
```

2021-09-21 16:23 UTC, Girgias commented
> > I also added the comment as a mergeable suggestion, so after this is done, the PR looks ready to go.
> 
> +1. If no one is opposed to merge this PR for a while, I want to commit suggestions and process this PR.
> It is not good for PHP users, especially for newbies to leave this PR as it is.

Sorry forgot about this PR, but feel free to apply suggestions and commit. :-)

2021-09-22 16:38 UTC, merged