fixed localtime returnvalues description.
php/doc-en pull request #692
Opened 2021-06-15 23:46 UTC by mumumu

`localtime` function of PHP returns assosiative array which has  identical elements of the structure returned by the C [*1].
Also, it is inconsistent with [function description](https://github.com/php/doc-en/blob/d91e36266dddbe570789dbe218e5672fc0b85089/reference/datetime/functions/localtime.xml#L18).

[*1] https://linux.die.net/man/3/localtime

2021-06-16 08:35 UTC, kamil-tekiela commented
I don't agree with this PR. I see the language isn't clear, but I would maybe use "the" instead of "identical" and keep "of the keys" in the second line

2021-08-17 15:02 UTC, afilina requested changes
@kamil-tekiela See my suggestions. Is this what you had in mind?

2021-08-17 15:02 UTC, afilina commented on reference/datetime/functions/localtime.xml
> +   identical elements of the structure returned by the C
```suggestion
   the elements of the structure returned by the C
```

2021-08-17 15:02 UTC, afilina commented on reference/datetime/functions/localtime.xml
> +   The names of the associative array are as follows:
```suggestion
   The keys of the associative array are as follows:
```

2021-09-17 20:28 UTC, kamil-tekiela approved these changes

2021-09-17 20:28 UTC, merged

2021-09-17 20:29 UTC, kamil-tekiela commented
Thanks. I decided to merge the changes proposed by Anna