Fix issues in solr directory
php/doc-en pull request #693
Opened 2021-06-16 07:27 UTC by saundefined

2021-06-16 07:29 UTC, sashano69 approved these changes

2021-07-31 15:32 UTC, Girgias requested changes

2021-07-31 15:32 UTC, Girgias commented on reference/solr/solrquery/addgroupfield.xml
> +   Returns an <classname>SolrQuery</classname> instance.
```suggestion
   Returns an instance of <classname>SolrQuery</classname>.
```

2021-07-31 15:32 UTC, Girgias commented on reference/solr/solrquery/getexpand.xml
> +   Returns &true; if group expanding is enabled.
False otherwise?

2021-07-31 15:32 UTC, Girgias commented on reference/solr/solrquery/setgroupmain.xml
> +   Returns an <classname>SolrQuery</classname> instance.
```suggestion
   Returns an instance of <classname>SolrQuery</classname>.
```

2021-07-31 15:32 UTC, Girgias commented on reference/solr/solrquery/sethighlightformatter.xml
> +   Returns an <classname>SolrQuery</classname> instance.
```suggestion
   Returns an instance of <classname>SolrQuery</classname>.
```

2021-07-31 15:32 UTC, Girgias commented on reference/solr/solrquery/sethighlightsimplepost.xml
> +   Returns an <classname>SolrQuery</classname> instance.
```suggestion
   Returns an instance of <classname>SolrQuery</classname>.
```

2021-08-02 10:27 UTC, cmb69 approved these changes
Thank you! Maybe change the commented return value section?

2021-08-02 10:27 UTC, cmb69 commented on reference/solr/solrquery/getexpand.xml
> +   Returns &true; if group expanding is enabled,&return.falseforfailure;.
I *guess* that should be
```suggestion
   Returns whether group expanding is enabled.
```

2021-08-02 10:34 UTC, saundefined commented on reference/solr/solrquery/getexpand.xml
> +   Returns &true; if group expanding is enabled,&return.falseforfailure;.
Thank you! Looks good =)

2021-08-02 17:26 UTC, Girgias approved these changes
LGTM

2021-08-03 10:10 UTC, merged