Remove E_STRICT and other PHP 5 related information
php/doc-en pull request #730
Opened 2021-06-24 21:06 UTC by kamil-tekiela

2021-06-24 21:11 UTC, kamil-tekiela commented
The only thing I am unsure of is the new default for error_report. I left it as it was.

2021-06-25 11:19 UTC, Girgias commented
As of PHP 8.0.0 the default is E_ALL

2021-06-25 11:26 UTC, kamil-tekiela commented
@Girgias  Thanks, but we need to keep the changelog of that. I didn't know how to add the changelog as part of this PR.

2021-06-25 17:19 UTC, cmb69 commented on reference/errorfunc/functions/error-reporting.xml
> +    behaviour is equivalent to passing <constant>E_ALL</constant> constant.
Prefer American English spelling:
```suggestion
    behavior is equivalent to passing <constant>E_ALL</constant> constant.
```

2021-06-25 17:22 UTC, cmb69 commented
> I didn't know how to add the changelog as part of this PR.

If it's about the ini setting page, changelog entries can be added to the table at the top of the page.

2021-07-03 10:31 UTC, cmb69 requested changes
Thank you! Except for `dom.allowstatic` this looks good to me.

2021-07-03 10:31 UTC, cmb69 commented on language-snippets.ent
> +<!ENTITY dom.allowstatic '<para xmlns="http://docbook.org/ns/docbook">This method <emphasis>may</emphasis> be called statically, but will issue an <constant>E_DEPRECATED</constant> error.</para>'>
It's E_DEPRECATED in PHP 7, but an `Error` as of PHP 8.0.0.

2021-07-03 11:20 UTC, kamil-tekiela commented on language-snippets.ent
> +<!ENTITY dom.allowstatic '<para xmlns="http://docbook.org/ns/docbook">This method <emphasis>may</emphasis> be called statically, but will issue an <constant>E_DEPRECATED</constant> error.</para>'>
Is this acceptable or should I mention that it triggers an error now?

2021-07-03 11:31 UTC, cmb69 commented on language-snippets.ent
> +<!ENTITY dom.allowstatic '<para xmlns="http://docbook.org/ns/docbook">This method <emphasis>may</emphasis> be called statically, but will issue an <constant>E_DEPRECATED</constant> error.</para>'>
I think it's better to state that it triggers an error now.

2021-07-03 11:59 UTC, kamil-tekiela commented on language-snippets.ent
> +As of PHP 8.0.0 calling this method statically emits an <constant>E_ERROR</constant> level error</para>'>
How about now? @cmb69

2021-07-03 12:19 UTC, cmb69 commented on language-snippets.ent
> +As of PHP 8.0.0 calling this method statically emits an <constant>E_ERROR</constant> level error</para>'>
Hmm, isn't it rather an `Error` exception?

2021-07-03 15:32 UTC, kamil-tekiela commented on language-snippets.ent
> +As of PHP 8.0.0 calling this method statically emits an <constant>E_ERROR</constant> level error</para>'>
It's not an exception. It's a an error of severity `E_ERROR`. Compare:
```
error_reporting(E_ALL & ~E_ERROR);
$doc = DOMDocument::loadXML('<root><node/></root>');
echo $doc->saveXML();
```
and 
```
try {
    $doc = DOMDocument::loadXML('<root><node/></root>');
    echo $doc->saveXML();
} catch (Exception $e) {
    echo $e->getMessage();
}
```
Of course, `Error` is a type of exception in PHP, but it does not inherit from `Exception`.

2021-07-03 17:59 UTC, Girgias commented on language-snippets.ent
> +As of PHP 8.0.0 calling this method statically emits an <constant>E_ERROR</constant> level error</para>'>
But one can catch an `Error` whereas one cannot catch an E_ERROR

2021-07-04 18:02 UTC, kamil-tekiela commented on language-snippets.ent
> +As of PHP 8.0.0 calling this method statically emits an <constant>E_ERROR</constant> level error</para>'>
Changed to "throws an <classname>Error</classname> exception"

2021-08-17 16:15 UTC, cmb69 approved these changes
Thank you!

2021-08-17 16:56 UTC, merged