is_numeric: See also filter_var (specifically with validation_filters)
php/doc-en pull request #735
Opened 2021-06-26 14:51 UTC by AllenJB

filter_var validation filters provide for more specific filtering than is_numeric (such as "is integer").

I've avoided the <function> tag here to specifically link to validation filters. If you can think of a better alternative, let me know.

2021-06-26 23:14 UTC, Girgias requested changes

2021-06-26 23:14 UTC, Girgias commented on reference/var/functions/is-numeric.xml
> +    <member><link linkend="function.filter-var">filter_var</link> - Filters a variable with <link linkend="filter.filters.validate">validation filters</link></member>
```suggestion
    <member><function>filter_var</function> - Filters a variable with <link linkend="filter.filters.validate">validation filters</link></member>
```

The function tag takes care of auto linking functions.

2021-06-27 09:38 UTC, AllenJB commented on reference/var/functions/is-numeric.xml
> +    <member><link linkend="function.filter-var">filter_var</link> - Filters a variable with <link linkend="filter.filters.validate">validation filters</link></member>
The function tag also generates a description along side the link. If the suggested change were implemented, it would look something like:

* **filter_var** - Filters a variable with a specified filter - Filters a variable with **validation filters**

I thought of using:

`<member><function>filter_var</function> (see specifically the <link linkend="filter.filters.validate">validation filters</link>)</member>`

Which results in:

* **filter_var** - Filters a variable with a specific filter (see specifically the **validation filters**)

But this feels a bit disjointed and long-winded to me.

2021-06-27 11:33 UTC, cmb69 commented on reference/var/functions/is-numeric.xml
> +    <member><link linkend="function.filter-var">filter_var</link> - Filters a variable with <link linkend="filter.filters.validate">validation filters</link></member>
Maybe don't mention filter_var at all?

2021-06-27 11:52 UTC, AllenJB commented on reference/var/functions/is-numeric.xml
> +    <member><link linkend="function.filter-var">filter_var</link> - Filters a variable with <link linkend="filter.filters.validate">validation filters</link></member>
I believe that would cause confusion because the validation filters page does not link back to filter_var / indicate how to use them. The only link back is by following breadcrumbs, which I don't think is obvious enough.

2022-12-23 21:45 UTC, afilina commented
Bumping reviewers: @Girgias @cmb69

2022-12-24 11:46 UTC, cmb69 commented
`filter_var()` has already been linked by #1744. In my opinion, we can leave it at this.

2022-12-24 11:46 UTC, closed without merging