Cubrid enhancement
php/doc-en pull request #740
Opened 2021-06-28 07:46 UTC by saundefined

Mostly changed `return values` section.
Some values wrapped with `literal` tag.

2021-07-02 14:20 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-get-charset.xml
> -   A string that represents the CUBRID connection charset; on success.
The semicolon makes the sentence; weird. Can you fix it, please?

2021-07-02 14:20 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-get-client-info.xml
> -   A string that represents the client library version; on success.
ditto

2021-07-02 14:20 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-get-db-parameter.xml
> +   This function returns the CUBRID database parameters or it returns &false; on
Why not use `&return.falseforfailure;` here also?

2021-07-02 14:21 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-get-server-info.xml
> +   A string that represents the CUBRID server version; on success,&return.falseforfailure;.
Ditto

2021-07-02 14:22 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-lob-close.xml
> +  <listitem><para>LOB identifier array return from <function>cubrid_lob_get</function>.</para></listitem>
`returned` maybe?

2021-07-02 14:23 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-lob2-read.xml
> +    &null; on failure.
Not sure we need 3 paragraphs for that.

2021-07-02 14:24 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-move-cursor.xml
> +   <parameter>origin</parameter> argument, you can use <literal>CUBRID_CURSOR_FIRST</literal>
What happened to indentation here?

2021-07-02 14:25 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-num-rows.xml
> +    you have to use the <function>cubrid_affected_rows</function> function.
If we are touching this paragraph at all, the please rewrite it in a non-personal style, i.e. avoid `you`

2021-07-02 14:27 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-schema.xml
> +   information on certain attribute (can be used only with <literal>CUBRID_SCH_ATTR_PRIVILEGE</literal>).
I'd rewrite this paragraph too, avoid `you` and the phrase "get information on certain attribute" doesn't sound very grammatically correct to me.

2021-07-03 09:09 UTC, saundefined commented
@kamil-tekiela, thank you!

2021-07-03 12:21 UTC, kamil-tekiela commented on reference/cubrid/functions/cubrid-move-cursor.xml
>      location of the result, or CUBRID_CURSOR_LAST for the last part of the
Why did you remove `<literal>` around this constant?

2021-07-03 12:29 UTC, cmb69 commented on reference/cubrid/functions/cubrid-move-cursor.xml
>      location of the result, or CUBRID_CURSOR_LAST for the last part of the
That should probably be `<constant>` throughout the cubrid book.

2021-07-03 12:47 UTC, saundefined commented on reference/cubrid/functions/cubrid-move-cursor.xml
>      location of the result, or CUBRID_CURSOR_LAST for the last part of the
@cmb, thanks! fixed that and the rest

2021-07-03 13:04 UTC, kamil-tekiela requested changes

2021-07-03 13:30 UTC, kamil-tekiela approved these changes

2021-07-03 13:47 UTC, cmb69 approved these changes

2021-07-03 15:57 UTC, merged