add eventConfig missing method
php/doc-en pull request #810
Opened 2021-07-22 08:51 UTC by mowangjuanzi

1. add `eventConfig::setFlags`. Source reference: https://bitbucket.org/osmanov/pecl-event/src/1fa696a0dc145d5d5f40a144f7a27be31eaf14a5/php8/classes/event_config.c#lines-135
2. add `eventConfig::requireFeatures` missing return value description
3. add `EventConfig::setMaxDispatchInterval` required pecl event version

2021-07-22 09:19 UTC, sy-records requested changes

2021-07-22 09:19 UTC, sy-records commented on reference/event/eventconfig/requirefeatures.xml
> +   Returns &true; on success, otherwise &false;.
You can just use `&return.success;`

```suggestion
   &return.success;
```

2021-07-22 09:19 UTC, sy-records commented on reference/event/eventconfig/setflags.xml
> + </refsect1>
Repeat, the same can be done with `&return.success;`
```suggestion
<refsect1 role="returnvalues">
  &reftitle.returnvalues;
  <para>
   &return.success;
  </para>
 </refsect1>
```

2021-07-22 09:21 UTC, sy-records requested changes

2021-07-22 09:21 UTC, sy-records commented on reference/event/eventconfig/setflags.xml
> +<refentry xml:id="eventconfig.requirefeatures" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
You need to change the id.

```suggestion
<refentry xml:id="eventconfig.setflags" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2021-07-22 13:22 UTC, mowangjuanzi commented on reference/event/eventconfig/requirefeatures.xml
> +   Returns &true; on success, otherwise &false;.
Is this a shorthand?

2021-07-22 14:03 UTC, cmb69 commented on reference/event/eventconfig/requirefeatures.xml
> +   Returns &true; on success, otherwise &false;.
Yes; see https://github.com/php/doc-en/blob/668b6fc28891062b1c96202009ccb70b7147740d/language-snippets.ent#L648.

2021-07-22 15:04 UTC, mowangjuanzi commented on reference/event/eventconfig/requirefeatures.xml
> +   Returns &true; on success, otherwise &false;.
i see.

2021-07-23 01:24 UTC, sy-records requested changes

2021-07-23 01:24 UTC, sy-records commented on reference/event/eventconfig/setflags.xml
> +      One of <literal>EventBase::LOOP_*</literal>constants.
Need a space 

```suggestion
      One of <literal>EventBase::LOOP_*</literal> constants. 
```

2021-07-23 02:19 UTC, sy-records approved these changes
Thank you.

2021-07-23 02:19 UTC, merged