Document Flexible heredoc/nowdoc.
php/doc-en pull request #829
Opened 2021-07-29 14:44 UTC by mumumu

Newly documented Flexible heredoc/nowdoc, based on RFC [*1], 

Closes #741

[*1] https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

2021-07-30 12:56 UTC, cmb69 requested changes
Thank you very much! It's about time that we document this.

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    If the closing identifier is indented further than any lines of the body, then a ParseError will be thrown:
```suggestion
    If the closing identifier is indented further than any lines of the body, then a <classname>ParseError</classname> will be thrown:
```

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    Prior to PHP 7.3.0, The closing identifier <emphasis>must</emphasis>
```suggestion
    Prior to PHP 7.3.0, the closing identifier <emphasis>must</emphasis>
```

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    <title>Closing identifier must not be indented further than any lines of the body, as of PHP 7.3.0</title>
The "as of PHP 7.3.0" appears to be superfluous, since prior to PHP 7.3.0 the closing indentifier must not be indented at all. Maybe move the "as of PHP 7.3.0" into a `<para>` after the `<title>`?

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    be thrown.
Please don't use personalization ("you") in the manual. Reword to passive voice instead. Something like "If the closing identifier is indented, tabs can be used as well, …"

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    <title>Different indentation for body (spaces) closing identifier, as of PHP 7.3.0</title>
The same concerns regarding the "as of PHP 7.3.0" in the title as above.

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +     To avoid this problem, It is safe for you to follow the simple rule:
```suggestion
     To avoid this problem, it is safe for you to follow the simple rule:
```

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +     of the text</emphasis>
```suggestion
     of the text</emphasis>.
```

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +     as the closing identifier and causes ParseError.
```suggestion
     as the closing identifier and causes a <classname>ParseError</classname>.
```

2021-07-30 12:56 UTC, cmb69 commented on language/types/string.xml
> +    <title>You can continue expression after closing identifier.</title>
```suggestion
    <title>Continuing an expression after a closing identifier</title>
```

2021-08-08 15:01 UTC, mumumu commented on language/types/string.xml
> +    <title>Closing identifier must not be indented further than any lines of the body, as of PHP 7.3.0</title>
> The "as of PHP 7.3.0" appears to be superfluous

Agree. I simply deleted `as of PHP 7.3.0` from title.

2021-08-08 15:02 UTC, mumumu commented on language/types/string.xml
> +    be thrown.
> Please don't use personalization ("you") in the manual. 

OK. Applied your suggestion, too.

2021-08-08 15:29 UTC, cmb69 approved these changes
Thank you!

2021-08-08 15:39 UTC, merged