Generate ext/dom class synopses based on stubs
php/doc-en pull request #839
Opened 2021-08-04 16:59 UTC by kocsismate

2021-08-05 08:35 UTC, kocsismate commented
@salathe Can you please clarify your concerns?

2021-08-17 16:22 UTC, salathe commented
On initially visually scanning the changes, I stopped reading when the very first file in the list (`domattr.xml`) _looked_ to be introducing mistakes. (Whether they really are mistakes, or not, remains to be seen.)

At the time, I didn't have any particular desire to continue on down that rabbit hole, so just gave a thumbs down and moved on.  I didn't reply to Máté, because I don't want to clarify my concerns.  And now, I continue to not have any particular desire to go down this rabbit hole, and so won't be giving a review _at this time_ either.

2021-08-17 16:31 UTC, cmb69 commented
A problem with reviewing this PR is that it is noisy (particularly the re-ordering of the properties). OTOH, it is done (based on?) an automated script, so later changes won't probably shuffle again. Still, a lot to review.

2021-08-17 16:52 UTC, kocsismate commented
> A problem with reviewing this PR is that it is noisy (particularly the re-ordering of the properties). OTOH, it is done (based on?) an automated script, so later changes won't probably shuffle again. Still, a lot to review.

Yes, the command I used is ``./php-src/build/gen_stub.php --replace-classsynopses ./ext/dom ./ext/spl ./Zend/ ./ext/json  ./doc-en/reference/dom`

I agree that the property reordering makes the PR noisy. We could change the order of properties in php-src, but I'm not sure which order makes more sense, so I'm eager for suggestions. The only thing I'd like to avoid is to make manual adjustments to the generated output, since it would make subsequent class synopsis page regenerations very inconvenient.

2021-08-17 17:17 UTC, Girgias commented
This LGTM, I think its more likely the manual was mistaken than the stubs but it might just be wise to double checked all the ``mixed`` property types, as if they are readonly I would imagine that restricting their type should also be possible.

2021-08-19 12:11 UTC, salathe requested changes
I managed to get past the first file this time (to 6/20 files), and there seem to be a few issues common to many files in this PR.  

See inline comments for specific details.

**General note**

Reviewing this PR _critically_ has been made more difficult than it really ought to be, due to the mixing of:
a) whitespace/formatting-only changes
b) consistency changes (e.g. adding `xi:fallback`s)
c) re-ordering of lists of things (e.g. `classref` attributes, lists of things)
d) actual content changes (e.g. new interfaces, properties, etc.)

I have very likely missed issues in the latter (let's be honest, most important) category of changes due to the others, even in the few files I've looked through thus far.   Also, if it's not clear already, please consider this review _incomplete_.  I encourage other reviewers to cast a _critial_ eye on these changes.

2021-08-19 12:27 UTC, cmb69 commented on reference/dom/domattr.xml
>       <modifier>readonly</modifier>
Right: https://3v4l.org/Fe0kG and https://dom.spec.whatwg.org/#interface-attr. Needs to be fixed in [the stub file](https://heap.space/xref/php-src/ext/dom/php_dom.stub.php?r=ca94d55a#288).

2021-08-19 12:39 UTC, cmb69 commented on reference/dom/domcharacterdata.xml
> +     <modifier>readonly</modifier>
Right: https://3v4l.org/UgSEZ and https://dom.spec.whatwg.org/#interface-characterdata. Needs to be fixed in the [stub file](https://heap.space/xref/php-src/ext/dom/php_dom.stub.php?r=ca94d55a#241).

2021-08-25 07:14 UTC, kocsismate commented on reference/dom/domattr.xml
> +    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.domnode')/db:partintro/db:section/db:classsynopsis/db:fieldsynopsis[preceding-sibling::db:classsynopsisinfo[1][@ro
No, this is not a mistake: https://github.com/php/php-src/pull/7340#discussion_r682800971 I simply didn't manage to encode the string properly, so I went without the entity. I'll try to retain `&Properties;`, and I'll appreciate any help, if anyone has a clue what to do.

2021-08-25 07:21 UTC, kocsismate commented on reference/dom/domdocument.xml
> +    </varlistentry>
Thanks for the hint, I didn't notice it's ordered alphabetically. I can update the script to generate an ordered property list, and doing so will reduce the number of changes significantly.

2021-08-25 07:26 UTC, kocsismate commented on reference/dom/domattr.xml
>       <modifier>readonly</modifier>
Thanks! I've just pushed https://github.com/php/php-src/commit/cdf2f3eb165f0ceb1e58405b20146a5acdec4605 to fix both issues.

2021-08-25 08:54 UTC, salathe commented on reference/dom/domattr.xml
> +    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.domnode')/db:partintro/db:section/db:classsynopsis/db:fieldsynopsis[preceding-sibling::db:classsynopsisinfo[1][@ro
Opened https://github.com/php/php-src/pull/7400 to address this `gen_stubs.php` issue.

2021-09-02 16:39 UTC, kocsismate commented on reference/dom/domdocument.xml
> +    </varlistentry>
Thanks! I ordered the varlistentries alphabetically.

2021-09-02 16:41 UTC, kocsismate commented
> consistency changes (e.g. adding xi:fallback)

When should I add `xi:fallbacks` elements? Currently, I always add them. What issue do extraneous `fi:fallback`s cause?

2022-04-06 17:15 UTC, closed without merging