Updating mysqli: set_charset
php/doc-en pull request #844
Opened 2021-08-07 14:16 UTC by kamil-tekiela

I am not sure if the first note on this page is still relevant.

2021-08-07 17:57 UTC, zors1 commented
I know that it's not directly related to this PR, but isn't `&style.oop;` missing a hyphen?

![image](https://user-images.githubusercontent.com/78965690/128609640-acf4abb7-fe4b-4431-b4e0-0dfd59958218.png)

2021-08-07 18:27 UTC, kamil-tekiela commented
@zors1 Can you explain where do you think the hyphen is missing? What should it look like with a hyphen?

2021-08-07 18:31 UTC, zors1 commented
>  Do you mean that is should be "Object-oriented style"?

Yes, I'm sorry my previous comment wasn't clear enough.

2021-08-07 18:34 UTC, kamil-tekiela commented
Then, yes. It should be "Object-oriented", but that's not part of this PR.

2021-08-17 15:14 UTC, afilina commented on reference/mysqli/mysqli/set-charset.xml
> +       The character set to be set.
Maybe a nitpick, but having the word "set" twice makes it a bit harder to read. Perhaps "The desired character set." or "The character set to be used". We already say "Sets the character set to be used" in the description; the second option merely reiterates that in context.

2021-08-17 15:15 UTC, afilina requested changes
Other than the one comment, LGTM.

2021-08-17 17:01 UTC, kamil-tekiela commented on reference/mysqli/mysqli/set-charset.xml
> +       The character set to be set.
I agree. I used "The desired character set."

2021-08-17 17:52 UTC, afilina approved these changes

2021-08-17 17:52 UTC, merged