Documentation for net_get_interfaces()
php/doc-en pull request #847
Opened 2021-08-08 16:32 UTC by tored

Relates to #663 
Resolves https://bugs.php.net/bug.php?id=79251

Unsure where to put documentation for this function because it is a brand new file (`ext/standard/net.c`) in `php-src`, but I put it into **Other Services / Network / Network Functions**

Requires  more documentation regarding flags and family attributes for the unicast subarray.

2021-09-15 20:26 UTC, Girgias requested changes
I don't really now how the function is meant to behave but a couple of nits.

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +<!-- $Revision$ -->
This comment can be removed.

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +   <void />
```suggestion
   <void/>
```

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +   Issues an E_WARNING on failure to get interface information.
```suggestion
   Emits an <constant>E_WARNING</constant> on failure to get interface information.
```

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +       <entry>Meaning</entry>
```suggestion
       <entry>&Name;</entry>
       <entry>&Description;</entry>
```

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +       <entry>Meaning</entry>
```suggestion
       <entry>&Name;</entry>
       <entry>&Description;</entry>
```

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +   This function returns an associative array where key  is the name of the interface and
```suggestion
   Returns an associative &array; where the key is the name of the interface and
```

2021-09-15 20:26 UTC, Girgias commented on reference/network/functions/net-get-interfaces.xml
> +   &return.falseforfailure;. Each interface associative array contains
```suggestion
   &return.falseforfailure;.
  </para>
  <para>
   Each interface associative array contains:
```

2021-09-15 20:46 UTC, tored commented
> I don't really now how the function is meant to behave but a couple of nits.

My pull request isn't 100% done, but the function is a bit weird, the outer structure is for POSIX, and the inner structure (unicast) is mostly Windows. Mixing both results in the same documentation can be confusing, because some keys  is not even present on the other platform. Name for the adapter differs too, if I remember correctly it is a GUID on Windows but a string name on POSIX. And I think some field refers to a platform specific constant.

Should we separate the result for POSIX and Windows? Or should we still try to keep everything together but add notes that some properties does not exist on the other platform? Can be messy.  I personally think that separating POSIX and Windows two different tables is better to avoid the confusion, but I'm not aware if php-doc does this for other functions.

How do you usually do this in the doc group?



The outer structure is mainly for

2021-09-15 21:30 UTC, tored commented
Okay, I remembered wrong, it is mostly Windows that uses the outer structure.

Here is an example for Linux

```
array(2) {
  ["lo"]=>
  array(2) {
    ["unicast"]=>
    array(3) {
      [0]=>
      array(2) {
        ["flags"]=>
        int(65609)
        ["family"]=>
        int(17)
      }
      [1]=>
      array(4) {
        ["flags"]=>
        int(65609)
        ["family"]=>
        int(2)
        ["address"]=>
        string(9) "127.0.0.1"
        ["netmask"]=>
        string(9) "255.0.0.0"
      }
      [2]=>
      array(4) {
        ["flags"]=>
        int(65609)
        ["family"]=>
        int(10)
        ["address"]=>
        string(3) "::1"
        ["netmask"]=>
        string(39) "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
      }
    }
    ["up"]=>
    bool(true)
  }
  ["enp0s3"]=>
  array(2) {
    ["unicast"]=>
    array(3) {
      [0]=>
      array(2) {
        ["flags"]=>
        int(69699)
        ["family"]=>
        int(17)
      }
      [1]=>
      array(5) {
        ["flags"]=>
        int(69699)
        ["family"]=>
        int(2)
        ["address"]=>
        string(9) "10.0.2.15"
        ["netmask"]=>
        string(13) "255.255.255.0"
        ["broadcast"]=>
        string(10) "10.0.2.255"
      }
      [2]=>
      array(4) {
        ["flags"]=>
        int(69699)
        ["family"]=>
        int(10)
        ["address"]=>
        string(24) "fe80::a00:27ff:fe35:9693"
        ["netmask"]=>
        string(21) "ffff:ffff:ffff:ffff::"
      }
    }
    ["up"]=>
    bool(true)
  }
}
```

Windows

```
array(2) {
  ["{AE348A58-926B-4BE4-ADA1-0E4F74BF1A4A}"]=>
  array(5) {
    ["description"]=>
    string(33) "Microsoft Hyper-V Network Adapter"
    ["mac"]=>
    string(17) "00:15:5D:0B:27:88"
    ["mtu"]=>
    int(1500)
    ["unicast"]=>
    array(2) {
      [0]=>
      array(4) {
        ["flags"]=>
        int(453)
        ["family"]=>
        int(23)
        ["address"]=>
        string(25) "fe80::dc54:f386:1c72:5604"
        ["netmask"]=>
        string(21) "ffff:ffff:ffff:ffff::"
      }
      [1]=>
      array(4) {
        ["flags"]=>
        int(453)
        ["family"]=>
        int(2)
        ["address"]=>
        string(14) "172.23.193.175"
        ["netmask"]=>
        string(13) "255.255.240.0"
      }
    }
    ["up"]=>
    bool(true)
  }
  ["{D62CD1F7-07AF-11EC-B28D-806E6F6E6963}"]=>
  array(4) {
    ["description"]=>
    string(29) "Software Loopback Interface 1"
    ["mtu"]=>
    int(4294967295)
    ["unicast"]=>
    array(2) {
      [0]=>
      array(4) {
        ["flags"]=>
        int(385)
        ["family"]=>
        int(23)
        ["address"]=>
        string(3) "::1"
        ["netmask"]=>
        string(39) "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
      }
      [1]=>
      array(4) {
        ["flags"]=>
        int(385)
        ["family"]=>
        int(2)
        ["address"]=>
        string(9) "127.0.0.1"
        ["netmask"]=>
        string(9) "255.0.0.0"
      }
    }
    ["up"]=>
    bool(true)
  }
}
```

2021-09-15 21:36 UTC, cmb69 commented
If the results are grossly different on Windows and other platforms, it makes sense to separate the results. Not sure if that's done elsewhere, but function results may not be that different for other functions.

2021-12-15 16:33 UTC, cmb69 commented
While I think this doc page can be improved, given that the function is available for more than three years, this PR is a reasonable start. Thank you very much! I'm going to tweak a bit (most notably regarding the Windows/POSIX differences, which don't appear to be that grave).

2021-12-15 16:33 UTC, cmb69 commented on reference/network/functions/net-get-interfaces.xml
> +<!-- $Revision$ -->
Will do.

2021-12-15 16:33 UTC, closed without merging