Add documentation for var_representation PECL
php/doc-en pull request #885
Opened 2021-08-28 00:39 UTC by TysonAndre

Information about the extension can be found at https://github.com/TysonAndre/var_representation https://pecl.php.net/var_representation - it was proposed at https://marc.info/?l=pecl-dev&m=162400655627665&w=2 in June.

2021-08-28 01:47 UTC, Girgias requested changes
Couple of nits.

Also wondering if the comments at the end of each file as still necessary.

2021-08-28 01:47 UTC, Girgias commented on reference/var_representation/constants.xml
> +     (<type>integer</type>)
Should be
```suggestion
     (<type>int</type>)
```
here and bellow

2021-08-28 01:47 UTC, Girgias commented on reference/var_representation/book.xml
> +   The var_representation extension provides a compact alternative to var_export that properly escapes control characters.
```suggestion
   The var_representation extension provides a compact alternative to <function>var_export</function> that properly escapes control characters.
```

2021-08-28 01:47 UTC, Girgias commented on reference/var_representation/book.xml
> +
This tag is now unnecessary

2021-08-28 01:47 UTC, Girgias commented on reference/var_representation/functions/var-representation.xml
> +       The variable you want to generate a representation of.
```suggestion
       The variable to generate a representation of.
```
Please avoid the usage of "you".

2021-08-28 01:47 UTC, Girgias commented on reference/var_representation/functions/var-representation.xml
> +    <title>Exporting stdClass</title>
```suggestion
    <title>Exporting <classname>stdClass</classname></title>
```

2021-08-28 01:50 UTC, TysonAndre commented on reference/var_representation/book.xml
> +
Will fix. This is automatically generated - the scripts in doc-base should be updated to remove $Revision$, $Id$, etc.

2021-08-28 01:52 UTC, TysonAndre commented on reference/var_representation/functions/var-representation.xml
> +       The variable you want to generate a representation of.
This was based on https://www.php.net/manual/en/function.var-export.php#refsect1-function.var-export-parameters so I forgot about that writing rule

2021-08-28 02:11 UTC, TysonAndre commented
> Also wondering if the comments at the end of each file as still necessary.

It's what doc-base emits in the skeleton so I consider changing that a separate discussion/project needing more input. `.editorconfig` would work on more IDEs (and I see one's already added) but you'd have to install a plugin for it in vim, though I've already done that.

Maybe some of the regular commiters use the settings, but I'm not sure if it's making much of a difference other than indentation.

In some cases the `sw=1` common settings are going to save time preventing bad identation if a new contributor uses vim/a vim-aware IDE

2021-08-28 10:14 UTC, Girgias commented
> > Also wondering if the comments at the end of each file as still necessary.
> 
> It's what doc-base emits in the skeleton so I consider changing that a separate discussion/project needing more input. `.editorconfig` would work on more IDEs (and I see one's already added) but you'd have to install a plugin for it in vim, though I've already done that.
> 
> Maybe some of the regular commiters use the settings, but I'm not sure if it's making much of a difference other than indentation.
> 
> In some cases the `sw=1` common settings are going to save time preventing bad identation if a new contributor uses vim/a vim-aware IDE

Oh for sure I wasn't saying that it should be done now, but it's an interesting discussion to have if/when we get a way to skip commits for revcheck.

However can you run the ``doc-base/scripts/qa/extensions.xml.php`` QA script so that the extension gets listed in the appendice (this is what is causing the build failure)

2021-08-28 10:17 UTC, Girgias commented on reference/var_representation/functions/var-representation.xml
> +   <type class="union">string</type><methodname>var_representation</methodname>
```suggestion
   <type>string</type><methodname>var_representation</methodname>
```
Probably? Not exactly sure how those are meant to work any more @cmb69 is it fine to have a single type in a union?

2021-09-02 23:34 UTC, TysonAndre commented on reference/var_representation/functions/var-representation.xml
> +   <type class="union">string</type><methodname>var_representation</methodname>
Removed, misread something else when basing this change on it

2021-09-02 23:35 UTC, TysonAndre commented
> However can you run the doc-base/scripts/qa/extensions.xml.php QA script so that the extension gets listed in the appendice (this is what is causing the build failure)

Done. doc-base is the next cause of the new build failure (which I believe would be fixed by https://github.com/php/doc-base/pull/43)

```
> 
ERROR (/home/runner/work/doc-en/doc-en/doc-base/manual.xml:378:0)
  <set xml:id="refs.webservice">
^
 IDREF attribute linkend references an unknown ID "book.var_representation"
```

2021-09-16 16:50 UTC, TysonAndre commented
Review comments have been addressed.

Are there any objections or any more remaining tasks before this and the doc-base PR can be merged?

2021-09-16 17:14 UTC, merged

2021-09-16 17:14 UTC, cmb69 commented
Thank you!