Generate methodsynopses based on stubs for recent changes
php/doc-en pull request #903
Opened 2021-09-04 14:25 UTC by kocsismate

2021-09-14 16:50 UTC, thinkverse commented
Adding this list of the references that are included in this PR. Might be useful if someone wants a quick peek at references to not change if they want to do similar work and fix up other method synopsis, which could limit potential conflicts.

- datetime
- dir
- dom
- ldap
- mysqli
- reflection
- session
- snmp

2021-09-30 12:13 UTC, kamil-tekiela requested changes

2021-10-01 14:45 UTC, kocsismate commented on reference/ldap/functions/ldap-free-result.xml
> +   <methodparam><type>resource</type><parameter>ldap</parameter></methodparam>
It used to be true that time when I generated this methodsynopsis, because we were only documenting PHP 8.0.

2021-10-01 14:54 UTC, kocsismate commented on reference/datetime/datetimeinterface/gettimestamp.xml
> +   <modifier>public</modifier> <type class="union"><type>int</type><type>false</type></type><methodname>DateTimeInterface::getTimestamp</methodname>
I've just rebased to fix the conflicts and address this comment

2021-10-01 15:20 UTC, kamil-tekiela commented on reference/ldap/functions/ldap-free-result.xml
> +   <methodparam><type>resource</type><parameter>ldap</parameter></methodparam>
Ok, that makes sense. Although that is not entirely possible and we are changing the manual back and forth. The next PR will have to revert this change.

2021-10-01 15:20 UTC, kamil-tekiela approved these changes
I see no other issues. Thank you.

2021-10-01 15:22 UTC, kocsismate commented on reference/ldap/functions/ldap-free-result.xml
> +   <methodparam><type>resource</type><parameter>ldap</parameter></methodparam>
(This change completely went away when I rebased to master)

2021-10-01 15:23 UTC, merged

2021-10-01 15:24 UTC, kamil-tekiela commented on reference/ldap/functions/ldap-free-result.xml
> +   <methodparam><type>resource</type><parameter>ldap</parameter></methodparam>
Even better.