Generate ext/pgsql methodsynopses based on stubs
php/doc-en pull request #915
Opened 2021-09-05 18:42 UTC by kocsismate

2021-09-23 13:14 UTC, Girgias commented
Does it make sense to regenerate this for PHP 8.1?

2021-09-23 13:22 UTC, kocsismate commented
Yeah maybe... So we can add PHP 8.1 changes, right?

On one hand, regenerating for PHP 8.1 would make the PR even larger, thus decreasing its chances for a proper review in the close future ^^ On the other hand, translators don't have to implement a lot of changes twice.. What's your preference?

2021-09-23 13:33 UTC, cmb69 commented
It might be better to have two separate PRs (i.e. address this one first).

2021-09-30 11:58 UTC, saundefined commented
Can we merge this PR to make changes for PHP 8.1
or is there something preventing us from doing this now?

2021-09-30 12:05 UTC, kocsismate commented
> or is there something preventing us from doing this now?

Yeah, the lack of a proper code review ^^ I hope that someone finds some time for it. I agree that's it's a bit too much at once.

2021-09-30 12:52 UTC, kamil-tekiela commented
Before we review it, would it be possible to update it from the stub changes? I see no point in reviewing resource signatures when we need to maintain objects now.

2021-09-30 14:33 UTC, Girgias requested changes
Well, pgsql is truly something.

2021-09-30 14:33 UTC, Girgias commented on reference/pgsql/functions/pg-send-query.xml
> +   <type class="union"><type>int</type><type>bool</type></type><methodname>pg_send_query</methodname>
Same as ``pg_send_execute()``

2021-09-30 14:33 UTC, Girgias commented on reference/pgsql/functions/pg-untrace.xml
>     Always returns &true;.
```suggestion
   &return.true.always;
```

2021-09-30 20:18 UTC, kamil-tekiela requested changes
This took a while... Few smaller changes requested.

2021-09-30 20:18 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-update.xml
>     <literal>assoc_array</literal> which has
Parameter instead of literal

2021-09-30 20:18 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-update.xml
>    <para>If <literal>options</literal> is specified,
Flags, not options

2021-09-30 20:18 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-update.xml
>     <function>pg_update</function> updates records that matches
One line below: conditions instead of condition, values instead of data, flags instead of options

2021-09-30 20:18 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-client-encoding.xml
>        </para>
This should have been a snippet.

2021-10-03 21:18 UTC, kocsismate commented on reference/pgsql/functions/pg-fetch-all-columns.xml
> +   &false; is returned if <parameter>field</parameter> is larger than the number
As far as I see, it can't return null, but only an array.

2021-10-03 21:33 UTC, kocsismate commented on reference/pgsql/functions/pg-last-notice.xml
> +   <type class="union"><type>array</type><type>string</type><type>bool</type></type><methodname>pg_last_notice</methodname>
Oh yes, false cannot be returned. I'll file a PR for php-src.

2021-10-03 21:44 UTC, kocsismate commented on reference/pgsql/functions/pg-host.xml
>     <type>string</type><methodname>pg_host</methodname>
True! And in case of any other error: https://www.postgresql.org/docs/13/libpq-status.html

2021-10-03 21:47 UTC, kocsismate commented on reference/pgsql/functions/pg-last-oid.xml
> +   <type class="union"><type>string</type><type>int</type><type>false</type></type><methodname>pg_last_oid</methodname>
What is the "same issue as `pg_field_type_oid()`"?

2021-10-03 21:49 UTC, kocsismate commented on reference/pgsql/functions/pg-port.xml
> +   <type>string</type><methodname>pg_port</methodname>
God... Nice catch again!

2021-10-03 21:59 UTC, kocsismate commented on reference/pgsql/functions/pg-send-execute.xml
> +   <type class="union"><type>int</type><type>bool</type></type><methodname>pg_send_execute</methodname>
I would say that it definitely shouldn't be this PR: it's already huge and my first (and basically one) priority is to make sure that the docs match the stubs as much as possible. Other improvements should be done separately, otherwise the whole project will stall even more (it has been going on for 1 year)  :/

(P.S. we are very close to the end for now!)

2021-10-03 22:10 UTC, kocsismate commented on reference/pgsql/functions/pg-copy-from.xml
> +   <methodparam choice="opt"><type>string</type><parameter>null_as</parameter><initializer>"\\\\N"</initializer></methodparam>
Hmmm, I think it should be only two! Nice catch!

2021-10-03 22:36 UTC, kocsismate commented on reference/pgsql/functions/pg-select.xml
>    </para>
I think it can return 0 in non-blocking due to:
```
if (is_non_blocking) {
    ret = PQflush(pgsql);
}
```

since PQflush can return 1: https://www.postgresql.org/docs/13/libpq-async.html

2021-10-03 22:38 UTC, kocsismate commented on reference/pgsql/functions/pg-send-execute.xml
> +   <type class="union"><type>int</type><type>bool</type></type><methodname>pg_send_execute</methodname>
I think it can return 0 in non-blocking mode due to:
```
if (is_non_blocking) {
    ret = PQflush(pgsql);
}
```

since PQflush can return 1: https://www.postgresql.org/docs/13/libpq-async.html

2021-10-03 22:53 UTC, kocsismate commented on reference/pgsql/functions/pg-select.xml
>    </para>
Hopefully, I found out a text which makes sense.

2021-10-03 22:57 UTC, kocsismate commented on reference/pgsql/functions/pg-update.xml
>     <literal>assoc_array</literal> which has
hmm.. is `assoc_array` in fact called `data` (which is now `values`)?

2021-10-03 22:59 UTC, kocsismate commented
I'w just rebased to master (to be able to build locally) and pushed a new commit with hopefully all the fixes (except for 1 in connection with the `$assoc_array` param).

2021-10-08 07:12 UTC, kocsismate commented on reference/pgsql/functions/pg-copy-from.xml
> +   <methodparam choice="opt"><type>string</type><parameter>null_as</parameter><initializer>"\\\\N"</initializer></methodparam>
It turned out that the original default value was correct so I retained it. Short discussion: https://github.com/php/php-src/pull/7565

2021-10-08 08:32 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-copy-from.xml
> +   <methodparam choice="opt"><type>string</type><parameter>null_as</parameter><initializer>"\\\\N"</initializer></methodparam>
Ok, but then the rest of that page (and the other one) has to be adjusted to say the right thing.

2021-10-08 10:37 UTC, Girgias commented on reference/pgsql/functions/pg-last-oid.xml
> +   <type class="union"><type>string</type><type>int</type><type>false</type></type><methodname>pg_last_oid</methodname>
In that it cannot return false. :-)

2021-10-08 10:40 UTC, Girgias commented on reference/pgsql/functions/pg-select.xml
> +   via <parameter>flags</parameter>, otherwise it returns an <type>array</type> on success or &false; on failure.
```suggestion
   via <parameter>flags</parameter>, otherwise it returns an <type>array</type> on success, &return.falseforfailure;
```

2021-10-08 22:55 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-update.xml
>     <literal>assoc_array</literal> which has
It looks like it. Probably copied over from `pg_select`. This page is quite noisy, and this line should probably be removed.

2021-10-08 23:11 UTC, Girgias commented on reference/pgsql/functions/pg-insert.xml
> +   &return.success;. Or returns a &string; on success if <constant>PGSQL_DML_STRING</constant> is passed
It does, please look at the source code again. It only returns a string when ``return_sql`` is true and is defined to ``return_sql = option & PGSQL_DML_STRING;`` on line 5450.

2021-10-09 18:26 UTC, kamil-tekiela requested changes
Amazing work. I think these are the last two. 

P.S. I did not know pgsql has so many overloaded functions. They should probably be deprecated as soon as possible.

2021-10-09 18:26 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-insert.xml
>    <para>If <literal>options</literal> is specified,
```suggestion
  <para>If <parameter>flags</parameter> is specified,
```

One more `assoc_array` 4 lines below

2021-10-09 18:26 UTC, kamil-tekiela commented on reference/pgsql/functions/pg-update.xml
>     <literal>assoc_array</literal> with the specified flags.
```suggestion
   <parameter>values</parameter> with the specified flags.
```

2021-10-09 20:47 UTC, kocsismate commented
> They should probably be deprecated as soon as possible.

Yes, definitely. I'l try to improve the situation in the coming months. :)

2021-10-09 22:23 UTC, merged

2021-10-09 22:24 UTC, kocsismate commented
Thank you, guys, for the thorough reviews!