Followed change of default value of display_startup_errors, as of PHP 8.0.0
php/doc-en pull request #927
Opened 2021-09-07 16:57 UTC by mumumu

Quoted from [appendices/migration80/incompatible.xml](https://github.com/php/doc-en/blob/master/appendices/migration80/incompatible.xml#L175-L180).

```
display_startup_errors is now enabled by default.
```

2021-09-07 23:42 UTC, Girgias requested changes

2021-09-07 23:42 UTC, Girgias commented on appendices/ini.list.xml
> +        Previous version of PHP 8.0.0, the default value was "0".
```suggestion
        Prior to PHP 8.0.0, the default value was <literal>"0"</literal>.
```
Similarly below

2021-09-08 07:30 UTC, mumumu commented
@Girgias Thank you! I followed you suggestions.

2021-09-08 08:58 UTC, cmb69 approved these changes
Thank you!

2021-09-08 10:00 UTC, merged