[Draft] Clean up filesystem function signatures
php/doc-en pull request #931
Opened 2021-09-08 02:47 UTC by thinkverse

This PR intends to clean up the function signatures for the filesystem functions. Some are missing default initializers, mostly the nullable parameters, and some have missing return types. `copy` though for instance had the wrong parameter names, in the [documentation](https://www.php.net/manual/en/function.copy.php), they are `$source` and `$dest` respectively but the actual names - found in the [php-src](https://github.com/php/php-src/blob/bf92bddb878dbd86d23db2900bad1cdfcd449eb7/ext/standard/basic_functions.stub.php#L853), are `$from` and `$to`.

This PR will be squashed down to one commit before it is ready to merge.

2021-09-08 04:04 UTC, thinkverse commented
I'm pretty sure I got all mismatched signatures, if I missed any let me know. 👍

2021-09-08 13:07 UTC, Girgias commented
I'm surprised this isn't caught by #903, @kocsismate any idea why?

2021-09-08 13:10 UTC, kocsismate commented
> I'm surprised this isn't caught by #903, kocsismate any idea why?

Yes, I only added a subset of all the changes, and I left most of the functions in ext/standard untouched until the majority of my outstanding PRs are merged.

2021-09-08 13:19 UTC, Girgias commented
Okay that explains that then. :-)

2021-09-08 13:26 UTC, Girgias requested changes
I haven't marked all the union type issues as it is a recurrent issue.

The var name changes in the examples are dubious IMHO.

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/fgets.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
The type declaration needs to be amended to be a union of int and null

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/copy.xml
> +   <methodparam choice="opt"><type>resource</type><parameter>context</parameter><initializer>&null;</initializer></methodparam>
The type declaration needs to be amended to be a union of resource and null

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/fgets.xml
> +    fclose($fp);
I'm not sure ``$fp`` is better than ``$handle``

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/file-get-contents.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Same here, union types are needed.

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/touch.xml
> +       the current system <function>time</function> is used.
I don't see the point in referencing the time *function* here?

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/fwrite.xml
> +    fclose($fp);
Again I don't think fp is a better name here.

2021-09-08 13:26 UTC, Girgias commented on reference/filesystem/functions/fwrite.xml
> +        $fwrite = fwrite($fp, substr($data, $written));
In the Para just above we are talking about strings, so I'm not sure changing to ``$data`` is better.

2021-09-08 13:39 UTC, thinkverse commented on reference/filesystem/functions/fgets.xml
> +    fclose($fp);
`$fp` and `$fh` are what most other functions use for their examples, hence the change from `handle` to  `fp` to keep it more consistent.

2021-09-08 13:44 UTC, thinkverse commented on reference/filesystem/functions/fwrite.xml
> +        $fwrite = fwrite($fp, substr($data, $written));
Because the parameter was named `string` and not `data`, I figured the original author named the variable `$string` because the parameter was named that.

After changing the parameter to its correct name, I figured changing the example variable to match would make it easier for readers to understand the connection.

Can change it back to `$string` if desired.

2021-09-08 13:45 UTC, thinkverse commented on reference/filesystem/functions/fwrite.xml
> +    fclose($fp);
Same reason as before, changed it to keep it consistent with other similar examples.

2021-09-08 13:52 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
> +       the current system <function>time</function> is used.
Previously `time` now `mtime` had its default set to `time()` - I'm guessing to indicate its default behavior when passed null, referencing the time _function_ here keeps that early reference.

2021-09-08 13:53 UTC, cmb69 commented on reference/filesystem/functions/fwrite.xml
> +        $fwrite = fwrite($fp, substr($data, $written));
I think it's better not to change variable names in the examples for now (unless that would be actual parameter names).

2021-09-08 13:55 UTC, cmb69 commented on reference/filesystem/functions/fgets.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Generally, the supposedly proper function signatures can be found in https://github.com/php/php-src/blob/master/ext/standard/basic_functions.stub.php.

2021-09-08 13:55 UTC, thinkverse commented on reference/filesystem/functions/file-get-contents.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Will update all union types. 👍

2021-09-08 14:04 UTC, thinkverse commented on reference/filesystem/functions/fgets.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Some have a strict union of `int|null` and some are nullable, meaning `?int`, do we have a `<type>` for that, or is `int|null` the correct choice to indicate nullable? 🤔

2021-09-08 14:09 UTC, cmb69 commented on reference/filesystem/functions/touch.xml
> +       the current system <function>time</function> is used.
That makes some sense; however, `is not supplied` should better be changed to `is &null`, and there should be a changelog entry about these parameters being nullable as of PHP 8.0.0.

2021-09-08 14:10 UTC, cmb69 commented on reference/filesystem/functions/fgets.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
`<type class="union"><type>int</type><type>null</type></type>` will be displayed as `?int` anyway.

2021-09-08 14:11 UTC, thinkverse commented on reference/filesystem/functions/fgets.xml
> +   <methodparam choice="opt"><type>int</type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Ooh, gotcha. 👍

2021-09-08 14:24 UTC, thinkverse commented on reference/filesystem/functions/fwrite.xml
> +        $fwrite = fwrite($fp, substr($data, $written));
Ok, I'm changing it back to `$string`.

2021-09-08 14:27 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
> +       the current system <function>time</function> is used.
`is &null;` and changelog added.

2021-09-08 15:02 UTC, Girgias requested changes
Still the minor complaint about using ``$fp`` but that's fine.

2021-09-08 15:02 UTC, Girgias commented on reference/filesystem/functions/touch.xml
>         If neither are present, the current system time is used.
This needs similar adjustment in wording to remove "is present".

2021-09-08 15:26 UTC, cmb69 commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is nullable now.
I've written it several times like this, though. :)

2021-09-08 15:35 UTC, Girgias commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is nullable now.
So you are to blame for the inconsistency. :-p

2021-09-08 15:45 UTC, cmb69 commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is nullable now.
Well, I might have been the first to write this, but I didn't "correct" later on, because I wasn't sure about the wording. I guess I would have introduced an entity early on, if these were parameterizable.

2021-09-08 17:33 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is nullable now.
I grabbed the wording from the [mbstring.changelog.encoding-nullable](https://github.com/php/doc-en/blob/3cdd39bb9505e6735d802da83a04870cfa8f2311/language-snippets.ent#L1055) entity, I have https://github.com/php/doc-en/pull/630 open which adds another changelog entity. I could commit an update to the wording of the `encoding-nullable` entity in that PR since it's related to mb string changelogs already. Might help reduce the inconsistency.

2021-09-08 17:38 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
>         If neither are present, the current system time is used.
So changing it from using `if present` to `if &null;` instead? Would this replacement work OK?

```
If &null;, the access time of the given filename is set to 
the value of <parameter>atime</parameter>. Otherwise, it is set to
the value passed to the <parameter>mtime</parameter> parameter.
If both are &null;, the current system time is used.
```

2021-12-22 09:06 UTC, kocsismate reviewed
A few nits. Please fix these, and then finally we can merge this PR :)

2021-12-22 09:06 UTC, kocsismate commented on reference/filesystem/functions/fwrite.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
needs a change log entry + mention `null` instead of "argument is given"

2021-12-22 09:06 UTC, kocsismate commented on reference/filesystem/functions/file-get-contents.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
needs a change log entry

2021-12-22 09:43 UTC, thinkverse commented on reference/filesystem/functions/unlink.xml
> +   <methodparam choice="opt"><type class="union"><type>resource</type><type>null</type></type><parameter>context</parameter><initializer>&null;</initializer></methodparam>
The `&note.context-support;` entity is used on `dir`, `file`, `fopen`, `mkdir`, `readfile`, `rename`, `rmdir` and `unlink`, looking at the src for 8.0 it seems all except `null` so should I update the entity and add the paragraph to `language-snippets.ent` instead?

```
<!ENTITY note.context-support '<para xmlns="http://docbook.org/ns/docbook">A <link linkend="stream.contexts">context stream</link>
<type>resource</type>. If &null; a default context will be used.</para>'>
```

Not sure how to word that exactly.

2021-12-22 09:58 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is now nullable.
Would the following work OK instead?

```suggestion
       <parameter>mtime</parameter> and <parameter>atime</parameter>
       are now nullable.
```

2021-12-22 10:06 UTC, kocsismate commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is now nullable.
Yes! That's the wording what I also use :)

2021-12-22 10:09 UTC, kocsismate commented on reference/filesystem/functions/unlink.xml
> +   <methodparam choice="opt"><type class="union"><type>resource</type><type>null</type></type><parameter>context</parameter><initializer>&null;</initializer></methodparam>
Yes, I think the entity should be updated in this case. I'm ok with the suggested wording, but @cmb69 may have a better idea.

2021-12-22 10:16 UTC, thinkverse commented on reference/filesystem/functions/file-get-contents.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Changelog entry added.

2021-12-22 10:16 UTC, thinkverse commented on reference/filesystem/functions/fwrite.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>length</parameter><initializer>&null;</initializer></methodparam>
Changelog entry and parameter description clarified.

2021-12-22 10:16 UTC, thinkverse commented on reference/filesystem/functions/touch.xml
> +       <parameter>mtime</parameter> is now nullable.
Changelog entries combined.

2021-12-22 10:17 UTC, thinkverse commented on reference/filesystem/functions/umask.xml
> +   <methodparam choice="opt"><type class="union"><type>int</type><type>null</type></type><parameter>mask</parameter><initializer>&null;</initializer></methodparam>
Changelog entry and parameter description updated.

2021-12-22 10:17 UTC, thinkverse commented on reference/filesystem/functions/unlink.xml
> +   <methodparam choice="opt"><type class="union"><type>resource</type><type>null</type></type><parameter>context</parameter><initializer>&null;</initializer></methodparam>
Then I think it might be better for a more senior doc member to update the entry. 👍

2021-12-22 11:31 UTC, kocsismate commented on reference/filesystem/functions/file-get-contents.xml
> +        <parameter>length</parameter> is nullable now.
The docs uses the `is nullable now` wording elsewhere

2021-12-22 11:31 UTC, kocsismate commented on reference/filesystem/functions/fwrite.xml
> +       If <parameter>length</parameter> is not &null;, writing will stop
When suggesting to use null, I didn't take the current wording into account. So with that in mind,
```
If <parameter>length</parameter> is an &integer;, writing will stop
```

would sound much better.

2021-12-22 12:09 UTC, thinkverse commented on reference/filesystem/functions/fwrite.xml
> +       If <parameter>length</parameter> is not &null;, writing will stop
```suggestion
       If <parameter>length</parameter> is an &integer;, writing will stop
```

2021-12-22 12:10 UTC, thinkverse commented on reference/filesystem/functions/file-get-contents.xml
> +        <parameter>length</parameter> is nullable now.
> The docs uses the `is nullable now` wording elsewhere

Yes, and we don't want to keep that wording consistent between functions? 🤔

2021-12-22 12:13 UTC, kocsismate commented on reference/filesystem/functions/file-get-contents.xml
> +        <parameter>length</parameter> is nullable now.
Ah... I wanted to write `is now nullable`, sorry!

2021-12-22 12:14 UTC, kocsismate commented on reference/filesystem/functions/file-get-contents.xml
> +        <parameter>length</parameter> is nullable now.
Although, I've just checked and they are almost used equally. OK, then I don't mind which one is used now :)

2021-12-22 12:15 UTC, kocsismate approved these changes
I'm going to merge this tomorrow, unless someone else spots any new issues.

2021-12-22 12:26 UTC, thinkverse commented on reference/filesystem/functions/file-get-contents.xml
> +        <parameter>length</parameter> is nullable now.
Yes, they're used interchangeably around the docs. I used `is nullable now` because that's what is used in the MB entity `mbstring.changelog.encoding-nullable` (https://github.com/php/doc-en/commit/ab493e941a14dcc760adbbe08976650b3a105be6) and that's the wording I found first. LDAP also uses `is nullable now`.

2021-12-23 09:34 UTC, merged