Fix `mixed` return type declarations of Misc. Functions
php/doc-en pull request #942
Opened 2021-09-12 15:37 UTC by alexanderpas

Noticed that the return types for some functions in the Misc Functions were wrong.

This PR makes sure the return types matches up with the internal return types found in [standard/basic_functions.stub.php.](https://github.com/php/php-src/blob/master/ext/standard/basic_functions.stub.php)

2021-09-12 19:19 UTC, thinkverse requested changes

2021-09-12 19:19 UTC, thinkverse commented on reference/misc/functions/get-browser.xml
>     <methodparam choice="opt"><type>string</type><parameter>user_agent</parameter></methodparam>
Might as well fix the parameter type and the fallback value while you're at it. 🙂

```suggestion
   <methodparam choice="opt"><type class="union"><type>string</type><type>null</type></type><parameter>user_agent</parameter><initializer>&null;</initializer></methodparam>
```

2021-09-13 13:40 UTC, cmb69 commented on reference/misc/functions/get-browser.xml
>     <methodparam choice="opt"><type>string</type><parameter>user_agent</parameter></methodparam>
And the fact that `get_browser()` returns `false` on failure should also be mentioned in the return values section.

2021-09-17 19:46 UTC, kamil-tekiela requested changes

2021-09-17 19:46 UTC, kamil-tekiela commented on reference/misc/functions/highlight-string.xml
>     <methodparam><type>string</type><parameter>str</parameter></methodparam>
```suggestion
   <methodparam><type>string</type><parameter>string</parameter></methodparam>
```

2021-09-17 19:46 UTC, kamil-tekiela commented on reference/misc/functions/highlight-string.xml
>     <methodparam><type>string</type><parameter>str</parameter></methodparam>
Same in the parameter section.

2021-09-21 11:10 UTC, kamil-tekiela approved these changes

2021-09-21 11:11 UTC, merged

2021-09-21 11:11 UTC, kamil-tekiela commented
LGTM. Thanks.