[PHP 8.1] Use an `FTP\Connection` instance instead of a resource
php/doc-en pull request #967
Opened 2021-09-23 07:16 UTC by saundefined

Related [changelog](https://github.com/php/doc-en/commit/4d2479dcf35d82aca39ee61f8ab36ceed78a869c#diff-8290829d06b811e45b3f0e3b04e8b24f8f339e59e1c70a15e63bc8f5c97539f2R91-R93).

PR can wait for other PRs related to PHP 8.1 if there are no comments.

2021-09-23 08:24 UTC, salathe commented
@saundefined  Is this a draft or is it ready to review?

2021-09-23 08:29 UTC, saundefined commented
@salathe, PR can be reviewed.

Since many PRs related to PHP 8.1 milestone have not yet been merged,
I marked it as a draft so that this would not be merged either.

2021-09-23 08:49 UTC, salathe commented
Documentation of the new `FTP\Connection` class is missing.

2021-09-23 09:17 UTC, salathe requested changes
The resources appendix `appendices/resources.xml` should be updated as well.

2021-09-23 09:17 UTC, salathe commented on language-snippets.ent
> +  <parameter>ftp</parameter> expects an <classname xmlns="http://docbook.org/ns/docbook">FTP\Connection</classname>
It might not be clear to readers that `ftp` refers to the *parameter* with that name.

```suggestion
  The <parameter>ftp</parameter> parameter expects an
  <classname xmlns="http://docbook.org/ns/docbook">FTP\Connection</classname>
```

2021-09-23 09:17 UTC, salathe commented on reference/ftp/functions/ftp-alloc.xml
> +       An <classname>FTP\Connection</classname> instance.
This sentence is repeated 30+ times.
Suggestion: use a language snippet.

2021-09-23 09:17 UTC, salathe commented on reference/ftp/examples.xml
>  // close the FTP stream
```suggestion
// close the FTP connection 
```

2021-09-23 09:17 UTC, salathe commented on reference/ftp/functions/ftp-get-option.xml
>  // Get the timeout of the given FTP stream
```suggestion
// Get the timeout of the given FTP connection
```

**Note:** the `<refpurpose>` for this page refers to `FTP stream` and should also be changed.

2021-09-23 09:17 UTC, salathe commented on reference/ftp/functions/ftp-login.xml
> +   <methodparam><type>FTP\Connection</type><parameter>ftp</parameter></methodparam>
The `<para>` below this synopsis refers to "FTP stream", this should be changed to "FTP connection".

2021-09-23 10:36 UTC, saundefined commented
@salathe thank you for the review!
Also updated `versions.xml`.

2021-09-23 11:18 UTC, salathe commented on appendices/resources.xml
> +    <entry>FTP connection</entry>
```suggestion
    <entry>FTP connection (prior to PHP 8.1.0)</entry>
```

2021-09-23 11:50 UTC, salathe commented
Thanks @saundefined.

For the `FTP\Connection` class the classref file should be `ftp.connection.xml` not `ftp-connection.xml`.

There should also be pages for the methods; e.g. `reference/ftp/ftp/connection/construct.xml` for the constructor.

2021-09-23 14:34 UTC, salathe requested changes

2021-09-23 14:34 UTC, salathe commented on reference/ftp/ftp.connection.xml
> +<phpdoc:classref xml:id="class.ftp.connection" xmlns:phpdoc="http://php.net/ns/phpdoc" xmlns="http://docbook.org/ns/docbook">
The `id` should have stayed as `class.ftp-connection` (to follow normal conventions). Similarly, other ids should use `ftp-connection` (see suggestions below).

```suggestion
<phpdoc:classref xml:id="class.ftp-connection" xmlns:phpdoc="http://php.net/ns/phpdoc" xmlns="http://docbook.org/ns/docbook">
```

2021-09-23 14:34 UTC, salathe commented on reference/ftp/ftp.connection.xml
> +  <section xml:id="ftp.connection.intro">
```suggestion
  <section xml:id="ftp-connection.intro">
```

2021-09-23 14:34 UTC, salathe commented on reference/ftp/ftp.connection.xml
> +  <section xml:id="ftp.connection.synopsis">
```suggestion
  <section xml:id="ftp-connection.synopsis">
```

2021-09-23 14:34 UTC, salathe commented on reference/ftp/versions.xml
> + <function name='FTP\Connection' from='PHP 8 &gt;= 8.1.0'/>
```suggestion
 <function name='ftp\connection' from='PHP 8 &gt;= 8.1.0'/>
```

2021-09-23 14:37 UTC, salathe approved these changes

2021-09-23 14:39 UTC, salathe commented
@saundefined the PR look good to me, thanks for making the changes. 👍

2021-09-24 08:57 UTC, saundefined commented
@salathe thanks for your help!

@cmb69 should I merge it or is it better some wait?

2021-09-24 10:10 UTC, cmb69 commented
Please go ahead an merge it!

2021-09-24 10:17 UTC, merged