Reword description on DOMDocument::domElement
php/doc-en pull request #973
Opened 2021-09-25 21:56 UTC by eclipxe13

A better description for documentElement that can be `NULL`.

See #955

2021-09-25 21:56 UTC, eclipxe13 commented
@tiffany-taylor could you please review? Thanks in advance

2021-10-10 23:25 UTC, tiffany-taylor requested changes

2021-10-10 23:25 UTC, tiffany-taylor commented on reference/dom/domdocument.xml
> +       document element. If not found, this will return &null;.
After testing locally, if the parent isn't found, `DOMDocument::documentElement` evaluates to null. While this doesn't affect most programmers, it can matter for some. I think it's important that the docs specify the distinction.

> If not found, this evaluates to &null;.

2021-10-11 17:56 UTC, eclipxe13 commented on reference/dom/domdocument.xml
> +       document element. If not found, this will return &null;.
Thanks! Rewording to "evaluates to"

2021-12-12 01:14 UTC, tiffany-taylor approved these changes

2021-12-12 01:14 UTC, merged

2021-12-12 01:16 UTC, tiffany-taylor commented
Thank you!