[PHP 8.1] Add `array_is_list` description
php/doc-en pull request #986
Opened 2021-09-30 20:23 UTC by saundefined

2021-09-30 20:53 UTC, kamil-tekiela requested changes

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +  <refpurpose>Returns whether a given array is an array with all sequential integers starting from 0</refpurpose>
```suggestion
  <refpurpose>Checks whether a given &array; is an &array; with keys that are consecutive integers starting from <literal>0</literal></refpurpose>
```
This is important since it doesn't check values in the array, but it checks whether keys are consecutive. Also, the keys are not only sequential but more importantly consecutive.

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +   Returns whether a given <parameter>array</parameter> is an &array; with all sequential integers starting from 0.
Same changes here. You could also add this bit from RFC as part of the description:
>will return true if the array keys are 0 .. count($array)-1 in that order

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +   Returns &true; if <parameter>array</parameter> is an &array; whose keys are all numeric, sequential, and start at 0.
Again, sequential doesn't explain it properly. The following numbers are sequential: 1,2,3,5,7,11. The keys must consist of consecutive numbers from 0 up to count($array)-1.

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +// Key does not start with 0
```suggestion
// The array does not start at 0
```
or "The array is missing a key at index 0" or "The key with index 0 is missing from the array"

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +// Keys are not in order
```suggestion
// The keys are not consecutive
```

2021-09-30 20:53 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +// Non-sequential keys
```suggestion
// Non-consecutive keys
```
However, now it's the same as the other description. Maybe someone has a better idea of how to describe this.

2021-09-30 21:42 UTC, saundefined commented
@kamil-tekiela thanks for the review!

What do you think about the following changes:

Refpurpose: so as not to repeat the same thing several times and use a shorter description:
>Checks whether a given <parameter>array</parameter> is a list

Methodsynopsis:
>Checks whether a given <parameter>array</parameter> keys are <literal>0 .. count($array)-1</literal> in that order.

Returnvalues:
>Returns &true;, if the <parameter>array</parameter> keys are <literal>0 .. count($array)-1</literal> in that order.

2021-10-01 18:54 UTC, kamil-tekiela requested changes
Sorry for changing so much, but I really believe this function needs a clear description. I think that what I am proposing now would be sufficient and it follows the style of the other functions in PHP manual.

2021-10-01 18:54 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +   Checks whether a given <parameter>array</parameter> keys are <literal>0 .. count($array)-1</literal> in that order.
This is good, but I wonder if we can give 140%. If we must duplicate one or the other, I'd prefer the refpurpose and the description to be similar. 
```suggestion
   Determines if the given <parameter>array</parameter> is a list.
   An &array; is considered a list if its keys consist of consecutive numbers
   from <literal>0</literal> to <literal>count($array)-1</literal>.
```

2021-10-01 18:54 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +// The keys are not consecutive
```suggestion
// The keys are not in the correct order
```

2021-10-01 18:54 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +   Returns &true;, if the <parameter>array</parameter> keys are <literal>0 .. count($array)-1</literal> in that order.
```suggestion
   Returns &true; if <parameter>array</parameter> is a list, &false;
   otherwise.
```

2021-10-01 18:54 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +       An &array;.
```suggestion
       The &array; being evaluated. 
```

2021-10-01 18:54 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +  </para>
If it's ought to be a note, then make it a note. 

```suggestion
  <note>
   <para>
    This function returns &true; on empty arrays as well.
   </para>
  </note>
```

2021-10-01 18:57 UTC, saundefined commented
Thank you very much for your help!

2021-10-01 19:01 UTC, kamil-tekiela commented
It'd be nice if we could get another set of eyes on this before merging. It looks good to me as it is now. 
@cmb69 ?

2021-10-01 21:59 UTC, salathe commented on reference/array/functions/array-is-list.xml
> +]]>
There should be a closing PHP tag (manual convention).

2021-10-01 21:59 UTC, salathe commented on reference/array/functions/array-is-list.xml
> +    This function returns &true; on empty arrays as well.
Nit: "as well" as what?

```suggestion
    This function returns &true; on empty arrays.
```

2021-10-01 21:59 UTC, salathe commented on reference/array/functions/array-is-list.xml
> + </refsect1>
It would be good to have a "see also" section, with at least `array_values()` (a way of making an arbitrary array into a "list").

2021-10-01 22:13 UTC, kamil-tekiela commented on reference/array/functions/array-is-list.xml
> +]]>
I am not going to argue against adding it, but I don't really see the point. The closing PHP tag is generally considered bad practice if there's no output following the PHP block. Adding it to every example in PHP manual works against that recommendation. I'd only make it a rule that it should be consistent across examples on any given page.

2021-10-01 23:30 UTC, salathe commented on reference/array/functions/array-is-list.xml
> +]]>
Regardless of whether you see the point or not, the tag should be there for this example.

2021-10-02 08:18 UTC, saundefined commented
Thanks! Committed changes

2021-10-02 11:36 UTC, kamil-tekiela approved these changes

2021-10-02 16:52 UTC, merged