[PHP 8.1] Update `mysqli_stmt::execute` description
php/doc-en pull request #987
Opened 2021-10-01 07:05 UTC by saundefined

Related [RFC](https://wiki.php.net/rfc/mysqli_bind_in_execute)

2021-10-01 10:40 UTC, kamil-tekiela reviewed
Thanks. I will review it later.

2021-10-01 10:40 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +    <![CDATA[
```suggestion
<![CDATA[
```
Not sure if it matters, but I have seen no space before CDATA anywhere else.

2021-10-01 10:40 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +    <![CDATA[
```suggestion
<![CDATA[
```

2021-10-01 10:40 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +    <![CDATA[
```suggestion
<![CDATA[
```

2021-10-01 16:49 UTC, kamil-tekiela commented
Can you please apply similar fixes to the ones in #989?

2021-10-01 17:28 UTC, saundefined commented
@kamil-tekiela sure, updated.

2021-10-01 21:45 UTC, kamil-tekiela requested changes

2021-10-01 21:45 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <methodparam choice="opt"><type>array</type><parameter>params</parameter><initializer>&null;</initializer></methodparam>
It's a nullable parameter. 
```suggestion
   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>params</parameter><initializer>&null;</initializer></methodparam>
```

2021-10-01 21:45 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <methodparam choice="opt"><type>array</type><parameter>params</parameter><initializer>&null;</initializer></methodparam>
```suggestion
   <methodparam choice="opt"><type class="union"><type>array</type><type>null</type></type><parameter>params</parameter><initializer>&null;</initializer></methodparam>
```

2021-10-01 21:45 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +       An optional list &array; with variables corresponding to the parameters in the statement.
```suggestion
       An optional list &array; with as many elements as there are bound parameters in the SQL statement being executed. Each value is treated as a &string;.
```

2021-10-01 21:45 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <title><methodname>mysqli_stmt::execute</methodname> example as of PHP 8.1</title>
```suggestion
   <title>Execute a prepared statement with an array of values</title>
```

2021-10-01 21:45 UTC, kamil-tekiela commented on reference/mysqli/mysqli_stmt/execute.xml
> +   <title><methodname>mysqli_stmt::execute</methodname> example as of PHP 8.1</title>
You may want to change the first example's title to:
>Execute a prepared statement with bound variables

2021-10-02 08:12 UTC, saundefined commented
Thank you!

2021-10-02 11:35 UTC, kamil-tekiela approved these changes

2021-10-02 16:50 UTC, merged